###################################################################

# Created by write_sdc on Tue Apr 21 16:07:06 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name Small -library                                       \
sc9_cln40g_base_rvt_ss_typical_max_0p81v_125c
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {d[61]}]
set_load -pin_load 0.05 [get_ports {d[60]}]
set_load -pin_load 0.05 [get_ports {d[59]}]
set_load -pin_load 0.05 [get_ports {d[58]}]
set_load -pin_load 0.05 [get_ports {d[57]}]
set_load -pin_load 0.05 [get_ports {d[56]}]
set_load -pin_load 0.05 [get_ports {d[55]}]
set_load -pin_load 0.05 [get_ports {d[54]}]
set_load -pin_load 0.05 [get_ports {d[53]}]
set_load -pin_load 0.05 [get_ports {d[52]}]
set_load -pin_load 0.05 [get_ports {d[51]}]
set_load -pin_load 0.05 [get_ports {d[50]}]
set_load -pin_load 0.05 [get_ports {d[49]}]
set_load -pin_load 0.05 [get_ports {d[48]}]
set_load -pin_load 0.05 [get_ports {d[47]}]
set_load -pin_load 0.05 [get_ports {d[46]}]
set_load -pin_load 0.05 [get_ports {d[45]}]
set_load -pin_load 0.05 [get_ports {d[44]}]
set_load -pin_load 0.05 [get_ports {d[43]}]
set_load -pin_load 0.05 [get_ports {d[42]}]
set_load -pin_load 0.05 [get_ports {d[41]}]
set_load -pin_load 0.05 [get_ports {d[40]}]
set_load -pin_load 0.05 [get_ports {d[39]}]
set_load -pin_load 0.05 [get_ports {d[38]}]
set_load -pin_load 0.05 [get_ports {d[37]}]
set_load -pin_load 0.05 [get_ports {d[36]}]
set_load -pin_load 0.05 [get_ports {d[35]}]
set_load -pin_load 0.05 [get_ports {d[34]}]
set_load -pin_load 0.05 [get_ports {d[33]}]
set_load -pin_load 0.05 [get_ports {d[32]}]
set_load -pin_load 0.05 [get_ports {d[31]}]
set_load -pin_load 0.05 [get_ports {d[30]}]
set_load -pin_load 0.05 [get_ports {d[29]}]
set_load -pin_load 0.05 [get_ports {d[28]}]
set_load -pin_load 0.05 [get_ports {d[27]}]
set_load -pin_load 0.05 [get_ports {d[26]}]
set_load -pin_load 0.05 [get_ports {d[25]}]
set_load -pin_load 0.05 [get_ports {d[24]}]
set_load -pin_load 0.05 [get_ports {d[23]}]
set_load -pin_load 0.05 [get_ports {d[22]}]
set_load -pin_load 0.05 [get_ports {d[21]}]
set_load -pin_load 0.05 [get_ports {d[20]}]
set_load -pin_load 0.05 [get_ports {d[19]}]
set_load -pin_load 0.05 [get_ports {d[18]}]
set_load -pin_load 0.05 [get_ports {d[17]}]
set_load -pin_load 0.05 [get_ports {d[16]}]
set_load -pin_load 0.05 [get_ports {d[15]}]
set_load -pin_load 0.05 [get_ports {d[14]}]
set_load -pin_load 0.05 [get_ports {d[13]}]
set_load -pin_load 0.05 [get_ports {d[12]}]
set_load -pin_load 0.05 [get_ports {d[11]}]
set_load -pin_load 0.05 [get_ports {d[10]}]
set_load -pin_load 0.05 [get_ports {d[9]}]
set_load -pin_load 0.05 [get_ports {d[8]}]
set_load -pin_load 0.05 [get_ports {d[7]}]
set_load -pin_load 0.05 [get_ports {d[6]}]
set_load -pin_load 0.05 [get_ports {d[5]}]
set_load -pin_load 0.05 [get_ports {d[4]}]
set_load -pin_load 0.05 [get_ports {d[3]}]
set_load -pin_load 0.05 [get_ports {d[2]}]
set_load -pin_load 0.05 [get_ports {d[1]}]
set_load -pin_load 0.05 [get_ports {d[0]}]
set_load -pin_load 0.05 [get_ports {o_bus[1]}]
set_load -pin_load 0.05 [get_ports {o_bus[2]}]
create_clock [get_ports clk]  -period 1.25  -waveform {0 0.625}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  0  [get_ports in_valid]
set_input_delay -clock clk  0  [get_ports {a[61]}]
set_input_delay -clock clk  0  [get_ports {a[60]}]
set_input_delay -clock clk  0  [get_ports {a[59]}]
set_input_delay -clock clk  0  [get_ports {a[58]}]
set_input_delay -clock clk  0  [get_ports {a[57]}]
set_input_delay -clock clk  0  [get_ports {a[56]}]
set_input_delay -clock clk  0  [get_ports {a[55]}]
set_input_delay -clock clk  0  [get_ports {a[54]}]
set_input_delay -clock clk  0  [get_ports {a[53]}]
set_input_delay -clock clk  0  [get_ports {a[52]}]
set_input_delay -clock clk  0  [get_ports {a[51]}]
set_input_delay -clock clk  0  [get_ports {a[50]}]
set_input_delay -clock clk  0  [get_ports {a[49]}]
set_input_delay -clock clk  0  [get_ports {a[48]}]
set_input_delay -clock clk  0  [get_ports {a[47]}]
set_input_delay -clock clk  0  [get_ports {a[46]}]
set_input_delay -clock clk  0  [get_ports {a[45]}]
set_input_delay -clock clk  0  [get_ports {a[44]}]
set_input_delay -clock clk  0  [get_ports {a[43]}]
set_input_delay -clock clk  0  [get_ports {a[42]}]
set_input_delay -clock clk  0  [get_ports {a[41]}]
set_input_delay -clock clk  0  [get_ports {a[40]}]
set_input_delay -clock clk  0  [get_ports {a[39]}]
set_input_delay -clock clk  0  [get_ports {a[38]}]
set_input_delay -clock clk  0  [get_ports {a[37]}]
set_input_delay -clock clk  0  [get_ports {a[36]}]
set_input_delay -clock clk  0  [get_ports {a[35]}]
set_input_delay -clock clk  0  [get_ports {a[34]}]
set_input_delay -clock clk  0  [get_ports {a[33]}]
set_input_delay -clock clk  0  [get_ports {a[32]}]
set_input_delay -clock clk  0  [get_ports {a[31]}]
set_input_delay -clock clk  0  [get_ports {a[30]}]
set_input_delay -clock clk  0  [get_ports {a[29]}]
set_input_delay -clock clk  0  [get_ports {a[28]}]
set_input_delay -clock clk  0  [get_ports {a[27]}]
set_input_delay -clock clk  0  [get_ports {a[26]}]
set_input_delay -clock clk  0  [get_ports {a[25]}]
set_input_delay -clock clk  0  [get_ports {a[24]}]
set_input_delay -clock clk  0  [get_ports {a[23]}]
set_input_delay -clock clk  0  [get_ports {a[22]}]
set_input_delay -clock clk  0  [get_ports {a[21]}]
set_input_delay -clock clk  0  [get_ports {a[20]}]
set_input_delay -clock clk  0  [get_ports {a[19]}]
set_input_delay -clock clk  0  [get_ports {a[18]}]
set_input_delay -clock clk  0  [get_ports {a[17]}]
set_input_delay -clock clk  0  [get_ports {a[16]}]
set_input_delay -clock clk  0  [get_ports {a[15]}]
set_input_delay -clock clk  0  [get_ports {a[14]}]
set_input_delay -clock clk  0  [get_ports {a[13]}]
set_input_delay -clock clk  0  [get_ports {a[12]}]
set_input_delay -clock clk  0  [get_ports {a[11]}]
set_input_delay -clock clk  0  [get_ports {a[10]}]
set_input_delay -clock clk  0  [get_ports {a[9]}]
set_input_delay -clock clk  0  [get_ports {a[8]}]
set_input_delay -clock clk  0  [get_ports {a[7]}]
set_input_delay -clock clk  0  [get_ports {a[6]}]
set_input_delay -clock clk  0  [get_ports {a[5]}]
set_input_delay -clock clk  0  [get_ports {a[4]}]
set_input_delay -clock clk  0  [get_ports {a[3]}]
set_input_delay -clock clk  0  [get_ports {a[2]}]
set_input_delay -clock clk  0  [get_ports {a[1]}]
set_input_delay -clock clk  0  [get_ports {a[0]}]
set_input_delay -clock clk  0  [get_ports {b[61]}]
set_input_delay -clock clk  0  [get_ports {b[60]}]
set_input_delay -clock clk  0  [get_ports {b[59]}]
set_input_delay -clock clk  0  [get_ports {b[58]}]
set_input_delay -clock clk  0  [get_ports {b[57]}]
set_input_delay -clock clk  0  [get_ports {b[56]}]
set_input_delay -clock clk  0  [get_ports {b[55]}]
set_input_delay -clock clk  0  [get_ports {b[54]}]
set_input_delay -clock clk  0  [get_ports {b[53]}]
set_input_delay -clock clk  0  [get_ports {b[52]}]
set_input_delay -clock clk  0  [get_ports {b[51]}]
set_input_delay -clock clk  0  [get_ports {b[50]}]
set_input_delay -clock clk  0  [get_ports {b[49]}]
set_input_delay -clock clk  0  [get_ports {b[48]}]
set_input_delay -clock clk  0  [get_ports {b[47]}]
set_input_delay -clock clk  0  [get_ports {b[46]}]
set_input_delay -clock clk  0  [get_ports {b[45]}]
set_input_delay -clock clk  0  [get_ports {b[44]}]
set_input_delay -clock clk  0  [get_ports {b[43]}]
set_input_delay -clock clk  0  [get_ports {b[42]}]
set_input_delay -clock clk  0  [get_ports {b[41]}]
set_input_delay -clock clk  0  [get_ports {b[40]}]
set_input_delay -clock clk  0  [get_ports {b[39]}]
set_input_delay -clock clk  0  [get_ports {b[38]}]
set_input_delay -clock clk  0  [get_ports {b[37]}]
set_input_delay -clock clk  0  [get_ports {b[36]}]
set_input_delay -clock clk  0  [get_ports {b[35]}]
set_input_delay -clock clk  0  [get_ports {b[34]}]
set_input_delay -clock clk  0  [get_ports {b[33]}]
set_input_delay -clock clk  0  [get_ports {b[32]}]
set_input_delay -clock clk  0  [get_ports {b[31]}]
set_input_delay -clock clk  0  [get_ports {b[30]}]
set_input_delay -clock clk  0  [get_ports {b[29]}]
set_input_delay -clock clk  0  [get_ports {b[28]}]
set_input_delay -clock clk  0  [get_ports {b[27]}]
set_input_delay -clock clk  0  [get_ports {b[26]}]
set_input_delay -clock clk  0  [get_ports {b[25]}]
set_input_delay -clock clk  0  [get_ports {b[24]}]
set_input_delay -clock clk  0  [get_ports {b[23]}]
set_input_delay -clock clk  0  [get_ports {b[22]}]
set_input_delay -clock clk  0  [get_ports {b[21]}]
set_input_delay -clock clk  0  [get_ports {b[20]}]
set_input_delay -clock clk  0  [get_ports {b[19]}]
set_input_delay -clock clk  0  [get_ports {b[18]}]
set_input_delay -clock clk  0  [get_ports {b[17]}]
set_input_delay -clock clk  0  [get_ports {b[16]}]
set_input_delay -clock clk  0  [get_ports {b[15]}]
set_input_delay -clock clk  0  [get_ports {b[14]}]
set_input_delay -clock clk  0  [get_ports {b[13]}]
set_input_delay -clock clk  0  [get_ports {b[12]}]
set_input_delay -clock clk  0  [get_ports {b[11]}]
set_input_delay -clock clk  0  [get_ports {b[10]}]
set_input_delay -clock clk  0  [get_ports {b[9]}]
set_input_delay -clock clk  0  [get_ports {b[8]}]
set_input_delay -clock clk  0  [get_ports {b[7]}]
set_input_delay -clock clk  0  [get_ports {b[6]}]
set_input_delay -clock clk  0  [get_ports {b[5]}]
set_input_delay -clock clk  0  [get_ports {b[4]}]
set_input_delay -clock clk  0  [get_ports {b[3]}]
set_input_delay -clock clk  0  [get_ports {b[2]}]
set_input_delay -clock clk  0  [get_ports {b[1]}]
set_input_delay -clock clk  0  [get_ports {b[0]}]
set_input_delay -clock clk  0  [get_ports {p[61]}]
set_input_delay -clock clk  0  [get_ports {p[60]}]
set_input_delay -clock clk  0  [get_ports {p[59]}]
set_input_delay -clock clk  0  [get_ports {p[58]}]
set_input_delay -clock clk  0  [get_ports {p[57]}]
set_input_delay -clock clk  0  [get_ports {p[56]}]
set_input_delay -clock clk  0  [get_ports {p[55]}]
set_input_delay -clock clk  0  [get_ports {p[54]}]
set_input_delay -clock clk  0  [get_ports {p[53]}]
set_input_delay -clock clk  0  [get_ports {p[52]}]
set_input_delay -clock clk  0  [get_ports {p[51]}]
set_input_delay -clock clk  0  [get_ports {p[50]}]
set_input_delay -clock clk  0  [get_ports {p[49]}]
set_input_delay -clock clk  0  [get_ports {p[48]}]
set_input_delay -clock clk  0  [get_ports {p[47]}]
set_input_delay -clock clk  0  [get_ports {p[46]}]
set_input_delay -clock clk  0  [get_ports {p[45]}]
set_input_delay -clock clk  0  [get_ports {p[44]}]
set_input_delay -clock clk  0  [get_ports {p[43]}]
set_input_delay -clock clk  0  [get_ports {p[42]}]
set_input_delay -clock clk  0  [get_ports {p[41]}]
set_input_delay -clock clk  0  [get_ports {p[40]}]
set_input_delay -clock clk  0  [get_ports {p[39]}]
set_input_delay -clock clk  0  [get_ports {p[38]}]
set_input_delay -clock clk  0  [get_ports {p[37]}]
set_input_delay -clock clk  0  [get_ports {p[36]}]
set_input_delay -clock clk  0  [get_ports {p[35]}]
set_input_delay -clock clk  0  [get_ports {p[34]}]
set_input_delay -clock clk  0  [get_ports {p[33]}]
set_input_delay -clock clk  0  [get_ports {p[32]}]
set_input_delay -clock clk  0  [get_ports {p[31]}]
set_input_delay -clock clk  0  [get_ports {p[30]}]
set_input_delay -clock clk  0  [get_ports {p[29]}]
set_input_delay -clock clk  0  [get_ports {p[28]}]
set_input_delay -clock clk  0  [get_ports {p[27]}]
set_input_delay -clock clk  0  [get_ports {p[26]}]
set_input_delay -clock clk  0  [get_ports {p[25]}]
set_input_delay -clock clk  0  [get_ports {p[24]}]
set_input_delay -clock clk  0  [get_ports {p[23]}]
set_input_delay -clock clk  0  [get_ports {p[22]}]
set_input_delay -clock clk  0  [get_ports {p[21]}]
set_input_delay -clock clk  0  [get_ports {p[20]}]
set_input_delay -clock clk  0  [get_ports {p[19]}]
set_input_delay -clock clk  0  [get_ports {p[18]}]
set_input_delay -clock clk  0  [get_ports {p[17]}]
set_input_delay -clock clk  0  [get_ports {p[16]}]
set_input_delay -clock clk  0  [get_ports {p[15]}]
set_input_delay -clock clk  0  [get_ports {p[14]}]
set_input_delay -clock clk  0  [get_ports {p[13]}]
set_input_delay -clock clk  0  [get_ports {p[12]}]
set_input_delay -clock clk  0  [get_ports {p[11]}]
set_input_delay -clock clk  0  [get_ports {p[10]}]
set_input_delay -clock clk  0  [get_ports {p[9]}]
set_input_delay -clock clk  0  [get_ports {p[8]}]
set_input_delay -clock clk  0  [get_ports {p[7]}]
set_input_delay -clock clk  0  [get_ports {p[6]}]
set_input_delay -clock clk  0  [get_ports {p[5]}]
set_input_delay -clock clk  0  [get_ports {p[4]}]
set_input_delay -clock clk  0  [get_ports {p[3]}]
set_input_delay -clock clk  0  [get_ports {p[2]}]
set_input_delay -clock clk  0  [get_ports {p[1]}]
set_input_delay -clock clk  0  [get_ports {p[0]}]
set_input_delay -clock clk  0  [get_ports {p0i[61]}]
set_input_delay -clock clk  0  [get_ports {p0i[60]}]
set_input_delay -clock clk  0  [get_ports {p0i[59]}]
set_input_delay -clock clk  0  [get_ports {p0i[58]}]
set_input_delay -clock clk  0  [get_ports {p0i[57]}]
set_input_delay -clock clk  0  [get_ports {p0i[56]}]
set_input_delay -clock clk  0  [get_ports {p0i[55]}]
set_input_delay -clock clk  0  [get_ports {p0i[54]}]
set_input_delay -clock clk  0  [get_ports {p0i[53]}]
set_input_delay -clock clk  0  [get_ports {p0i[52]}]
set_input_delay -clock clk  0  [get_ports {p0i[51]}]
set_input_delay -clock clk  0  [get_ports {p0i[50]}]
set_input_delay -clock clk  0  [get_ports {p0i[49]}]
set_input_delay -clock clk  0  [get_ports {p0i[48]}]
set_input_delay -clock clk  0  [get_ports {p0i[47]}]
set_input_delay -clock clk  0  [get_ports {p0i[46]}]
set_input_delay -clock clk  0  [get_ports {p0i[45]}]
set_input_delay -clock clk  0  [get_ports {p0i[44]}]
set_input_delay -clock clk  0  [get_ports {p0i[43]}]
set_input_delay -clock clk  0  [get_ports {p0i[42]}]
set_input_delay -clock clk  0  [get_ports {p0i[41]}]
set_input_delay -clock clk  0  [get_ports {p0i[40]}]
set_input_delay -clock clk  0  [get_ports {p0i[39]}]
set_input_delay -clock clk  0  [get_ports {p0i[38]}]
set_input_delay -clock clk  0  [get_ports {p0i[37]}]
set_input_delay -clock clk  0  [get_ports {p0i[36]}]
set_input_delay -clock clk  0  [get_ports {p0i[35]}]
set_input_delay -clock clk  0  [get_ports {p0i[34]}]
set_input_delay -clock clk  0  [get_ports {p0i[33]}]
set_input_delay -clock clk  0  [get_ports {p0i[32]}]
set_input_delay -clock clk  0  [get_ports {p0i[31]}]
set_input_delay -clock clk  0  [get_ports {p0i[30]}]
set_input_delay -clock clk  0  [get_ports {p0i[29]}]
set_input_delay -clock clk  0  [get_ports {p0i[28]}]
set_input_delay -clock clk  0  [get_ports {p0i[27]}]
set_input_delay -clock clk  0  [get_ports {p0i[26]}]
set_input_delay -clock clk  0  [get_ports {p0i[25]}]
set_input_delay -clock clk  0  [get_ports {p0i[24]}]
set_input_delay -clock clk  0  [get_ports {p0i[23]}]
set_input_delay -clock clk  0  [get_ports {p0i[22]}]
set_input_delay -clock clk  0  [get_ports {p0i[21]}]
set_input_delay -clock clk  0  [get_ports {p0i[20]}]
set_input_delay -clock clk  0  [get_ports {p0i[19]}]
set_input_delay -clock clk  0  [get_ports {p0i[18]}]
set_input_delay -clock clk  0  [get_ports {p0i[17]}]
set_input_delay -clock clk  0  [get_ports {p0i[16]}]
set_input_delay -clock clk  0  [get_ports {p0i[15]}]
set_input_delay -clock clk  0  [get_ports {p0i[14]}]
set_input_delay -clock clk  0  [get_ports {p0i[13]}]
set_input_delay -clock clk  0  [get_ports {p0i[12]}]
set_input_delay -clock clk  0  [get_ports {p0i[11]}]
set_input_delay -clock clk  0  [get_ports {p0i[10]}]
set_input_delay -clock clk  0  [get_ports {p0i[9]}]
set_input_delay -clock clk  0  [get_ports {p0i[8]}]
set_input_delay -clock clk  0  [get_ports {p0i[7]}]
set_input_delay -clock clk  0  [get_ports {p0i[6]}]
set_input_delay -clock clk  0  [get_ports {p0i[5]}]
set_input_delay -clock clk  0  [get_ports {p0i[4]}]
set_input_delay -clock clk  0  [get_ports {p0i[3]}]
set_input_delay -clock clk  0  [get_ports {p0i[2]}]
set_input_delay -clock clk  0  [get_ports {p0i[1]}]
set_input_delay -clock clk  0  [get_ports {p0i[0]}]
set_input_delay -clock clk  0  [get_ports isMQ]
set_input_delay -clock clk  0  [get_ports {i_bus[1]}]
set_input_delay -clock clk  0  [get_ports {i_bus[2]}]
set_output_delay -clock clk  0  [get_ports out_valid]
set_output_delay -clock clk  0  [get_ports {d[61]}]
set_output_delay -clock clk  0  [get_ports {d[60]}]
set_output_delay -clock clk  0  [get_ports {d[59]}]
set_output_delay -clock clk  0  [get_ports {d[58]}]
set_output_delay -clock clk  0  [get_ports {d[57]}]
set_output_delay -clock clk  0  [get_ports {d[56]}]
set_output_delay -clock clk  0  [get_ports {d[55]}]
set_output_delay -clock clk  0  [get_ports {d[54]}]
set_output_delay -clock clk  0  [get_ports {d[53]}]
set_output_delay -clock clk  0  [get_ports {d[52]}]
set_output_delay -clock clk  0  [get_ports {d[51]}]
set_output_delay -clock clk  0  [get_ports {d[50]}]
set_output_delay -clock clk  0  [get_ports {d[49]}]
set_output_delay -clock clk  0  [get_ports {d[48]}]
set_output_delay -clock clk  0  [get_ports {d[47]}]
set_output_delay -clock clk  0  [get_ports {d[46]}]
set_output_delay -clock clk  0  [get_ports {d[45]}]
set_output_delay -clock clk  0  [get_ports {d[44]}]
set_output_delay -clock clk  0  [get_ports {d[43]}]
set_output_delay -clock clk  0  [get_ports {d[42]}]
set_output_delay -clock clk  0  [get_ports {d[41]}]
set_output_delay -clock clk  0  [get_ports {d[40]}]
set_output_delay -clock clk  0  [get_ports {d[39]}]
set_output_delay -clock clk  0  [get_ports {d[38]}]
set_output_delay -clock clk  0  [get_ports {d[37]}]
set_output_delay -clock clk  0  [get_ports {d[36]}]
set_output_delay -clock clk  0  [get_ports {d[35]}]
set_output_delay -clock clk  0  [get_ports {d[34]}]
set_output_delay -clock clk  0  [get_ports {d[33]}]
set_output_delay -clock clk  0  [get_ports {d[32]}]
set_output_delay -clock clk  0  [get_ports {d[31]}]
set_output_delay -clock clk  0  [get_ports {d[30]}]
set_output_delay -clock clk  0  [get_ports {d[29]}]
set_output_delay -clock clk  0  [get_ports {d[28]}]
set_output_delay -clock clk  0  [get_ports {d[27]}]
set_output_delay -clock clk  0  [get_ports {d[26]}]
set_output_delay -clock clk  0  [get_ports {d[25]}]
set_output_delay -clock clk  0  [get_ports {d[24]}]
set_output_delay -clock clk  0  [get_ports {d[23]}]
set_output_delay -clock clk  0  [get_ports {d[22]}]
set_output_delay -clock clk  0  [get_ports {d[21]}]
set_output_delay -clock clk  0  [get_ports {d[20]}]
set_output_delay -clock clk  0  [get_ports {d[19]}]
set_output_delay -clock clk  0  [get_ports {d[18]}]
set_output_delay -clock clk  0  [get_ports {d[17]}]
set_output_delay -clock clk  0  [get_ports {d[16]}]
set_output_delay -clock clk  0  [get_ports {d[15]}]
set_output_delay -clock clk  0  [get_ports {d[14]}]
set_output_delay -clock clk  0  [get_ports {d[13]}]
set_output_delay -clock clk  0  [get_ports {d[12]}]
set_output_delay -clock clk  0  [get_ports {d[11]}]
set_output_delay -clock clk  0  [get_ports {d[10]}]
set_output_delay -clock clk  0  [get_ports {d[9]}]
set_output_delay -clock clk  0  [get_ports {d[8]}]
set_output_delay -clock clk  0  [get_ports {d[7]}]
set_output_delay -clock clk  0  [get_ports {d[6]}]
set_output_delay -clock clk  0  [get_ports {d[5]}]
set_output_delay -clock clk  0  [get_ports {d[4]}]
set_output_delay -clock clk  0  [get_ports {d[3]}]
set_output_delay -clock clk  0  [get_ports {d[2]}]
set_output_delay -clock clk  0  [get_ports {d[1]}]
set_output_delay -clock clk  0  [get_ports {d[0]}]
set_output_delay -clock clk  0  [get_ports {o_bus[1]}]
set_output_delay -clock clk  0  [get_ports {o_bus[2]}]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports in_valid]
set_input_transition -min 0.5  [get_ports in_valid]
set_input_transition -max 0.5  [get_ports {a[61]}]
set_input_transition -min 0.5  [get_ports {a[61]}]
set_input_transition -max 0.5  [get_ports {a[60]}]
set_input_transition -min 0.5  [get_ports {a[60]}]
set_input_transition -max 0.5  [get_ports {a[59]}]
set_input_transition -min 0.5  [get_ports {a[59]}]
set_input_transition -max 0.5  [get_ports {a[58]}]
set_input_transition -min 0.5  [get_ports {a[58]}]
set_input_transition -max 0.5  [get_ports {a[57]}]
set_input_transition -min 0.5  [get_ports {a[57]}]
set_input_transition -max 0.5  [get_ports {a[56]}]
set_input_transition -min 0.5  [get_ports {a[56]}]
set_input_transition -max 0.5  [get_ports {a[55]}]
set_input_transition -min 0.5  [get_ports {a[55]}]
set_input_transition -max 0.5  [get_ports {a[54]}]
set_input_transition -min 0.5  [get_ports {a[54]}]
set_input_transition -max 0.5  [get_ports {a[53]}]
set_input_transition -min 0.5  [get_ports {a[53]}]
set_input_transition -max 0.5  [get_ports {a[52]}]
set_input_transition -min 0.5  [get_ports {a[52]}]
set_input_transition -max 0.5  [get_ports {a[51]}]
set_input_transition -min 0.5  [get_ports {a[51]}]
set_input_transition -max 0.5  [get_ports {a[50]}]
set_input_transition -min 0.5  [get_ports {a[50]}]
set_input_transition -max 0.5  [get_ports {a[49]}]
set_input_transition -min 0.5  [get_ports {a[49]}]
set_input_transition -max 0.5  [get_ports {a[48]}]
set_input_transition -min 0.5  [get_ports {a[48]}]
set_input_transition -max 0.5  [get_ports {a[47]}]
set_input_transition -min 0.5  [get_ports {a[47]}]
set_input_transition -max 0.5  [get_ports {a[46]}]
set_input_transition -min 0.5  [get_ports {a[46]}]
set_input_transition -max 0.5  [get_ports {a[45]}]
set_input_transition -min 0.5  [get_ports {a[45]}]
set_input_transition -max 0.5  [get_ports {a[44]}]
set_input_transition -min 0.5  [get_ports {a[44]}]
set_input_transition -max 0.5  [get_ports {a[43]}]
set_input_transition -min 0.5  [get_ports {a[43]}]
set_input_transition -max 0.5  [get_ports {a[42]}]
set_input_transition -min 0.5  [get_ports {a[42]}]
set_input_transition -max 0.5  [get_ports {a[41]}]
set_input_transition -min 0.5  [get_ports {a[41]}]
set_input_transition -max 0.5  [get_ports {a[40]}]
set_input_transition -min 0.5  [get_ports {a[40]}]
set_input_transition -max 0.5  [get_ports {a[39]}]
set_input_transition -min 0.5  [get_ports {a[39]}]
set_input_transition -max 0.5  [get_ports {a[38]}]
set_input_transition -min 0.5  [get_ports {a[38]}]
set_input_transition -max 0.5  [get_ports {a[37]}]
set_input_transition -min 0.5  [get_ports {a[37]}]
set_input_transition -max 0.5  [get_ports {a[36]}]
set_input_transition -min 0.5  [get_ports {a[36]}]
set_input_transition -max 0.5  [get_ports {a[35]}]
set_input_transition -min 0.5  [get_ports {a[35]}]
set_input_transition -max 0.5  [get_ports {a[34]}]
set_input_transition -min 0.5  [get_ports {a[34]}]
set_input_transition -max 0.5  [get_ports {a[33]}]
set_input_transition -min 0.5  [get_ports {a[33]}]
set_input_transition -max 0.5  [get_ports {a[32]}]
set_input_transition -min 0.5  [get_ports {a[32]}]
set_input_transition -max 0.5  [get_ports {a[31]}]
set_input_transition -min 0.5  [get_ports {a[31]}]
set_input_transition -max 0.5  [get_ports {a[30]}]
set_input_transition -min 0.5  [get_ports {a[30]}]
set_input_transition -max 0.5  [get_ports {a[29]}]
set_input_transition -min 0.5  [get_ports {a[29]}]
set_input_transition -max 0.5  [get_ports {a[28]}]
set_input_transition -min 0.5  [get_ports {a[28]}]
set_input_transition -max 0.5  [get_ports {a[27]}]
set_input_transition -min 0.5  [get_ports {a[27]}]
set_input_transition -max 0.5  [get_ports {a[26]}]
set_input_transition -min 0.5  [get_ports {a[26]}]
set_input_transition -max 0.5  [get_ports {a[25]}]
set_input_transition -min 0.5  [get_ports {a[25]}]
set_input_transition -max 0.5  [get_ports {a[24]}]
set_input_transition -min 0.5  [get_ports {a[24]}]
set_input_transition -max 0.5  [get_ports {a[23]}]
set_input_transition -min 0.5  [get_ports {a[23]}]
set_input_transition -max 0.5  [get_ports {a[22]}]
set_input_transition -min 0.5  [get_ports {a[22]}]
set_input_transition -max 0.5  [get_ports {a[21]}]
set_input_transition -min 0.5  [get_ports {a[21]}]
set_input_transition -max 0.5  [get_ports {a[20]}]
set_input_transition -min 0.5  [get_ports {a[20]}]
set_input_transition -max 0.5  [get_ports {a[19]}]
set_input_transition -min 0.5  [get_ports {a[19]}]
set_input_transition -max 0.5  [get_ports {a[18]}]
set_input_transition -min 0.5  [get_ports {a[18]}]
set_input_transition -max 0.5  [get_ports {a[17]}]
set_input_transition -min 0.5  [get_ports {a[17]}]
set_input_transition -max 0.5  [get_ports {a[16]}]
set_input_transition -min 0.5  [get_ports {a[16]}]
set_input_transition -max 0.5  [get_ports {a[15]}]
set_input_transition -min 0.5  [get_ports {a[15]}]
set_input_transition -max 0.5  [get_ports {a[14]}]
set_input_transition -min 0.5  [get_ports {a[14]}]
set_input_transition -max 0.5  [get_ports {a[13]}]
set_input_transition -min 0.5  [get_ports {a[13]}]
set_input_transition -max 0.5  [get_ports {a[12]}]
set_input_transition -min 0.5  [get_ports {a[12]}]
set_input_transition -max 0.5  [get_ports {a[11]}]
set_input_transition -min 0.5  [get_ports {a[11]}]
set_input_transition -max 0.5  [get_ports {a[10]}]
set_input_transition -min 0.5  [get_ports {a[10]}]
set_input_transition -max 0.5  [get_ports {a[9]}]
set_input_transition -min 0.5  [get_ports {a[9]}]
set_input_transition -max 0.5  [get_ports {a[8]}]
set_input_transition -min 0.5  [get_ports {a[8]}]
set_input_transition -max 0.5  [get_ports {a[7]}]
set_input_transition -min 0.5  [get_ports {a[7]}]
set_input_transition -max 0.5  [get_ports {a[6]}]
set_input_transition -min 0.5  [get_ports {a[6]}]
set_input_transition -max 0.5  [get_ports {a[5]}]
set_input_transition -min 0.5  [get_ports {a[5]}]
set_input_transition -max 0.5  [get_ports {a[4]}]
set_input_transition -min 0.5  [get_ports {a[4]}]
set_input_transition -max 0.5  [get_ports {a[3]}]
set_input_transition -min 0.5  [get_ports {a[3]}]
set_input_transition -max 0.5  [get_ports {a[2]}]
set_input_transition -min 0.5  [get_ports {a[2]}]
set_input_transition -max 0.5  [get_ports {a[1]}]
set_input_transition -min 0.5  [get_ports {a[1]}]
set_input_transition -max 0.5  [get_ports {a[0]}]
set_input_transition -min 0.5  [get_ports {a[0]}]
set_input_transition -max 0.5  [get_ports {b[61]}]
set_input_transition -min 0.5  [get_ports {b[61]}]
set_input_transition -max 0.5  [get_ports {b[60]}]
set_input_transition -min 0.5  [get_ports {b[60]}]
set_input_transition -max 0.5  [get_ports {b[59]}]
set_input_transition -min 0.5  [get_ports {b[59]}]
set_input_transition -max 0.5  [get_ports {b[58]}]
set_input_transition -min 0.5  [get_ports {b[58]}]
set_input_transition -max 0.5  [get_ports {b[57]}]
set_input_transition -min 0.5  [get_ports {b[57]}]
set_input_transition -max 0.5  [get_ports {b[56]}]
set_input_transition -min 0.5  [get_ports {b[56]}]
set_input_transition -max 0.5  [get_ports {b[55]}]
set_input_transition -min 0.5  [get_ports {b[55]}]
set_input_transition -max 0.5  [get_ports {b[54]}]
set_input_transition -min 0.5  [get_ports {b[54]}]
set_input_transition -max 0.5  [get_ports {b[53]}]
set_input_transition -min 0.5  [get_ports {b[53]}]
set_input_transition -max 0.5  [get_ports {b[52]}]
set_input_transition -min 0.5  [get_ports {b[52]}]
set_input_transition -max 0.5  [get_ports {b[51]}]
set_input_transition -min 0.5  [get_ports {b[51]}]
set_input_transition -max 0.5  [get_ports {b[50]}]
set_input_transition -min 0.5  [get_ports {b[50]}]
set_input_transition -max 0.5  [get_ports {b[49]}]
set_input_transition -min 0.5  [get_ports {b[49]}]
set_input_transition -max 0.5  [get_ports {b[48]}]
set_input_transition -min 0.5  [get_ports {b[48]}]
set_input_transition -max 0.5  [get_ports {b[47]}]
set_input_transition -min 0.5  [get_ports {b[47]}]
set_input_transition -max 0.5  [get_ports {b[46]}]
set_input_transition -min 0.5  [get_ports {b[46]}]
set_input_transition -max 0.5  [get_ports {b[45]}]
set_input_transition -min 0.5  [get_ports {b[45]}]
set_input_transition -max 0.5  [get_ports {b[44]}]
set_input_transition -min 0.5  [get_ports {b[44]}]
set_input_transition -max 0.5  [get_ports {b[43]}]
set_input_transition -min 0.5  [get_ports {b[43]}]
set_input_transition -max 0.5  [get_ports {b[42]}]
set_input_transition -min 0.5  [get_ports {b[42]}]
set_input_transition -max 0.5  [get_ports {b[41]}]
set_input_transition -min 0.5  [get_ports {b[41]}]
set_input_transition -max 0.5  [get_ports {b[40]}]
set_input_transition -min 0.5  [get_ports {b[40]}]
set_input_transition -max 0.5  [get_ports {b[39]}]
set_input_transition -min 0.5  [get_ports {b[39]}]
set_input_transition -max 0.5  [get_ports {b[38]}]
set_input_transition -min 0.5  [get_ports {b[38]}]
set_input_transition -max 0.5  [get_ports {b[37]}]
set_input_transition -min 0.5  [get_ports {b[37]}]
set_input_transition -max 0.5  [get_ports {b[36]}]
set_input_transition -min 0.5  [get_ports {b[36]}]
set_input_transition -max 0.5  [get_ports {b[35]}]
set_input_transition -min 0.5  [get_ports {b[35]}]
set_input_transition -max 0.5  [get_ports {b[34]}]
set_input_transition -min 0.5  [get_ports {b[34]}]
set_input_transition -max 0.5  [get_ports {b[33]}]
set_input_transition -min 0.5  [get_ports {b[33]}]
set_input_transition -max 0.5  [get_ports {b[32]}]
set_input_transition -min 0.5  [get_ports {b[32]}]
set_input_transition -max 0.5  [get_ports {b[31]}]
set_input_transition -min 0.5  [get_ports {b[31]}]
set_input_transition -max 0.5  [get_ports {b[30]}]
set_input_transition -min 0.5  [get_ports {b[30]}]
set_input_transition -max 0.5  [get_ports {b[29]}]
set_input_transition -min 0.5  [get_ports {b[29]}]
set_input_transition -max 0.5  [get_ports {b[28]}]
set_input_transition -min 0.5  [get_ports {b[28]}]
set_input_transition -max 0.5  [get_ports {b[27]}]
set_input_transition -min 0.5  [get_ports {b[27]}]
set_input_transition -max 0.5  [get_ports {b[26]}]
set_input_transition -min 0.5  [get_ports {b[26]}]
set_input_transition -max 0.5  [get_ports {b[25]}]
set_input_transition -min 0.5  [get_ports {b[25]}]
set_input_transition -max 0.5  [get_ports {b[24]}]
set_input_transition -min 0.5  [get_ports {b[24]}]
set_input_transition -max 0.5  [get_ports {b[23]}]
set_input_transition -min 0.5  [get_ports {b[23]}]
set_input_transition -max 0.5  [get_ports {b[22]}]
set_input_transition -min 0.5  [get_ports {b[22]}]
set_input_transition -max 0.5  [get_ports {b[21]}]
set_input_transition -min 0.5  [get_ports {b[21]}]
set_input_transition -max 0.5  [get_ports {b[20]}]
set_input_transition -min 0.5  [get_ports {b[20]}]
set_input_transition -max 0.5  [get_ports {b[19]}]
set_input_transition -min 0.5  [get_ports {b[19]}]
set_input_transition -max 0.5  [get_ports {b[18]}]
set_input_transition -min 0.5  [get_ports {b[18]}]
set_input_transition -max 0.5  [get_ports {b[17]}]
set_input_transition -min 0.5  [get_ports {b[17]}]
set_input_transition -max 0.5  [get_ports {b[16]}]
set_input_transition -min 0.5  [get_ports {b[16]}]
set_input_transition -max 0.5  [get_ports {b[15]}]
set_input_transition -min 0.5  [get_ports {b[15]}]
set_input_transition -max 0.5  [get_ports {b[14]}]
set_input_transition -min 0.5  [get_ports {b[14]}]
set_input_transition -max 0.5  [get_ports {b[13]}]
set_input_transition -min 0.5  [get_ports {b[13]}]
set_input_transition -max 0.5  [get_ports {b[12]}]
set_input_transition -min 0.5  [get_ports {b[12]}]
set_input_transition -max 0.5  [get_ports {b[11]}]
set_input_transition -min 0.5  [get_ports {b[11]}]
set_input_transition -max 0.5  [get_ports {b[10]}]
set_input_transition -min 0.5  [get_ports {b[10]}]
set_input_transition -max 0.5  [get_ports {b[9]}]
set_input_transition -min 0.5  [get_ports {b[9]}]
set_input_transition -max 0.5  [get_ports {b[8]}]
set_input_transition -min 0.5  [get_ports {b[8]}]
set_input_transition -max 0.5  [get_ports {b[7]}]
set_input_transition -min 0.5  [get_ports {b[7]}]
set_input_transition -max 0.5  [get_ports {b[6]}]
set_input_transition -min 0.5  [get_ports {b[6]}]
set_input_transition -max 0.5  [get_ports {b[5]}]
set_input_transition -min 0.5  [get_ports {b[5]}]
set_input_transition -max 0.5  [get_ports {b[4]}]
set_input_transition -min 0.5  [get_ports {b[4]}]
set_input_transition -max 0.5  [get_ports {b[3]}]
set_input_transition -min 0.5  [get_ports {b[3]}]
set_input_transition -max 0.5  [get_ports {b[2]}]
set_input_transition -min 0.5  [get_ports {b[2]}]
set_input_transition -max 0.5  [get_ports {b[1]}]
set_input_transition -min 0.5  [get_ports {b[1]}]
set_input_transition -max 0.5  [get_ports {b[0]}]
set_input_transition -min 0.5  [get_ports {b[0]}]
set_input_transition -max 0.5  [get_ports {p[61]}]
set_input_transition -min 0.5  [get_ports {p[61]}]
set_input_transition -max 0.5  [get_ports {p[60]}]
set_input_transition -min 0.5  [get_ports {p[60]}]
set_input_transition -max 0.5  [get_ports {p[59]}]
set_input_transition -min 0.5  [get_ports {p[59]}]
set_input_transition -max 0.5  [get_ports {p[58]}]
set_input_transition -min 0.5  [get_ports {p[58]}]
set_input_transition -max 0.5  [get_ports {p[57]}]
set_input_transition -min 0.5  [get_ports {p[57]}]
set_input_transition -max 0.5  [get_ports {p[56]}]
set_input_transition -min 0.5  [get_ports {p[56]}]
set_input_transition -max 0.5  [get_ports {p[55]}]
set_input_transition -min 0.5  [get_ports {p[55]}]
set_input_transition -max 0.5  [get_ports {p[54]}]
set_input_transition -min 0.5  [get_ports {p[54]}]
set_input_transition -max 0.5  [get_ports {p[53]}]
set_input_transition -min 0.5  [get_ports {p[53]}]
set_input_transition -max 0.5  [get_ports {p[52]}]
set_input_transition -min 0.5  [get_ports {p[52]}]
set_input_transition -max 0.5  [get_ports {p[51]}]
set_input_transition -min 0.5  [get_ports {p[51]}]
set_input_transition -max 0.5  [get_ports {p[50]}]
set_input_transition -min 0.5  [get_ports {p[50]}]
set_input_transition -max 0.5  [get_ports {p[49]}]
set_input_transition -min 0.5  [get_ports {p[49]}]
set_input_transition -max 0.5  [get_ports {p[48]}]
set_input_transition -min 0.5  [get_ports {p[48]}]
set_input_transition -max 0.5  [get_ports {p[47]}]
set_input_transition -min 0.5  [get_ports {p[47]}]
set_input_transition -max 0.5  [get_ports {p[46]}]
set_input_transition -min 0.5  [get_ports {p[46]}]
set_input_transition -max 0.5  [get_ports {p[45]}]
set_input_transition -min 0.5  [get_ports {p[45]}]
set_input_transition -max 0.5  [get_ports {p[44]}]
set_input_transition -min 0.5  [get_ports {p[44]}]
set_input_transition -max 0.5  [get_ports {p[43]}]
set_input_transition -min 0.5  [get_ports {p[43]}]
set_input_transition -max 0.5  [get_ports {p[42]}]
set_input_transition -min 0.5  [get_ports {p[42]}]
set_input_transition -max 0.5  [get_ports {p[41]}]
set_input_transition -min 0.5  [get_ports {p[41]}]
set_input_transition -max 0.5  [get_ports {p[40]}]
set_input_transition -min 0.5  [get_ports {p[40]}]
set_input_transition -max 0.5  [get_ports {p[39]}]
set_input_transition -min 0.5  [get_ports {p[39]}]
set_input_transition -max 0.5  [get_ports {p[38]}]
set_input_transition -min 0.5  [get_ports {p[38]}]
set_input_transition -max 0.5  [get_ports {p[37]}]
set_input_transition -min 0.5  [get_ports {p[37]}]
set_input_transition -max 0.5  [get_ports {p[36]}]
set_input_transition -min 0.5  [get_ports {p[36]}]
set_input_transition -max 0.5  [get_ports {p[35]}]
set_input_transition -min 0.5  [get_ports {p[35]}]
set_input_transition -max 0.5  [get_ports {p[34]}]
set_input_transition -min 0.5  [get_ports {p[34]}]
set_input_transition -max 0.5  [get_ports {p[33]}]
set_input_transition -min 0.5  [get_ports {p[33]}]
set_input_transition -max 0.5  [get_ports {p[32]}]
set_input_transition -min 0.5  [get_ports {p[32]}]
set_input_transition -max 0.5  [get_ports {p[31]}]
set_input_transition -min 0.5  [get_ports {p[31]}]
set_input_transition -max 0.5  [get_ports {p[30]}]
set_input_transition -min 0.5  [get_ports {p[30]}]
set_input_transition -max 0.5  [get_ports {p[29]}]
set_input_transition -min 0.5  [get_ports {p[29]}]
set_input_transition -max 0.5  [get_ports {p[28]}]
set_input_transition -min 0.5  [get_ports {p[28]}]
set_input_transition -max 0.5  [get_ports {p[27]}]
set_input_transition -min 0.5  [get_ports {p[27]}]
set_input_transition -max 0.5  [get_ports {p[26]}]
set_input_transition -min 0.5  [get_ports {p[26]}]
set_input_transition -max 0.5  [get_ports {p[25]}]
set_input_transition -min 0.5  [get_ports {p[25]}]
set_input_transition -max 0.5  [get_ports {p[24]}]
set_input_transition -min 0.5  [get_ports {p[24]}]
set_input_transition -max 0.5  [get_ports {p[23]}]
set_input_transition -min 0.5  [get_ports {p[23]}]
set_input_transition -max 0.5  [get_ports {p[22]}]
set_input_transition -min 0.5  [get_ports {p[22]}]
set_input_transition -max 0.5  [get_ports {p[21]}]
set_input_transition -min 0.5  [get_ports {p[21]}]
set_input_transition -max 0.5  [get_ports {p[20]}]
set_input_transition -min 0.5  [get_ports {p[20]}]
set_input_transition -max 0.5  [get_ports {p[19]}]
set_input_transition -min 0.5  [get_ports {p[19]}]
set_input_transition -max 0.5  [get_ports {p[18]}]
set_input_transition -min 0.5  [get_ports {p[18]}]
set_input_transition -max 0.5  [get_ports {p[17]}]
set_input_transition -min 0.5  [get_ports {p[17]}]
set_input_transition -max 0.5  [get_ports {p[16]}]
set_input_transition -min 0.5  [get_ports {p[16]}]
set_input_transition -max 0.5  [get_ports {p[15]}]
set_input_transition -min 0.5  [get_ports {p[15]}]
set_input_transition -max 0.5  [get_ports {p[14]}]
set_input_transition -min 0.5  [get_ports {p[14]}]
set_input_transition -max 0.5  [get_ports {p[13]}]
set_input_transition -min 0.5  [get_ports {p[13]}]
set_input_transition -max 0.5  [get_ports {p[12]}]
set_input_transition -min 0.5  [get_ports {p[12]}]
set_input_transition -max 0.5  [get_ports {p[11]}]
set_input_transition -min 0.5  [get_ports {p[11]}]
set_input_transition -max 0.5  [get_ports {p[10]}]
set_input_transition -min 0.5  [get_ports {p[10]}]
set_input_transition -max 0.5  [get_ports {p[9]}]
set_input_transition -min 0.5  [get_ports {p[9]}]
set_input_transition -max 0.5  [get_ports {p[8]}]
set_input_transition -min 0.5  [get_ports {p[8]}]
set_input_transition -max 0.5  [get_ports {p[7]}]
set_input_transition -min 0.5  [get_ports {p[7]}]
set_input_transition -max 0.5  [get_ports {p[6]}]
set_input_transition -min 0.5  [get_ports {p[6]}]
set_input_transition -max 0.5  [get_ports {p[5]}]
set_input_transition -min 0.5  [get_ports {p[5]}]
set_input_transition -max 0.5  [get_ports {p[4]}]
set_input_transition -min 0.5  [get_ports {p[4]}]
set_input_transition -max 0.5  [get_ports {p[3]}]
set_input_transition -min 0.5  [get_ports {p[3]}]
set_input_transition -max 0.5  [get_ports {p[2]}]
set_input_transition -min 0.5  [get_ports {p[2]}]
set_input_transition -max 0.5  [get_ports {p[1]}]
set_input_transition -min 0.5  [get_ports {p[1]}]
set_input_transition -max 0.5  [get_ports {p[0]}]
set_input_transition -min 0.5  [get_ports {p[0]}]
set_input_transition -max 0.5  [get_ports {p0i[61]}]
set_input_transition -min 0.5  [get_ports {p0i[61]}]
set_input_transition -max 0.5  [get_ports {p0i[60]}]
set_input_transition -min 0.5  [get_ports {p0i[60]}]
set_input_transition -max 0.5  [get_ports {p0i[59]}]
set_input_transition -min 0.5  [get_ports {p0i[59]}]
set_input_transition -max 0.5  [get_ports {p0i[58]}]
set_input_transition -min 0.5  [get_ports {p0i[58]}]
set_input_transition -max 0.5  [get_ports {p0i[57]}]
set_input_transition -min 0.5  [get_ports {p0i[57]}]
set_input_transition -max 0.5  [get_ports {p0i[56]}]
set_input_transition -min 0.5  [get_ports {p0i[56]}]
set_input_transition -max 0.5  [get_ports {p0i[55]}]
set_input_transition -min 0.5  [get_ports {p0i[55]}]
set_input_transition -max 0.5  [get_ports {p0i[54]}]
set_input_transition -min 0.5  [get_ports {p0i[54]}]
set_input_transition -max 0.5  [get_ports {p0i[53]}]
set_input_transition -min 0.5  [get_ports {p0i[53]}]
set_input_transition -max 0.5  [get_ports {p0i[52]}]
set_input_transition -min 0.5  [get_ports {p0i[52]}]
set_input_transition -max 0.5  [get_ports {p0i[51]}]
set_input_transition -min 0.5  [get_ports {p0i[51]}]
set_input_transition -max 0.5  [get_ports {p0i[50]}]
set_input_transition -min 0.5  [get_ports {p0i[50]}]
set_input_transition -max 0.5  [get_ports {p0i[49]}]
set_input_transition -min 0.5  [get_ports {p0i[49]}]
set_input_transition -max 0.5  [get_ports {p0i[48]}]
set_input_transition -min 0.5  [get_ports {p0i[48]}]
set_input_transition -max 0.5  [get_ports {p0i[47]}]
set_input_transition -min 0.5  [get_ports {p0i[47]}]
set_input_transition -max 0.5  [get_ports {p0i[46]}]
set_input_transition -min 0.5  [get_ports {p0i[46]}]
set_input_transition -max 0.5  [get_ports {p0i[45]}]
set_input_transition -min 0.5  [get_ports {p0i[45]}]
set_input_transition -max 0.5  [get_ports {p0i[44]}]
set_input_transition -min 0.5  [get_ports {p0i[44]}]
set_input_transition -max 0.5  [get_ports {p0i[43]}]
set_input_transition -min 0.5  [get_ports {p0i[43]}]
set_input_transition -max 0.5  [get_ports {p0i[42]}]
set_input_transition -min 0.5  [get_ports {p0i[42]}]
set_input_transition -max 0.5  [get_ports {p0i[41]}]
set_input_transition -min 0.5  [get_ports {p0i[41]}]
set_input_transition -max 0.5  [get_ports {p0i[40]}]
set_input_transition -min 0.5  [get_ports {p0i[40]}]
set_input_transition -max 0.5  [get_ports {p0i[39]}]
set_input_transition -min 0.5  [get_ports {p0i[39]}]
set_input_transition -max 0.5  [get_ports {p0i[38]}]
set_input_transition -min 0.5  [get_ports {p0i[38]}]
set_input_transition -max 0.5  [get_ports {p0i[37]}]
set_input_transition -min 0.5  [get_ports {p0i[37]}]
set_input_transition -max 0.5  [get_ports {p0i[36]}]
set_input_transition -min 0.5  [get_ports {p0i[36]}]
set_input_transition -max 0.5  [get_ports {p0i[35]}]
set_input_transition -min 0.5  [get_ports {p0i[35]}]
set_input_transition -max 0.5  [get_ports {p0i[34]}]
set_input_transition -min 0.5  [get_ports {p0i[34]}]
set_input_transition -max 0.5  [get_ports {p0i[33]}]
set_input_transition -min 0.5  [get_ports {p0i[33]}]
set_input_transition -max 0.5  [get_ports {p0i[32]}]
set_input_transition -min 0.5  [get_ports {p0i[32]}]
set_input_transition -max 0.5  [get_ports {p0i[31]}]
set_input_transition -min 0.5  [get_ports {p0i[31]}]
set_input_transition -max 0.5  [get_ports {p0i[30]}]
set_input_transition -min 0.5  [get_ports {p0i[30]}]
set_input_transition -max 0.5  [get_ports {p0i[29]}]
set_input_transition -min 0.5  [get_ports {p0i[29]}]
set_input_transition -max 0.5  [get_ports {p0i[28]}]
set_input_transition -min 0.5  [get_ports {p0i[28]}]
set_input_transition -max 0.5  [get_ports {p0i[27]}]
set_input_transition -min 0.5  [get_ports {p0i[27]}]
set_input_transition -max 0.5  [get_ports {p0i[26]}]
set_input_transition -min 0.5  [get_ports {p0i[26]}]
set_input_transition -max 0.5  [get_ports {p0i[25]}]
set_input_transition -min 0.5  [get_ports {p0i[25]}]
set_input_transition -max 0.5  [get_ports {p0i[24]}]
set_input_transition -min 0.5  [get_ports {p0i[24]}]
set_input_transition -max 0.5  [get_ports {p0i[23]}]
set_input_transition -min 0.5  [get_ports {p0i[23]}]
set_input_transition -max 0.5  [get_ports {p0i[22]}]
set_input_transition -min 0.5  [get_ports {p0i[22]}]
set_input_transition -max 0.5  [get_ports {p0i[21]}]
set_input_transition -min 0.5  [get_ports {p0i[21]}]
set_input_transition -max 0.5  [get_ports {p0i[20]}]
set_input_transition -min 0.5  [get_ports {p0i[20]}]
set_input_transition -max 0.5  [get_ports {p0i[19]}]
set_input_transition -min 0.5  [get_ports {p0i[19]}]
set_input_transition -max 0.5  [get_ports {p0i[18]}]
set_input_transition -min 0.5  [get_ports {p0i[18]}]
set_input_transition -max 0.5  [get_ports {p0i[17]}]
set_input_transition -min 0.5  [get_ports {p0i[17]}]
set_input_transition -max 0.5  [get_ports {p0i[16]}]
set_input_transition -min 0.5  [get_ports {p0i[16]}]
set_input_transition -max 0.5  [get_ports {p0i[15]}]
set_input_transition -min 0.5  [get_ports {p0i[15]}]
set_input_transition -max 0.5  [get_ports {p0i[14]}]
set_input_transition -min 0.5  [get_ports {p0i[14]}]
set_input_transition -max 0.5  [get_ports {p0i[13]}]
set_input_transition -min 0.5  [get_ports {p0i[13]}]
set_input_transition -max 0.5  [get_ports {p0i[12]}]
set_input_transition -min 0.5  [get_ports {p0i[12]}]
set_input_transition -max 0.5  [get_ports {p0i[11]}]
set_input_transition -min 0.5  [get_ports {p0i[11]}]
set_input_transition -max 0.5  [get_ports {p0i[10]}]
set_input_transition -min 0.5  [get_ports {p0i[10]}]
set_input_transition -max 0.5  [get_ports {p0i[9]}]
set_input_transition -min 0.5  [get_ports {p0i[9]}]
set_input_transition -max 0.5  [get_ports {p0i[8]}]
set_input_transition -min 0.5  [get_ports {p0i[8]}]
set_input_transition -max 0.5  [get_ports {p0i[7]}]
set_input_transition -min 0.5  [get_ports {p0i[7]}]
set_input_transition -max 0.5  [get_ports {p0i[6]}]
set_input_transition -min 0.5  [get_ports {p0i[6]}]
set_input_transition -max 0.5  [get_ports {p0i[5]}]
set_input_transition -min 0.5  [get_ports {p0i[5]}]
set_input_transition -max 0.5  [get_ports {p0i[4]}]
set_input_transition -min 0.5  [get_ports {p0i[4]}]
set_input_transition -max 0.5  [get_ports {p0i[3]}]
set_input_transition -min 0.5  [get_ports {p0i[3]}]
set_input_transition -max 0.5  [get_ports {p0i[2]}]
set_input_transition -min 0.5  [get_ports {p0i[2]}]
set_input_transition -max 0.5  [get_ports {p0i[1]}]
set_input_transition -min 0.5  [get_ports {p0i[1]}]
set_input_transition -max 0.5  [get_ports {p0i[0]}]
set_input_transition -min 0.5  [get_ports {p0i[0]}]
set_input_transition -max 0.5  [get_ports isMQ]
set_input_transition -min 0.5  [get_ports isMQ]
set_input_transition -max 0.5  [get_ports {i_bus[1]}]
set_input_transition -min 0.5  [get_ports {i_bus[1]}]
set_input_transition -max 0.5  [get_ports {i_bus[2]}]
set_input_transition -min 0.5  [get_ports {i_bus[2]}]
