###################################################################

# Created by write_sdc on Fri Oct  3 02:11:42 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name Small -library                                       \
sc9_cln40g_base_rvt_ss_typical_max_0p81v_125c
set_load -pin_load 0.05 [get_ports {out_valid_bus[2]}]
set_load -pin_load 0.05 [get_ports {out_valid_bus[1]}]
set_load -pin_load 0.05 [get_ports {out_valid_bus[0]}]
set_load -pin_load 0.05 [get_ports {R2_bus[92]}]
set_load -pin_load 0.05 [get_ports {R2_bus[91]}]
set_load -pin_load 0.05 [get_ports {R2_bus[90]}]
set_load -pin_load 0.05 [get_ports {R2_bus[89]}]
set_load -pin_load 0.05 [get_ports {R2_bus[88]}]
set_load -pin_load 0.05 [get_ports {R2_bus[87]}]
set_load -pin_load 0.05 [get_ports {R2_bus[86]}]
set_load -pin_load 0.05 [get_ports {R2_bus[85]}]
set_load -pin_load 0.05 [get_ports {R2_bus[84]}]
set_load -pin_load 0.05 [get_ports {R2_bus[83]}]
set_load -pin_load 0.05 [get_ports {R2_bus[82]}]
set_load -pin_load 0.05 [get_ports {R2_bus[81]}]
set_load -pin_load 0.05 [get_ports {R2_bus[80]}]
set_load -pin_load 0.05 [get_ports {R2_bus[79]}]
set_load -pin_load 0.05 [get_ports {R2_bus[78]}]
set_load -pin_load 0.05 [get_ports {R2_bus[77]}]
set_load -pin_load 0.05 [get_ports {R2_bus[76]}]
set_load -pin_load 0.05 [get_ports {R2_bus[75]}]
set_load -pin_load 0.05 [get_ports {R2_bus[74]}]
set_load -pin_load 0.05 [get_ports {R2_bus[73]}]
set_load -pin_load 0.05 [get_ports {R2_bus[72]}]
set_load -pin_load 0.05 [get_ports {R2_bus[71]}]
set_load -pin_load 0.05 [get_ports {R2_bus[70]}]
set_load -pin_load 0.05 [get_ports {R2_bus[69]}]
set_load -pin_load 0.05 [get_ports {R2_bus[68]}]
set_load -pin_load 0.05 [get_ports {R2_bus[67]}]
set_load -pin_load 0.05 [get_ports {R2_bus[66]}]
set_load -pin_load 0.05 [get_ports {R2_bus[65]}]
set_load -pin_load 0.05 [get_ports {R2_bus[64]}]
set_load -pin_load 0.05 [get_ports {R2_bus[63]}]
set_load -pin_load 0.05 [get_ports {R2_bus[62]}]
set_load -pin_load 0.05 [get_ports {R2_bus[61]}]
set_load -pin_load 0.05 [get_ports {R2_bus[60]}]
set_load -pin_load 0.05 [get_ports {R2_bus[59]}]
set_load -pin_load 0.05 [get_ports {R2_bus[58]}]
set_load -pin_load 0.05 [get_ports {R2_bus[57]}]
set_load -pin_load 0.05 [get_ports {R2_bus[56]}]
set_load -pin_load 0.05 [get_ports {R2_bus[55]}]
set_load -pin_load 0.05 [get_ports {R2_bus[54]}]
set_load -pin_load 0.05 [get_ports {R2_bus[53]}]
set_load -pin_load 0.05 [get_ports {R2_bus[52]}]
set_load -pin_load 0.05 [get_ports {R2_bus[51]}]
set_load -pin_load 0.05 [get_ports {R2_bus[50]}]
set_load -pin_load 0.05 [get_ports {R2_bus[49]}]
set_load -pin_load 0.05 [get_ports {R2_bus[48]}]
set_load -pin_load 0.05 [get_ports {R2_bus[47]}]
set_load -pin_load 0.05 [get_ports {R2_bus[46]}]
set_load -pin_load 0.05 [get_ports {R2_bus[45]}]
set_load -pin_load 0.05 [get_ports {R2_bus[44]}]
set_load -pin_load 0.05 [get_ports {R2_bus[43]}]
set_load -pin_load 0.05 [get_ports {R2_bus[42]}]
set_load -pin_load 0.05 [get_ports {R2_bus[41]}]
set_load -pin_load 0.05 [get_ports {R2_bus[40]}]
set_load -pin_load 0.05 [get_ports {R2_bus[39]}]
set_load -pin_load 0.05 [get_ports {R2_bus[38]}]
set_load -pin_load 0.05 [get_ports {R2_bus[37]}]
set_load -pin_load 0.05 [get_ports {R2_bus[36]}]
set_load -pin_load 0.05 [get_ports {R2_bus[35]}]
set_load -pin_load 0.05 [get_ports {R2_bus[34]}]
set_load -pin_load 0.05 [get_ports {R2_bus[33]}]
set_load -pin_load 0.05 [get_ports {R2_bus[32]}]
set_load -pin_load 0.05 [get_ports {R2_bus[31]}]
set_load -pin_load 0.05 [get_ports {R2_bus[30]}]
set_load -pin_load 0.05 [get_ports {R2_bus[29]}]
set_load -pin_load 0.05 [get_ports {R2_bus[28]}]
set_load -pin_load 0.05 [get_ports {R2_bus[27]}]
set_load -pin_load 0.05 [get_ports {R2_bus[26]}]
set_load -pin_load 0.05 [get_ports {R2_bus[25]}]
set_load -pin_load 0.05 [get_ports {R2_bus[24]}]
set_load -pin_load 0.05 [get_ports {R2_bus[23]}]
set_load -pin_load 0.05 [get_ports {R2_bus[22]}]
set_load -pin_load 0.05 [get_ports {R2_bus[21]}]
set_load -pin_load 0.05 [get_ports {R2_bus[20]}]
set_load -pin_load 0.05 [get_ports {R2_bus[19]}]
set_load -pin_load 0.05 [get_ports {R2_bus[18]}]
set_load -pin_load 0.05 [get_ports {R2_bus[17]}]
set_load -pin_load 0.05 [get_ports {R2_bus[16]}]
set_load -pin_load 0.05 [get_ports {R2_bus[15]}]
set_load -pin_load 0.05 [get_ports {R2_bus[14]}]
set_load -pin_load 0.05 [get_ports {R2_bus[13]}]
set_load -pin_load 0.05 [get_ports {R2_bus[12]}]
set_load -pin_load 0.05 [get_ports {R2_bus[11]}]
set_load -pin_load 0.05 [get_ports {R2_bus[10]}]
set_load -pin_load 0.05 [get_ports {R2_bus[9]}]
set_load -pin_load 0.05 [get_ports {R2_bus[8]}]
set_load -pin_load 0.05 [get_ports {R2_bus[7]}]
set_load -pin_load 0.05 [get_ports {R2_bus[6]}]
set_load -pin_load 0.05 [get_ports {R2_bus[5]}]
set_load -pin_load 0.05 [get_ports {R2_bus[4]}]
set_load -pin_load 0.05 [get_ports {R2_bus[3]}]
set_load -pin_load 0.05 [get_ports {R2_bus[2]}]
set_load -pin_load 0.05 [get_ports {R2_bus[1]}]
set_load -pin_load 0.05 [get_ports {R2_bus[0]}]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports {in_valid_bus[2]}]
set_max_capacitance 0.15 [get_ports {in_valid_bus[1]}]
set_max_capacitance 0.15 [get_ports {in_valid_bus[0]}]
set_max_capacitance 0.15 [get_ports {p_bus[92]}]
set_max_capacitance 0.15 [get_ports {p_bus[91]}]
set_max_capacitance 0.15 [get_ports {p_bus[90]}]
set_max_capacitance 0.15 [get_ports {p_bus[89]}]
set_max_capacitance 0.15 [get_ports {p_bus[88]}]
set_max_capacitance 0.15 [get_ports {p_bus[87]}]
set_max_capacitance 0.15 [get_ports {p_bus[86]}]
set_max_capacitance 0.15 [get_ports {p_bus[85]}]
set_max_capacitance 0.15 [get_ports {p_bus[84]}]
set_max_capacitance 0.15 [get_ports {p_bus[83]}]
set_max_capacitance 0.15 [get_ports {p_bus[82]}]
set_max_capacitance 0.15 [get_ports {p_bus[81]}]
set_max_capacitance 0.15 [get_ports {p_bus[80]}]
set_max_capacitance 0.15 [get_ports {p_bus[79]}]
set_max_capacitance 0.15 [get_ports {p_bus[78]}]
set_max_capacitance 0.15 [get_ports {p_bus[77]}]
set_max_capacitance 0.15 [get_ports {p_bus[76]}]
set_max_capacitance 0.15 [get_ports {p_bus[75]}]
set_max_capacitance 0.15 [get_ports {p_bus[74]}]
set_max_capacitance 0.15 [get_ports {p_bus[73]}]
set_max_capacitance 0.15 [get_ports {p_bus[72]}]
set_max_capacitance 0.15 [get_ports {p_bus[71]}]
set_max_capacitance 0.15 [get_ports {p_bus[70]}]
set_max_capacitance 0.15 [get_ports {p_bus[69]}]
set_max_capacitance 0.15 [get_ports {p_bus[68]}]
set_max_capacitance 0.15 [get_ports {p_bus[67]}]
set_max_capacitance 0.15 [get_ports {p_bus[66]}]
set_max_capacitance 0.15 [get_ports {p_bus[65]}]
set_max_capacitance 0.15 [get_ports {p_bus[64]}]
set_max_capacitance 0.15 [get_ports {p_bus[63]}]
set_max_capacitance 0.15 [get_ports {p_bus[62]}]
set_max_capacitance 0.15 [get_ports {p_bus[61]}]
set_max_capacitance 0.15 [get_ports {p_bus[60]}]
set_max_capacitance 0.15 [get_ports {p_bus[59]}]
set_max_capacitance 0.15 [get_ports {p_bus[58]}]
set_max_capacitance 0.15 [get_ports {p_bus[57]}]
set_max_capacitance 0.15 [get_ports {p_bus[56]}]
set_max_capacitance 0.15 [get_ports {p_bus[55]}]
set_max_capacitance 0.15 [get_ports {p_bus[54]}]
set_max_capacitance 0.15 [get_ports {p_bus[53]}]
set_max_capacitance 0.15 [get_ports {p_bus[52]}]
set_max_capacitance 0.15 [get_ports {p_bus[51]}]
set_max_capacitance 0.15 [get_ports {p_bus[50]}]
set_max_capacitance 0.15 [get_ports {p_bus[49]}]
set_max_capacitance 0.15 [get_ports {p_bus[48]}]
set_max_capacitance 0.15 [get_ports {p_bus[47]}]
set_max_capacitance 0.15 [get_ports {p_bus[46]}]
set_max_capacitance 0.15 [get_ports {p_bus[45]}]
set_max_capacitance 0.15 [get_ports {p_bus[44]}]
set_max_capacitance 0.15 [get_ports {p_bus[43]}]
set_max_capacitance 0.15 [get_ports {p_bus[42]}]
set_max_capacitance 0.15 [get_ports {p_bus[41]}]
set_max_capacitance 0.15 [get_ports {p_bus[40]}]
set_max_capacitance 0.15 [get_ports {p_bus[39]}]
set_max_capacitance 0.15 [get_ports {p_bus[38]}]
set_max_capacitance 0.15 [get_ports {p_bus[37]}]
set_max_capacitance 0.15 [get_ports {p_bus[36]}]
set_max_capacitance 0.15 [get_ports {p_bus[35]}]
set_max_capacitance 0.15 [get_ports {p_bus[34]}]
set_max_capacitance 0.15 [get_ports {p_bus[33]}]
set_max_capacitance 0.15 [get_ports {p_bus[32]}]
set_max_capacitance 0.15 [get_ports {p_bus[31]}]
set_max_capacitance 0.15 [get_ports {p_bus[30]}]
set_max_capacitance 0.15 [get_ports {p_bus[29]}]
set_max_capacitance 0.15 [get_ports {p_bus[28]}]
set_max_capacitance 0.15 [get_ports {p_bus[27]}]
set_max_capacitance 0.15 [get_ports {p_bus[26]}]
set_max_capacitance 0.15 [get_ports {p_bus[25]}]
set_max_capacitance 0.15 [get_ports {p_bus[24]}]
set_max_capacitance 0.15 [get_ports {p_bus[23]}]
set_max_capacitance 0.15 [get_ports {p_bus[22]}]
set_max_capacitance 0.15 [get_ports {p_bus[21]}]
set_max_capacitance 0.15 [get_ports {p_bus[20]}]
set_max_capacitance 0.15 [get_ports {p_bus[19]}]
set_max_capacitance 0.15 [get_ports {p_bus[18]}]
set_max_capacitance 0.15 [get_ports {p_bus[17]}]
set_max_capacitance 0.15 [get_ports {p_bus[16]}]
set_max_capacitance 0.15 [get_ports {p_bus[15]}]
set_max_capacitance 0.15 [get_ports {p_bus[14]}]
set_max_capacitance 0.15 [get_ports {p_bus[13]}]
set_max_capacitance 0.15 [get_ports {p_bus[12]}]
set_max_capacitance 0.15 [get_ports {p_bus[11]}]
set_max_capacitance 0.15 [get_ports {p_bus[10]}]
set_max_capacitance 0.15 [get_ports {p_bus[9]}]
set_max_capacitance 0.15 [get_ports {p_bus[8]}]
set_max_capacitance 0.15 [get_ports {p_bus[7]}]
set_max_capacitance 0.15 [get_ports {p_bus[6]}]
set_max_capacitance 0.15 [get_ports {p_bus[5]}]
set_max_capacitance 0.15 [get_ports {p_bus[4]}]
set_max_capacitance 0.15 [get_ports {p_bus[3]}]
set_max_capacitance 0.15 [get_ports {p_bus[2]}]
set_max_capacitance 0.15 [get_ports {p_bus[1]}]
set_max_capacitance 0.15 [get_ports {p_bus[0]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[92]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[91]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[90]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[89]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[88]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[87]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[86]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[85]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[84]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[83]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[82]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[81]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[80]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[79]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[78]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[77]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[76]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[75]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[74]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[73]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[72]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[71]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[70]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[69]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[68]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[67]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[66]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[65]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[64]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[63]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[62]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[61]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[60]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[59]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[58]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[57]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[56]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[55]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[54]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[53]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[52]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[51]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[50]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[49]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[48]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[47]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[46]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[45]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[44]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[43]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[42]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[41]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[40]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[39]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[38]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[37]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[36]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[35]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[34]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[33]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[32]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[31]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[30]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[29]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[28]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[27]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[26]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[25]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[24]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[23]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[22]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[21]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[20]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[19]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[18]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[17]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[16]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[15]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[14]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[13]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[12]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[11]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[10]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[9]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[8]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[7]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[6]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[5]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[4]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[3]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[2]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[1]}]
set_max_capacitance 0.15 [get_ports {p0i_bus[0]}]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports {in_valid_bus[2]}]
set_max_fanout 10 [get_ports {in_valid_bus[1]}]
set_max_fanout 10 [get_ports {in_valid_bus[0]}]
set_max_fanout 10 [get_ports {p_bus[92]}]
set_max_fanout 10 [get_ports {p_bus[91]}]
set_max_fanout 10 [get_ports {p_bus[90]}]
set_max_fanout 10 [get_ports {p_bus[89]}]
set_max_fanout 10 [get_ports {p_bus[88]}]
set_max_fanout 10 [get_ports {p_bus[87]}]
set_max_fanout 10 [get_ports {p_bus[86]}]
set_max_fanout 10 [get_ports {p_bus[85]}]
set_max_fanout 10 [get_ports {p_bus[84]}]
set_max_fanout 10 [get_ports {p_bus[83]}]
set_max_fanout 10 [get_ports {p_bus[82]}]
set_max_fanout 10 [get_ports {p_bus[81]}]
set_max_fanout 10 [get_ports {p_bus[80]}]
set_max_fanout 10 [get_ports {p_bus[79]}]
set_max_fanout 10 [get_ports {p_bus[78]}]
set_max_fanout 10 [get_ports {p_bus[77]}]
set_max_fanout 10 [get_ports {p_bus[76]}]
set_max_fanout 10 [get_ports {p_bus[75]}]
set_max_fanout 10 [get_ports {p_bus[74]}]
set_max_fanout 10 [get_ports {p_bus[73]}]
set_max_fanout 10 [get_ports {p_bus[72]}]
set_max_fanout 10 [get_ports {p_bus[71]}]
set_max_fanout 10 [get_ports {p_bus[70]}]
set_max_fanout 10 [get_ports {p_bus[69]}]
set_max_fanout 10 [get_ports {p_bus[68]}]
set_max_fanout 10 [get_ports {p_bus[67]}]
set_max_fanout 10 [get_ports {p_bus[66]}]
set_max_fanout 10 [get_ports {p_bus[65]}]
set_max_fanout 10 [get_ports {p_bus[64]}]
set_max_fanout 10 [get_ports {p_bus[63]}]
set_max_fanout 10 [get_ports {p_bus[62]}]
set_max_fanout 10 [get_ports {p_bus[61]}]
set_max_fanout 10 [get_ports {p_bus[60]}]
set_max_fanout 10 [get_ports {p_bus[59]}]
set_max_fanout 10 [get_ports {p_bus[58]}]
set_max_fanout 10 [get_ports {p_bus[57]}]
set_max_fanout 10 [get_ports {p_bus[56]}]
set_max_fanout 10 [get_ports {p_bus[55]}]
set_max_fanout 10 [get_ports {p_bus[54]}]
set_max_fanout 10 [get_ports {p_bus[53]}]
set_max_fanout 10 [get_ports {p_bus[52]}]
set_max_fanout 10 [get_ports {p_bus[51]}]
set_max_fanout 10 [get_ports {p_bus[50]}]
set_max_fanout 10 [get_ports {p_bus[49]}]
set_max_fanout 10 [get_ports {p_bus[48]}]
set_max_fanout 10 [get_ports {p_bus[47]}]
set_max_fanout 10 [get_ports {p_bus[46]}]
set_max_fanout 10 [get_ports {p_bus[45]}]
set_max_fanout 10 [get_ports {p_bus[44]}]
set_max_fanout 10 [get_ports {p_bus[43]}]
set_max_fanout 10 [get_ports {p_bus[42]}]
set_max_fanout 10 [get_ports {p_bus[41]}]
set_max_fanout 10 [get_ports {p_bus[40]}]
set_max_fanout 10 [get_ports {p_bus[39]}]
set_max_fanout 10 [get_ports {p_bus[38]}]
set_max_fanout 10 [get_ports {p_bus[37]}]
set_max_fanout 10 [get_ports {p_bus[36]}]
set_max_fanout 10 [get_ports {p_bus[35]}]
set_max_fanout 10 [get_ports {p_bus[34]}]
set_max_fanout 10 [get_ports {p_bus[33]}]
set_max_fanout 10 [get_ports {p_bus[32]}]
set_max_fanout 10 [get_ports {p_bus[31]}]
set_max_fanout 10 [get_ports {p_bus[30]}]
set_max_fanout 10 [get_ports {p_bus[29]}]
set_max_fanout 10 [get_ports {p_bus[28]}]
set_max_fanout 10 [get_ports {p_bus[27]}]
set_max_fanout 10 [get_ports {p_bus[26]}]
set_max_fanout 10 [get_ports {p_bus[25]}]
set_max_fanout 10 [get_ports {p_bus[24]}]
set_max_fanout 10 [get_ports {p_bus[23]}]
set_max_fanout 10 [get_ports {p_bus[22]}]
set_max_fanout 10 [get_ports {p_bus[21]}]
set_max_fanout 10 [get_ports {p_bus[20]}]
set_max_fanout 10 [get_ports {p_bus[19]}]
set_max_fanout 10 [get_ports {p_bus[18]}]
set_max_fanout 10 [get_ports {p_bus[17]}]
set_max_fanout 10 [get_ports {p_bus[16]}]
set_max_fanout 10 [get_ports {p_bus[15]}]
set_max_fanout 10 [get_ports {p_bus[14]}]
set_max_fanout 10 [get_ports {p_bus[13]}]
set_max_fanout 10 [get_ports {p_bus[12]}]
set_max_fanout 10 [get_ports {p_bus[11]}]
set_max_fanout 10 [get_ports {p_bus[10]}]
set_max_fanout 10 [get_ports {p_bus[9]}]
set_max_fanout 10 [get_ports {p_bus[8]}]
set_max_fanout 10 [get_ports {p_bus[7]}]
set_max_fanout 10 [get_ports {p_bus[6]}]
set_max_fanout 10 [get_ports {p_bus[5]}]
set_max_fanout 10 [get_ports {p_bus[4]}]
set_max_fanout 10 [get_ports {p_bus[3]}]
set_max_fanout 10 [get_ports {p_bus[2]}]
set_max_fanout 10 [get_ports {p_bus[1]}]
set_max_fanout 10 [get_ports {p_bus[0]}]
set_max_fanout 10 [get_ports {p0i_bus[92]}]
set_max_fanout 10 [get_ports {p0i_bus[91]}]
set_max_fanout 10 [get_ports {p0i_bus[90]}]
set_max_fanout 10 [get_ports {p0i_bus[89]}]
set_max_fanout 10 [get_ports {p0i_bus[88]}]
set_max_fanout 10 [get_ports {p0i_bus[87]}]
set_max_fanout 10 [get_ports {p0i_bus[86]}]
set_max_fanout 10 [get_ports {p0i_bus[85]}]
set_max_fanout 10 [get_ports {p0i_bus[84]}]
set_max_fanout 10 [get_ports {p0i_bus[83]}]
set_max_fanout 10 [get_ports {p0i_bus[82]}]
set_max_fanout 10 [get_ports {p0i_bus[81]}]
set_max_fanout 10 [get_ports {p0i_bus[80]}]
set_max_fanout 10 [get_ports {p0i_bus[79]}]
set_max_fanout 10 [get_ports {p0i_bus[78]}]
set_max_fanout 10 [get_ports {p0i_bus[77]}]
set_max_fanout 10 [get_ports {p0i_bus[76]}]
set_max_fanout 10 [get_ports {p0i_bus[75]}]
set_max_fanout 10 [get_ports {p0i_bus[74]}]
set_max_fanout 10 [get_ports {p0i_bus[73]}]
set_max_fanout 10 [get_ports {p0i_bus[72]}]
set_max_fanout 10 [get_ports {p0i_bus[71]}]
set_max_fanout 10 [get_ports {p0i_bus[70]}]
set_max_fanout 10 [get_ports {p0i_bus[69]}]
set_max_fanout 10 [get_ports {p0i_bus[68]}]
set_max_fanout 10 [get_ports {p0i_bus[67]}]
set_max_fanout 10 [get_ports {p0i_bus[66]}]
set_max_fanout 10 [get_ports {p0i_bus[65]}]
set_max_fanout 10 [get_ports {p0i_bus[64]}]
set_max_fanout 10 [get_ports {p0i_bus[63]}]
set_max_fanout 10 [get_ports {p0i_bus[62]}]
set_max_fanout 10 [get_ports {p0i_bus[61]}]
set_max_fanout 10 [get_ports {p0i_bus[60]}]
set_max_fanout 10 [get_ports {p0i_bus[59]}]
set_max_fanout 10 [get_ports {p0i_bus[58]}]
set_max_fanout 10 [get_ports {p0i_bus[57]}]
set_max_fanout 10 [get_ports {p0i_bus[56]}]
set_max_fanout 10 [get_ports {p0i_bus[55]}]
set_max_fanout 10 [get_ports {p0i_bus[54]}]
set_max_fanout 10 [get_ports {p0i_bus[53]}]
set_max_fanout 10 [get_ports {p0i_bus[52]}]
set_max_fanout 10 [get_ports {p0i_bus[51]}]
set_max_fanout 10 [get_ports {p0i_bus[50]}]
set_max_fanout 10 [get_ports {p0i_bus[49]}]
set_max_fanout 10 [get_ports {p0i_bus[48]}]
set_max_fanout 10 [get_ports {p0i_bus[47]}]
set_max_fanout 10 [get_ports {p0i_bus[46]}]
set_max_fanout 10 [get_ports {p0i_bus[45]}]
set_max_fanout 10 [get_ports {p0i_bus[44]}]
set_max_fanout 10 [get_ports {p0i_bus[43]}]
set_max_fanout 10 [get_ports {p0i_bus[42]}]
set_max_fanout 10 [get_ports {p0i_bus[41]}]
set_max_fanout 10 [get_ports {p0i_bus[40]}]
set_max_fanout 10 [get_ports {p0i_bus[39]}]
set_max_fanout 10 [get_ports {p0i_bus[38]}]
set_max_fanout 10 [get_ports {p0i_bus[37]}]
set_max_fanout 10 [get_ports {p0i_bus[36]}]
set_max_fanout 10 [get_ports {p0i_bus[35]}]
set_max_fanout 10 [get_ports {p0i_bus[34]}]
set_max_fanout 10 [get_ports {p0i_bus[33]}]
set_max_fanout 10 [get_ports {p0i_bus[32]}]
set_max_fanout 10 [get_ports {p0i_bus[31]}]
set_max_fanout 10 [get_ports {p0i_bus[30]}]
set_max_fanout 10 [get_ports {p0i_bus[29]}]
set_max_fanout 10 [get_ports {p0i_bus[28]}]
set_max_fanout 10 [get_ports {p0i_bus[27]}]
set_max_fanout 10 [get_ports {p0i_bus[26]}]
set_max_fanout 10 [get_ports {p0i_bus[25]}]
set_max_fanout 10 [get_ports {p0i_bus[24]}]
set_max_fanout 10 [get_ports {p0i_bus[23]}]
set_max_fanout 10 [get_ports {p0i_bus[22]}]
set_max_fanout 10 [get_ports {p0i_bus[21]}]
set_max_fanout 10 [get_ports {p0i_bus[20]}]
set_max_fanout 10 [get_ports {p0i_bus[19]}]
set_max_fanout 10 [get_ports {p0i_bus[18]}]
set_max_fanout 10 [get_ports {p0i_bus[17]}]
set_max_fanout 10 [get_ports {p0i_bus[16]}]
set_max_fanout 10 [get_ports {p0i_bus[15]}]
set_max_fanout 10 [get_ports {p0i_bus[14]}]
set_max_fanout 10 [get_ports {p0i_bus[13]}]
set_max_fanout 10 [get_ports {p0i_bus[12]}]
set_max_fanout 10 [get_ports {p0i_bus[11]}]
set_max_fanout 10 [get_ports {p0i_bus[10]}]
set_max_fanout 10 [get_ports {p0i_bus[9]}]
set_max_fanout 10 [get_ports {p0i_bus[8]}]
set_max_fanout 10 [get_ports {p0i_bus[7]}]
set_max_fanout 10 [get_ports {p0i_bus[6]}]
set_max_fanout 10 [get_ports {p0i_bus[5]}]
set_max_fanout 10 [get_ports {p0i_bus[4]}]
set_max_fanout 10 [get_ports {p0i_bus[3]}]
set_max_fanout 10 [get_ports {p0i_bus[2]}]
set_max_fanout 10 [get_ports {p0i_bus[1]}]
set_max_fanout 10 [get_ports {p0i_bus[0]}]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports {in_valid_bus[2]}]
set_max_transition 3 [get_ports {in_valid_bus[1]}]
set_max_transition 3 [get_ports {in_valid_bus[0]}]
set_max_transition 3 [get_ports {p_bus[92]}]
set_max_transition 3 [get_ports {p_bus[91]}]
set_max_transition 3 [get_ports {p_bus[90]}]
set_max_transition 3 [get_ports {p_bus[89]}]
set_max_transition 3 [get_ports {p_bus[88]}]
set_max_transition 3 [get_ports {p_bus[87]}]
set_max_transition 3 [get_ports {p_bus[86]}]
set_max_transition 3 [get_ports {p_bus[85]}]
set_max_transition 3 [get_ports {p_bus[84]}]
set_max_transition 3 [get_ports {p_bus[83]}]
set_max_transition 3 [get_ports {p_bus[82]}]
set_max_transition 3 [get_ports {p_bus[81]}]
set_max_transition 3 [get_ports {p_bus[80]}]
set_max_transition 3 [get_ports {p_bus[79]}]
set_max_transition 3 [get_ports {p_bus[78]}]
set_max_transition 3 [get_ports {p_bus[77]}]
set_max_transition 3 [get_ports {p_bus[76]}]
set_max_transition 3 [get_ports {p_bus[75]}]
set_max_transition 3 [get_ports {p_bus[74]}]
set_max_transition 3 [get_ports {p_bus[73]}]
set_max_transition 3 [get_ports {p_bus[72]}]
set_max_transition 3 [get_ports {p_bus[71]}]
set_max_transition 3 [get_ports {p_bus[70]}]
set_max_transition 3 [get_ports {p_bus[69]}]
set_max_transition 3 [get_ports {p_bus[68]}]
set_max_transition 3 [get_ports {p_bus[67]}]
set_max_transition 3 [get_ports {p_bus[66]}]
set_max_transition 3 [get_ports {p_bus[65]}]
set_max_transition 3 [get_ports {p_bus[64]}]
set_max_transition 3 [get_ports {p_bus[63]}]
set_max_transition 3 [get_ports {p_bus[62]}]
set_max_transition 3 [get_ports {p_bus[61]}]
set_max_transition 3 [get_ports {p_bus[60]}]
set_max_transition 3 [get_ports {p_bus[59]}]
set_max_transition 3 [get_ports {p_bus[58]}]
set_max_transition 3 [get_ports {p_bus[57]}]
set_max_transition 3 [get_ports {p_bus[56]}]
set_max_transition 3 [get_ports {p_bus[55]}]
set_max_transition 3 [get_ports {p_bus[54]}]
set_max_transition 3 [get_ports {p_bus[53]}]
set_max_transition 3 [get_ports {p_bus[52]}]
set_max_transition 3 [get_ports {p_bus[51]}]
set_max_transition 3 [get_ports {p_bus[50]}]
set_max_transition 3 [get_ports {p_bus[49]}]
set_max_transition 3 [get_ports {p_bus[48]}]
set_max_transition 3 [get_ports {p_bus[47]}]
set_max_transition 3 [get_ports {p_bus[46]}]
set_max_transition 3 [get_ports {p_bus[45]}]
set_max_transition 3 [get_ports {p_bus[44]}]
set_max_transition 3 [get_ports {p_bus[43]}]
set_max_transition 3 [get_ports {p_bus[42]}]
set_max_transition 3 [get_ports {p_bus[41]}]
set_max_transition 3 [get_ports {p_bus[40]}]
set_max_transition 3 [get_ports {p_bus[39]}]
set_max_transition 3 [get_ports {p_bus[38]}]
set_max_transition 3 [get_ports {p_bus[37]}]
set_max_transition 3 [get_ports {p_bus[36]}]
set_max_transition 3 [get_ports {p_bus[35]}]
set_max_transition 3 [get_ports {p_bus[34]}]
set_max_transition 3 [get_ports {p_bus[33]}]
set_max_transition 3 [get_ports {p_bus[32]}]
set_max_transition 3 [get_ports {p_bus[31]}]
set_max_transition 3 [get_ports {p_bus[30]}]
set_max_transition 3 [get_ports {p_bus[29]}]
set_max_transition 3 [get_ports {p_bus[28]}]
set_max_transition 3 [get_ports {p_bus[27]}]
set_max_transition 3 [get_ports {p_bus[26]}]
set_max_transition 3 [get_ports {p_bus[25]}]
set_max_transition 3 [get_ports {p_bus[24]}]
set_max_transition 3 [get_ports {p_bus[23]}]
set_max_transition 3 [get_ports {p_bus[22]}]
set_max_transition 3 [get_ports {p_bus[21]}]
set_max_transition 3 [get_ports {p_bus[20]}]
set_max_transition 3 [get_ports {p_bus[19]}]
set_max_transition 3 [get_ports {p_bus[18]}]
set_max_transition 3 [get_ports {p_bus[17]}]
set_max_transition 3 [get_ports {p_bus[16]}]
set_max_transition 3 [get_ports {p_bus[15]}]
set_max_transition 3 [get_ports {p_bus[14]}]
set_max_transition 3 [get_ports {p_bus[13]}]
set_max_transition 3 [get_ports {p_bus[12]}]
set_max_transition 3 [get_ports {p_bus[11]}]
set_max_transition 3 [get_ports {p_bus[10]}]
set_max_transition 3 [get_ports {p_bus[9]}]
set_max_transition 3 [get_ports {p_bus[8]}]
set_max_transition 3 [get_ports {p_bus[7]}]
set_max_transition 3 [get_ports {p_bus[6]}]
set_max_transition 3 [get_ports {p_bus[5]}]
set_max_transition 3 [get_ports {p_bus[4]}]
set_max_transition 3 [get_ports {p_bus[3]}]
set_max_transition 3 [get_ports {p_bus[2]}]
set_max_transition 3 [get_ports {p_bus[1]}]
set_max_transition 3 [get_ports {p_bus[0]}]
set_max_transition 3 [get_ports {p0i_bus[92]}]
set_max_transition 3 [get_ports {p0i_bus[91]}]
set_max_transition 3 [get_ports {p0i_bus[90]}]
set_max_transition 3 [get_ports {p0i_bus[89]}]
set_max_transition 3 [get_ports {p0i_bus[88]}]
set_max_transition 3 [get_ports {p0i_bus[87]}]
set_max_transition 3 [get_ports {p0i_bus[86]}]
set_max_transition 3 [get_ports {p0i_bus[85]}]
set_max_transition 3 [get_ports {p0i_bus[84]}]
set_max_transition 3 [get_ports {p0i_bus[83]}]
set_max_transition 3 [get_ports {p0i_bus[82]}]
set_max_transition 3 [get_ports {p0i_bus[81]}]
set_max_transition 3 [get_ports {p0i_bus[80]}]
set_max_transition 3 [get_ports {p0i_bus[79]}]
set_max_transition 3 [get_ports {p0i_bus[78]}]
set_max_transition 3 [get_ports {p0i_bus[77]}]
set_max_transition 3 [get_ports {p0i_bus[76]}]
set_max_transition 3 [get_ports {p0i_bus[75]}]
set_max_transition 3 [get_ports {p0i_bus[74]}]
set_max_transition 3 [get_ports {p0i_bus[73]}]
set_max_transition 3 [get_ports {p0i_bus[72]}]
set_max_transition 3 [get_ports {p0i_bus[71]}]
set_max_transition 3 [get_ports {p0i_bus[70]}]
set_max_transition 3 [get_ports {p0i_bus[69]}]
set_max_transition 3 [get_ports {p0i_bus[68]}]
set_max_transition 3 [get_ports {p0i_bus[67]}]
set_max_transition 3 [get_ports {p0i_bus[66]}]
set_max_transition 3 [get_ports {p0i_bus[65]}]
set_max_transition 3 [get_ports {p0i_bus[64]}]
set_max_transition 3 [get_ports {p0i_bus[63]}]
set_max_transition 3 [get_ports {p0i_bus[62]}]
set_max_transition 3 [get_ports {p0i_bus[61]}]
set_max_transition 3 [get_ports {p0i_bus[60]}]
set_max_transition 3 [get_ports {p0i_bus[59]}]
set_max_transition 3 [get_ports {p0i_bus[58]}]
set_max_transition 3 [get_ports {p0i_bus[57]}]
set_max_transition 3 [get_ports {p0i_bus[56]}]
set_max_transition 3 [get_ports {p0i_bus[55]}]
set_max_transition 3 [get_ports {p0i_bus[54]}]
set_max_transition 3 [get_ports {p0i_bus[53]}]
set_max_transition 3 [get_ports {p0i_bus[52]}]
set_max_transition 3 [get_ports {p0i_bus[51]}]
set_max_transition 3 [get_ports {p0i_bus[50]}]
set_max_transition 3 [get_ports {p0i_bus[49]}]
set_max_transition 3 [get_ports {p0i_bus[48]}]
set_max_transition 3 [get_ports {p0i_bus[47]}]
set_max_transition 3 [get_ports {p0i_bus[46]}]
set_max_transition 3 [get_ports {p0i_bus[45]}]
set_max_transition 3 [get_ports {p0i_bus[44]}]
set_max_transition 3 [get_ports {p0i_bus[43]}]
set_max_transition 3 [get_ports {p0i_bus[42]}]
set_max_transition 3 [get_ports {p0i_bus[41]}]
set_max_transition 3 [get_ports {p0i_bus[40]}]
set_max_transition 3 [get_ports {p0i_bus[39]}]
set_max_transition 3 [get_ports {p0i_bus[38]}]
set_max_transition 3 [get_ports {p0i_bus[37]}]
set_max_transition 3 [get_ports {p0i_bus[36]}]
set_max_transition 3 [get_ports {p0i_bus[35]}]
set_max_transition 3 [get_ports {p0i_bus[34]}]
set_max_transition 3 [get_ports {p0i_bus[33]}]
set_max_transition 3 [get_ports {p0i_bus[32]}]
set_max_transition 3 [get_ports {p0i_bus[31]}]
set_max_transition 3 [get_ports {p0i_bus[30]}]
set_max_transition 3 [get_ports {p0i_bus[29]}]
set_max_transition 3 [get_ports {p0i_bus[28]}]
set_max_transition 3 [get_ports {p0i_bus[27]}]
set_max_transition 3 [get_ports {p0i_bus[26]}]
set_max_transition 3 [get_ports {p0i_bus[25]}]
set_max_transition 3 [get_ports {p0i_bus[24]}]
set_max_transition 3 [get_ports {p0i_bus[23]}]
set_max_transition 3 [get_ports {p0i_bus[22]}]
set_max_transition 3 [get_ports {p0i_bus[21]}]
set_max_transition 3 [get_ports {p0i_bus[20]}]
set_max_transition 3 [get_ports {p0i_bus[19]}]
set_max_transition 3 [get_ports {p0i_bus[18]}]
set_max_transition 3 [get_ports {p0i_bus[17]}]
set_max_transition 3 [get_ports {p0i_bus[16]}]
set_max_transition 3 [get_ports {p0i_bus[15]}]
set_max_transition 3 [get_ports {p0i_bus[14]}]
set_max_transition 3 [get_ports {p0i_bus[13]}]
set_max_transition 3 [get_ports {p0i_bus[12]}]
set_max_transition 3 [get_ports {p0i_bus[11]}]
set_max_transition 3 [get_ports {p0i_bus[10]}]
set_max_transition 3 [get_ports {p0i_bus[9]}]
set_max_transition 3 [get_ports {p0i_bus[8]}]
set_max_transition 3 [get_ports {p0i_bus[7]}]
set_max_transition 3 [get_ports {p0i_bus[6]}]
set_max_transition 3 [get_ports {p0i_bus[5]}]
set_max_transition 3 [get_ports {p0i_bus[4]}]
set_max_transition 3 [get_ports {p0i_bus[3]}]
set_max_transition 3 [get_ports {p0i_bus[2]}]
set_max_transition 3 [get_ports {p0i_bus[1]}]
set_max_transition 3 [get_ports {p0i_bus[0]}]
create_clock [get_ports clk]  -period 2  -waveform {0 1}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  0  [get_ports {in_valid_bus[2]}]
set_input_delay -clock clk  0  [get_ports {in_valid_bus[1]}]
set_input_delay -clock clk  0  [get_ports {in_valid_bus[0]}]
set_input_delay -clock clk  0  [get_ports {p_bus[92]}]
set_input_delay -clock clk  0  [get_ports {p_bus[91]}]
set_input_delay -clock clk  0  [get_ports {p_bus[90]}]
set_input_delay -clock clk  0  [get_ports {p_bus[89]}]
set_input_delay -clock clk  0  [get_ports {p_bus[88]}]
set_input_delay -clock clk  0  [get_ports {p_bus[87]}]
set_input_delay -clock clk  0  [get_ports {p_bus[86]}]
set_input_delay -clock clk  0  [get_ports {p_bus[85]}]
set_input_delay -clock clk  0  [get_ports {p_bus[84]}]
set_input_delay -clock clk  0  [get_ports {p_bus[83]}]
set_input_delay -clock clk  0  [get_ports {p_bus[82]}]
set_input_delay -clock clk  0  [get_ports {p_bus[81]}]
set_input_delay -clock clk  0  [get_ports {p_bus[80]}]
set_input_delay -clock clk  0  [get_ports {p_bus[79]}]
set_input_delay -clock clk  0  [get_ports {p_bus[78]}]
set_input_delay -clock clk  0  [get_ports {p_bus[77]}]
set_input_delay -clock clk  0  [get_ports {p_bus[76]}]
set_input_delay -clock clk  0  [get_ports {p_bus[75]}]
set_input_delay -clock clk  0  [get_ports {p_bus[74]}]
set_input_delay -clock clk  0  [get_ports {p_bus[73]}]
set_input_delay -clock clk  0  [get_ports {p_bus[72]}]
set_input_delay -clock clk  0  [get_ports {p_bus[71]}]
set_input_delay -clock clk  0  [get_ports {p_bus[70]}]
set_input_delay -clock clk  0  [get_ports {p_bus[69]}]
set_input_delay -clock clk  0  [get_ports {p_bus[68]}]
set_input_delay -clock clk  0  [get_ports {p_bus[67]}]
set_input_delay -clock clk  0  [get_ports {p_bus[66]}]
set_input_delay -clock clk  0  [get_ports {p_bus[65]}]
set_input_delay -clock clk  0  [get_ports {p_bus[64]}]
set_input_delay -clock clk  0  [get_ports {p_bus[63]}]
set_input_delay -clock clk  0  [get_ports {p_bus[62]}]
set_input_delay -clock clk  0  [get_ports {p_bus[61]}]
set_input_delay -clock clk  0  [get_ports {p_bus[60]}]
set_input_delay -clock clk  0  [get_ports {p_bus[59]}]
set_input_delay -clock clk  0  [get_ports {p_bus[58]}]
set_input_delay -clock clk  0  [get_ports {p_bus[57]}]
set_input_delay -clock clk  0  [get_ports {p_bus[56]}]
set_input_delay -clock clk  0  [get_ports {p_bus[55]}]
set_input_delay -clock clk  0  [get_ports {p_bus[54]}]
set_input_delay -clock clk  0  [get_ports {p_bus[53]}]
set_input_delay -clock clk  0  [get_ports {p_bus[52]}]
set_input_delay -clock clk  0  [get_ports {p_bus[51]}]
set_input_delay -clock clk  0  [get_ports {p_bus[50]}]
set_input_delay -clock clk  0  [get_ports {p_bus[49]}]
set_input_delay -clock clk  0  [get_ports {p_bus[48]}]
set_input_delay -clock clk  0  [get_ports {p_bus[47]}]
set_input_delay -clock clk  0  [get_ports {p_bus[46]}]
set_input_delay -clock clk  0  [get_ports {p_bus[45]}]
set_input_delay -clock clk  0  [get_ports {p_bus[44]}]
set_input_delay -clock clk  0  [get_ports {p_bus[43]}]
set_input_delay -clock clk  0  [get_ports {p_bus[42]}]
set_input_delay -clock clk  0  [get_ports {p_bus[41]}]
set_input_delay -clock clk  0  [get_ports {p_bus[40]}]
set_input_delay -clock clk  0  [get_ports {p_bus[39]}]
set_input_delay -clock clk  0  [get_ports {p_bus[38]}]
set_input_delay -clock clk  0  [get_ports {p_bus[37]}]
set_input_delay -clock clk  0  [get_ports {p_bus[36]}]
set_input_delay -clock clk  0  [get_ports {p_bus[35]}]
set_input_delay -clock clk  0  [get_ports {p_bus[34]}]
set_input_delay -clock clk  0  [get_ports {p_bus[33]}]
set_input_delay -clock clk  0  [get_ports {p_bus[32]}]
set_input_delay -clock clk  0  [get_ports {p_bus[31]}]
set_input_delay -clock clk  0  [get_ports {p_bus[30]}]
set_input_delay -clock clk  0  [get_ports {p_bus[29]}]
set_input_delay -clock clk  0  [get_ports {p_bus[28]}]
set_input_delay -clock clk  0  [get_ports {p_bus[27]}]
set_input_delay -clock clk  0  [get_ports {p_bus[26]}]
set_input_delay -clock clk  0  [get_ports {p_bus[25]}]
set_input_delay -clock clk  0  [get_ports {p_bus[24]}]
set_input_delay -clock clk  0  [get_ports {p_bus[23]}]
set_input_delay -clock clk  0  [get_ports {p_bus[22]}]
set_input_delay -clock clk  0  [get_ports {p_bus[21]}]
set_input_delay -clock clk  0  [get_ports {p_bus[20]}]
set_input_delay -clock clk  0  [get_ports {p_bus[19]}]
set_input_delay -clock clk  0  [get_ports {p_bus[18]}]
set_input_delay -clock clk  0  [get_ports {p_bus[17]}]
set_input_delay -clock clk  0  [get_ports {p_bus[16]}]
set_input_delay -clock clk  0  [get_ports {p_bus[15]}]
set_input_delay -clock clk  0  [get_ports {p_bus[14]}]
set_input_delay -clock clk  0  [get_ports {p_bus[13]}]
set_input_delay -clock clk  0  [get_ports {p_bus[12]}]
set_input_delay -clock clk  0  [get_ports {p_bus[11]}]
set_input_delay -clock clk  0  [get_ports {p_bus[10]}]
set_input_delay -clock clk  0  [get_ports {p_bus[9]}]
set_input_delay -clock clk  0  [get_ports {p_bus[8]}]
set_input_delay -clock clk  0  [get_ports {p_bus[7]}]
set_input_delay -clock clk  0  [get_ports {p_bus[6]}]
set_input_delay -clock clk  0  [get_ports {p_bus[5]}]
set_input_delay -clock clk  0  [get_ports {p_bus[4]}]
set_input_delay -clock clk  0  [get_ports {p_bus[3]}]
set_input_delay -clock clk  0  [get_ports {p_bus[2]}]
set_input_delay -clock clk  0  [get_ports {p_bus[1]}]
set_input_delay -clock clk  0  [get_ports {p_bus[0]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[92]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[91]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[90]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[89]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[88]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[87]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[86]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[85]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[84]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[83]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[82]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[81]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[80]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[79]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[78]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[77]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[76]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[75]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[74]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[73]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[72]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[71]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[70]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[69]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[68]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[67]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[66]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[65]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[64]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[63]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[62]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[61]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[60]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[59]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[58]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[57]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[56]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[55]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[54]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[53]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[52]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[51]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[50]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[49]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[48]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[47]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[46]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[45]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[44]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[43]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[42]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[41]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[40]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[39]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[38]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[37]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[36]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[35]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[34]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[33]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[32]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[31]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[30]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[29]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[28]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[27]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[26]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[25]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[24]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[23]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[22]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[21]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[20]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[19]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[18]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[17]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[16]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[15]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[14]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[13]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[12]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[11]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[10]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[9]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[8]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[7]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[6]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[5]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[4]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[3]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[2]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[1]}]
set_input_delay -clock clk  0  [get_ports {p0i_bus[0]}]
set_output_delay -clock clk  0  [get_ports {out_valid_bus[2]}]
set_output_delay -clock clk  0  [get_ports {out_valid_bus[1]}]
set_output_delay -clock clk  0  [get_ports {out_valid_bus[0]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[92]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[91]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[90]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[89]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[88]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[87]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[86]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[85]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[84]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[83]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[82]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[81]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[80]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[79]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[78]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[77]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[76]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[75]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[74]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[73]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[72]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[71]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[70]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[69]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[68]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[67]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[66]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[65]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[64]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[63]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[62]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[61]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[60]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[59]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[58]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[57]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[56]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[55]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[54]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[53]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[52]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[51]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[50]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[49]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[48]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[47]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[46]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[45]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[44]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[43]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[42]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[41]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[40]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[39]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[38]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[37]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[36]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[35]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[34]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[33]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[32]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[31]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[30]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[29]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[28]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[27]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[26]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[25]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[24]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[23]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[22]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[21]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[20]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[19]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[18]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[17]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[16]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[15]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[14]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[13]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[12]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[11]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[10]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[9]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[8]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[7]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[6]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[5]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[4]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[3]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[2]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[1]}]
set_output_delay -clock clk  0  [get_ports {R2_bus[0]}]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports {in_valid_bus[2]}]
set_input_transition -min 0.5  [get_ports {in_valid_bus[2]}]
set_input_transition -max 0.5  [get_ports {in_valid_bus[1]}]
set_input_transition -min 0.5  [get_ports {in_valid_bus[1]}]
set_input_transition -max 0.5  [get_ports {in_valid_bus[0]}]
set_input_transition -min 0.5  [get_ports {in_valid_bus[0]}]
set_input_transition -max 0.5  [get_ports {p_bus[92]}]
set_input_transition -min 0.5  [get_ports {p_bus[92]}]
set_input_transition -max 0.5  [get_ports {p_bus[91]}]
set_input_transition -min 0.5  [get_ports {p_bus[91]}]
set_input_transition -max 0.5  [get_ports {p_bus[90]}]
set_input_transition -min 0.5  [get_ports {p_bus[90]}]
set_input_transition -max 0.5  [get_ports {p_bus[89]}]
set_input_transition -min 0.5  [get_ports {p_bus[89]}]
set_input_transition -max 0.5  [get_ports {p_bus[88]}]
set_input_transition -min 0.5  [get_ports {p_bus[88]}]
set_input_transition -max 0.5  [get_ports {p_bus[87]}]
set_input_transition -min 0.5  [get_ports {p_bus[87]}]
set_input_transition -max 0.5  [get_ports {p_bus[86]}]
set_input_transition -min 0.5  [get_ports {p_bus[86]}]
set_input_transition -max 0.5  [get_ports {p_bus[85]}]
set_input_transition -min 0.5  [get_ports {p_bus[85]}]
set_input_transition -max 0.5  [get_ports {p_bus[84]}]
set_input_transition -min 0.5  [get_ports {p_bus[84]}]
set_input_transition -max 0.5  [get_ports {p_bus[83]}]
set_input_transition -min 0.5  [get_ports {p_bus[83]}]
set_input_transition -max 0.5  [get_ports {p_bus[82]}]
set_input_transition -min 0.5  [get_ports {p_bus[82]}]
set_input_transition -max 0.5  [get_ports {p_bus[81]}]
set_input_transition -min 0.5  [get_ports {p_bus[81]}]
set_input_transition -max 0.5  [get_ports {p_bus[80]}]
set_input_transition -min 0.5  [get_ports {p_bus[80]}]
set_input_transition -max 0.5  [get_ports {p_bus[79]}]
set_input_transition -min 0.5  [get_ports {p_bus[79]}]
set_input_transition -max 0.5  [get_ports {p_bus[78]}]
set_input_transition -min 0.5  [get_ports {p_bus[78]}]
set_input_transition -max 0.5  [get_ports {p_bus[77]}]
set_input_transition -min 0.5  [get_ports {p_bus[77]}]
set_input_transition -max 0.5  [get_ports {p_bus[76]}]
set_input_transition -min 0.5  [get_ports {p_bus[76]}]
set_input_transition -max 0.5  [get_ports {p_bus[75]}]
set_input_transition -min 0.5  [get_ports {p_bus[75]}]
set_input_transition -max 0.5  [get_ports {p_bus[74]}]
set_input_transition -min 0.5  [get_ports {p_bus[74]}]
set_input_transition -max 0.5  [get_ports {p_bus[73]}]
set_input_transition -min 0.5  [get_ports {p_bus[73]}]
set_input_transition -max 0.5  [get_ports {p_bus[72]}]
set_input_transition -min 0.5  [get_ports {p_bus[72]}]
set_input_transition -max 0.5  [get_ports {p_bus[71]}]
set_input_transition -min 0.5  [get_ports {p_bus[71]}]
set_input_transition -max 0.5  [get_ports {p_bus[70]}]
set_input_transition -min 0.5  [get_ports {p_bus[70]}]
set_input_transition -max 0.5  [get_ports {p_bus[69]}]
set_input_transition -min 0.5  [get_ports {p_bus[69]}]
set_input_transition -max 0.5  [get_ports {p_bus[68]}]
set_input_transition -min 0.5  [get_ports {p_bus[68]}]
set_input_transition -max 0.5  [get_ports {p_bus[67]}]
set_input_transition -min 0.5  [get_ports {p_bus[67]}]
set_input_transition -max 0.5  [get_ports {p_bus[66]}]
set_input_transition -min 0.5  [get_ports {p_bus[66]}]
set_input_transition -max 0.5  [get_ports {p_bus[65]}]
set_input_transition -min 0.5  [get_ports {p_bus[65]}]
set_input_transition -max 0.5  [get_ports {p_bus[64]}]
set_input_transition -min 0.5  [get_ports {p_bus[64]}]
set_input_transition -max 0.5  [get_ports {p_bus[63]}]
set_input_transition -min 0.5  [get_ports {p_bus[63]}]
set_input_transition -max 0.5  [get_ports {p_bus[62]}]
set_input_transition -min 0.5  [get_ports {p_bus[62]}]
set_input_transition -max 0.5  [get_ports {p_bus[61]}]
set_input_transition -min 0.5  [get_ports {p_bus[61]}]
set_input_transition -max 0.5  [get_ports {p_bus[60]}]
set_input_transition -min 0.5  [get_ports {p_bus[60]}]
set_input_transition -max 0.5  [get_ports {p_bus[59]}]
set_input_transition -min 0.5  [get_ports {p_bus[59]}]
set_input_transition -max 0.5  [get_ports {p_bus[58]}]
set_input_transition -min 0.5  [get_ports {p_bus[58]}]
set_input_transition -max 0.5  [get_ports {p_bus[57]}]
set_input_transition -min 0.5  [get_ports {p_bus[57]}]
set_input_transition -max 0.5  [get_ports {p_bus[56]}]
set_input_transition -min 0.5  [get_ports {p_bus[56]}]
set_input_transition -max 0.5  [get_ports {p_bus[55]}]
set_input_transition -min 0.5  [get_ports {p_bus[55]}]
set_input_transition -max 0.5  [get_ports {p_bus[54]}]
set_input_transition -min 0.5  [get_ports {p_bus[54]}]
set_input_transition -max 0.5  [get_ports {p_bus[53]}]
set_input_transition -min 0.5  [get_ports {p_bus[53]}]
set_input_transition -max 0.5  [get_ports {p_bus[52]}]
set_input_transition -min 0.5  [get_ports {p_bus[52]}]
set_input_transition -max 0.5  [get_ports {p_bus[51]}]
set_input_transition -min 0.5  [get_ports {p_bus[51]}]
set_input_transition -max 0.5  [get_ports {p_bus[50]}]
set_input_transition -min 0.5  [get_ports {p_bus[50]}]
set_input_transition -max 0.5  [get_ports {p_bus[49]}]
set_input_transition -min 0.5  [get_ports {p_bus[49]}]
set_input_transition -max 0.5  [get_ports {p_bus[48]}]
set_input_transition -min 0.5  [get_ports {p_bus[48]}]
set_input_transition -max 0.5  [get_ports {p_bus[47]}]
set_input_transition -min 0.5  [get_ports {p_bus[47]}]
set_input_transition -max 0.5  [get_ports {p_bus[46]}]
set_input_transition -min 0.5  [get_ports {p_bus[46]}]
set_input_transition -max 0.5  [get_ports {p_bus[45]}]
set_input_transition -min 0.5  [get_ports {p_bus[45]}]
set_input_transition -max 0.5  [get_ports {p_bus[44]}]
set_input_transition -min 0.5  [get_ports {p_bus[44]}]
set_input_transition -max 0.5  [get_ports {p_bus[43]}]
set_input_transition -min 0.5  [get_ports {p_bus[43]}]
set_input_transition -max 0.5  [get_ports {p_bus[42]}]
set_input_transition -min 0.5  [get_ports {p_bus[42]}]
set_input_transition -max 0.5  [get_ports {p_bus[41]}]
set_input_transition -min 0.5  [get_ports {p_bus[41]}]
set_input_transition -max 0.5  [get_ports {p_bus[40]}]
set_input_transition -min 0.5  [get_ports {p_bus[40]}]
set_input_transition -max 0.5  [get_ports {p_bus[39]}]
set_input_transition -min 0.5  [get_ports {p_bus[39]}]
set_input_transition -max 0.5  [get_ports {p_bus[38]}]
set_input_transition -min 0.5  [get_ports {p_bus[38]}]
set_input_transition -max 0.5  [get_ports {p_bus[37]}]
set_input_transition -min 0.5  [get_ports {p_bus[37]}]
set_input_transition -max 0.5  [get_ports {p_bus[36]}]
set_input_transition -min 0.5  [get_ports {p_bus[36]}]
set_input_transition -max 0.5  [get_ports {p_bus[35]}]
set_input_transition -min 0.5  [get_ports {p_bus[35]}]
set_input_transition -max 0.5  [get_ports {p_bus[34]}]
set_input_transition -min 0.5  [get_ports {p_bus[34]}]
set_input_transition -max 0.5  [get_ports {p_bus[33]}]
set_input_transition -min 0.5  [get_ports {p_bus[33]}]
set_input_transition -max 0.5  [get_ports {p_bus[32]}]
set_input_transition -min 0.5  [get_ports {p_bus[32]}]
set_input_transition -max 0.5  [get_ports {p_bus[31]}]
set_input_transition -min 0.5  [get_ports {p_bus[31]}]
set_input_transition -max 0.5  [get_ports {p_bus[30]}]
set_input_transition -min 0.5  [get_ports {p_bus[30]}]
set_input_transition -max 0.5  [get_ports {p_bus[29]}]
set_input_transition -min 0.5  [get_ports {p_bus[29]}]
set_input_transition -max 0.5  [get_ports {p_bus[28]}]
set_input_transition -min 0.5  [get_ports {p_bus[28]}]
set_input_transition -max 0.5  [get_ports {p_bus[27]}]
set_input_transition -min 0.5  [get_ports {p_bus[27]}]
set_input_transition -max 0.5  [get_ports {p_bus[26]}]
set_input_transition -min 0.5  [get_ports {p_bus[26]}]
set_input_transition -max 0.5  [get_ports {p_bus[25]}]
set_input_transition -min 0.5  [get_ports {p_bus[25]}]
set_input_transition -max 0.5  [get_ports {p_bus[24]}]
set_input_transition -min 0.5  [get_ports {p_bus[24]}]
set_input_transition -max 0.5  [get_ports {p_bus[23]}]
set_input_transition -min 0.5  [get_ports {p_bus[23]}]
set_input_transition -max 0.5  [get_ports {p_bus[22]}]
set_input_transition -min 0.5  [get_ports {p_bus[22]}]
set_input_transition -max 0.5  [get_ports {p_bus[21]}]
set_input_transition -min 0.5  [get_ports {p_bus[21]}]
set_input_transition -max 0.5  [get_ports {p_bus[20]}]
set_input_transition -min 0.5  [get_ports {p_bus[20]}]
set_input_transition -max 0.5  [get_ports {p_bus[19]}]
set_input_transition -min 0.5  [get_ports {p_bus[19]}]
set_input_transition -max 0.5  [get_ports {p_bus[18]}]
set_input_transition -min 0.5  [get_ports {p_bus[18]}]
set_input_transition -max 0.5  [get_ports {p_bus[17]}]
set_input_transition -min 0.5  [get_ports {p_bus[17]}]
set_input_transition -max 0.5  [get_ports {p_bus[16]}]
set_input_transition -min 0.5  [get_ports {p_bus[16]}]
set_input_transition -max 0.5  [get_ports {p_bus[15]}]
set_input_transition -min 0.5  [get_ports {p_bus[15]}]
set_input_transition -max 0.5  [get_ports {p_bus[14]}]
set_input_transition -min 0.5  [get_ports {p_bus[14]}]
set_input_transition -max 0.5  [get_ports {p_bus[13]}]
set_input_transition -min 0.5  [get_ports {p_bus[13]}]
set_input_transition -max 0.5  [get_ports {p_bus[12]}]
set_input_transition -min 0.5  [get_ports {p_bus[12]}]
set_input_transition -max 0.5  [get_ports {p_bus[11]}]
set_input_transition -min 0.5  [get_ports {p_bus[11]}]
set_input_transition -max 0.5  [get_ports {p_bus[10]}]
set_input_transition -min 0.5  [get_ports {p_bus[10]}]
set_input_transition -max 0.5  [get_ports {p_bus[9]}]
set_input_transition -min 0.5  [get_ports {p_bus[9]}]
set_input_transition -max 0.5  [get_ports {p_bus[8]}]
set_input_transition -min 0.5  [get_ports {p_bus[8]}]
set_input_transition -max 0.5  [get_ports {p_bus[7]}]
set_input_transition -min 0.5  [get_ports {p_bus[7]}]
set_input_transition -max 0.5  [get_ports {p_bus[6]}]
set_input_transition -min 0.5  [get_ports {p_bus[6]}]
set_input_transition -max 0.5  [get_ports {p_bus[5]}]
set_input_transition -min 0.5  [get_ports {p_bus[5]}]
set_input_transition -max 0.5  [get_ports {p_bus[4]}]
set_input_transition -min 0.5  [get_ports {p_bus[4]}]
set_input_transition -max 0.5  [get_ports {p_bus[3]}]
set_input_transition -min 0.5  [get_ports {p_bus[3]}]
set_input_transition -max 0.5  [get_ports {p_bus[2]}]
set_input_transition -min 0.5  [get_ports {p_bus[2]}]
set_input_transition -max 0.5  [get_ports {p_bus[1]}]
set_input_transition -min 0.5  [get_ports {p_bus[1]}]
set_input_transition -max 0.5  [get_ports {p_bus[0]}]
set_input_transition -min 0.5  [get_ports {p_bus[0]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[92]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[92]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[91]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[91]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[90]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[90]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[89]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[89]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[88]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[88]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[87]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[87]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[86]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[86]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[85]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[85]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[84]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[84]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[83]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[83]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[82]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[82]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[81]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[81]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[80]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[80]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[79]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[79]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[78]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[78]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[77]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[77]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[76]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[76]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[75]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[75]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[74]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[74]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[73]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[73]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[72]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[72]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[71]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[71]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[70]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[70]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[69]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[69]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[68]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[68]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[67]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[67]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[66]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[66]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[65]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[65]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[64]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[64]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[63]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[63]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[62]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[62]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[61]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[61]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[60]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[60]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[59]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[59]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[58]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[58]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[57]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[57]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[56]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[56]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[55]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[55]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[54]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[54]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[53]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[53]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[52]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[52]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[51]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[51]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[50]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[50]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[49]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[49]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[48]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[48]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[47]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[47]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[46]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[46]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[45]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[45]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[44]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[44]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[43]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[43]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[42]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[42]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[41]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[41]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[40]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[40]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[39]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[39]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[38]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[38]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[37]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[37]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[36]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[36]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[35]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[35]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[34]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[34]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[33]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[33]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[32]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[32]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[31]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[31]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[30]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[30]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[29]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[29]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[28]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[28]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[27]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[27]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[26]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[26]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[25]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[25]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[24]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[24]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[23]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[23]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[22]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[22]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[21]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[21]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[20]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[20]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[19]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[19]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[18]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[18]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[17]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[17]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[16]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[16]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[15]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[15]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[14]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[14]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[13]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[13]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[12]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[12]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[11]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[11]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[10]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[10]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[9]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[9]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[8]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[8]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[7]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[7]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[6]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[6]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[5]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[5]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[4]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[4]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[3]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[3]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[2]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[2]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[1]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[1]}]
set_input_transition -max 0.5  [get_ports {p0i_bus[0]}]
set_input_transition -min 0.5  [get_ports {p0i_bus[0]}]
