###################################################################

# Created by write_sdc on Thu Mar  5 00:48:54 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name Small -library                                       \
sc9_cln40g_base_rvt_ss_typical_max_0p81v_125c
set_load -pin_load 0.05 [get_ports inf_out_valid]
set_load -pin_load 0.05 [get_ports {inf_out_data[30]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[29]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[28]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[27]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[26]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[25]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[24]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[23]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[22]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[21]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[20]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[19]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[18]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[17]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[16]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[15]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[14]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[13]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[12]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[11]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[10]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[9]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[8]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[7]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[6]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[5]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[4]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[3]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[2]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[1]}]
set_load -pin_load 0.05 [get_ports {inf_out_data[0]}]
create_clock [get_ports clk]  -period 1.55  -waveform {0 0.775}
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  0  [get_ports inf_in_valid]
set_input_delay -clock clk  0  [get_ports {inf_in_data[30]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[29]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[28]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[27]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[26]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[25]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[24]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[23]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[22]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[21]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[20]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[19]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[18]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[17]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[16]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[15]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[14]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[13]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[12]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[11]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[10]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[9]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[8]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[7]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[6]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[5]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[4]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[3]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[2]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[1]}]
set_input_delay -clock clk  0  [get_ports {inf_in_data[0]}]
set_input_delay -clock clk  0  [get_ports inf_mode]
set_input_delay -clock clk  0  [get_ports inf_len_valid]
set_input_delay -clock clk  0  [get_ports {inf_logn[3]}]
set_input_delay -clock clk  0  [get_ports {inf_logn[2]}]
set_input_delay -clock clk  0  [get_ports {inf_logn[1]}]
set_input_delay -clock clk  0  [get_ports {inf_logn[0]}]
set_input_delay -clock clk  0  [get_ports {inf_xlen[8]}]
set_input_delay -clock clk  0  [get_ports {inf_xlen[7]}]
set_input_delay -clock clk  0  [get_ports {inf_xlen[6]}]
set_input_delay -clock clk  0  [get_ports {inf_xlen[5]}]
set_input_delay -clock clk  0  [get_ports {inf_xlen[4]}]
set_input_delay -clock clk  0  [get_ports {inf_xlen[3]}]
set_input_delay -clock clk  0  [get_ports {inf_xlen[2]}]
set_input_delay -clock clk  0  [get_ports {inf_xlen[1]}]
set_input_delay -clock clk  0  [get_ports {inf_xlen[0]}]
set_output_delay -clock clk  0  [get_ports inf_out_valid]
set_output_delay -clock clk  0  [get_ports {inf_out_data[30]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[29]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[28]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[27]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[26]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[25]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[24]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[23]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[22]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[21]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[20]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[19]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[18]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[17]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[16]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[15]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[14]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[13]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[12]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[11]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[10]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[9]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[8]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[7]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[6]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[5]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[4]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[3]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[2]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[1]}]
set_output_delay -clock clk  0  [get_ports {inf_out_data[0]}]
