#!/bin/bash

# ==============================================================================
# Parameters
# ==============================================================================
PERIOD="1.6"
WN="4"

# ==============================================================================
# Usage
# ==============================================================================
usage() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  -p <PERIOD>    Set cycle time (default: $PERIOD ns)"
    echo "  -w <WORD_NUM>  Set Word Number (default: $WN)"
    echo "                 Available: 2, 4, 8"
    echo "  -h             Help message"
    exit 1
}

# ==============================================================================
# Flag settings
# ==============================================================================
while getopts "m:w:h" opt; do
    case ${opt} in
        m)
            PERIOD=$OPTARG
            ;;
        w)
            WN=$OPTARG
            ;;
        h)
            usage
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
            ;;
    esac
done

make vcs_rtl period=$PERIOD word_num=$WN