###################################################################

# Created by write_sdc on Tue Jun  2 20:18:18 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name Small -library                                       \
sc9_cln40g_base_rvt_ss_typical_max_0p81v_125c
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {d_re[63]}]
set_load -pin_load 0.05 [get_ports {d_re[62]}]
set_load -pin_load 0.05 [get_ports {d_re[61]}]
set_load -pin_load 0.05 [get_ports {d_re[60]}]
set_load -pin_load 0.05 [get_ports {d_re[59]}]
set_load -pin_load 0.05 [get_ports {d_re[58]}]
set_load -pin_load 0.05 [get_ports {d_re[57]}]
set_load -pin_load 0.05 [get_ports {d_re[56]}]
set_load -pin_load 0.05 [get_ports {d_re[55]}]
set_load -pin_load 0.05 [get_ports {d_re[54]}]
set_load -pin_load 0.05 [get_ports {d_re[53]}]
set_load -pin_load 0.05 [get_ports {d_re[52]}]
set_load -pin_load 0.05 [get_ports {d_re[51]}]
set_load -pin_load 0.05 [get_ports {d_re[50]}]
set_load -pin_load 0.05 [get_ports {d_re[49]}]
set_load -pin_load 0.05 [get_ports {d_re[48]}]
set_load -pin_load 0.05 [get_ports {d_re[47]}]
set_load -pin_load 0.05 [get_ports {d_re[46]}]
set_load -pin_load 0.05 [get_ports {d_re[45]}]
set_load -pin_load 0.05 [get_ports {d_re[44]}]
set_load -pin_load 0.05 [get_ports {d_re[43]}]
set_load -pin_load 0.05 [get_ports {d_re[42]}]
set_load -pin_load 0.05 [get_ports {d_re[41]}]
set_load -pin_load 0.05 [get_ports {d_re[40]}]
set_load -pin_load 0.05 [get_ports {d_re[39]}]
set_load -pin_load 0.05 [get_ports {d_re[38]}]
set_load -pin_load 0.05 [get_ports {d_re[37]}]
set_load -pin_load 0.05 [get_ports {d_re[36]}]
set_load -pin_load 0.05 [get_ports {d_re[35]}]
set_load -pin_load 0.05 [get_ports {d_re[34]}]
set_load -pin_load 0.05 [get_ports {d_re[33]}]
set_load -pin_load 0.05 [get_ports {d_re[32]}]
set_load -pin_load 0.05 [get_ports {d_re[31]}]
set_load -pin_load 0.05 [get_ports {d_re[30]}]
set_load -pin_load 0.05 [get_ports {d_re[29]}]
set_load -pin_load 0.05 [get_ports {d_re[28]}]
set_load -pin_load 0.05 [get_ports {d_re[27]}]
set_load -pin_load 0.05 [get_ports {d_re[26]}]
set_load -pin_load 0.05 [get_ports {d_re[25]}]
set_load -pin_load 0.05 [get_ports {d_re[24]}]
set_load -pin_load 0.05 [get_ports {d_re[23]}]
set_load -pin_load 0.05 [get_ports {d_re[22]}]
set_load -pin_load 0.05 [get_ports {d_re[21]}]
set_load -pin_load 0.05 [get_ports {d_re[20]}]
set_load -pin_load 0.05 [get_ports {d_re[19]}]
set_load -pin_load 0.05 [get_ports {d_re[18]}]
set_load -pin_load 0.05 [get_ports {d_re[17]}]
set_load -pin_load 0.05 [get_ports {d_re[16]}]
set_load -pin_load 0.05 [get_ports {d_re[15]}]
set_load -pin_load 0.05 [get_ports {d_re[14]}]
set_load -pin_load 0.05 [get_ports {d_re[13]}]
set_load -pin_load 0.05 [get_ports {d_re[12]}]
set_load -pin_load 0.05 [get_ports {d_re[11]}]
set_load -pin_load 0.05 [get_ports {d_re[10]}]
set_load -pin_load 0.05 [get_ports {d_re[9]}]
set_load -pin_load 0.05 [get_ports {d_re[8]}]
set_load -pin_load 0.05 [get_ports {d_re[7]}]
set_load -pin_load 0.05 [get_ports {d_re[6]}]
set_load -pin_load 0.05 [get_ports {d_re[5]}]
set_load -pin_load 0.05 [get_ports {d_re[4]}]
set_load -pin_load 0.05 [get_ports {d_re[3]}]
set_load -pin_load 0.05 [get_ports {d_re[2]}]
set_load -pin_load 0.05 [get_ports {d_re[1]}]
set_load -pin_load 0.05 [get_ports {d_re[0]}]
set_load -pin_load 0.05 [get_ports {d_im[63]}]
set_load -pin_load 0.05 [get_ports {d_im[62]}]
set_load -pin_load 0.05 [get_ports {d_im[61]}]
set_load -pin_load 0.05 [get_ports {d_im[60]}]
set_load -pin_load 0.05 [get_ports {d_im[59]}]
set_load -pin_load 0.05 [get_ports {d_im[58]}]
set_load -pin_load 0.05 [get_ports {d_im[57]}]
set_load -pin_load 0.05 [get_ports {d_im[56]}]
set_load -pin_load 0.05 [get_ports {d_im[55]}]
set_load -pin_load 0.05 [get_ports {d_im[54]}]
set_load -pin_load 0.05 [get_ports {d_im[53]}]
set_load -pin_load 0.05 [get_ports {d_im[52]}]
set_load -pin_load 0.05 [get_ports {d_im[51]}]
set_load -pin_load 0.05 [get_ports {d_im[50]}]
set_load -pin_load 0.05 [get_ports {d_im[49]}]
set_load -pin_load 0.05 [get_ports {d_im[48]}]
set_load -pin_load 0.05 [get_ports {d_im[47]}]
set_load -pin_load 0.05 [get_ports {d_im[46]}]
set_load -pin_load 0.05 [get_ports {d_im[45]}]
set_load -pin_load 0.05 [get_ports {d_im[44]}]
set_load -pin_load 0.05 [get_ports {d_im[43]}]
set_load -pin_load 0.05 [get_ports {d_im[42]}]
set_load -pin_load 0.05 [get_ports {d_im[41]}]
set_load -pin_load 0.05 [get_ports {d_im[40]}]
set_load -pin_load 0.05 [get_ports {d_im[39]}]
set_load -pin_load 0.05 [get_ports {d_im[38]}]
set_load -pin_load 0.05 [get_ports {d_im[37]}]
set_load -pin_load 0.05 [get_ports {d_im[36]}]
set_load -pin_load 0.05 [get_ports {d_im[35]}]
set_load -pin_load 0.05 [get_ports {d_im[34]}]
set_load -pin_load 0.05 [get_ports {d_im[33]}]
set_load -pin_load 0.05 [get_ports {d_im[32]}]
set_load -pin_load 0.05 [get_ports {d_im[31]}]
set_load -pin_load 0.05 [get_ports {d_im[30]}]
set_load -pin_load 0.05 [get_ports {d_im[29]}]
set_load -pin_load 0.05 [get_ports {d_im[28]}]
set_load -pin_load 0.05 [get_ports {d_im[27]}]
set_load -pin_load 0.05 [get_ports {d_im[26]}]
set_load -pin_load 0.05 [get_ports {d_im[25]}]
set_load -pin_load 0.05 [get_ports {d_im[24]}]
set_load -pin_load 0.05 [get_ports {d_im[23]}]
set_load -pin_load 0.05 [get_ports {d_im[22]}]
set_load -pin_load 0.05 [get_ports {d_im[21]}]
set_load -pin_load 0.05 [get_ports {d_im[20]}]
set_load -pin_load 0.05 [get_ports {d_im[19]}]
set_load -pin_load 0.05 [get_ports {d_im[18]}]
set_load -pin_load 0.05 [get_ports {d_im[17]}]
set_load -pin_load 0.05 [get_ports {d_im[16]}]
set_load -pin_load 0.05 [get_ports {d_im[15]}]
set_load -pin_load 0.05 [get_ports {d_im[14]}]
set_load -pin_load 0.05 [get_ports {d_im[13]}]
set_load -pin_load 0.05 [get_ports {d_im[12]}]
set_load -pin_load 0.05 [get_ports {d_im[11]}]
set_load -pin_load 0.05 [get_ports {d_im[10]}]
set_load -pin_load 0.05 [get_ports {d_im[9]}]
set_load -pin_load 0.05 [get_ports {d_im[8]}]
set_load -pin_load 0.05 [get_ports {d_im[7]}]
set_load -pin_load 0.05 [get_ports {d_im[6]}]
set_load -pin_load 0.05 [get_ports {d_im[5]}]
set_load -pin_load 0.05 [get_ports {d_im[4]}]
set_load -pin_load 0.05 [get_ports {d_im[3]}]
set_load -pin_load 0.05 [get_ports {d_im[2]}]
set_load -pin_load 0.05 [get_ports {d_im[1]}]
set_load -pin_load 0.05 [get_ports {d_im[0]}]
create_clock [get_ports clk]  -period 1.2  -waveform {0 0.6}
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  -max 0.36  [get_ports in_valid]
set_input_delay -clock clk  -min 0  [get_ports in_valid]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[63]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[63]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[62]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[62]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[61]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[61]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[60]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[60]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[59]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[59]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[58]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[58]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[57]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[57]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[56]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[56]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[55]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[55]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[54]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[54]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[53]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[53]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[52]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[52]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[51]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[51]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[50]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[50]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[49]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[49]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[48]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[48]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[47]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[47]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[46]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[46]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[45]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[45]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[44]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[44]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[43]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[43]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[42]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[42]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[41]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[41]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[40]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[40]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[39]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[39]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[38]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[38]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[37]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[37]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[36]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[36]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[35]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[35]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[34]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[34]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[33]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[33]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[32]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[32]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[31]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[31]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[30]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[30]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[29]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[29]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[28]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[28]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[27]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[27]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[26]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[26]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[25]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[25]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[24]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[24]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[23]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[23]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[22]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[22]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[21]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[21]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[20]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[20]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[19]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[19]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[18]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[18]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[17]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[17]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[16]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[16]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[15]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[15]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[14]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[14]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[13]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[13]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[12]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[12]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[11]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[11]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[10]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[10]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[9]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[9]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[8]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[8]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[7]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[7]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[6]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[6]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[5]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[5]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[4]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[4]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[3]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[3]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[2]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[2]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[1]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[1]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_re[0]}]
set_input_delay -clock clk  -min 0  [get_ports {a_re[0]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[63]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[63]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[62]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[62]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[61]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[61]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[60]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[60]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[59]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[59]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[58]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[58]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[57]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[57]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[56]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[56]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[55]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[55]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[54]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[54]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[53]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[53]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[52]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[52]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[51]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[51]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[50]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[50]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[49]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[49]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[48]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[48]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[47]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[47]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[46]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[46]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[45]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[45]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[44]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[44]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[43]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[43]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[42]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[42]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[41]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[41]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[40]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[40]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[39]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[39]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[38]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[38]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[37]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[37]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[36]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[36]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[35]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[35]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[34]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[34]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[33]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[33]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[32]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[32]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[31]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[31]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[30]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[30]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[29]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[29]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[28]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[28]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[27]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[27]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[26]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[26]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[25]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[25]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[24]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[24]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[23]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[23]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[22]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[22]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[21]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[21]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[20]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[20]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[19]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[19]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[18]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[18]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[17]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[17]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[16]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[16]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[15]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[15]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[14]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[14]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[13]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[13]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[12]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[12]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[11]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[11]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[10]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[10]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[9]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[9]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[8]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[8]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[7]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[7]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[6]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[6]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[5]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[5]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[4]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[4]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[3]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[3]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[2]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[2]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[1]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[1]}]
set_input_delay -clock clk  -max 0.36  [get_ports {a_im[0]}]
set_input_delay -clock clk  -min 0  [get_ports {a_im[0]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[63]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[63]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[62]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[62]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[61]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[61]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[60]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[60]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[59]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[59]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[58]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[58]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[57]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[57]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[56]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[56]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[55]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[55]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[54]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[54]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[53]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[53]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[52]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[52]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[51]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[51]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[50]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[50]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[49]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[49]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[48]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[48]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[47]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[47]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[46]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[46]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[45]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[45]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[44]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[44]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[43]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[43]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[42]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[42]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[41]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[41]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[40]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[40]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[39]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[39]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[38]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[38]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[37]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[37]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[36]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[36]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[35]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[35]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[34]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[34]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[33]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[33]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[32]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[32]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[31]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[31]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[30]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[30]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[29]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[29]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[28]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[28]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[27]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[27]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[26]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[26]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[25]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[25]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[24]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[24]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[23]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[23]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[22]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[22]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[21]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[21]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[20]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[20]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[19]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[19]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[18]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[18]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[17]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[17]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[16]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[16]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[15]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[15]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[14]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[14]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[13]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[13]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[12]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[12]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[11]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[11]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[10]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[10]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[9]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[9]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[8]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[8]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[7]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[7]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[6]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[6]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[5]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[5]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[4]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[4]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[3]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[3]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[2]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[2]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[1]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[1]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_re[0]}]
set_input_delay -clock clk  -min 0  [get_ports {b_re[0]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[63]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[63]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[62]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[62]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[61]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[61]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[60]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[60]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[59]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[59]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[58]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[58]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[57]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[57]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[56]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[56]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[55]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[55]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[54]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[54]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[53]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[53]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[52]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[52]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[51]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[51]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[50]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[50]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[49]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[49]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[48]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[48]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[47]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[47]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[46]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[46]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[45]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[45]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[44]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[44]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[43]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[43]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[42]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[42]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[41]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[41]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[40]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[40]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[39]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[39]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[38]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[38]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[37]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[37]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[36]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[36]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[35]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[35]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[34]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[34]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[33]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[33]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[32]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[32]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[31]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[31]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[30]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[30]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[29]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[29]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[28]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[28]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[27]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[27]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[26]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[26]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[25]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[25]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[24]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[24]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[23]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[23]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[22]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[22]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[21]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[21]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[20]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[20]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[19]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[19]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[18]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[18]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[17]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[17]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[16]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[16]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[15]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[15]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[14]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[14]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[13]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[13]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[12]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[12]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[11]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[11]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[10]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[10]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[9]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[9]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[8]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[8]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[7]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[7]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[6]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[6]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[5]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[5]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[4]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[4]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[3]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[3]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[2]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[2]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[1]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[1]}]
set_input_delay -clock clk  -max 0.36  [get_ports {b_im[0]}]
set_input_delay -clock clk  -min 0  [get_ports {b_im[0]}]
set_output_delay -clock clk  0  [get_ports out_valid]
set_output_delay -clock clk  0  [get_ports {d_re[63]}]
set_output_delay -clock clk  0  [get_ports {d_re[62]}]
set_output_delay -clock clk  0  [get_ports {d_re[61]}]
set_output_delay -clock clk  0  [get_ports {d_re[60]}]
set_output_delay -clock clk  0  [get_ports {d_re[59]}]
set_output_delay -clock clk  0  [get_ports {d_re[58]}]
set_output_delay -clock clk  0  [get_ports {d_re[57]}]
set_output_delay -clock clk  0  [get_ports {d_re[56]}]
set_output_delay -clock clk  0  [get_ports {d_re[55]}]
set_output_delay -clock clk  0  [get_ports {d_re[54]}]
set_output_delay -clock clk  0  [get_ports {d_re[53]}]
set_output_delay -clock clk  0  [get_ports {d_re[52]}]
set_output_delay -clock clk  0  [get_ports {d_re[51]}]
set_output_delay -clock clk  0  [get_ports {d_re[50]}]
set_output_delay -clock clk  0  [get_ports {d_re[49]}]
set_output_delay -clock clk  0  [get_ports {d_re[48]}]
set_output_delay -clock clk  0  [get_ports {d_re[47]}]
set_output_delay -clock clk  0  [get_ports {d_re[46]}]
set_output_delay -clock clk  0  [get_ports {d_re[45]}]
set_output_delay -clock clk  0  [get_ports {d_re[44]}]
set_output_delay -clock clk  0  [get_ports {d_re[43]}]
set_output_delay -clock clk  0  [get_ports {d_re[42]}]
set_output_delay -clock clk  0  [get_ports {d_re[41]}]
set_output_delay -clock clk  0  [get_ports {d_re[40]}]
set_output_delay -clock clk  0  [get_ports {d_re[39]}]
set_output_delay -clock clk  0  [get_ports {d_re[38]}]
set_output_delay -clock clk  0  [get_ports {d_re[37]}]
set_output_delay -clock clk  0  [get_ports {d_re[36]}]
set_output_delay -clock clk  0  [get_ports {d_re[35]}]
set_output_delay -clock clk  0  [get_ports {d_re[34]}]
set_output_delay -clock clk  0  [get_ports {d_re[33]}]
set_output_delay -clock clk  0  [get_ports {d_re[32]}]
set_output_delay -clock clk  0  [get_ports {d_re[31]}]
set_output_delay -clock clk  0  [get_ports {d_re[30]}]
set_output_delay -clock clk  0  [get_ports {d_re[29]}]
set_output_delay -clock clk  0  [get_ports {d_re[28]}]
set_output_delay -clock clk  0  [get_ports {d_re[27]}]
set_output_delay -clock clk  0  [get_ports {d_re[26]}]
set_output_delay -clock clk  0  [get_ports {d_re[25]}]
set_output_delay -clock clk  0  [get_ports {d_re[24]}]
set_output_delay -clock clk  0  [get_ports {d_re[23]}]
set_output_delay -clock clk  0  [get_ports {d_re[22]}]
set_output_delay -clock clk  0  [get_ports {d_re[21]}]
set_output_delay -clock clk  0  [get_ports {d_re[20]}]
set_output_delay -clock clk  0  [get_ports {d_re[19]}]
set_output_delay -clock clk  0  [get_ports {d_re[18]}]
set_output_delay -clock clk  0  [get_ports {d_re[17]}]
set_output_delay -clock clk  0  [get_ports {d_re[16]}]
set_output_delay -clock clk  0  [get_ports {d_re[15]}]
set_output_delay -clock clk  0  [get_ports {d_re[14]}]
set_output_delay -clock clk  0  [get_ports {d_re[13]}]
set_output_delay -clock clk  0  [get_ports {d_re[12]}]
set_output_delay -clock clk  0  [get_ports {d_re[11]}]
set_output_delay -clock clk  0  [get_ports {d_re[10]}]
set_output_delay -clock clk  0  [get_ports {d_re[9]}]
set_output_delay -clock clk  0  [get_ports {d_re[8]}]
set_output_delay -clock clk  0  [get_ports {d_re[7]}]
set_output_delay -clock clk  0  [get_ports {d_re[6]}]
set_output_delay -clock clk  0  [get_ports {d_re[5]}]
set_output_delay -clock clk  0  [get_ports {d_re[4]}]
set_output_delay -clock clk  0  [get_ports {d_re[3]}]
set_output_delay -clock clk  0  [get_ports {d_re[2]}]
set_output_delay -clock clk  0  [get_ports {d_re[1]}]
set_output_delay -clock clk  0  [get_ports {d_re[0]}]
set_output_delay -clock clk  0  [get_ports {d_im[63]}]
set_output_delay -clock clk  0  [get_ports {d_im[62]}]
set_output_delay -clock clk  0  [get_ports {d_im[61]}]
set_output_delay -clock clk  0  [get_ports {d_im[60]}]
set_output_delay -clock clk  0  [get_ports {d_im[59]}]
set_output_delay -clock clk  0  [get_ports {d_im[58]}]
set_output_delay -clock clk  0  [get_ports {d_im[57]}]
set_output_delay -clock clk  0  [get_ports {d_im[56]}]
set_output_delay -clock clk  0  [get_ports {d_im[55]}]
set_output_delay -clock clk  0  [get_ports {d_im[54]}]
set_output_delay -clock clk  0  [get_ports {d_im[53]}]
set_output_delay -clock clk  0  [get_ports {d_im[52]}]
set_output_delay -clock clk  0  [get_ports {d_im[51]}]
set_output_delay -clock clk  0  [get_ports {d_im[50]}]
set_output_delay -clock clk  0  [get_ports {d_im[49]}]
set_output_delay -clock clk  0  [get_ports {d_im[48]}]
set_output_delay -clock clk  0  [get_ports {d_im[47]}]
set_output_delay -clock clk  0  [get_ports {d_im[46]}]
set_output_delay -clock clk  0  [get_ports {d_im[45]}]
set_output_delay -clock clk  0  [get_ports {d_im[44]}]
set_output_delay -clock clk  0  [get_ports {d_im[43]}]
set_output_delay -clock clk  0  [get_ports {d_im[42]}]
set_output_delay -clock clk  0  [get_ports {d_im[41]}]
set_output_delay -clock clk  0  [get_ports {d_im[40]}]
set_output_delay -clock clk  0  [get_ports {d_im[39]}]
set_output_delay -clock clk  0  [get_ports {d_im[38]}]
set_output_delay -clock clk  0  [get_ports {d_im[37]}]
set_output_delay -clock clk  0  [get_ports {d_im[36]}]
set_output_delay -clock clk  0  [get_ports {d_im[35]}]
set_output_delay -clock clk  0  [get_ports {d_im[34]}]
set_output_delay -clock clk  0  [get_ports {d_im[33]}]
set_output_delay -clock clk  0  [get_ports {d_im[32]}]
set_output_delay -clock clk  0  [get_ports {d_im[31]}]
set_output_delay -clock clk  0  [get_ports {d_im[30]}]
set_output_delay -clock clk  0  [get_ports {d_im[29]}]
set_output_delay -clock clk  0  [get_ports {d_im[28]}]
set_output_delay -clock clk  0  [get_ports {d_im[27]}]
set_output_delay -clock clk  0  [get_ports {d_im[26]}]
set_output_delay -clock clk  0  [get_ports {d_im[25]}]
set_output_delay -clock clk  0  [get_ports {d_im[24]}]
set_output_delay -clock clk  0  [get_ports {d_im[23]}]
set_output_delay -clock clk  0  [get_ports {d_im[22]}]
set_output_delay -clock clk  0  [get_ports {d_im[21]}]
set_output_delay -clock clk  0  [get_ports {d_im[20]}]
set_output_delay -clock clk  0  [get_ports {d_im[19]}]
set_output_delay -clock clk  0  [get_ports {d_im[18]}]
set_output_delay -clock clk  0  [get_ports {d_im[17]}]
set_output_delay -clock clk  0  [get_ports {d_im[16]}]
set_output_delay -clock clk  0  [get_ports {d_im[15]}]
set_output_delay -clock clk  0  [get_ports {d_im[14]}]
set_output_delay -clock clk  0  [get_ports {d_im[13]}]
set_output_delay -clock clk  0  [get_ports {d_im[12]}]
set_output_delay -clock clk  0  [get_ports {d_im[11]}]
set_output_delay -clock clk  0  [get_ports {d_im[10]}]
set_output_delay -clock clk  0  [get_ports {d_im[9]}]
set_output_delay -clock clk  0  [get_ports {d_im[8]}]
set_output_delay -clock clk  0  [get_ports {d_im[7]}]
set_output_delay -clock clk  0  [get_ports {d_im[6]}]
set_output_delay -clock clk  0  [get_ports {d_im[5]}]
set_output_delay -clock clk  0  [get_ports {d_im[4]}]
set_output_delay -clock clk  0  [get_ports {d_im[3]}]
set_output_delay -clock clk  0  [get_ports {d_im[2]}]
set_output_delay -clock clk  0  [get_ports {d_im[1]}]
set_output_delay -clock clk  0  [get_ports {d_im[0]}]
