###################################################################

# Created by write_sdc on Wed Sep 24 03:46:05 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name Small -library                                       \
sc9_cln40g_base_rvt_ss_typical_max_0p81v_125c
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {p0i[30]}]
set_load -pin_load 0.05 [get_ports {p0i[29]}]
set_load -pin_load 0.05 [get_ports {p0i[28]}]
set_load -pin_load 0.05 [get_ports {p0i[27]}]
set_load -pin_load 0.05 [get_ports {p0i[26]}]
set_load -pin_load 0.05 [get_ports {p0i[25]}]
set_load -pin_load 0.05 [get_ports {p0i[24]}]
set_load -pin_load 0.05 [get_ports {p0i[23]}]
set_load -pin_load 0.05 [get_ports {p0i[22]}]
set_load -pin_load 0.05 [get_ports {p0i[21]}]
set_load -pin_load 0.05 [get_ports {p0i[20]}]
set_load -pin_load 0.05 [get_ports {p0i[19]}]
set_load -pin_load 0.05 [get_ports {p0i[18]}]
set_load -pin_load 0.05 [get_ports {p0i[17]}]
set_load -pin_load 0.05 [get_ports {p0i[16]}]
set_load -pin_load 0.05 [get_ports {p0i[15]}]
set_load -pin_load 0.05 [get_ports {p0i[14]}]
set_load -pin_load 0.05 [get_ports {p0i[13]}]
set_load -pin_load 0.05 [get_ports {p0i[12]}]
set_load -pin_load 0.05 [get_ports {p0i[11]}]
set_load -pin_load 0.05 [get_ports {p0i[10]}]
set_load -pin_load 0.05 [get_ports {p0i[9]}]
set_load -pin_load 0.05 [get_ports {p0i[8]}]
set_load -pin_load 0.05 [get_ports {p0i[7]}]
set_load -pin_load 0.05 [get_ports {p0i[6]}]
set_load -pin_load 0.05 [get_ports {p0i[5]}]
set_load -pin_load 0.05 [get_ports {p0i[4]}]
set_load -pin_load 0.05 [get_ports {p0i[3]}]
set_load -pin_load 0.05 [get_ports {p0i[2]}]
set_load -pin_load 0.05 [get_ports {p0i[1]}]
set_load -pin_load 0.05 [get_ports {p0i[0]}]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports in_valid]
set_max_capacitance 0.15 [get_ports {p[30]}]
set_max_capacitance 0.15 [get_ports {p[29]}]
set_max_capacitance 0.15 [get_ports {p[28]}]
set_max_capacitance 0.15 [get_ports {p[27]}]
set_max_capacitance 0.15 [get_ports {p[26]}]
set_max_capacitance 0.15 [get_ports {p[25]}]
set_max_capacitance 0.15 [get_ports {p[24]}]
set_max_capacitance 0.15 [get_ports {p[23]}]
set_max_capacitance 0.15 [get_ports {p[22]}]
set_max_capacitance 0.15 [get_ports {p[21]}]
set_max_capacitance 0.15 [get_ports {p[20]}]
set_max_capacitance 0.15 [get_ports {p[19]}]
set_max_capacitance 0.15 [get_ports {p[18]}]
set_max_capacitance 0.15 [get_ports {p[17]}]
set_max_capacitance 0.15 [get_ports {p[16]}]
set_max_capacitance 0.15 [get_ports {p[15]}]
set_max_capacitance 0.15 [get_ports {p[14]}]
set_max_capacitance 0.15 [get_ports {p[13]}]
set_max_capacitance 0.15 [get_ports {p[12]}]
set_max_capacitance 0.15 [get_ports {p[11]}]
set_max_capacitance 0.15 [get_ports {p[10]}]
set_max_capacitance 0.15 [get_ports {p[9]}]
set_max_capacitance 0.15 [get_ports {p[8]}]
set_max_capacitance 0.15 [get_ports {p[7]}]
set_max_capacitance 0.15 [get_ports {p[6]}]
set_max_capacitance 0.15 [get_ports {p[5]}]
set_max_capacitance 0.15 [get_ports {p[4]}]
set_max_capacitance 0.15 [get_ports {p[3]}]
set_max_capacitance 0.15 [get_ports {p[2]}]
set_max_capacitance 0.15 [get_ports {p[1]}]
set_max_capacitance 0.15 [get_ports {p[0]}]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports in_valid]
set_max_fanout 10 [get_ports {p[30]}]
set_max_fanout 10 [get_ports {p[29]}]
set_max_fanout 10 [get_ports {p[28]}]
set_max_fanout 10 [get_ports {p[27]}]
set_max_fanout 10 [get_ports {p[26]}]
set_max_fanout 10 [get_ports {p[25]}]
set_max_fanout 10 [get_ports {p[24]}]
set_max_fanout 10 [get_ports {p[23]}]
set_max_fanout 10 [get_ports {p[22]}]
set_max_fanout 10 [get_ports {p[21]}]
set_max_fanout 10 [get_ports {p[20]}]
set_max_fanout 10 [get_ports {p[19]}]
set_max_fanout 10 [get_ports {p[18]}]
set_max_fanout 10 [get_ports {p[17]}]
set_max_fanout 10 [get_ports {p[16]}]
set_max_fanout 10 [get_ports {p[15]}]
set_max_fanout 10 [get_ports {p[14]}]
set_max_fanout 10 [get_ports {p[13]}]
set_max_fanout 10 [get_ports {p[12]}]
set_max_fanout 10 [get_ports {p[11]}]
set_max_fanout 10 [get_ports {p[10]}]
set_max_fanout 10 [get_ports {p[9]}]
set_max_fanout 10 [get_ports {p[8]}]
set_max_fanout 10 [get_ports {p[7]}]
set_max_fanout 10 [get_ports {p[6]}]
set_max_fanout 10 [get_ports {p[5]}]
set_max_fanout 10 [get_ports {p[4]}]
set_max_fanout 10 [get_ports {p[3]}]
set_max_fanout 10 [get_ports {p[2]}]
set_max_fanout 10 [get_ports {p[1]}]
set_max_fanout 10 [get_ports {p[0]}]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports in_valid]
set_max_transition 3 [get_ports {p[30]}]
set_max_transition 3 [get_ports {p[29]}]
set_max_transition 3 [get_ports {p[28]}]
set_max_transition 3 [get_ports {p[27]}]
set_max_transition 3 [get_ports {p[26]}]
set_max_transition 3 [get_ports {p[25]}]
set_max_transition 3 [get_ports {p[24]}]
set_max_transition 3 [get_ports {p[23]}]
set_max_transition 3 [get_ports {p[22]}]
set_max_transition 3 [get_ports {p[21]}]
set_max_transition 3 [get_ports {p[20]}]
set_max_transition 3 [get_ports {p[19]}]
set_max_transition 3 [get_ports {p[18]}]
set_max_transition 3 [get_ports {p[17]}]
set_max_transition 3 [get_ports {p[16]}]
set_max_transition 3 [get_ports {p[15]}]
set_max_transition 3 [get_ports {p[14]}]
set_max_transition 3 [get_ports {p[13]}]
set_max_transition 3 [get_ports {p[12]}]
set_max_transition 3 [get_ports {p[11]}]
set_max_transition 3 [get_ports {p[10]}]
set_max_transition 3 [get_ports {p[9]}]
set_max_transition 3 [get_ports {p[8]}]
set_max_transition 3 [get_ports {p[7]}]
set_max_transition 3 [get_ports {p[6]}]
set_max_transition 3 [get_ports {p[5]}]
set_max_transition 3 [get_ports {p[4]}]
set_max_transition 3 [get_ports {p[3]}]
set_max_transition 3 [get_ports {p[2]}]
set_max_transition 3 [get_ports {p[1]}]
set_max_transition 3 [get_ports {p[0]}]
create_clock [get_ports clk]  -period 2  -waveform {0 1}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  0  [get_ports in_valid]
set_input_delay -clock clk  0  [get_ports {p[30]}]
set_input_delay -clock clk  0  [get_ports {p[29]}]
set_input_delay -clock clk  0  [get_ports {p[28]}]
set_input_delay -clock clk  0  [get_ports {p[27]}]
set_input_delay -clock clk  0  [get_ports {p[26]}]
set_input_delay -clock clk  0  [get_ports {p[25]}]
set_input_delay -clock clk  0  [get_ports {p[24]}]
set_input_delay -clock clk  0  [get_ports {p[23]}]
set_input_delay -clock clk  0  [get_ports {p[22]}]
set_input_delay -clock clk  0  [get_ports {p[21]}]
set_input_delay -clock clk  0  [get_ports {p[20]}]
set_input_delay -clock clk  0  [get_ports {p[19]}]
set_input_delay -clock clk  0  [get_ports {p[18]}]
set_input_delay -clock clk  0  [get_ports {p[17]}]
set_input_delay -clock clk  0  [get_ports {p[16]}]
set_input_delay -clock clk  0  [get_ports {p[15]}]
set_input_delay -clock clk  0  [get_ports {p[14]}]
set_input_delay -clock clk  0  [get_ports {p[13]}]
set_input_delay -clock clk  0  [get_ports {p[12]}]
set_input_delay -clock clk  0  [get_ports {p[11]}]
set_input_delay -clock clk  0  [get_ports {p[10]}]
set_input_delay -clock clk  0  [get_ports {p[9]}]
set_input_delay -clock clk  0  [get_ports {p[8]}]
set_input_delay -clock clk  0  [get_ports {p[7]}]
set_input_delay -clock clk  0  [get_ports {p[6]}]
set_input_delay -clock clk  0  [get_ports {p[5]}]
set_input_delay -clock clk  0  [get_ports {p[4]}]
set_input_delay -clock clk  0  [get_ports {p[3]}]
set_input_delay -clock clk  0  [get_ports {p[2]}]
set_input_delay -clock clk  0  [get_ports {p[1]}]
set_input_delay -clock clk  0  [get_ports {p[0]}]
set_output_delay -clock clk  -max 1  [get_ports out_valid]
set_output_delay -clock clk  -min 0  [get_ports out_valid]
set_output_delay -clock clk  -max 1  [get_ports {p0i[30]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[30]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[29]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[29]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[28]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[28]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[27]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[27]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[26]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[26]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[25]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[25]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[24]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[24]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[23]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[23]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[22]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[22]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[21]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[21]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[20]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[20]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[19]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[19]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[18]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[18]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[17]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[17]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[16]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[16]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[15]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[15]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[14]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[14]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[13]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[13]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[12]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[12]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[11]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[11]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[10]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[10]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[9]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[9]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[8]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[8]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[7]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[7]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[6]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[6]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[5]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[5]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[4]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[4]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[3]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[3]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[2]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[2]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[1]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[1]}]
set_output_delay -clock clk  -max 1  [get_ports {p0i[0]}]
set_output_delay -clock clk  -min 0  [get_ports {p0i[0]}]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports in_valid]
set_input_transition -min 0.5  [get_ports in_valid]
set_input_transition -max 0.5  [get_ports {p[30]}]
set_input_transition -min 0.5  [get_ports {p[30]}]
set_input_transition -max 0.5  [get_ports {p[29]}]
set_input_transition -min 0.5  [get_ports {p[29]}]
set_input_transition -max 0.5  [get_ports {p[28]}]
set_input_transition -min 0.5  [get_ports {p[28]}]
set_input_transition -max 0.5  [get_ports {p[27]}]
set_input_transition -min 0.5  [get_ports {p[27]}]
set_input_transition -max 0.5  [get_ports {p[26]}]
set_input_transition -min 0.5  [get_ports {p[26]}]
set_input_transition -max 0.5  [get_ports {p[25]}]
set_input_transition -min 0.5  [get_ports {p[25]}]
set_input_transition -max 0.5  [get_ports {p[24]}]
set_input_transition -min 0.5  [get_ports {p[24]}]
set_input_transition -max 0.5  [get_ports {p[23]}]
set_input_transition -min 0.5  [get_ports {p[23]}]
set_input_transition -max 0.5  [get_ports {p[22]}]
set_input_transition -min 0.5  [get_ports {p[22]}]
set_input_transition -max 0.5  [get_ports {p[21]}]
set_input_transition -min 0.5  [get_ports {p[21]}]
set_input_transition -max 0.5  [get_ports {p[20]}]
set_input_transition -min 0.5  [get_ports {p[20]}]
set_input_transition -max 0.5  [get_ports {p[19]}]
set_input_transition -min 0.5  [get_ports {p[19]}]
set_input_transition -max 0.5  [get_ports {p[18]}]
set_input_transition -min 0.5  [get_ports {p[18]}]
set_input_transition -max 0.5  [get_ports {p[17]}]
set_input_transition -min 0.5  [get_ports {p[17]}]
set_input_transition -max 0.5  [get_ports {p[16]}]
set_input_transition -min 0.5  [get_ports {p[16]}]
set_input_transition -max 0.5  [get_ports {p[15]}]
set_input_transition -min 0.5  [get_ports {p[15]}]
set_input_transition -max 0.5  [get_ports {p[14]}]
set_input_transition -min 0.5  [get_ports {p[14]}]
set_input_transition -max 0.5  [get_ports {p[13]}]
set_input_transition -min 0.5  [get_ports {p[13]}]
set_input_transition -max 0.5  [get_ports {p[12]}]
set_input_transition -min 0.5  [get_ports {p[12]}]
set_input_transition -max 0.5  [get_ports {p[11]}]
set_input_transition -min 0.5  [get_ports {p[11]}]
set_input_transition -max 0.5  [get_ports {p[10]}]
set_input_transition -min 0.5  [get_ports {p[10]}]
set_input_transition -max 0.5  [get_ports {p[9]}]
set_input_transition -min 0.5  [get_ports {p[9]}]
set_input_transition -max 0.5  [get_ports {p[8]}]
set_input_transition -min 0.5  [get_ports {p[8]}]
set_input_transition -max 0.5  [get_ports {p[7]}]
set_input_transition -min 0.5  [get_ports {p[7]}]
set_input_transition -max 0.5  [get_ports {p[6]}]
set_input_transition -min 0.5  [get_ports {p[6]}]
set_input_transition -max 0.5  [get_ports {p[5]}]
set_input_transition -min 0.5  [get_ports {p[5]}]
set_input_transition -max 0.5  [get_ports {p[4]}]
set_input_transition -min 0.5  [get_ports {p[4]}]
set_input_transition -max 0.5  [get_ports {p[3]}]
set_input_transition -min 0.5  [get_ports {p[3]}]
set_input_transition -max 0.5  [get_ports {p[2]}]
set_input_transition -min 0.5  [get_ports {p[2]}]
set_input_transition -max 0.5  [get_ports {p[1]}]
set_input_transition -min 0.5  [get_ports {p[1]}]
set_input_transition -max 0.5  [get_ports {p[0]}]
set_input_transition -min 0.5  [get_ports {p[0]}]
