 
****************************************
Report : resources
Design : KEYGEN
Version: T-2022.03
Date   : Thu Oct  9 16:42:40 2025
****************************************


Resource Report for this hierarchy in file ../01_RTL/MODP_MKGM2.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| ash_1          | DW_leftsh      | A_width=10 | u_MODP_MKGM2/sll_349 (MODP_MKGM2.v:349) |
    |                | SH_width=4 |                            |
| sub_x_2        | DW01_sub       | width=4    | u_MODP_MKGM2/sub_350 (MODP_MKGM2.v:350) |
| lt_x_27        | DW_cmp         | width=32   | u_MODP_MKGM2/lt_536 (MODP_MKGM2.v:536) |
| eq_x_32        | DW_cmp         | width=10   | u_MODP_MKGM2/eq_558 (MODP_MKGM2.v:558) |
| lt_x_36        | DW_cmp         | width=32   | u_MODP_MKGM2/lt_583 (MODP_MKGM2.v:583) |
| ash_43         | DW_leftsh      | A_width=9  | u_MODP_MKGM2/sll_684 (MODP_MKGM2.v:684) |
    |                | SH_width=4 |                            |
| ash_46         | DW_leftsh      | A_width=9  | u_MODP_MKGM2/sll_703 (MODP_MKGM2.v:703) |
    |                | SH_width=4 |                            |
| sub_x_114      | DW01_sub       | width=31   | u_MODP_MKGM2/u_MODP_R/sub_25 (MODP_R.v:25) |
| add_x_115      | DW01_inc       | width=3    | u_MODP_MKGM2/u_MODP_DIV/add_127 (MODP_DIV.v:127) |
| sub_x_117      | DW01_sub       | width=31   | u_MODP_MKGM2/u_MODP_DIV/sub_137 (MODP_DIV.v:137) |
| sub_x_118      | DW01_dec       | width=5    | u_MODP_MKGM2/u_MODP_DIV/sub_151 (MODP_DIV.v:151) |
| lt_x_137       | DW_cmp         | width=3    | u_MODP_R2_TOP/genblk1[0].u_MODP_R2/lt_455 (MODP_R2_TOP.v:455) |
| lt_x_138       | DW_cmp         | width=3    | u_MODP_R2_TOP/genblk1[0].u_MODP_R2/lt_456 (MODP_R2_TOP.v:456) |
| sub_x_142      | DW01_sub       | width=2    | u_MODP_R2_TOP/genblk1[0].u_MODP_R2/sub_489 (MODP_R2_TOP.v:489) |
| add_x_143      | DW01_add       | width=32   | u_MODP_R2_TOP/genblk1[0].u_MODP_R2/add_489 (MODP_R2_TOP.v:489) |
| sub_x_146      | DW01_sub       | width=31   | u_MODP_R2_TOP/genblk1[0].u_MODP_R2/u_MODP_R/sub_25 (MODP_R.v:25) |
| add_x_13       | DW01_inc       | width=10   | u_MODP_MKGM2/add_420 (MODP_MKGM2.v:420) |
    |                |            | u_MODP_MKGM2/add_425 (MODP_MKGM2.v:425) |
    |                |            | u_MODP_MKGM2/add_430 (MODP_MKGM2.v:430) |
    |                |            | u_MODP_MKGM2/add_435 (MODP_MKGM2.v:435) |
| sub_x_26       | DW01_sub       | width=11   | u_MODP_MKGM2/sub_536 (MODP_MKGM2.v:536) |
    |                |            | u_MODP_MKGM2/sub_583 (MODP_MKGM2.v:583) |
| add_x_21       | DW01_inc       | width=10   | u_MODP_MKGM2/add_449 (MODP_MKGM2.v:449) |
    |                |            | u_MODP_MKGM2/add_454 (MODP_MKGM2.v:454) |
| add_x_134      | DW01_inc       | width=3    | u_MODP_R2_TOP/genblk1[0].u_MODP_R2/add_403 (MODP_R2_TOP.v:403) |
|          | u_MODP_R2_TOP/genblk1[0].u_MODP_R2/add_405 (MODP_R2_TOP.v:405) |
| lt_x_147       | DW_cmp         | width=32   | u_MODP_MKGM2/lt_424 (MODP_MKGM2.v:424) |
     |                |            | u_MODP_MKGM2/lt_429 (MODP_MKGM2.v:429) |
     |                |            | u_MODP_MKGM2/lt_434 (MODP_MKGM2.v:434) |
| lt_x_148       | DW_cmp         | width=32   | u_MODP_MKGM2/lt_448 (MODP_MKGM2.v:448) |
     |                |            | u_MODP_MKGM2/lt_453 (MODP_MKGM2.v:453) |
| DP_OP_249J1_122_3176            |            |                            |
|                | DP_OP_249J1_122_3176 |      |                            |
| DP_OP_250J1_123_1144            |            |                            |
|                | DP_OP_250J1_123_1144 |      |                            |
| DP_OP_251J1_124_5295            |            |                            |
|                | DP_OP_251J1_124_5295 |      |                            |
| DP_OP_25_129_5090               |            |                            |
|                | DP_OP_25_129_5090 |         |                            |
| DP_OP_26_130_8311               |            |                            |
|                | DP_OP_26_130_8311 |         |                            |
=============================================================================

Datapath Report for DP_OP_249J1_122_3176
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_249J1_122_3176 | u_MODP_MKGM2/sub_379 (MODP_MKGM2.v:379)             |
|                      | u_MODP_MKGM2/sub_389 (MODP_MKGM2.v:389)             |
|                      | u_MODP_MKGM2/sub_399 (MODP_MKGM2.v:399)             |
|                      | u_MODP_MKGM2/sub_399_2 (MODP_MKGM2.v:399)           |
|                      | u_MODP_MKGM2/sub_424 (MODP_MKGM2.v:424)             |
|                      | u_MODP_MKGM2/sub_429 (MODP_MKGM2.v:429)             |
|                      | u_MODP_MKGM2/sub_434 (MODP_MKGM2.v:434)             |
|                      | u_MODP_MKGM2/sub_448 (MODP_MKGM2.v:448)             |
|                      | u_MODP_MKGM2/sub_453 (MODP_MKGM2.v:453)             |
|                      | u_MODP_MKGM2/eq_379 (MODP_MKGM2.v:379)              |
|                      | u_MODP_MKGM2/eq_399 (MODP_MKGM2.v:399)              |
|                      | u_MODP_MKGM2/eq_389 (MODP_MKGM2.v:389)              |
|                      | u_MODP_MKGM2/eq_399_2 (MODP_MKGM2.v:399)            |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 10    |                                          |
| I3    | PI   | Unsigned | 10    |                                          |
| T175  | IFO  | Signed   | 32    | O1                                       |
| T246  | IFO  | Signed   | 32    | O1                                       |
| O1    | PO   | Signed   | 11    | I1 - $unsigned(1'b1) ( MODP_MKGM2.v:379 MODP_MKGM2.v:389 MODP_MKGM2.v:399 MODP_MKGM2.v:424 MODP_MKGM2.v:429 MODP_MKGM2.v:434 MODP_MKGM2.v:448 MODP_MKGM2.v:453 ) |
| O2    | PO   | Unsigned | 1     | I2 == $unsigned(T175) ( MODP_MKGM2.v:379 MODP_MKGM2.v:399 ) |
| O3    | PO   | Unsigned | 1     | I3 == $unsigned(T246) ( MODP_MKGM2.v:389 MODP_MKGM2.v:399 ) |
==============================================================================

Datapath Report for DP_OP_250J1_123_1144
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_250J1_123_1144 | u_MODP_MKGM2/u_MODP_DIV/mult_add_121_aco (MODP_DIV.v:121) |
                 | u_MODP_MKGM2/u_MODP_DIV/add_121_aco (MODP_DIV.v:121) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 3     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| T149  | IFO  | Unsigned | 3     | I1 * I2 (MODP_DIV.v:121)                 |
| O1    | PO   | Unsigned | 3     | T149 + $unsigned(1'b1) (MODP_DIV.v:121)  |
==============================================================================

Datapath Report for DP_OP_251J1_124_5295
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_251J1_124_5295 | u_MODP_R2_TOP/genblk1[0].u_MODP_R2/u_MODP_ADD/add_43 (MODP_ADD.v:43) |
      | u_MODP_R2_TOP/genblk1[0].u_MODP_R2/u_MODP_ADD/sub_44 (MODP_ADD.v:44) |
      | u_MODP_R2_TOP/genblk1[0].u_MODP_R2/u_MODP_ADD/gte_45 (MODP_ADD.v:45) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| T220  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 32    | I1 + I1 (MODP_ADD.v:43)                  |
| O2    | PO   | Signed   | 31    | T220 - I2 (MODP_ADD.v:44)                |
| O3    | PO   | Unsigned | 1     | O1 >= I2 (MODP_ADD.v:45)                 |
==============================================================================

Datapath Report for DP_OP_25_129_5090
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_25_129_5090    | add_285 (MODP_MONTYMUL_TOP.v:285)                   |
|                      | sub_293 (MODP_MONTYMUL_TOP.v:293)                   |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 48    |                                          |
| I2    | PI   | Unsigned | 47    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T17   | IFO  | Signed   | 31    | O1[46:16]                                |
| O1    | PO   | Unsigned | 48    | I1 + I2 (MODP_MONTYMUL_TOP.v:285)        |
| O2    | PO   | Signed   | 31    | T17 - I3 (MODP_MONTYMUL_TOP.v:293)       |
==============================================================================

Datapath Report for DP_OP_26_130_8311
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_26_130_8311    | add_286 (MODP_MONTYMUL_TOP.v:286)                   |
|                      | gte_298 (MODP_MONTYMUL_TOP.v:298)                   |
|                      | sub_299 (MODP_MONTYMUL_TOP.v:299)                   |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 62    |                                          |
| I2    | PI   | Unsigned | 62    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T15   | IFO  | Unsigned | 32    | O1[62:31]                                |
| T18   | IFO  | Signed   | 31    | O1[61:31]                                |
| O1    | PO   | Unsigned | 63    | I1 + I2 (MODP_MONTYMUL_TOP.v:286)        |
| O2    | PO   | Unsigned | 1     | T15 >= I3 (MODP_MONTYMUL_TOP.v:298)      |
| O3    | PO   | Signed   | 31    | T18 - I3 (MODP_MONTYMUL_TOP.v:299)       |
==============================================================================


Resource Report for Ungrouped Hierarchy
        u_MODP_MONTYMUL_TOP/genblk1[0].u_MODP_MONTYMUL in file
        ../01_RTL/MODP_MONTYMUL_TOP.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| mult_x_1       | DW_mult_uns    | a_width=31 | mult_269 (MODP_MONTYMUL_TOP.v:269) |
         |                | b_width=31 |                            |
| mult_x_2       | DW_mult_uns    | a_width=31 | mult_274 (MODP_MONTYMUL_TOP.v:274) |
         |                | b_width=31 |                            |
| mult_x_3       | DW_mult_uns    | a_width=16 | mult_279 (MODP_MONTYMUL_TOP.v:279) |
         |                | b_width=31 |                            |
| mult_x_4       | DW_mult_uns    | a_width=31 | mult_280 (MODP_MONTYMUL_TOP.v:280) |
         |                | b_width=31 |                            |
| gte_x_5        | DW_cmp         | width=32   | gte_292 (MODP_MONTYMUL_TOP.v:292) |
=============================================================================


Datapath Extraction Report

Information: Operator associated with resources 'u_MODP_MKGM2/sub_379 (MODP_MKGM2.v:379) u_MODP_MKGM2/sub_389 (MODP_MKGM2.v:389) u_MODP_MKGM2/sub_399 (MODP_MKGM2.v:399) u_MODP_MKGM2/sub_399_2 (MODP_MKGM2.v:399) u_MODP_MKGM2/sub_424 (MODP_MKGM2.v:424) u_MODP_MKGM2/sub_429 (MODP_MKGM2.v:429) u_MODP_MKGM2/sub_434 (MODP_MKGM2.v:434) u_MODP_MKGM2/sub_448 (MODP_MKGM2.v:448) u_MODP_MKGM2/sub_453 (MODP_MKGM2.v:453)' in design 'KEYGEN' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'u_MODP_MKGM2/sll_349 (MODP_MKGM2.v:349)'.  (HDL-120)

Information: Operator associated with resources 'u_MODP_MKGM2/lt_424 (MODP_MKGM2.v:424) u_MODP_MKGM2/lt_429 (MODP_MKGM2.v:429) u_MODP_MKGM2/lt_434 (MODP_MKGM2.v:434)' in design 'KEYGEN' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'u_MODP_MKGM2/sub_379 (MODP_MKGM2.v:379) u_MODP_MKGM2/sub_389 (MODP_MKGM2.v:389) u_MODP_MKGM2/sub_399 (MODP_MKGM2.v:399) u_MODP_MKGM2/sub_399_2 (MODP_MKGM2.v:399) u_MODP_MKGM2/sub_424 (MODP_MKGM2.v:424) u_MODP_MKGM2/sub_429 (MODP_MKGM2.v:429) u_MODP_MKGM2/sub_434 (MODP_MKGM2.v:434) u_MODP_MKGM2/sub_448 (MODP_MKGM2.v:448) u_MODP_MKGM2/sub_453 (MODP_MKGM2.v:453)'.  (HDL-120)

Information: The output of subtractor associated with resources 'u_MODP_MKGM2/sub_379 (MODP_MKGM2.v:379) u_MODP_MKGM2/sub_389 (MODP_MKGM2.v:389) u_MODP_MKGM2/sub_399 (MODP_MKGM2.v:399) u_MODP_MKGM2/sub_399_2 (MODP_MKGM2.v:399) u_MODP_MKGM2/sub_424 (MODP_MKGM2.v:424) u_MODP_MKGM2/sub_429 (MODP_MKGM2.v:429) u_MODP_MKGM2/sub_434 (MODP_MKGM2.v:434) u_MODP_MKGM2/sub_448 (MODP_MKGM2.v:448) u_MODP_MKGM2/sub_453 (MODP_MKGM2.v:453)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'u_MODP_MKGM2/lt_536 (MODP_MKGM2.v:536)' in design 'KEYGEN' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'u_MODP_MKGM2/sub_536 (MODP_MKGM2.v:536) u_MODP_MKGM2/sub_583 (MODP_MKGM2.v:583)'.  (HDL-120)

Information: The output of subtractor associated with resources 'u_MODP_MKGM2/sub_536 (MODP_MKGM2.v:536) u_MODP_MKGM2/sub_583 (MODP_MKGM2.v:583)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'u_MODP_R2_TOP/genblk1[0].u_MODP_R2/u_MODP_R/sub_25 (MODP_R.v:25)' in design 'KEYGEN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'u_MODP_R2_TOP/genblk1[0].u_MODP_R2/u_MODP_ADD/add_43 (MODP_ADD.v:43)'.  (HDL-120)


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| ash_1              | DW_leftsh        | astr (area)        |                |
| sub_x_2            | DW01_sub         | apparch (area)     |                |
| lt_x_27            | DW_cmp           | apparch (area)     |                |
| eq_x_32            | DW_cmp           | apparch (area)     |                |
| lt_x_36            | DW_cmp           | apparch (area)     |                |
| ash_43             | DW_leftsh        | astr (area)        |                |
| ash_46             | DW_leftsh        | astr (area)        |                |
| sub_x_114          | DW01_sub         | pparch (area,speed)                 |
| add_x_115          | DW01_inc         | apparch (area)     |                |
| sub_x_117          | DW01_sub         | pparch (area,speed)                 |
| sub_x_118          | DW01_dec         | apparch (area)     |                |
| lt_x_137           | DW_cmp           | apparch (area)     |                |
| lt_x_138           | DW_cmp           | apparch (area)     |                |
| sub_x_142          | DW01_sub         | apparch (area)     |                |
| add_x_143          | DW01_add         | pparch (area,speed)                 |
| sub_x_146          | DW01_sub         | pparch (area,speed)                 |
| add_x_13           | DW01_inc         | apparch (area)     |                |
| sub_x_26           | DW01_sub         | apparch (area)     |                |
| add_x_21           | DW01_inc         | apparch (area)     |                |
| add_x_134          | DW01_inc         | apparch (area)     |                |
| lt_x_147           | DW_cmp           | apparch (area)     |                |
| lt_x_148           | DW_cmp           | apparch (area)     |                |
| mult_x_1           | DW_mult_uns      | pparch (area,speed)                 |
|                    |                  | mult_arch: benc_radix4              |
| mult_x_2           | DW_mult_uns      | pparch (area,speed)                 |
|                    |                  | mult_arch: benc_radix4              |
| mult_x_4           | DW_mult_uns      | pparch (area,speed)                 |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_249J1_122_3176                  |                    |                |
|                    | DP_OP_249J1_122_3176 | str (area,speed)                |
| DP_OP_250J1_123_1144                  |                    |                |
|                    | DP_OP_250J1_123_1144 | str (area)     |                |
|                    |                  | mult_arch: and     |                |
| DP_OP_251J1_124_5295                  |                    |                |
|                    | DP_OP_251J1_124_5295 | str (area,speed)                |
| DP_OP_25_129_5090  | DP_OP_25_129_5090 | str (area)        |                |
| DP_OP_26_130_8311  | DP_OP_26_130_8311 | str (area,speed)  |                |
===============================================================================

1
