#!/bin/bash

# ==============================================================================
# Parameters
# ==============================================================================
PERIOD="1.2"

# ==============================================================================
# Usage
# ==============================================================================
usage() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  -p <PERIOD>    Set cycle time (default: $PERIOD ns)"
    echo "  -h             Help message"
    exit 1
}

# ==============================================================================
# Flag settings
# ==============================================================================
while getopts "p:h" opt; do
    case ${opt} in
        p)
            PERIOD=$OPTARG
            ;;
        h)
            usage
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
            ;;
    esac
done

make vcs_gate period=$PERIOD