 
****************************************
Report : resources
Design : MQ_NTT
Version: T-2022.03
Date   : Fri Sep  5 09:24:43 2025
****************************************


Resource Report for this hierarchy
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_130      | DW_cmp         | width=10   | genblk1[0].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_134       | DW_cmp         | width=10   | genblk1[0].u_RADIX2/lt_152 (RADIX2.v:152) |
| add_x_135      | DW01_inc       | width=10   | genblk1[0].u_RADIX2/add_158 (RADIX2.v:158) |
| add_x_136      | DW01_inc       | width=2    | genblk1[0].u_RADIX2/add_159 (RADIX2.v:159) |
| eq_x_139       | DW_cmp         | width=9    | genblk1[0].u_RADIX2/eq_167 (RADIX2.v:167) |
| eq_x_140       | DW_cmp         | width=9    | genblk1[0].u_RADIX2/eq_174 (RADIX2.v:174) |
| gte_x_153      | DW_cmp         | width=10   | genblk1[1].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_157       | DW_cmp         | width=10   | genblk1[1].u_RADIX2/lt_152 (RADIX2.v:152) |
| add_x_158      | DW01_inc       | width=9    | genblk1[1].u_RADIX2/add_158 (RADIX2.v:158) |
| add_x_159      | DW01_add       | width=3    | genblk1[1].u_RADIX2/add_159 (RADIX2.v:159) |
| eq_x_162       | DW_cmp         | width=8    | genblk1[1].u_RADIX2/eq_167 (RADIX2.v:167) |
| eq_x_163       | DW_cmp         | width=8    | genblk1[1].u_RADIX2/eq_174 (RADIX2.v:174) |
| gte_x_176      | DW_cmp         | width=10   | genblk1[2].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_180       | DW_cmp         | width=10   | genblk1[2].u_RADIX2/lt_152 (RADIX2.v:152) |
| add_x_181      | DW01_inc       | width=9    | genblk1[2].u_RADIX2/add_158 (RADIX2.v:158) |
| add_x_182      | DW01_add       | width=4    | genblk1[2].u_RADIX2/add_159 (RADIX2.v:159) |
| eq_x_185       | DW_cmp         | width=7    | genblk1[2].u_RADIX2/eq_167 (RADIX2.v:167) |
| eq_x_186       | DW_cmp         | width=7    | genblk1[2].u_RADIX2/eq_174 (RADIX2.v:174) |
| gte_x_199      | DW_cmp         | width=10   | genblk1[3].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_203       | DW_cmp         | width=10   | genblk1[3].u_RADIX2/lt_152 (RADIX2.v:152) |
| add_x_204      | DW01_inc       | width=9    | genblk1[3].u_RADIX2/add_158 (RADIX2.v:158) |
| eq_x_208       | DW_cmp         | width=6    | genblk1[3].u_RADIX2/eq_167 (RADIX2.v:167) |
| eq_x_209       | DW_cmp         | width=6    | genblk1[3].u_RADIX2/eq_174 (RADIX2.v:174) |
| gte_x_222      | DW_cmp         | width=10   | genblk1[4].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_226       | DW_cmp         | width=10   | genblk1[4].u_RADIX2/lt_152 (RADIX2.v:152) |
| add_x_227      | DW01_inc       | width=9    | genblk1[4].u_RADIX2/add_158 (RADIX2.v:158) |
| eq_x_231       | DW_cmp         | width=5    | genblk1[4].u_RADIX2/eq_167 (RADIX2.v:167) |
| eq_x_232       | DW_cmp         | width=5    | genblk1[4].u_RADIX2/eq_174 (RADIX2.v:174) |
| gte_x_245      | DW_cmp         | width=10   | genblk1[5].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_249       | DW_cmp         | width=10   | genblk1[5].u_RADIX2/lt_152 (RADIX2.v:152) |
| add_x_250      | DW01_inc       | width=9    | genblk1[5].u_RADIX2/add_158 (RADIX2.v:158) |
| eq_x_254       | DW_cmp         | width=4    | genblk1[5].u_RADIX2/eq_167 (RADIX2.v:167) |
| eq_x_255       | DW_cmp         | width=4    | genblk1[5].u_RADIX2/eq_174 (RADIX2.v:174) |
| gte_x_268      | DW_cmp         | width=10   | genblk1[6].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_272       | DW_cmp         | width=10   | genblk1[6].u_RADIX2/lt_152 (RADIX2.v:152) |
| add_x_273      | DW01_inc       | width=9    | genblk1[6].u_RADIX2/add_158 (RADIX2.v:158) |
| eq_x_277       | DW_cmp         | width=3    | genblk1[6].u_RADIX2/eq_167 (RADIX2.v:167) |
| eq_x_278       | DW_cmp         | width=3    | genblk1[6].u_RADIX2/eq_174 (RADIX2.v:174) |
| gte_x_291      | DW_cmp         | width=10   | genblk1[7].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_295       | DW_cmp         | width=10   | genblk1[7].u_RADIX2/lt_152 (RADIX2.v:152) |
| add_x_296      | DW01_inc       | width=9    | genblk1[7].u_RADIX2/add_158 (RADIX2.v:158) |
| eq_x_300       | DW_cmp         | width=2    | genblk1[7].u_RADIX2/eq_167 (RADIX2.v:167) |
| eq_x_301       | DW_cmp         | width=2    | genblk1[7].u_RADIX2/eq_174 (RADIX2.v:174) |
| gte_x_314      | DW_cmp         | width=10   | genblk1[8].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_318       | DW_cmp         | width=10   | genblk1[8].u_RADIX2/lt_152 (RADIX2.v:152) |
| add_x_319      | DW01_inc       | width=9    | genblk1[8].u_RADIX2/add_158 (RADIX2.v:158) |
| mult_x_331     | DW_mult_uns    | a_width=16 | genblk1[0].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_333     | DW_mult_uns    | a_width=16 | genblk1[8].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_335     | DW_mult_uns    | a_width=16 | genblk1[7].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_337     | DW_mult_uns    | a_width=16 | genblk1[6].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_339     | DW_mult_uns    | a_width=16 | genblk1[5].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_341     | DW_mult_uns    | a_width=16 | genblk1[4].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_343     | DW_mult_uns    | a_width=16 | genblk1[3].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_345     | DW_mult_uns    | a_width=16 | genblk1[2].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_347     | DW_mult_uns    | a_width=16 | genblk1[1].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| add_x_138      | DW01_add       | width=9    | genblk1[0].u_RADIX2/add_167 (RADIX2.v:167) |
 |                |            | genblk1[0].u_RADIX2/add_172 (RADIX2.v:172) |
 |                |            | genblk1[0].u_RADIX2/add_174 (RADIX2.v:174) |
| add_x_161      | DW01_add       | width=8    | genblk1[1].u_RADIX2/add_167 (RADIX2.v:167) |
 |                |            | genblk1[1].u_RADIX2/add_172 (RADIX2.v:172) |
 |                |            | genblk1[1].u_RADIX2/add_174 (RADIX2.v:174) |
| add_x_184      | DW01_add       | width=7    | genblk1[2].u_RADIX2/add_167 (RADIX2.v:167) |
 |                |            | genblk1[2].u_RADIX2/add_172 (RADIX2.v:172) |
 |                |            | genblk1[2].u_RADIX2/add_174 (RADIX2.v:174) |
| add_x_207      | DW01_add       | width=6    | genblk1[3].u_RADIX2/add_167 (RADIX2.v:167) |
 |                |            | genblk1[3].u_RADIX2/add_172 (RADIX2.v:172) |
 |                |            | genblk1[3].u_RADIX2/add_174 (RADIX2.v:174) |
| add_x_230      | DW01_add       | width=5    | genblk1[4].u_RADIX2/add_167 (RADIX2.v:167) |
 |                |            | genblk1[4].u_RADIX2/add_172 (RADIX2.v:172) |
 |                |            | genblk1[4].u_RADIX2/add_174 (RADIX2.v:174) |
| add_x_253      | DW01_add       | width=4    | genblk1[5].u_RADIX2/add_167 (RADIX2.v:167) |
 |                |            | genblk1[5].u_RADIX2/add_172 (RADIX2.v:172) |
 |                |            | genblk1[5].u_RADIX2/add_174 (RADIX2.v:174) |
| add_x_276      | DW01_add       | width=3    | genblk1[6].u_RADIX2/add_167 (RADIX2.v:167) |
 |                |            | genblk1[6].u_RADIX2/add_172 (RADIX2.v:172) |
 |                |            | genblk1[6].u_RADIX2/add_174 (RADIX2.v:174) |
| add_x_299      | DW01_add       | width=2    | genblk1[7].u_RADIX2/add_167 (RADIX2.v:167) |
 |                |            | genblk1[7].u_RADIX2/add_172 (RADIX2.v:172) |
 |                |            | genblk1[7].u_RADIX2/add_174 (RADIX2.v:174) |
| add_x_131      | DW01_inc       | width=10   | genblk1[0].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[0].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_154      | DW01_inc       | width=10   | genblk1[1].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[1].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_177      | DW01_inc       | width=10   | genblk1[2].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[2].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_200      | DW01_inc       | width=10   | genblk1[3].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[3].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_223      | DW01_inc       | width=10   | genblk1[4].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[4].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_246      | DW01_inc       | width=10   | genblk1[5].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[5].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_269      | DW01_inc       | width=10   | genblk1[6].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[6].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_292      | DW01_inc       | width=10   | genblk1[7].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[7].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_315      | DW01_inc       | width=10   | genblk1[8].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[8].u_RADIX2/add_142 (RADIX2.v:142) |
| DP_OP_684J1_122_4154            |            |                            |
|                | DP_OP_684J1_122_4154 |      |                            |
| DP_OP_685J1_123_3090            |            |                            |
|                | DP_OP_685J1_123_3090 |      |                            |
| DP_OP_686J1_124_9405            |            |                            |
|                | DP_OP_686J1_124_9405 |      |                            |
| DP_OP_687J1_125_4154            |            |                            |
|                | DP_OP_687J1_125_4154 |      |                            |
| DP_OP_688J1_126_3090            |            |                            |
|                | DP_OP_688J1_126_3090 |      |                            |
| DP_OP_689J1_127_9405            |            |                            |
|                | DP_OP_689J1_127_9405 |      |                            |
| DP_OP_690J1_128_4154            |            |                            |
|                | DP_OP_690J1_128_4154 |      |                            |
| DP_OP_691J1_129_3090            |            |                            |
|                | DP_OP_691J1_129_3090 |      |                            |
| DP_OP_692J1_130_9405            |            |                            |
|                | DP_OP_692J1_130_9405 |      |                            |
| DP_OP_693J1_131_4154            |            |                            |
|                | DP_OP_693J1_131_4154 |      |                            |
| DP_OP_694J1_132_3090            |            |                            |
|                | DP_OP_694J1_132_3090 |      |                            |
| DP_OP_695J1_133_9405            |            |                            |
|                | DP_OP_695J1_133_9405 |      |                            |
| DP_OP_696J1_134_4154            |            |                            |
|                | DP_OP_696J1_134_4154 |      |                            |
| DP_OP_697J1_135_3090            |            |                            |
|                | DP_OP_697J1_135_3090 |      |                            |
| DP_OP_698J1_136_9405            |            |                            |
|                | DP_OP_698J1_136_9405 |      |                            |
| DP_OP_699J1_137_4154            |            |                            |
|                | DP_OP_699J1_137_4154 |      |                            |
| DP_OP_700J1_138_3090            |            |                            |
|                | DP_OP_700J1_138_3090 |      |                            |
| DP_OP_701J1_139_9405            |            |                            |
|                | DP_OP_701J1_139_9405 |      |                            |
| DP_OP_702J1_140_4154            |            |                            |
|                | DP_OP_702J1_140_4154 |      |                            |
| DP_OP_703J1_141_3090            |            |                            |
|                | DP_OP_703J1_141_3090 |      |                            |
| DP_OP_704J1_142_9405            |            |                            |
|                | DP_OP_704J1_142_9405 |      |                            |
| DP_OP_705J1_143_4154            |            |                            |
|                | DP_OP_705J1_143_4154 |      |                            |
| DP_OP_706J1_144_3090            |            |                            |
|                | DP_OP_706J1_144_3090 |      |                            |
| DP_OP_707J1_145_9405            |            |                            |
|                | DP_OP_707J1_145_9405 |      |                            |
| DP_OP_708J1_146_4154            |            |                            |
|                | DP_OP_708J1_146_4154 |      |                            |
| DP_OP_709J1_147_3090            |            |                            |
|                | DP_OP_709J1_147_3090 |      |                            |
| DP_OP_710J1_148_9405            |            |                            |
|                | DP_OP_710J1_148_9405 |      |                            |
| DP_OP_711J1_149_8155            |            |                            |
|                | DP_OP_711J1_149_8155 |      |                            |
| DP_OP_712J1_150_8155            |            |                            |
|                | DP_OP_712J1_150_8155 |      |                            |
| DP_OP_713J1_151_8155            |            |                            |
|                | DP_OP_713J1_151_8155 |      |                            |
| DP_OP_714J1_152_8155            |            |                            |
|                | DP_OP_714J1_152_8155 |      |                            |
| DP_OP_715J1_153_8155            |            |                            |
|                | DP_OP_715J1_153_8155 |      |                            |
| DP_OP_716J1_154_8155            |            |                            |
|                | DP_OP_716J1_154_8155 |      |                            |
| DP_OP_717J1_155_8155            |            |                            |
|                | DP_OP_717J1_155_8155 |      |                            |
| DP_OP_718J1_156_8155            |            |                            |
|                | DP_OP_718J1_156_8155 |      |                            |
| DP_OP_719J1_157_8155            |            |                            |
|                | DP_OP_719J1_157_8155 |      |                            |
=============================================================================

Datapath Report for DP_OP_684J1_122_4154
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_684J1_122_4154 | genblk1[0].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[0].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T624  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T624 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_685J1_123_3090
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_685J1_123_3090 | genblk1[0].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[0].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[0].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T418  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T622  | IFO  | Signed   | 14    | T418[13:0]                               |
| O1    | PO   | Signed   | 14    | T622 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T418 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_686J1_124_9405
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_686J1_124_9405 | genblk1[0].u_RADIX2/u_mq_montymul/add_162 (MQ.v:162) |
                      | genblk1[0].u_RADIX2/u_mq_montymul/gte_172 (MQ.v:172) |
                      | genblk1[0].u_RADIX2/u_mq_montymul/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T358  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T571  | IFO  | Unsigned | 15    | T358[30:16]                              |
| T572  | IFO  | Signed   | 14    | T358[29:16]                              |
| O1    | PO   | Unsigned | 1     | T571 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T572 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_687J1_125_4154
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_687J1_125_4154 | genblk1[1].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[1].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T656  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T656 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_688J1_126_3090
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_688J1_126_3090 | genblk1[1].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[1].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[1].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T444  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T640  | IFO  | Signed   | 14    | T444[13:0]                               |
| O1    | PO   | Signed   | 14    | T640 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T444 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_689J1_127_9405
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_689J1_127_9405 | genblk1[1].u_RADIX2/u_mq_montymul/add_162 (MQ.v:162) |
                      | genblk1[1].u_RADIX2/u_mq_montymul/gte_172 (MQ.v:172) |
                      | genblk1[1].u_RADIX2/u_mq_montymul/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T414  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T619  | IFO  | Unsigned | 15    | T414[30:16]                              |
| T620  | IFO  | Signed   | 14    | T414[29:16]                              |
| O1    | PO   | Unsigned | 1     | T619 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T620 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_690J1_128_4154
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_690J1_128_4154 | genblk1[2].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[2].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T654  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T654 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_691J1_129_3090
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_691J1_129_3090 | genblk1[2].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[2].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[2].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T441  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T638  | IFO  | Signed   | 14    | T441[13:0]                               |
| O1    | PO   | Signed   | 14    | T638 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T441 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_692J1_130_9405
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_692J1_130_9405 | genblk1[2].u_RADIX2/u_mq_montymul/add_162 (MQ.v:162) |
                      | genblk1[2].u_RADIX2/u_mq_montymul/gte_172 (MQ.v:172) |
                      | genblk1[2].u_RADIX2/u_mq_montymul/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T407  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T613  | IFO  | Unsigned | 15    | T407[30:16]                              |
| T614  | IFO  | Signed   | 14    | T407[29:16]                              |
| O1    | PO   | Unsigned | 1     | T613 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T614 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_693J1_131_4154
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_693J1_131_4154 | genblk1[3].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[3].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T652  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T652 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_694J1_132_3090
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_694J1_132_3090 | genblk1[3].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[3].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[3].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T438  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T636  | IFO  | Signed   | 14    | T438[13:0]                               |
| O1    | PO   | Signed   | 14    | T636 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T438 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_695J1_133_9405
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_695J1_133_9405 | genblk1[3].u_RADIX2/u_mq_montymul/add_162 (MQ.v:162) |
                      | genblk1[3].u_RADIX2/u_mq_montymul/gte_172 (MQ.v:172) |
                      | genblk1[3].u_RADIX2/u_mq_montymul/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T400  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T607  | IFO  | Unsigned | 15    | T400[30:16]                              |
| T608  | IFO  | Signed   | 14    | T400[29:16]                              |
| O1    | PO   | Unsigned | 1     | T607 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T608 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_696J1_134_4154
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_696J1_134_4154 | genblk1[4].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[4].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T650  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T650 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_697J1_135_3090
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_697J1_135_3090 | genblk1[4].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[4].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[4].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T435  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T634  | IFO  | Signed   | 14    | T435[13:0]                               |
| O1    | PO   | Signed   | 14    | T634 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T435 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_698J1_136_9405
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_698J1_136_9405 | genblk1[4].u_RADIX2/u_mq_montymul/add_162 (MQ.v:162) |
                      | genblk1[4].u_RADIX2/u_mq_montymul/gte_172 (MQ.v:172) |
                      | genblk1[4].u_RADIX2/u_mq_montymul/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T393  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T601  | IFO  | Unsigned | 15    | T393[30:16]                              |
| T602  | IFO  | Signed   | 14    | T393[29:16]                              |
| O1    | PO   | Unsigned | 1     | T601 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T602 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_699J1_137_4154
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_699J1_137_4154 | genblk1[5].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[5].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T648  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T648 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_700J1_138_3090
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_700J1_138_3090 | genblk1[5].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[5].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[5].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T432  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T632  | IFO  | Signed   | 14    | T432[13:0]                               |
| O1    | PO   | Signed   | 14    | T632 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T432 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_701J1_139_9405
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_701J1_139_9405 | genblk1[5].u_RADIX2/u_mq_montymul/add_162 (MQ.v:162) |
                      | genblk1[5].u_RADIX2/u_mq_montymul/gte_172 (MQ.v:172) |
                      | genblk1[5].u_RADIX2/u_mq_montymul/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T386  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T595  | IFO  | Unsigned | 15    | T386[30:16]                              |
| T596  | IFO  | Signed   | 14    | T386[29:16]                              |
| O1    | PO   | Unsigned | 1     | T595 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T596 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_702J1_140_4154
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_702J1_140_4154 | genblk1[6].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[6].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T646  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T646 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_703J1_141_3090
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_703J1_141_3090 | genblk1[6].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[6].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[6].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T429  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T630  | IFO  | Signed   | 14    | T429[13:0]                               |
| O1    | PO   | Signed   | 14    | T630 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T429 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_704J1_142_9405
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_704J1_142_9405 | genblk1[6].u_RADIX2/u_mq_montymul/add_162 (MQ.v:162) |
                      | genblk1[6].u_RADIX2/u_mq_montymul/gte_172 (MQ.v:172) |
                      | genblk1[6].u_RADIX2/u_mq_montymul/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T379  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T589  | IFO  | Unsigned | 15    | T379[30:16]                              |
| T590  | IFO  | Signed   | 14    | T379[29:16]                              |
| O1    | PO   | Unsigned | 1     | T589 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T590 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_705J1_143_4154
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_705J1_143_4154 | genblk1[7].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[7].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T644  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T644 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_706J1_144_3090
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_706J1_144_3090 | genblk1[7].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[7].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[7].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T426  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T628  | IFO  | Signed   | 14    | T426[13:0]                               |
| O1    | PO   | Signed   | 14    | T628 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T426 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_707J1_145_9405
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_707J1_145_9405 | genblk1[7].u_RADIX2/u_mq_montymul/add_162 (MQ.v:162) |
                      | genblk1[7].u_RADIX2/u_mq_montymul/gte_172 (MQ.v:172) |
                      | genblk1[7].u_RADIX2/u_mq_montymul/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T372  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T583  | IFO  | Unsigned | 15    | T372[30:16]                              |
| T584  | IFO  | Signed   | 14    | T372[29:16]                              |
| O1    | PO   | Unsigned | 1     | T583 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T584 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_708J1_146_4154
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_708J1_146_4154 | genblk1[8].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[8].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T642  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T642 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_709J1_147_3090
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_709J1_147_3090 | genblk1[8].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[8].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[8].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T423  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T626  | IFO  | Signed   | 14    | T423[13:0]                               |
| O1    | PO   | Signed   | 14    | T626 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T423 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_710J1_148_9405
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_710J1_148_9405 | genblk1[8].u_RADIX2/u_mq_montymul/add_162 (MQ.v:162) |
                      | genblk1[8].u_RADIX2/u_mq_montymul/gte_172 (MQ.v:172) |
                      | genblk1[8].u_RADIX2/u_mq_montymul/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T365  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T577  | IFO  | Unsigned | 15    | T365[30:16]                              |
| T578  | IFO  | Signed   | 14    | T365[29:16]                              |
| O1    | PO   | Unsigned | 1     | T577 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T578 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_711J1_149_8155
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_711J1_149_8155 | genblk1[0].u_RADIX2/u_mq_montymul/mult_152 (MQ.v:152) |
                     | genblk1[0].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T570  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T570 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_712J1_150_8155
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_712J1_150_8155 | genblk1[8].u_RADIX2/u_mq_montymul/mult_152 (MQ.v:152) |
                     | genblk1[8].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T576  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T576 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_713J1_151_8155
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_713J1_151_8155 | genblk1[7].u_RADIX2/u_mq_montymul/mult_152 (MQ.v:152) |
                     | genblk1[7].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T582  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T582 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_714J1_152_8155
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_714J1_152_8155 | genblk1[6].u_RADIX2/u_mq_montymul/mult_152 (MQ.v:152) |
                     | genblk1[6].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T588  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T588 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_715J1_153_8155
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_715J1_153_8155 | genblk1[5].u_RADIX2/u_mq_montymul/mult_152 (MQ.v:152) |
                     | genblk1[5].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T594  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T594 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_716J1_154_8155
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_716J1_154_8155 | genblk1[4].u_RADIX2/u_mq_montymul/mult_152 (MQ.v:152) |
                     | genblk1[4].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T600  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T600 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_717J1_155_8155
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_717J1_155_8155 | genblk1[3].u_RADIX2/u_mq_montymul/mult_152 (MQ.v:152) |
                     | genblk1[3].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T606  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T606 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_718J1_156_8155
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_718J1_156_8155 | genblk1[2].u_RADIX2/u_mq_montymul/mult_152 (MQ.v:152) |
                     | genblk1[2].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T612  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T612 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_719J1_157_8155
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_719J1_157_8155 | genblk1[1].u_RADIX2/u_mq_montymul/mult_152 (MQ.v:152) |
                     | genblk1[1].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T618  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T618 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================


Datapath Extraction Report

Information: Operator associated with resources 'genblk1[0].u_RADIX2/add_140 (RADIX2.v:140) genblk1[0].u_RADIX2/add_142 (RADIX2.v:142)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[0].u_RADIX2/C321 (RADIX2.v:139)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[0].u_RADIX2/add_159 (RADIX2.v:159)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[0].u_RADIX2/add_158 (RADIX2.v:158)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[1].u_RADIX2/add_140 (RADIX2.v:140) genblk1[1].u_RADIX2/add_142 (RADIX2.v:142)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[1].u_RADIX2/C322 (RADIX2.v:139)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[1].u_RADIX2/add_159 (RADIX2.v:159)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[1].u_RADIX2/add_158 (RADIX2.v:158)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[2].u_RADIX2/add_140 (RADIX2.v:140) genblk1[2].u_RADIX2/add_142 (RADIX2.v:142)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[2].u_RADIX2/C323 (RADIX2.v:139)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[2].u_RADIX2/add_159 (RADIX2.v:159)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[2].u_RADIX2/add_158 (RADIX2.v:158)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[3].u_RADIX2/add_140 (RADIX2.v:140) genblk1[3].u_RADIX2/add_142 (RADIX2.v:142)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[3].u_RADIX2/C324 (RADIX2.v:139)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[3].u_RADIX2/add_159 (RADIX2.v:159)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[3].u_RADIX2/add_158 (RADIX2.v:158)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[4].u_RADIX2/add_140 (RADIX2.v:140) genblk1[4].u_RADIX2/add_142 (RADIX2.v:142)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[4].u_RADIX2/C325 (RADIX2.v:139)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[4].u_RADIX2/add_159 (RADIX2.v:159)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[4].u_RADIX2/add_158 (RADIX2.v:158)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[5].u_RADIX2/add_140 (RADIX2.v:140) genblk1[5].u_RADIX2/add_142 (RADIX2.v:142)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[5].u_RADIX2/C326 (RADIX2.v:139)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[5].u_RADIX2/add_159 (RADIX2.v:159)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[5].u_RADIX2/add_158 (RADIX2.v:158)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[6].u_RADIX2/add_140 (RADIX2.v:140) genblk1[6].u_RADIX2/add_142 (RADIX2.v:142)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[6].u_RADIX2/C327 (RADIX2.v:139)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[6].u_RADIX2/add_159 (RADIX2.v:159)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[6].u_RADIX2/add_158 (RADIX2.v:158)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[7].u_RADIX2/add_140 (RADIX2.v:140) genblk1[7].u_RADIX2/add_142 (RADIX2.v:142)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[7].u_RADIX2/C328 (RADIX2.v:139)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[7].u_RADIX2/add_159 (RADIX2.v:159)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[7].u_RADIX2/add_158 (RADIX2.v:158)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[8].u_RADIX2/add_140 (RADIX2.v:140) genblk1[8].u_RADIX2/add_142 (RADIX2.v:142)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[8].u_RADIX2/C361 (RADIX2.v:139)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[8].u_RADIX2/add_159 (RADIX2.v:159)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[8].u_RADIX2/add_158 (RADIX2.v:158)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[0].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[0].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[8].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[8].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[7].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[7].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[6].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[6].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[5].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[5].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[4].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[4].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[3].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[3].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[2].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[2].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[1].u_RADIX2/u_mq_montymul/mult_153 (MQ.v:153)' in design 'MQ_NTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[1].u_RADIX2/u_mq_montymul/mult_154 (MQ.v:154)'.  (HDL-120)


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| gte_x_130          | DW_cmp           | apparch (area)     |                |
| lt_x_134           | DW_cmp           | apparch (area)     |                |
| add_x_135          | DW01_inc         | apparch (area)     |                |
| add_x_136          | DW01_inc         | apparch (area)     |                |
| eq_x_139           | DW_cmp           | apparch (area)     |                |
| eq_x_140           | DW_cmp           | apparch (area)     |                |
| gte_x_153          | DW_cmp           | apparch (area)     |                |
| lt_x_157           | DW_cmp           | apparch (area)     |                |
| add_x_158          | DW01_inc         | apparch (area)     |                |
| add_x_159          | DW01_add         | apparch (area)     |                |
| eq_x_162           | DW_cmp           | apparch (area)     |                |
| eq_x_163           | DW_cmp           | apparch (area)     |                |
| gte_x_176          | DW_cmp           | apparch (area)     |                |
| lt_x_180           | DW_cmp           | apparch (area)     |                |
| add_x_181          | DW01_inc         | apparch (area)     |                |
| add_x_182          | DW01_add         | apparch (area)     |                |
| eq_x_185           | DW_cmp           | apparch (area)     |                |
| eq_x_186           | DW_cmp           | apparch (area)     |                |
| gte_x_199          | DW_cmp           | apparch (area)     |                |
| lt_x_203           | DW_cmp           | apparch (area)     |                |
| add_x_204          | DW01_inc         | apparch (area)     |                |
| eq_x_208           | DW_cmp           | apparch (area)     |                |
| eq_x_209           | DW_cmp           | apparch (area)     |                |
| gte_x_222          | DW_cmp           | apparch (area)     |                |
| lt_x_226           | DW_cmp           | apparch (area)     |                |
| add_x_227          | DW01_inc         | apparch (area)     |                |
| eq_x_231           | DW_cmp           | apparch (area)     |                |
| eq_x_232           | DW_cmp           | apparch (area)     |                |
| gte_x_245          | DW_cmp           | apparch (area)     |                |
| lt_x_249           | DW_cmp           | apparch (area)     |                |
| add_x_250          | DW01_inc         | pparch (area,speed)                 |
| eq_x_254           | DW_cmp           | apparch (area)     |                |
| eq_x_255           | DW_cmp           | apparch (area)     |                |
| gte_x_268          | DW_cmp           | apparch (area)     |                |
| lt_x_272           | DW_cmp           | apparch (area)     |                |
| add_x_273          | DW01_inc         | pparch (area,speed)                 |
| eq_x_277           | DW_cmp           | apparch (area)     |                |
| eq_x_278           | DW_cmp           | apparch (area)     |                |
| gte_x_291          | DW_cmp           | apparch (area)     |                |
| lt_x_295           | DW_cmp           | apparch (area)     |                |
| add_x_296          | DW01_inc         | pparch (area,speed)                 |
| eq_x_300           | DW_cmp           | apparch (area)     |                |
| eq_x_301           | DW_cmp           | apparch (area)     |                |
| gte_x_314          | DW_cmp           | apparch (area)     |                |
| lt_x_318           | DW_cmp           | apparch (area)     |                |
| add_x_319          | DW01_inc         | pparch (area,speed)                 |
| mult_x_331         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_333         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_335         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_337         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_339         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_341         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_343         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_345         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_347         | DW_mult_uns      | pparch (area,speed)                 |
| add_x_138          | DW01_add         | apparch (area)     |                |
| add_x_161          | DW01_add         | apparch (area)     |                |
| add_x_184          | DW01_add         | apparch (area)     |                |
| add_x_207          | DW01_add         | apparch (area)     |                |
| add_x_230          | DW01_add         | apparch (area)     |                |
| add_x_253          | DW01_add         | apparch (area)     |                |
| add_x_276          | DW01_add         | apparch (area)     |                |
| add_x_299          | DW01_add         | apparch (area)     |                |
| add_x_131          | DW01_inc         | apparch (area)     |                |
| add_x_154          | DW01_inc         | apparch (area)     |                |
| add_x_177          | DW01_inc         | apparch (area)     |                |
| add_x_200          | DW01_inc         | apparch (area)     |                |
| add_x_223          | DW01_inc         | apparch (area)     |                |
| add_x_246          | DW01_inc         | apparch (area)     |                |
| add_x_269          | DW01_inc         | pparch (area,speed)                 |
| add_x_292          | DW01_inc         | apparch (area)     |                |
| add_x_315          | DW01_inc         | pparch (area,speed)                 |
| DP_OP_684J1_122_4154                  |                    |                |
|                    | DP_OP_684J1_122_4154 | str (area,speed)                |
| DP_OP_685J1_123_3090                  |                    |                |
|                    | DP_OP_685J1_123_3090 | str (area,speed)                |
| DP_OP_686J1_124_9405                  |                    |                |
|                    | DP_OP_686J1_124_9405 | str (area,speed)                |
| DP_OP_687J1_125_4154                  |                    |                |
|                    | DP_OP_687J1_125_4154 | str (area,speed)                |
| DP_OP_688J1_126_3090                  |                    |                |
|                    | DP_OP_688J1_126_3090 | str (area,speed)                |
| DP_OP_689J1_127_9405                  |                    |                |
|                    | DP_OP_689J1_127_9405 | str (area,speed)                |
| DP_OP_690J1_128_4154                  |                    |                |
|                    | DP_OP_690J1_128_4154 | str (area,speed)                |
| DP_OP_691J1_129_3090                  |                    |                |
|                    | DP_OP_691J1_129_3090 | str (area,speed)                |
| DP_OP_692J1_130_9405                  |                    |                |
|                    | DP_OP_692J1_130_9405 | str (area,speed)                |
| DP_OP_693J1_131_4154                  |                    |                |
|                    | DP_OP_693J1_131_4154 | str (area,speed)                |
| DP_OP_694J1_132_3090                  |                    |                |
|                    | DP_OP_694J1_132_3090 | str (area,speed)                |
| DP_OP_695J1_133_9405                  |                    |                |
|                    | DP_OP_695J1_133_9405 | str (area,speed)                |
| DP_OP_696J1_134_4154                  |                    |                |
|                    | DP_OP_696J1_134_4154 | str (area,speed)                |
| DP_OP_697J1_135_3090                  |                    |                |
|                    | DP_OP_697J1_135_3090 | str (area,speed)                |
| DP_OP_698J1_136_9405                  |                    |                |
|                    | DP_OP_698J1_136_9405 | str (area,speed)                |
| DP_OP_699J1_137_4154                  |                    |                |
|                    | DP_OP_699J1_137_4154 | str (area,speed)                |
| DP_OP_700J1_138_3090                  |                    |                |
|                    | DP_OP_700J1_138_3090 | str (area,speed)                |
| DP_OP_701J1_139_9405                  |                    |                |
|                    | DP_OP_701J1_139_9405 | str (area,speed)                |
| DP_OP_702J1_140_4154                  |                    |                |
|                    | DP_OP_702J1_140_4154 | str (area,speed)                |
| DP_OP_703J1_141_3090                  |                    |                |
|                    | DP_OP_703J1_141_3090 | str (area,speed)                |
| DP_OP_704J1_142_9405                  |                    |                |
|                    | DP_OP_704J1_142_9405 | str (area,speed)                |
| DP_OP_705J1_143_4154                  |                    |                |
|                    | DP_OP_705J1_143_4154 | str (area,speed)                |
| DP_OP_706J1_144_3090                  |                    |                |
|                    | DP_OP_706J1_144_3090 | str (area,speed)                |
| DP_OP_707J1_145_9405                  |                    |                |
|                    | DP_OP_707J1_145_9405 | str (area,speed)                |
| DP_OP_708J1_146_4154                  |                    |                |
|                    | DP_OP_708J1_146_4154 | str (area,speed)                |
| DP_OP_709J1_147_3090                  |                    |                |
|                    | DP_OP_709J1_147_3090 | str (area,speed)                |
| DP_OP_710J1_148_9405                  |                    |                |
|                    | DP_OP_710J1_148_9405 | str (area,speed)                |
| DP_OP_711J1_149_8155                  |                    |                |
|                    | DP_OP_711J1_149_8155 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_712J1_150_8155                  |                    |                |
|                    | DP_OP_712J1_150_8155 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_713J1_151_8155                  |                    |                |
|                    | DP_OP_713J1_151_8155 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_714J1_152_8155                  |                    |                |
|                    | DP_OP_714J1_152_8155 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_715J1_153_8155                  |                    |                |
|                    | DP_OP_715J1_153_8155 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_716J1_154_8155                  |                    |                |
|                    | DP_OP_716J1_154_8155 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_717J1_155_8155                  |                    |                |
|                    | DP_OP_717J1_155_8155 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_718J1_156_8155                  |                    |                |
|                    | DP_OP_718J1_156_8155 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_719J1_157_8155                  |                    |                |
|                    | DP_OP_719J1_157_8155 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
===============================================================================

1
