###################################################################

# Created by write_sdc on Thu Jul 17 22:02:26 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name Small -library                                       \
sc9_cln40g_base_rvt_ss_typical_max_0p81v_125c
set_load -pin_load 0.05 [get_ports rng_extract]
set_load -pin_load 0.05 [get_ports f_valid]
set_load -pin_load 0.05 [get_ports {f[6]}]
set_load -pin_load 0.05 [get_ports {f[5]}]
set_load -pin_load 0.05 [get_ports {f[4]}]
set_load -pin_load 0.05 [get_ports {f[3]}]
set_load -pin_load 0.05 [get_ports {f[2]}]
set_load -pin_load 0.05 [get_ports {f[1]}]
set_load -pin_load 0.05 [get_ports {f[0]}]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports ena]
set_max_capacitance 0.15 [get_ports rng_valid]
set_max_capacitance 0.15 [get_ports {rng[127]}]
set_max_capacitance 0.15 [get_ports {rng[126]}]
set_max_capacitance 0.15 [get_ports {rng[125]}]
set_max_capacitance 0.15 [get_ports {rng[124]}]
set_max_capacitance 0.15 [get_ports {rng[123]}]
set_max_capacitance 0.15 [get_ports {rng[122]}]
set_max_capacitance 0.15 [get_ports {rng[121]}]
set_max_capacitance 0.15 [get_ports {rng[120]}]
set_max_capacitance 0.15 [get_ports {rng[119]}]
set_max_capacitance 0.15 [get_ports {rng[118]}]
set_max_capacitance 0.15 [get_ports {rng[117]}]
set_max_capacitance 0.15 [get_ports {rng[116]}]
set_max_capacitance 0.15 [get_ports {rng[115]}]
set_max_capacitance 0.15 [get_ports {rng[114]}]
set_max_capacitance 0.15 [get_ports {rng[113]}]
set_max_capacitance 0.15 [get_ports {rng[112]}]
set_max_capacitance 0.15 [get_ports {rng[111]}]
set_max_capacitance 0.15 [get_ports {rng[110]}]
set_max_capacitance 0.15 [get_ports {rng[109]}]
set_max_capacitance 0.15 [get_ports {rng[108]}]
set_max_capacitance 0.15 [get_ports {rng[107]}]
set_max_capacitance 0.15 [get_ports {rng[106]}]
set_max_capacitance 0.15 [get_ports {rng[105]}]
set_max_capacitance 0.15 [get_ports {rng[104]}]
set_max_capacitance 0.15 [get_ports {rng[103]}]
set_max_capacitance 0.15 [get_ports {rng[102]}]
set_max_capacitance 0.15 [get_ports {rng[101]}]
set_max_capacitance 0.15 [get_ports {rng[100]}]
set_max_capacitance 0.15 [get_ports {rng[99]}]
set_max_capacitance 0.15 [get_ports {rng[98]}]
set_max_capacitance 0.15 [get_ports {rng[97]}]
set_max_capacitance 0.15 [get_ports {rng[96]}]
set_max_capacitance 0.15 [get_ports {rng[95]}]
set_max_capacitance 0.15 [get_ports {rng[94]}]
set_max_capacitance 0.15 [get_ports {rng[93]}]
set_max_capacitance 0.15 [get_ports {rng[92]}]
set_max_capacitance 0.15 [get_ports {rng[91]}]
set_max_capacitance 0.15 [get_ports {rng[90]}]
set_max_capacitance 0.15 [get_ports {rng[89]}]
set_max_capacitance 0.15 [get_ports {rng[88]}]
set_max_capacitance 0.15 [get_ports {rng[87]}]
set_max_capacitance 0.15 [get_ports {rng[86]}]
set_max_capacitance 0.15 [get_ports {rng[85]}]
set_max_capacitance 0.15 [get_ports {rng[84]}]
set_max_capacitance 0.15 [get_ports {rng[83]}]
set_max_capacitance 0.15 [get_ports {rng[82]}]
set_max_capacitance 0.15 [get_ports {rng[81]}]
set_max_capacitance 0.15 [get_ports {rng[80]}]
set_max_capacitance 0.15 [get_ports {rng[79]}]
set_max_capacitance 0.15 [get_ports {rng[78]}]
set_max_capacitance 0.15 [get_ports {rng[77]}]
set_max_capacitance 0.15 [get_ports {rng[76]}]
set_max_capacitance 0.15 [get_ports {rng[75]}]
set_max_capacitance 0.15 [get_ports {rng[74]}]
set_max_capacitance 0.15 [get_ports {rng[73]}]
set_max_capacitance 0.15 [get_ports {rng[72]}]
set_max_capacitance 0.15 [get_ports {rng[71]}]
set_max_capacitance 0.15 [get_ports {rng[70]}]
set_max_capacitance 0.15 [get_ports {rng[69]}]
set_max_capacitance 0.15 [get_ports {rng[68]}]
set_max_capacitance 0.15 [get_ports {rng[67]}]
set_max_capacitance 0.15 [get_ports {rng[66]}]
set_max_capacitance 0.15 [get_ports {rng[65]}]
set_max_capacitance 0.15 [get_ports {rng[64]}]
set_max_capacitance 0.15 [get_ports {rng[63]}]
set_max_capacitance 0.15 [get_ports {rng[62]}]
set_max_capacitance 0.15 [get_ports {rng[61]}]
set_max_capacitance 0.15 [get_ports {rng[60]}]
set_max_capacitance 0.15 [get_ports {rng[59]}]
set_max_capacitance 0.15 [get_ports {rng[58]}]
set_max_capacitance 0.15 [get_ports {rng[57]}]
set_max_capacitance 0.15 [get_ports {rng[56]}]
set_max_capacitance 0.15 [get_ports {rng[55]}]
set_max_capacitance 0.15 [get_ports {rng[54]}]
set_max_capacitance 0.15 [get_ports {rng[53]}]
set_max_capacitance 0.15 [get_ports {rng[52]}]
set_max_capacitance 0.15 [get_ports {rng[51]}]
set_max_capacitance 0.15 [get_ports {rng[50]}]
set_max_capacitance 0.15 [get_ports {rng[49]}]
set_max_capacitance 0.15 [get_ports {rng[48]}]
set_max_capacitance 0.15 [get_ports {rng[47]}]
set_max_capacitance 0.15 [get_ports {rng[46]}]
set_max_capacitance 0.15 [get_ports {rng[45]}]
set_max_capacitance 0.15 [get_ports {rng[44]}]
set_max_capacitance 0.15 [get_ports {rng[43]}]
set_max_capacitance 0.15 [get_ports {rng[42]}]
set_max_capacitance 0.15 [get_ports {rng[41]}]
set_max_capacitance 0.15 [get_ports {rng[40]}]
set_max_capacitance 0.15 [get_ports {rng[39]}]
set_max_capacitance 0.15 [get_ports {rng[38]}]
set_max_capacitance 0.15 [get_ports {rng[37]}]
set_max_capacitance 0.15 [get_ports {rng[36]}]
set_max_capacitance 0.15 [get_ports {rng[35]}]
set_max_capacitance 0.15 [get_ports {rng[34]}]
set_max_capacitance 0.15 [get_ports {rng[33]}]
set_max_capacitance 0.15 [get_ports {rng[32]}]
set_max_capacitance 0.15 [get_ports {rng[31]}]
set_max_capacitance 0.15 [get_ports {rng[30]}]
set_max_capacitance 0.15 [get_ports {rng[29]}]
set_max_capacitance 0.15 [get_ports {rng[28]}]
set_max_capacitance 0.15 [get_ports {rng[27]}]
set_max_capacitance 0.15 [get_ports {rng[26]}]
set_max_capacitance 0.15 [get_ports {rng[25]}]
set_max_capacitance 0.15 [get_ports {rng[24]}]
set_max_capacitance 0.15 [get_ports {rng[23]}]
set_max_capacitance 0.15 [get_ports {rng[22]}]
set_max_capacitance 0.15 [get_ports {rng[21]}]
set_max_capacitance 0.15 [get_ports {rng[20]}]
set_max_capacitance 0.15 [get_ports {rng[19]}]
set_max_capacitance 0.15 [get_ports {rng[18]}]
set_max_capacitance 0.15 [get_ports {rng[17]}]
set_max_capacitance 0.15 [get_ports {rng[16]}]
set_max_capacitance 0.15 [get_ports {rng[15]}]
set_max_capacitance 0.15 [get_ports {rng[14]}]
set_max_capacitance 0.15 [get_ports {rng[13]}]
set_max_capacitance 0.15 [get_ports {rng[12]}]
set_max_capacitance 0.15 [get_ports {rng[11]}]
set_max_capacitance 0.15 [get_ports {rng[10]}]
set_max_capacitance 0.15 [get_ports {rng[9]}]
set_max_capacitance 0.15 [get_ports {rng[8]}]
set_max_capacitance 0.15 [get_ports {rng[7]}]
set_max_capacitance 0.15 [get_ports {rng[6]}]
set_max_capacitance 0.15 [get_ports {rng[5]}]
set_max_capacitance 0.15 [get_ports {rng[4]}]
set_max_capacitance 0.15 [get_ports {rng[3]}]
set_max_capacitance 0.15 [get_ports {rng[2]}]
set_max_capacitance 0.15 [get_ports {rng[1]}]
set_max_capacitance 0.15 [get_ports {rng[0]}]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports ena]
set_max_fanout 10 [get_ports rng_valid]
set_max_fanout 10 [get_ports {rng[127]}]
set_max_fanout 10 [get_ports {rng[126]}]
set_max_fanout 10 [get_ports {rng[125]}]
set_max_fanout 10 [get_ports {rng[124]}]
set_max_fanout 10 [get_ports {rng[123]}]
set_max_fanout 10 [get_ports {rng[122]}]
set_max_fanout 10 [get_ports {rng[121]}]
set_max_fanout 10 [get_ports {rng[120]}]
set_max_fanout 10 [get_ports {rng[119]}]
set_max_fanout 10 [get_ports {rng[118]}]
set_max_fanout 10 [get_ports {rng[117]}]
set_max_fanout 10 [get_ports {rng[116]}]
set_max_fanout 10 [get_ports {rng[115]}]
set_max_fanout 10 [get_ports {rng[114]}]
set_max_fanout 10 [get_ports {rng[113]}]
set_max_fanout 10 [get_ports {rng[112]}]
set_max_fanout 10 [get_ports {rng[111]}]
set_max_fanout 10 [get_ports {rng[110]}]
set_max_fanout 10 [get_ports {rng[109]}]
set_max_fanout 10 [get_ports {rng[108]}]
set_max_fanout 10 [get_ports {rng[107]}]
set_max_fanout 10 [get_ports {rng[106]}]
set_max_fanout 10 [get_ports {rng[105]}]
set_max_fanout 10 [get_ports {rng[104]}]
set_max_fanout 10 [get_ports {rng[103]}]
set_max_fanout 10 [get_ports {rng[102]}]
set_max_fanout 10 [get_ports {rng[101]}]
set_max_fanout 10 [get_ports {rng[100]}]
set_max_fanout 10 [get_ports {rng[99]}]
set_max_fanout 10 [get_ports {rng[98]}]
set_max_fanout 10 [get_ports {rng[97]}]
set_max_fanout 10 [get_ports {rng[96]}]
set_max_fanout 10 [get_ports {rng[95]}]
set_max_fanout 10 [get_ports {rng[94]}]
set_max_fanout 10 [get_ports {rng[93]}]
set_max_fanout 10 [get_ports {rng[92]}]
set_max_fanout 10 [get_ports {rng[91]}]
set_max_fanout 10 [get_ports {rng[90]}]
set_max_fanout 10 [get_ports {rng[89]}]
set_max_fanout 10 [get_ports {rng[88]}]
set_max_fanout 10 [get_ports {rng[87]}]
set_max_fanout 10 [get_ports {rng[86]}]
set_max_fanout 10 [get_ports {rng[85]}]
set_max_fanout 10 [get_ports {rng[84]}]
set_max_fanout 10 [get_ports {rng[83]}]
set_max_fanout 10 [get_ports {rng[82]}]
set_max_fanout 10 [get_ports {rng[81]}]
set_max_fanout 10 [get_ports {rng[80]}]
set_max_fanout 10 [get_ports {rng[79]}]
set_max_fanout 10 [get_ports {rng[78]}]
set_max_fanout 10 [get_ports {rng[77]}]
set_max_fanout 10 [get_ports {rng[76]}]
set_max_fanout 10 [get_ports {rng[75]}]
set_max_fanout 10 [get_ports {rng[74]}]
set_max_fanout 10 [get_ports {rng[73]}]
set_max_fanout 10 [get_ports {rng[72]}]
set_max_fanout 10 [get_ports {rng[71]}]
set_max_fanout 10 [get_ports {rng[70]}]
set_max_fanout 10 [get_ports {rng[69]}]
set_max_fanout 10 [get_ports {rng[68]}]
set_max_fanout 10 [get_ports {rng[67]}]
set_max_fanout 10 [get_ports {rng[66]}]
set_max_fanout 10 [get_ports {rng[65]}]
set_max_fanout 10 [get_ports {rng[64]}]
set_max_fanout 10 [get_ports {rng[63]}]
set_max_fanout 10 [get_ports {rng[62]}]
set_max_fanout 10 [get_ports {rng[61]}]
set_max_fanout 10 [get_ports {rng[60]}]
set_max_fanout 10 [get_ports {rng[59]}]
set_max_fanout 10 [get_ports {rng[58]}]
set_max_fanout 10 [get_ports {rng[57]}]
set_max_fanout 10 [get_ports {rng[56]}]
set_max_fanout 10 [get_ports {rng[55]}]
set_max_fanout 10 [get_ports {rng[54]}]
set_max_fanout 10 [get_ports {rng[53]}]
set_max_fanout 10 [get_ports {rng[52]}]
set_max_fanout 10 [get_ports {rng[51]}]
set_max_fanout 10 [get_ports {rng[50]}]
set_max_fanout 10 [get_ports {rng[49]}]
set_max_fanout 10 [get_ports {rng[48]}]
set_max_fanout 10 [get_ports {rng[47]}]
set_max_fanout 10 [get_ports {rng[46]}]
set_max_fanout 10 [get_ports {rng[45]}]
set_max_fanout 10 [get_ports {rng[44]}]
set_max_fanout 10 [get_ports {rng[43]}]
set_max_fanout 10 [get_ports {rng[42]}]
set_max_fanout 10 [get_ports {rng[41]}]
set_max_fanout 10 [get_ports {rng[40]}]
set_max_fanout 10 [get_ports {rng[39]}]
set_max_fanout 10 [get_ports {rng[38]}]
set_max_fanout 10 [get_ports {rng[37]}]
set_max_fanout 10 [get_ports {rng[36]}]
set_max_fanout 10 [get_ports {rng[35]}]
set_max_fanout 10 [get_ports {rng[34]}]
set_max_fanout 10 [get_ports {rng[33]}]
set_max_fanout 10 [get_ports {rng[32]}]
set_max_fanout 10 [get_ports {rng[31]}]
set_max_fanout 10 [get_ports {rng[30]}]
set_max_fanout 10 [get_ports {rng[29]}]
set_max_fanout 10 [get_ports {rng[28]}]
set_max_fanout 10 [get_ports {rng[27]}]
set_max_fanout 10 [get_ports {rng[26]}]
set_max_fanout 10 [get_ports {rng[25]}]
set_max_fanout 10 [get_ports {rng[24]}]
set_max_fanout 10 [get_ports {rng[23]}]
set_max_fanout 10 [get_ports {rng[22]}]
set_max_fanout 10 [get_ports {rng[21]}]
set_max_fanout 10 [get_ports {rng[20]}]
set_max_fanout 10 [get_ports {rng[19]}]
set_max_fanout 10 [get_ports {rng[18]}]
set_max_fanout 10 [get_ports {rng[17]}]
set_max_fanout 10 [get_ports {rng[16]}]
set_max_fanout 10 [get_ports {rng[15]}]
set_max_fanout 10 [get_ports {rng[14]}]
set_max_fanout 10 [get_ports {rng[13]}]
set_max_fanout 10 [get_ports {rng[12]}]
set_max_fanout 10 [get_ports {rng[11]}]
set_max_fanout 10 [get_ports {rng[10]}]
set_max_fanout 10 [get_ports {rng[9]}]
set_max_fanout 10 [get_ports {rng[8]}]
set_max_fanout 10 [get_ports {rng[7]}]
set_max_fanout 10 [get_ports {rng[6]}]
set_max_fanout 10 [get_ports {rng[5]}]
set_max_fanout 10 [get_ports {rng[4]}]
set_max_fanout 10 [get_ports {rng[3]}]
set_max_fanout 10 [get_ports {rng[2]}]
set_max_fanout 10 [get_ports {rng[1]}]
set_max_fanout 10 [get_ports {rng[0]}]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports ena]
set_max_transition 3 [get_ports rng_valid]
set_max_transition 3 [get_ports {rng[127]}]
set_max_transition 3 [get_ports {rng[126]}]
set_max_transition 3 [get_ports {rng[125]}]
set_max_transition 3 [get_ports {rng[124]}]
set_max_transition 3 [get_ports {rng[123]}]
set_max_transition 3 [get_ports {rng[122]}]
set_max_transition 3 [get_ports {rng[121]}]
set_max_transition 3 [get_ports {rng[120]}]
set_max_transition 3 [get_ports {rng[119]}]
set_max_transition 3 [get_ports {rng[118]}]
set_max_transition 3 [get_ports {rng[117]}]
set_max_transition 3 [get_ports {rng[116]}]
set_max_transition 3 [get_ports {rng[115]}]
set_max_transition 3 [get_ports {rng[114]}]
set_max_transition 3 [get_ports {rng[113]}]
set_max_transition 3 [get_ports {rng[112]}]
set_max_transition 3 [get_ports {rng[111]}]
set_max_transition 3 [get_ports {rng[110]}]
set_max_transition 3 [get_ports {rng[109]}]
set_max_transition 3 [get_ports {rng[108]}]
set_max_transition 3 [get_ports {rng[107]}]
set_max_transition 3 [get_ports {rng[106]}]
set_max_transition 3 [get_ports {rng[105]}]
set_max_transition 3 [get_ports {rng[104]}]
set_max_transition 3 [get_ports {rng[103]}]
set_max_transition 3 [get_ports {rng[102]}]
set_max_transition 3 [get_ports {rng[101]}]
set_max_transition 3 [get_ports {rng[100]}]
set_max_transition 3 [get_ports {rng[99]}]
set_max_transition 3 [get_ports {rng[98]}]
set_max_transition 3 [get_ports {rng[97]}]
set_max_transition 3 [get_ports {rng[96]}]
set_max_transition 3 [get_ports {rng[95]}]
set_max_transition 3 [get_ports {rng[94]}]
set_max_transition 3 [get_ports {rng[93]}]
set_max_transition 3 [get_ports {rng[92]}]
set_max_transition 3 [get_ports {rng[91]}]
set_max_transition 3 [get_ports {rng[90]}]
set_max_transition 3 [get_ports {rng[89]}]
set_max_transition 3 [get_ports {rng[88]}]
set_max_transition 3 [get_ports {rng[87]}]
set_max_transition 3 [get_ports {rng[86]}]
set_max_transition 3 [get_ports {rng[85]}]
set_max_transition 3 [get_ports {rng[84]}]
set_max_transition 3 [get_ports {rng[83]}]
set_max_transition 3 [get_ports {rng[82]}]
set_max_transition 3 [get_ports {rng[81]}]
set_max_transition 3 [get_ports {rng[80]}]
set_max_transition 3 [get_ports {rng[79]}]
set_max_transition 3 [get_ports {rng[78]}]
set_max_transition 3 [get_ports {rng[77]}]
set_max_transition 3 [get_ports {rng[76]}]
set_max_transition 3 [get_ports {rng[75]}]
set_max_transition 3 [get_ports {rng[74]}]
set_max_transition 3 [get_ports {rng[73]}]
set_max_transition 3 [get_ports {rng[72]}]
set_max_transition 3 [get_ports {rng[71]}]
set_max_transition 3 [get_ports {rng[70]}]
set_max_transition 3 [get_ports {rng[69]}]
set_max_transition 3 [get_ports {rng[68]}]
set_max_transition 3 [get_ports {rng[67]}]
set_max_transition 3 [get_ports {rng[66]}]
set_max_transition 3 [get_ports {rng[65]}]
set_max_transition 3 [get_ports {rng[64]}]
set_max_transition 3 [get_ports {rng[63]}]
set_max_transition 3 [get_ports {rng[62]}]
set_max_transition 3 [get_ports {rng[61]}]
set_max_transition 3 [get_ports {rng[60]}]
set_max_transition 3 [get_ports {rng[59]}]
set_max_transition 3 [get_ports {rng[58]}]
set_max_transition 3 [get_ports {rng[57]}]
set_max_transition 3 [get_ports {rng[56]}]
set_max_transition 3 [get_ports {rng[55]}]
set_max_transition 3 [get_ports {rng[54]}]
set_max_transition 3 [get_ports {rng[53]}]
set_max_transition 3 [get_ports {rng[52]}]
set_max_transition 3 [get_ports {rng[51]}]
set_max_transition 3 [get_ports {rng[50]}]
set_max_transition 3 [get_ports {rng[49]}]
set_max_transition 3 [get_ports {rng[48]}]
set_max_transition 3 [get_ports {rng[47]}]
set_max_transition 3 [get_ports {rng[46]}]
set_max_transition 3 [get_ports {rng[45]}]
set_max_transition 3 [get_ports {rng[44]}]
set_max_transition 3 [get_ports {rng[43]}]
set_max_transition 3 [get_ports {rng[42]}]
set_max_transition 3 [get_ports {rng[41]}]
set_max_transition 3 [get_ports {rng[40]}]
set_max_transition 3 [get_ports {rng[39]}]
set_max_transition 3 [get_ports {rng[38]}]
set_max_transition 3 [get_ports {rng[37]}]
set_max_transition 3 [get_ports {rng[36]}]
set_max_transition 3 [get_ports {rng[35]}]
set_max_transition 3 [get_ports {rng[34]}]
set_max_transition 3 [get_ports {rng[33]}]
set_max_transition 3 [get_ports {rng[32]}]
set_max_transition 3 [get_ports {rng[31]}]
set_max_transition 3 [get_ports {rng[30]}]
set_max_transition 3 [get_ports {rng[29]}]
set_max_transition 3 [get_ports {rng[28]}]
set_max_transition 3 [get_ports {rng[27]}]
set_max_transition 3 [get_ports {rng[26]}]
set_max_transition 3 [get_ports {rng[25]}]
set_max_transition 3 [get_ports {rng[24]}]
set_max_transition 3 [get_ports {rng[23]}]
set_max_transition 3 [get_ports {rng[22]}]
set_max_transition 3 [get_ports {rng[21]}]
set_max_transition 3 [get_ports {rng[20]}]
set_max_transition 3 [get_ports {rng[19]}]
set_max_transition 3 [get_ports {rng[18]}]
set_max_transition 3 [get_ports {rng[17]}]
set_max_transition 3 [get_ports {rng[16]}]
set_max_transition 3 [get_ports {rng[15]}]
set_max_transition 3 [get_ports {rng[14]}]
set_max_transition 3 [get_ports {rng[13]}]
set_max_transition 3 [get_ports {rng[12]}]
set_max_transition 3 [get_ports {rng[11]}]
set_max_transition 3 [get_ports {rng[10]}]
set_max_transition 3 [get_ports {rng[9]}]
set_max_transition 3 [get_ports {rng[8]}]
set_max_transition 3 [get_ports {rng[7]}]
set_max_transition 3 [get_ports {rng[6]}]
set_max_transition 3 [get_ports {rng[5]}]
set_max_transition 3 [get_ports {rng[4]}]
set_max_transition 3 [get_ports {rng[3]}]
set_max_transition 3 [get_ports {rng[2]}]
set_max_transition 3 [get_ports {rng[1]}]
set_max_transition 3 [get_ports {rng[0]}]
create_clock [get_ports clk]  -period 2  -waveform {0 1}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  -max 1  [get_ports ena]
set_input_delay -clock clk  -min 0  [get_ports ena]
set_input_delay -clock clk  -max 1  [get_ports rng_valid]
set_input_delay -clock clk  -min 0  [get_ports rng_valid]
set_input_delay -clock clk  -max 1  [get_ports {rng[127]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[127]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[126]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[126]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[125]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[125]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[124]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[124]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[123]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[123]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[122]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[122]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[121]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[121]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[120]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[120]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[119]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[119]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[118]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[118]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[117]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[117]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[116]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[116]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[115]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[115]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[114]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[114]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[113]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[113]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[112]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[112]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[111]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[111]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[110]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[110]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[109]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[109]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[108]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[108]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[107]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[107]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[106]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[106]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[105]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[105]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[104]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[104]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[103]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[103]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[102]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[102]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[101]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[101]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[100]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[100]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[99]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[99]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[98]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[98]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[97]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[97]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[96]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[96]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[95]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[95]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[94]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[94]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[93]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[93]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[92]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[92]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[91]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[91]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[90]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[90]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[89]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[89]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[88]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[88]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[87]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[87]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[86]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[86]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[85]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[85]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[84]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[84]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[83]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[83]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[82]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[82]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[81]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[81]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[80]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[80]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[79]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[79]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[78]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[78]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[77]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[77]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[76]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[76]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[75]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[75]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[74]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[74]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[73]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[73]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[72]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[72]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[71]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[71]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[70]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[70]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[69]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[69]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[68]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[68]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[67]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[67]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[66]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[66]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[65]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[65]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[64]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[64]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[63]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[63]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[62]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[62]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[61]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[61]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[60]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[60]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[59]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[59]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[58]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[58]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[57]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[57]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[56]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[56]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[55]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[55]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[54]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[54]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[53]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[53]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[52]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[52]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[51]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[51]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[50]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[50]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[49]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[49]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[48]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[48]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[47]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[47]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[46]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[46]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[45]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[45]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[44]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[44]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[43]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[43]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[42]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[42]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[41]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[41]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[40]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[40]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[39]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[39]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[38]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[38]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[37]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[37]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[36]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[36]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[35]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[35]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[34]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[34]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[33]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[33]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[32]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[32]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[31]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[31]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[30]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[30]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[29]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[29]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[28]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[28]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[27]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[27]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[26]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[26]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[25]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[25]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[24]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[24]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[23]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[23]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[22]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[22]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[21]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[21]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[20]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[20]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[19]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[19]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[18]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[18]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[17]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[17]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[16]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[16]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[15]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[15]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[14]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[14]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[13]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[13]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[12]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[12]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[11]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[11]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[10]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[10]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[9]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[9]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[8]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[8]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[7]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[7]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[6]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[6]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[5]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[5]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[4]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[4]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[3]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[3]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[2]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[2]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[1]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[1]}]
set_input_delay -clock clk  -max 1  [get_ports {rng[0]}]
set_input_delay -clock clk  -min 0  [get_ports {rng[0]}]
set_output_delay -clock clk  -max 1  [get_ports rng_extract]
set_output_delay -clock clk  -min 0  [get_ports rng_extract]
set_output_delay -clock clk  -max 1  [get_ports f_valid]
set_output_delay -clock clk  -min 0  [get_ports f_valid]
set_output_delay -clock clk  -max 1  [get_ports {f[6]}]
set_output_delay -clock clk  -min 0  [get_ports {f[6]}]
set_output_delay -clock clk  -max 1  [get_ports {f[5]}]
set_output_delay -clock clk  -min 0  [get_ports {f[5]}]
set_output_delay -clock clk  -max 1  [get_ports {f[4]}]
set_output_delay -clock clk  -min 0  [get_ports {f[4]}]
set_output_delay -clock clk  -max 1  [get_ports {f[3]}]
set_output_delay -clock clk  -min 0  [get_ports {f[3]}]
set_output_delay -clock clk  -max 1  [get_ports {f[2]}]
set_output_delay -clock clk  -min 0  [get_ports {f[2]}]
set_output_delay -clock clk  -max 1  [get_ports {f[1]}]
set_output_delay -clock clk  -min 0  [get_ports {f[1]}]
set_output_delay -clock clk  -max 1  [get_ports {f[0]}]
set_output_delay -clock clk  -min 0  [get_ports {f[0]}]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports ena]
set_input_transition -min 0.5  [get_ports ena]
set_input_transition -max 0.5  [get_ports rng_valid]
set_input_transition -min 0.5  [get_ports rng_valid]
set_input_transition -max 0.5  [get_ports {rng[127]}]
set_input_transition -min 0.5  [get_ports {rng[127]}]
set_input_transition -max 0.5  [get_ports {rng[126]}]
set_input_transition -min 0.5  [get_ports {rng[126]}]
set_input_transition -max 0.5  [get_ports {rng[125]}]
set_input_transition -min 0.5  [get_ports {rng[125]}]
set_input_transition -max 0.5  [get_ports {rng[124]}]
set_input_transition -min 0.5  [get_ports {rng[124]}]
set_input_transition -max 0.5  [get_ports {rng[123]}]
set_input_transition -min 0.5  [get_ports {rng[123]}]
set_input_transition -max 0.5  [get_ports {rng[122]}]
set_input_transition -min 0.5  [get_ports {rng[122]}]
set_input_transition -max 0.5  [get_ports {rng[121]}]
set_input_transition -min 0.5  [get_ports {rng[121]}]
set_input_transition -max 0.5  [get_ports {rng[120]}]
set_input_transition -min 0.5  [get_ports {rng[120]}]
set_input_transition -max 0.5  [get_ports {rng[119]}]
set_input_transition -min 0.5  [get_ports {rng[119]}]
set_input_transition -max 0.5  [get_ports {rng[118]}]
set_input_transition -min 0.5  [get_ports {rng[118]}]
set_input_transition -max 0.5  [get_ports {rng[117]}]
set_input_transition -min 0.5  [get_ports {rng[117]}]
set_input_transition -max 0.5  [get_ports {rng[116]}]
set_input_transition -min 0.5  [get_ports {rng[116]}]
set_input_transition -max 0.5  [get_ports {rng[115]}]
set_input_transition -min 0.5  [get_ports {rng[115]}]
set_input_transition -max 0.5  [get_ports {rng[114]}]
set_input_transition -min 0.5  [get_ports {rng[114]}]
set_input_transition -max 0.5  [get_ports {rng[113]}]
set_input_transition -min 0.5  [get_ports {rng[113]}]
set_input_transition -max 0.5  [get_ports {rng[112]}]
set_input_transition -min 0.5  [get_ports {rng[112]}]
set_input_transition -max 0.5  [get_ports {rng[111]}]
set_input_transition -min 0.5  [get_ports {rng[111]}]
set_input_transition -max 0.5  [get_ports {rng[110]}]
set_input_transition -min 0.5  [get_ports {rng[110]}]
set_input_transition -max 0.5  [get_ports {rng[109]}]
set_input_transition -min 0.5  [get_ports {rng[109]}]
set_input_transition -max 0.5  [get_ports {rng[108]}]
set_input_transition -min 0.5  [get_ports {rng[108]}]
set_input_transition -max 0.5  [get_ports {rng[107]}]
set_input_transition -min 0.5  [get_ports {rng[107]}]
set_input_transition -max 0.5  [get_ports {rng[106]}]
set_input_transition -min 0.5  [get_ports {rng[106]}]
set_input_transition -max 0.5  [get_ports {rng[105]}]
set_input_transition -min 0.5  [get_ports {rng[105]}]
set_input_transition -max 0.5  [get_ports {rng[104]}]
set_input_transition -min 0.5  [get_ports {rng[104]}]
set_input_transition -max 0.5  [get_ports {rng[103]}]
set_input_transition -min 0.5  [get_ports {rng[103]}]
set_input_transition -max 0.5  [get_ports {rng[102]}]
set_input_transition -min 0.5  [get_ports {rng[102]}]
set_input_transition -max 0.5  [get_ports {rng[101]}]
set_input_transition -min 0.5  [get_ports {rng[101]}]
set_input_transition -max 0.5  [get_ports {rng[100]}]
set_input_transition -min 0.5  [get_ports {rng[100]}]
set_input_transition -max 0.5  [get_ports {rng[99]}]
set_input_transition -min 0.5  [get_ports {rng[99]}]
set_input_transition -max 0.5  [get_ports {rng[98]}]
set_input_transition -min 0.5  [get_ports {rng[98]}]
set_input_transition -max 0.5  [get_ports {rng[97]}]
set_input_transition -min 0.5  [get_ports {rng[97]}]
set_input_transition -max 0.5  [get_ports {rng[96]}]
set_input_transition -min 0.5  [get_ports {rng[96]}]
set_input_transition -max 0.5  [get_ports {rng[95]}]
set_input_transition -min 0.5  [get_ports {rng[95]}]
set_input_transition -max 0.5  [get_ports {rng[94]}]
set_input_transition -min 0.5  [get_ports {rng[94]}]
set_input_transition -max 0.5  [get_ports {rng[93]}]
set_input_transition -min 0.5  [get_ports {rng[93]}]
set_input_transition -max 0.5  [get_ports {rng[92]}]
set_input_transition -min 0.5  [get_ports {rng[92]}]
set_input_transition -max 0.5  [get_ports {rng[91]}]
set_input_transition -min 0.5  [get_ports {rng[91]}]
set_input_transition -max 0.5  [get_ports {rng[90]}]
set_input_transition -min 0.5  [get_ports {rng[90]}]
set_input_transition -max 0.5  [get_ports {rng[89]}]
set_input_transition -min 0.5  [get_ports {rng[89]}]
set_input_transition -max 0.5  [get_ports {rng[88]}]
set_input_transition -min 0.5  [get_ports {rng[88]}]
set_input_transition -max 0.5  [get_ports {rng[87]}]
set_input_transition -min 0.5  [get_ports {rng[87]}]
set_input_transition -max 0.5  [get_ports {rng[86]}]
set_input_transition -min 0.5  [get_ports {rng[86]}]
set_input_transition -max 0.5  [get_ports {rng[85]}]
set_input_transition -min 0.5  [get_ports {rng[85]}]
set_input_transition -max 0.5  [get_ports {rng[84]}]
set_input_transition -min 0.5  [get_ports {rng[84]}]
set_input_transition -max 0.5  [get_ports {rng[83]}]
set_input_transition -min 0.5  [get_ports {rng[83]}]
set_input_transition -max 0.5  [get_ports {rng[82]}]
set_input_transition -min 0.5  [get_ports {rng[82]}]
set_input_transition -max 0.5  [get_ports {rng[81]}]
set_input_transition -min 0.5  [get_ports {rng[81]}]
set_input_transition -max 0.5  [get_ports {rng[80]}]
set_input_transition -min 0.5  [get_ports {rng[80]}]
set_input_transition -max 0.5  [get_ports {rng[79]}]
set_input_transition -min 0.5  [get_ports {rng[79]}]
set_input_transition -max 0.5  [get_ports {rng[78]}]
set_input_transition -min 0.5  [get_ports {rng[78]}]
set_input_transition -max 0.5  [get_ports {rng[77]}]
set_input_transition -min 0.5  [get_ports {rng[77]}]
set_input_transition -max 0.5  [get_ports {rng[76]}]
set_input_transition -min 0.5  [get_ports {rng[76]}]
set_input_transition -max 0.5  [get_ports {rng[75]}]
set_input_transition -min 0.5  [get_ports {rng[75]}]
set_input_transition -max 0.5  [get_ports {rng[74]}]
set_input_transition -min 0.5  [get_ports {rng[74]}]
set_input_transition -max 0.5  [get_ports {rng[73]}]
set_input_transition -min 0.5  [get_ports {rng[73]}]
set_input_transition -max 0.5  [get_ports {rng[72]}]
set_input_transition -min 0.5  [get_ports {rng[72]}]
set_input_transition -max 0.5  [get_ports {rng[71]}]
set_input_transition -min 0.5  [get_ports {rng[71]}]
set_input_transition -max 0.5  [get_ports {rng[70]}]
set_input_transition -min 0.5  [get_ports {rng[70]}]
set_input_transition -max 0.5  [get_ports {rng[69]}]
set_input_transition -min 0.5  [get_ports {rng[69]}]
set_input_transition -max 0.5  [get_ports {rng[68]}]
set_input_transition -min 0.5  [get_ports {rng[68]}]
set_input_transition -max 0.5  [get_ports {rng[67]}]
set_input_transition -min 0.5  [get_ports {rng[67]}]
set_input_transition -max 0.5  [get_ports {rng[66]}]
set_input_transition -min 0.5  [get_ports {rng[66]}]
set_input_transition -max 0.5  [get_ports {rng[65]}]
set_input_transition -min 0.5  [get_ports {rng[65]}]
set_input_transition -max 0.5  [get_ports {rng[64]}]
set_input_transition -min 0.5  [get_ports {rng[64]}]
set_input_transition -max 0.5  [get_ports {rng[63]}]
set_input_transition -min 0.5  [get_ports {rng[63]}]
set_input_transition -max 0.5  [get_ports {rng[62]}]
set_input_transition -min 0.5  [get_ports {rng[62]}]
set_input_transition -max 0.5  [get_ports {rng[61]}]
set_input_transition -min 0.5  [get_ports {rng[61]}]
set_input_transition -max 0.5  [get_ports {rng[60]}]
set_input_transition -min 0.5  [get_ports {rng[60]}]
set_input_transition -max 0.5  [get_ports {rng[59]}]
set_input_transition -min 0.5  [get_ports {rng[59]}]
set_input_transition -max 0.5  [get_ports {rng[58]}]
set_input_transition -min 0.5  [get_ports {rng[58]}]
set_input_transition -max 0.5  [get_ports {rng[57]}]
set_input_transition -min 0.5  [get_ports {rng[57]}]
set_input_transition -max 0.5  [get_ports {rng[56]}]
set_input_transition -min 0.5  [get_ports {rng[56]}]
set_input_transition -max 0.5  [get_ports {rng[55]}]
set_input_transition -min 0.5  [get_ports {rng[55]}]
set_input_transition -max 0.5  [get_ports {rng[54]}]
set_input_transition -min 0.5  [get_ports {rng[54]}]
set_input_transition -max 0.5  [get_ports {rng[53]}]
set_input_transition -min 0.5  [get_ports {rng[53]}]
set_input_transition -max 0.5  [get_ports {rng[52]}]
set_input_transition -min 0.5  [get_ports {rng[52]}]
set_input_transition -max 0.5  [get_ports {rng[51]}]
set_input_transition -min 0.5  [get_ports {rng[51]}]
set_input_transition -max 0.5  [get_ports {rng[50]}]
set_input_transition -min 0.5  [get_ports {rng[50]}]
set_input_transition -max 0.5  [get_ports {rng[49]}]
set_input_transition -min 0.5  [get_ports {rng[49]}]
set_input_transition -max 0.5  [get_ports {rng[48]}]
set_input_transition -min 0.5  [get_ports {rng[48]}]
set_input_transition -max 0.5  [get_ports {rng[47]}]
set_input_transition -min 0.5  [get_ports {rng[47]}]
set_input_transition -max 0.5  [get_ports {rng[46]}]
set_input_transition -min 0.5  [get_ports {rng[46]}]
set_input_transition -max 0.5  [get_ports {rng[45]}]
set_input_transition -min 0.5  [get_ports {rng[45]}]
set_input_transition -max 0.5  [get_ports {rng[44]}]
set_input_transition -min 0.5  [get_ports {rng[44]}]
set_input_transition -max 0.5  [get_ports {rng[43]}]
set_input_transition -min 0.5  [get_ports {rng[43]}]
set_input_transition -max 0.5  [get_ports {rng[42]}]
set_input_transition -min 0.5  [get_ports {rng[42]}]
set_input_transition -max 0.5  [get_ports {rng[41]}]
set_input_transition -min 0.5  [get_ports {rng[41]}]
set_input_transition -max 0.5  [get_ports {rng[40]}]
set_input_transition -min 0.5  [get_ports {rng[40]}]
set_input_transition -max 0.5  [get_ports {rng[39]}]
set_input_transition -min 0.5  [get_ports {rng[39]}]
set_input_transition -max 0.5  [get_ports {rng[38]}]
set_input_transition -min 0.5  [get_ports {rng[38]}]
set_input_transition -max 0.5  [get_ports {rng[37]}]
set_input_transition -min 0.5  [get_ports {rng[37]}]
set_input_transition -max 0.5  [get_ports {rng[36]}]
set_input_transition -min 0.5  [get_ports {rng[36]}]
set_input_transition -max 0.5  [get_ports {rng[35]}]
set_input_transition -min 0.5  [get_ports {rng[35]}]
set_input_transition -max 0.5  [get_ports {rng[34]}]
set_input_transition -min 0.5  [get_ports {rng[34]}]
set_input_transition -max 0.5  [get_ports {rng[33]}]
set_input_transition -min 0.5  [get_ports {rng[33]}]
set_input_transition -max 0.5  [get_ports {rng[32]}]
set_input_transition -min 0.5  [get_ports {rng[32]}]
set_input_transition -max 0.5  [get_ports {rng[31]}]
set_input_transition -min 0.5  [get_ports {rng[31]}]
set_input_transition -max 0.5  [get_ports {rng[30]}]
set_input_transition -min 0.5  [get_ports {rng[30]}]
set_input_transition -max 0.5  [get_ports {rng[29]}]
set_input_transition -min 0.5  [get_ports {rng[29]}]
set_input_transition -max 0.5  [get_ports {rng[28]}]
set_input_transition -min 0.5  [get_ports {rng[28]}]
set_input_transition -max 0.5  [get_ports {rng[27]}]
set_input_transition -min 0.5  [get_ports {rng[27]}]
set_input_transition -max 0.5  [get_ports {rng[26]}]
set_input_transition -min 0.5  [get_ports {rng[26]}]
set_input_transition -max 0.5  [get_ports {rng[25]}]
set_input_transition -min 0.5  [get_ports {rng[25]}]
set_input_transition -max 0.5  [get_ports {rng[24]}]
set_input_transition -min 0.5  [get_ports {rng[24]}]
set_input_transition -max 0.5  [get_ports {rng[23]}]
set_input_transition -min 0.5  [get_ports {rng[23]}]
set_input_transition -max 0.5  [get_ports {rng[22]}]
set_input_transition -min 0.5  [get_ports {rng[22]}]
set_input_transition -max 0.5  [get_ports {rng[21]}]
set_input_transition -min 0.5  [get_ports {rng[21]}]
set_input_transition -max 0.5  [get_ports {rng[20]}]
set_input_transition -min 0.5  [get_ports {rng[20]}]
set_input_transition -max 0.5  [get_ports {rng[19]}]
set_input_transition -min 0.5  [get_ports {rng[19]}]
set_input_transition -max 0.5  [get_ports {rng[18]}]
set_input_transition -min 0.5  [get_ports {rng[18]}]
set_input_transition -max 0.5  [get_ports {rng[17]}]
set_input_transition -min 0.5  [get_ports {rng[17]}]
set_input_transition -max 0.5  [get_ports {rng[16]}]
set_input_transition -min 0.5  [get_ports {rng[16]}]
set_input_transition -max 0.5  [get_ports {rng[15]}]
set_input_transition -min 0.5  [get_ports {rng[15]}]
set_input_transition -max 0.5  [get_ports {rng[14]}]
set_input_transition -min 0.5  [get_ports {rng[14]}]
set_input_transition -max 0.5  [get_ports {rng[13]}]
set_input_transition -min 0.5  [get_ports {rng[13]}]
set_input_transition -max 0.5  [get_ports {rng[12]}]
set_input_transition -min 0.5  [get_ports {rng[12]}]
set_input_transition -max 0.5  [get_ports {rng[11]}]
set_input_transition -min 0.5  [get_ports {rng[11]}]
set_input_transition -max 0.5  [get_ports {rng[10]}]
set_input_transition -min 0.5  [get_ports {rng[10]}]
set_input_transition -max 0.5  [get_ports {rng[9]}]
set_input_transition -min 0.5  [get_ports {rng[9]}]
set_input_transition -max 0.5  [get_ports {rng[8]}]
set_input_transition -min 0.5  [get_ports {rng[8]}]
set_input_transition -max 0.5  [get_ports {rng[7]}]
set_input_transition -min 0.5  [get_ports {rng[7]}]
set_input_transition -max 0.5  [get_ports {rng[6]}]
set_input_transition -min 0.5  [get_ports {rng[6]}]
set_input_transition -max 0.5  [get_ports {rng[5]}]
set_input_transition -min 0.5  [get_ports {rng[5]}]
set_input_transition -max 0.5  [get_ports {rng[4]}]
set_input_transition -min 0.5  [get_ports {rng[4]}]
set_input_transition -max 0.5  [get_ports {rng[3]}]
set_input_transition -min 0.5  [get_ports {rng[3]}]
set_input_transition -max 0.5  [get_ports {rng[2]}]
set_input_transition -min 0.5  [get_ports {rng[2]}]
set_input_transition -max 0.5  [get_ports {rng[1]}]
set_input_transition -min 0.5  [get_ports {rng[1]}]
set_input_transition -max 0.5  [get_ports {rng[0]}]
set_input_transition -min 0.5  [get_ports {rng[0]}]
