###################################################################

# Created by write_sdc on Wed Jun  3 00:40:45 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name Small -library                                       \
sc9_cln40g_base_rvt_ss_typical_max_0p81v_125c
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {X_re0[63]}]
set_load -pin_load 0.05 [get_ports {X_re0[62]}]
set_load -pin_load 0.05 [get_ports {X_re0[61]}]
set_load -pin_load 0.05 [get_ports {X_re0[60]}]
set_load -pin_load 0.05 [get_ports {X_re0[59]}]
set_load -pin_load 0.05 [get_ports {X_re0[58]}]
set_load -pin_load 0.05 [get_ports {X_re0[57]}]
set_load -pin_load 0.05 [get_ports {X_re0[56]}]
set_load -pin_load 0.05 [get_ports {X_re0[55]}]
set_load -pin_load 0.05 [get_ports {X_re0[54]}]
set_load -pin_load 0.05 [get_ports {X_re0[53]}]
set_load -pin_load 0.05 [get_ports {X_re0[52]}]
set_load -pin_load 0.05 [get_ports {X_re0[51]}]
set_load -pin_load 0.05 [get_ports {X_re0[50]}]
set_load -pin_load 0.05 [get_ports {X_re0[49]}]
set_load -pin_load 0.05 [get_ports {X_re0[48]}]
set_load -pin_load 0.05 [get_ports {X_re0[47]}]
set_load -pin_load 0.05 [get_ports {X_re0[46]}]
set_load -pin_load 0.05 [get_ports {X_re0[45]}]
set_load -pin_load 0.05 [get_ports {X_re0[44]}]
set_load -pin_load 0.05 [get_ports {X_re0[43]}]
set_load -pin_load 0.05 [get_ports {X_re0[42]}]
set_load -pin_load 0.05 [get_ports {X_re0[41]}]
set_load -pin_load 0.05 [get_ports {X_re0[40]}]
set_load -pin_load 0.05 [get_ports {X_re0[39]}]
set_load -pin_load 0.05 [get_ports {X_re0[38]}]
set_load -pin_load 0.05 [get_ports {X_re0[37]}]
set_load -pin_load 0.05 [get_ports {X_re0[36]}]
set_load -pin_load 0.05 [get_ports {X_re0[35]}]
set_load -pin_load 0.05 [get_ports {X_re0[34]}]
set_load -pin_load 0.05 [get_ports {X_re0[33]}]
set_load -pin_load 0.05 [get_ports {X_re0[32]}]
set_load -pin_load 0.05 [get_ports {X_re0[31]}]
set_load -pin_load 0.05 [get_ports {X_re0[30]}]
set_load -pin_load 0.05 [get_ports {X_re0[29]}]
set_load -pin_load 0.05 [get_ports {X_re0[28]}]
set_load -pin_load 0.05 [get_ports {X_re0[27]}]
set_load -pin_load 0.05 [get_ports {X_re0[26]}]
set_load -pin_load 0.05 [get_ports {X_re0[25]}]
set_load -pin_load 0.05 [get_ports {X_re0[24]}]
set_load -pin_load 0.05 [get_ports {X_re0[23]}]
set_load -pin_load 0.05 [get_ports {X_re0[22]}]
set_load -pin_load 0.05 [get_ports {X_re0[21]}]
set_load -pin_load 0.05 [get_ports {X_re0[20]}]
set_load -pin_load 0.05 [get_ports {X_re0[19]}]
set_load -pin_load 0.05 [get_ports {X_re0[18]}]
set_load -pin_load 0.05 [get_ports {X_re0[17]}]
set_load -pin_load 0.05 [get_ports {X_re0[16]}]
set_load -pin_load 0.05 [get_ports {X_re0[15]}]
set_load -pin_load 0.05 [get_ports {X_re0[14]}]
set_load -pin_load 0.05 [get_ports {X_re0[13]}]
set_load -pin_load 0.05 [get_ports {X_re0[12]}]
set_load -pin_load 0.05 [get_ports {X_re0[11]}]
set_load -pin_load 0.05 [get_ports {X_re0[10]}]
set_load -pin_load 0.05 [get_ports {X_re0[9]}]
set_load -pin_load 0.05 [get_ports {X_re0[8]}]
set_load -pin_load 0.05 [get_ports {X_re0[7]}]
set_load -pin_load 0.05 [get_ports {X_re0[6]}]
set_load -pin_load 0.05 [get_ports {X_re0[5]}]
set_load -pin_load 0.05 [get_ports {X_re0[4]}]
set_load -pin_load 0.05 [get_ports {X_re0[3]}]
set_load -pin_load 0.05 [get_ports {X_re0[2]}]
set_load -pin_load 0.05 [get_ports {X_re0[1]}]
set_load -pin_load 0.05 [get_ports {X_re0[0]}]
set_load -pin_load 0.05 [get_ports {X_im0[63]}]
set_load -pin_load 0.05 [get_ports {X_im0[62]}]
set_load -pin_load 0.05 [get_ports {X_im0[61]}]
set_load -pin_load 0.05 [get_ports {X_im0[60]}]
set_load -pin_load 0.05 [get_ports {X_im0[59]}]
set_load -pin_load 0.05 [get_ports {X_im0[58]}]
set_load -pin_load 0.05 [get_ports {X_im0[57]}]
set_load -pin_load 0.05 [get_ports {X_im0[56]}]
set_load -pin_load 0.05 [get_ports {X_im0[55]}]
set_load -pin_load 0.05 [get_ports {X_im0[54]}]
set_load -pin_load 0.05 [get_ports {X_im0[53]}]
set_load -pin_load 0.05 [get_ports {X_im0[52]}]
set_load -pin_load 0.05 [get_ports {X_im0[51]}]
set_load -pin_load 0.05 [get_ports {X_im0[50]}]
set_load -pin_load 0.05 [get_ports {X_im0[49]}]
set_load -pin_load 0.05 [get_ports {X_im0[48]}]
set_load -pin_load 0.05 [get_ports {X_im0[47]}]
set_load -pin_load 0.05 [get_ports {X_im0[46]}]
set_load -pin_load 0.05 [get_ports {X_im0[45]}]
set_load -pin_load 0.05 [get_ports {X_im0[44]}]
set_load -pin_load 0.05 [get_ports {X_im0[43]}]
set_load -pin_load 0.05 [get_ports {X_im0[42]}]
set_load -pin_load 0.05 [get_ports {X_im0[41]}]
set_load -pin_load 0.05 [get_ports {X_im0[40]}]
set_load -pin_load 0.05 [get_ports {X_im0[39]}]
set_load -pin_load 0.05 [get_ports {X_im0[38]}]
set_load -pin_load 0.05 [get_ports {X_im0[37]}]
set_load -pin_load 0.05 [get_ports {X_im0[36]}]
set_load -pin_load 0.05 [get_ports {X_im0[35]}]
set_load -pin_load 0.05 [get_ports {X_im0[34]}]
set_load -pin_load 0.05 [get_ports {X_im0[33]}]
set_load -pin_load 0.05 [get_ports {X_im0[32]}]
set_load -pin_load 0.05 [get_ports {X_im0[31]}]
set_load -pin_load 0.05 [get_ports {X_im0[30]}]
set_load -pin_load 0.05 [get_ports {X_im0[29]}]
set_load -pin_load 0.05 [get_ports {X_im0[28]}]
set_load -pin_load 0.05 [get_ports {X_im0[27]}]
set_load -pin_load 0.05 [get_ports {X_im0[26]}]
set_load -pin_load 0.05 [get_ports {X_im0[25]}]
set_load -pin_load 0.05 [get_ports {X_im0[24]}]
set_load -pin_load 0.05 [get_ports {X_im0[23]}]
set_load -pin_load 0.05 [get_ports {X_im0[22]}]
set_load -pin_load 0.05 [get_ports {X_im0[21]}]
set_load -pin_load 0.05 [get_ports {X_im0[20]}]
set_load -pin_load 0.05 [get_ports {X_im0[19]}]
set_load -pin_load 0.05 [get_ports {X_im0[18]}]
set_load -pin_load 0.05 [get_ports {X_im0[17]}]
set_load -pin_load 0.05 [get_ports {X_im0[16]}]
set_load -pin_load 0.05 [get_ports {X_im0[15]}]
set_load -pin_load 0.05 [get_ports {X_im0[14]}]
set_load -pin_load 0.05 [get_ports {X_im0[13]}]
set_load -pin_load 0.05 [get_ports {X_im0[12]}]
set_load -pin_load 0.05 [get_ports {X_im0[11]}]
set_load -pin_load 0.05 [get_ports {X_im0[10]}]
set_load -pin_load 0.05 [get_ports {X_im0[9]}]
set_load -pin_load 0.05 [get_ports {X_im0[8]}]
set_load -pin_load 0.05 [get_ports {X_im0[7]}]
set_load -pin_load 0.05 [get_ports {X_im0[6]}]
set_load -pin_load 0.05 [get_ports {X_im0[5]}]
set_load -pin_load 0.05 [get_ports {X_im0[4]}]
set_load -pin_load 0.05 [get_ports {X_im0[3]}]
set_load -pin_load 0.05 [get_ports {X_im0[2]}]
set_load -pin_load 0.05 [get_ports {X_im0[1]}]
set_load -pin_load 0.05 [get_ports {X_im0[0]}]
set_load -pin_load 0.05 [get_ports {Y_re0[63]}]
set_load -pin_load 0.05 [get_ports {Y_re0[62]}]
set_load -pin_load 0.05 [get_ports {Y_re0[61]}]
set_load -pin_load 0.05 [get_ports {Y_re0[60]}]
set_load -pin_load 0.05 [get_ports {Y_re0[59]}]
set_load -pin_load 0.05 [get_ports {Y_re0[58]}]
set_load -pin_load 0.05 [get_ports {Y_re0[57]}]
set_load -pin_load 0.05 [get_ports {Y_re0[56]}]
set_load -pin_load 0.05 [get_ports {Y_re0[55]}]
set_load -pin_load 0.05 [get_ports {Y_re0[54]}]
set_load -pin_load 0.05 [get_ports {Y_re0[53]}]
set_load -pin_load 0.05 [get_ports {Y_re0[52]}]
set_load -pin_load 0.05 [get_ports {Y_re0[51]}]
set_load -pin_load 0.05 [get_ports {Y_re0[50]}]
set_load -pin_load 0.05 [get_ports {Y_re0[49]}]
set_load -pin_load 0.05 [get_ports {Y_re0[48]}]
set_load -pin_load 0.05 [get_ports {Y_re0[47]}]
set_load -pin_load 0.05 [get_ports {Y_re0[46]}]
set_load -pin_load 0.05 [get_ports {Y_re0[45]}]
set_load -pin_load 0.05 [get_ports {Y_re0[44]}]
set_load -pin_load 0.05 [get_ports {Y_re0[43]}]
set_load -pin_load 0.05 [get_ports {Y_re0[42]}]
set_load -pin_load 0.05 [get_ports {Y_re0[41]}]
set_load -pin_load 0.05 [get_ports {Y_re0[40]}]
set_load -pin_load 0.05 [get_ports {Y_re0[39]}]
set_load -pin_load 0.05 [get_ports {Y_re0[38]}]
set_load -pin_load 0.05 [get_ports {Y_re0[37]}]
set_load -pin_load 0.05 [get_ports {Y_re0[36]}]
set_load -pin_load 0.05 [get_ports {Y_re0[35]}]
set_load -pin_load 0.05 [get_ports {Y_re0[34]}]
set_load -pin_load 0.05 [get_ports {Y_re0[33]}]
set_load -pin_load 0.05 [get_ports {Y_re0[32]}]
set_load -pin_load 0.05 [get_ports {Y_re0[31]}]
set_load -pin_load 0.05 [get_ports {Y_re0[30]}]
set_load -pin_load 0.05 [get_ports {Y_re0[29]}]
set_load -pin_load 0.05 [get_ports {Y_re0[28]}]
set_load -pin_load 0.05 [get_ports {Y_re0[27]}]
set_load -pin_load 0.05 [get_ports {Y_re0[26]}]
set_load -pin_load 0.05 [get_ports {Y_re0[25]}]
set_load -pin_load 0.05 [get_ports {Y_re0[24]}]
set_load -pin_load 0.05 [get_ports {Y_re0[23]}]
set_load -pin_load 0.05 [get_ports {Y_re0[22]}]
set_load -pin_load 0.05 [get_ports {Y_re0[21]}]
set_load -pin_load 0.05 [get_ports {Y_re0[20]}]
set_load -pin_load 0.05 [get_ports {Y_re0[19]}]
set_load -pin_load 0.05 [get_ports {Y_re0[18]}]
set_load -pin_load 0.05 [get_ports {Y_re0[17]}]
set_load -pin_load 0.05 [get_ports {Y_re0[16]}]
set_load -pin_load 0.05 [get_ports {Y_re0[15]}]
set_load -pin_load 0.05 [get_ports {Y_re0[14]}]
set_load -pin_load 0.05 [get_ports {Y_re0[13]}]
set_load -pin_load 0.05 [get_ports {Y_re0[12]}]
set_load -pin_load 0.05 [get_ports {Y_re0[11]}]
set_load -pin_load 0.05 [get_ports {Y_re0[10]}]
set_load -pin_load 0.05 [get_ports {Y_re0[9]}]
set_load -pin_load 0.05 [get_ports {Y_re0[8]}]
set_load -pin_load 0.05 [get_ports {Y_re0[7]}]
set_load -pin_load 0.05 [get_ports {Y_re0[6]}]
set_load -pin_load 0.05 [get_ports {Y_re0[5]}]
set_load -pin_load 0.05 [get_ports {Y_re0[4]}]
set_load -pin_load 0.05 [get_ports {Y_re0[3]}]
set_load -pin_load 0.05 [get_ports {Y_re0[2]}]
set_load -pin_load 0.05 [get_ports {Y_re0[1]}]
set_load -pin_load 0.05 [get_ports {Y_re0[0]}]
set_load -pin_load 0.05 [get_ports {Y_im0[63]}]
set_load -pin_load 0.05 [get_ports {Y_im0[62]}]
set_load -pin_load 0.05 [get_ports {Y_im0[61]}]
set_load -pin_load 0.05 [get_ports {Y_im0[60]}]
set_load -pin_load 0.05 [get_ports {Y_im0[59]}]
set_load -pin_load 0.05 [get_ports {Y_im0[58]}]
set_load -pin_load 0.05 [get_ports {Y_im0[57]}]
set_load -pin_load 0.05 [get_ports {Y_im0[56]}]
set_load -pin_load 0.05 [get_ports {Y_im0[55]}]
set_load -pin_load 0.05 [get_ports {Y_im0[54]}]
set_load -pin_load 0.05 [get_ports {Y_im0[53]}]
set_load -pin_load 0.05 [get_ports {Y_im0[52]}]
set_load -pin_load 0.05 [get_ports {Y_im0[51]}]
set_load -pin_load 0.05 [get_ports {Y_im0[50]}]
set_load -pin_load 0.05 [get_ports {Y_im0[49]}]
set_load -pin_load 0.05 [get_ports {Y_im0[48]}]
set_load -pin_load 0.05 [get_ports {Y_im0[47]}]
set_load -pin_load 0.05 [get_ports {Y_im0[46]}]
set_load -pin_load 0.05 [get_ports {Y_im0[45]}]
set_load -pin_load 0.05 [get_ports {Y_im0[44]}]
set_load -pin_load 0.05 [get_ports {Y_im0[43]}]
set_load -pin_load 0.05 [get_ports {Y_im0[42]}]
set_load -pin_load 0.05 [get_ports {Y_im0[41]}]
set_load -pin_load 0.05 [get_ports {Y_im0[40]}]
set_load -pin_load 0.05 [get_ports {Y_im0[39]}]
set_load -pin_load 0.05 [get_ports {Y_im0[38]}]
set_load -pin_load 0.05 [get_ports {Y_im0[37]}]
set_load -pin_load 0.05 [get_ports {Y_im0[36]}]
set_load -pin_load 0.05 [get_ports {Y_im0[35]}]
set_load -pin_load 0.05 [get_ports {Y_im0[34]}]
set_load -pin_load 0.05 [get_ports {Y_im0[33]}]
set_load -pin_load 0.05 [get_ports {Y_im0[32]}]
set_load -pin_load 0.05 [get_ports {Y_im0[31]}]
set_load -pin_load 0.05 [get_ports {Y_im0[30]}]
set_load -pin_load 0.05 [get_ports {Y_im0[29]}]
set_load -pin_load 0.05 [get_ports {Y_im0[28]}]
set_load -pin_load 0.05 [get_ports {Y_im0[27]}]
set_load -pin_load 0.05 [get_ports {Y_im0[26]}]
set_load -pin_load 0.05 [get_ports {Y_im0[25]}]
set_load -pin_load 0.05 [get_ports {Y_im0[24]}]
set_load -pin_load 0.05 [get_ports {Y_im0[23]}]
set_load -pin_load 0.05 [get_ports {Y_im0[22]}]
set_load -pin_load 0.05 [get_ports {Y_im0[21]}]
set_load -pin_load 0.05 [get_ports {Y_im0[20]}]
set_load -pin_load 0.05 [get_ports {Y_im0[19]}]
set_load -pin_load 0.05 [get_ports {Y_im0[18]}]
set_load -pin_load 0.05 [get_ports {Y_im0[17]}]
set_load -pin_load 0.05 [get_ports {Y_im0[16]}]
set_load -pin_load 0.05 [get_ports {Y_im0[15]}]
set_load -pin_load 0.05 [get_ports {Y_im0[14]}]
set_load -pin_load 0.05 [get_ports {Y_im0[13]}]
set_load -pin_load 0.05 [get_ports {Y_im0[12]}]
set_load -pin_load 0.05 [get_ports {Y_im0[11]}]
set_load -pin_load 0.05 [get_ports {Y_im0[10]}]
set_load -pin_load 0.05 [get_ports {Y_im0[9]}]
set_load -pin_load 0.05 [get_ports {Y_im0[8]}]
set_load -pin_load 0.05 [get_ports {Y_im0[7]}]
set_load -pin_load 0.05 [get_ports {Y_im0[6]}]
set_load -pin_load 0.05 [get_ports {Y_im0[5]}]
set_load -pin_load 0.05 [get_ports {Y_im0[4]}]
set_load -pin_load 0.05 [get_ports {Y_im0[3]}]
set_load -pin_load 0.05 [get_ports {Y_im0[2]}]
set_load -pin_load 0.05 [get_ports {Y_im0[1]}]
set_load -pin_load 0.05 [get_ports {Y_im0[0]}]
create_clock [get_ports clk]  -period 1  -waveform {0 0.5}
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  0  [get_ports in_valid]
set_input_delay -clock clk  0  [get_ports is_ifft]
set_input_delay -clock clk  0  [get_ports {x_re[63]}]
set_input_delay -clock clk  0  [get_ports {x_re[62]}]
set_input_delay -clock clk  0  [get_ports {x_re[61]}]
set_input_delay -clock clk  0  [get_ports {x_re[60]}]
set_input_delay -clock clk  0  [get_ports {x_re[59]}]
set_input_delay -clock clk  0  [get_ports {x_re[58]}]
set_input_delay -clock clk  0  [get_ports {x_re[57]}]
set_input_delay -clock clk  0  [get_ports {x_re[56]}]
set_input_delay -clock clk  0  [get_ports {x_re[55]}]
set_input_delay -clock clk  0  [get_ports {x_re[54]}]
set_input_delay -clock clk  0  [get_ports {x_re[53]}]
set_input_delay -clock clk  0  [get_ports {x_re[52]}]
set_input_delay -clock clk  0  [get_ports {x_re[51]}]
set_input_delay -clock clk  0  [get_ports {x_re[50]}]
set_input_delay -clock clk  0  [get_ports {x_re[49]}]
set_input_delay -clock clk  0  [get_ports {x_re[48]}]
set_input_delay -clock clk  0  [get_ports {x_re[47]}]
set_input_delay -clock clk  0  [get_ports {x_re[46]}]
set_input_delay -clock clk  0  [get_ports {x_re[45]}]
set_input_delay -clock clk  0  [get_ports {x_re[44]}]
set_input_delay -clock clk  0  [get_ports {x_re[43]}]
set_input_delay -clock clk  0  [get_ports {x_re[42]}]
set_input_delay -clock clk  0  [get_ports {x_re[41]}]
set_input_delay -clock clk  0  [get_ports {x_re[40]}]
set_input_delay -clock clk  0  [get_ports {x_re[39]}]
set_input_delay -clock clk  0  [get_ports {x_re[38]}]
set_input_delay -clock clk  0  [get_ports {x_re[37]}]
set_input_delay -clock clk  0  [get_ports {x_re[36]}]
set_input_delay -clock clk  0  [get_ports {x_re[35]}]
set_input_delay -clock clk  0  [get_ports {x_re[34]}]
set_input_delay -clock clk  0  [get_ports {x_re[33]}]
set_input_delay -clock clk  0  [get_ports {x_re[32]}]
set_input_delay -clock clk  0  [get_ports {x_re[31]}]
set_input_delay -clock clk  0  [get_ports {x_re[30]}]
set_input_delay -clock clk  0  [get_ports {x_re[29]}]
set_input_delay -clock clk  0  [get_ports {x_re[28]}]
set_input_delay -clock clk  0  [get_ports {x_re[27]}]
set_input_delay -clock clk  0  [get_ports {x_re[26]}]
set_input_delay -clock clk  0  [get_ports {x_re[25]}]
set_input_delay -clock clk  0  [get_ports {x_re[24]}]
set_input_delay -clock clk  0  [get_ports {x_re[23]}]
set_input_delay -clock clk  0  [get_ports {x_re[22]}]
set_input_delay -clock clk  0  [get_ports {x_re[21]}]
set_input_delay -clock clk  0  [get_ports {x_re[20]}]
set_input_delay -clock clk  0  [get_ports {x_re[19]}]
set_input_delay -clock clk  0  [get_ports {x_re[18]}]
set_input_delay -clock clk  0  [get_ports {x_re[17]}]
set_input_delay -clock clk  0  [get_ports {x_re[16]}]
set_input_delay -clock clk  0  [get_ports {x_re[15]}]
set_input_delay -clock clk  0  [get_ports {x_re[14]}]
set_input_delay -clock clk  0  [get_ports {x_re[13]}]
set_input_delay -clock clk  0  [get_ports {x_re[12]}]
set_input_delay -clock clk  0  [get_ports {x_re[11]}]
set_input_delay -clock clk  0  [get_ports {x_re[10]}]
set_input_delay -clock clk  0  [get_ports {x_re[9]}]
set_input_delay -clock clk  0  [get_ports {x_re[8]}]
set_input_delay -clock clk  0  [get_ports {x_re[7]}]
set_input_delay -clock clk  0  [get_ports {x_re[6]}]
set_input_delay -clock clk  0  [get_ports {x_re[5]}]
set_input_delay -clock clk  0  [get_ports {x_re[4]}]
set_input_delay -clock clk  0  [get_ports {x_re[3]}]
set_input_delay -clock clk  0  [get_ports {x_re[2]}]
set_input_delay -clock clk  0  [get_ports {x_re[1]}]
set_input_delay -clock clk  0  [get_ports {x_re[0]}]
set_input_delay -clock clk  0  [get_ports {x_im[63]}]
set_input_delay -clock clk  0  [get_ports {x_im[62]}]
set_input_delay -clock clk  0  [get_ports {x_im[61]}]
set_input_delay -clock clk  0  [get_ports {x_im[60]}]
set_input_delay -clock clk  0  [get_ports {x_im[59]}]
set_input_delay -clock clk  0  [get_ports {x_im[58]}]
set_input_delay -clock clk  0  [get_ports {x_im[57]}]
set_input_delay -clock clk  0  [get_ports {x_im[56]}]
set_input_delay -clock clk  0  [get_ports {x_im[55]}]
set_input_delay -clock clk  0  [get_ports {x_im[54]}]
set_input_delay -clock clk  0  [get_ports {x_im[53]}]
set_input_delay -clock clk  0  [get_ports {x_im[52]}]
set_input_delay -clock clk  0  [get_ports {x_im[51]}]
set_input_delay -clock clk  0  [get_ports {x_im[50]}]
set_input_delay -clock clk  0  [get_ports {x_im[49]}]
set_input_delay -clock clk  0  [get_ports {x_im[48]}]
set_input_delay -clock clk  0  [get_ports {x_im[47]}]
set_input_delay -clock clk  0  [get_ports {x_im[46]}]
set_input_delay -clock clk  0  [get_ports {x_im[45]}]
set_input_delay -clock clk  0  [get_ports {x_im[44]}]
set_input_delay -clock clk  0  [get_ports {x_im[43]}]
set_input_delay -clock clk  0  [get_ports {x_im[42]}]
set_input_delay -clock clk  0  [get_ports {x_im[41]}]
set_input_delay -clock clk  0  [get_ports {x_im[40]}]
set_input_delay -clock clk  0  [get_ports {x_im[39]}]
set_input_delay -clock clk  0  [get_ports {x_im[38]}]
set_input_delay -clock clk  0  [get_ports {x_im[37]}]
set_input_delay -clock clk  0  [get_ports {x_im[36]}]
set_input_delay -clock clk  0  [get_ports {x_im[35]}]
set_input_delay -clock clk  0  [get_ports {x_im[34]}]
set_input_delay -clock clk  0  [get_ports {x_im[33]}]
set_input_delay -clock clk  0  [get_ports {x_im[32]}]
set_input_delay -clock clk  0  [get_ports {x_im[31]}]
set_input_delay -clock clk  0  [get_ports {x_im[30]}]
set_input_delay -clock clk  0  [get_ports {x_im[29]}]
set_input_delay -clock clk  0  [get_ports {x_im[28]}]
set_input_delay -clock clk  0  [get_ports {x_im[27]}]
set_input_delay -clock clk  0  [get_ports {x_im[26]}]
set_input_delay -clock clk  0  [get_ports {x_im[25]}]
set_input_delay -clock clk  0  [get_ports {x_im[24]}]
set_input_delay -clock clk  0  [get_ports {x_im[23]}]
set_input_delay -clock clk  0  [get_ports {x_im[22]}]
set_input_delay -clock clk  0  [get_ports {x_im[21]}]
set_input_delay -clock clk  0  [get_ports {x_im[20]}]
set_input_delay -clock clk  0  [get_ports {x_im[19]}]
set_input_delay -clock clk  0  [get_ports {x_im[18]}]
set_input_delay -clock clk  0  [get_ports {x_im[17]}]
set_input_delay -clock clk  0  [get_ports {x_im[16]}]
set_input_delay -clock clk  0  [get_ports {x_im[15]}]
set_input_delay -clock clk  0  [get_ports {x_im[14]}]
set_input_delay -clock clk  0  [get_ports {x_im[13]}]
set_input_delay -clock clk  0  [get_ports {x_im[12]}]
set_input_delay -clock clk  0  [get_ports {x_im[11]}]
set_input_delay -clock clk  0  [get_ports {x_im[10]}]
set_input_delay -clock clk  0  [get_ports {x_im[9]}]
set_input_delay -clock clk  0  [get_ports {x_im[8]}]
set_input_delay -clock clk  0  [get_ports {x_im[7]}]
set_input_delay -clock clk  0  [get_ports {x_im[6]}]
set_input_delay -clock clk  0  [get_ports {x_im[5]}]
set_input_delay -clock clk  0  [get_ports {x_im[4]}]
set_input_delay -clock clk  0  [get_ports {x_im[3]}]
set_input_delay -clock clk  0  [get_ports {x_im[2]}]
set_input_delay -clock clk  0  [get_ports {x_im[1]}]
set_input_delay -clock clk  0  [get_ports {x_im[0]}]
set_input_delay -clock clk  0  [get_ports {y_re[63]}]
set_input_delay -clock clk  0  [get_ports {y_re[62]}]
set_input_delay -clock clk  0  [get_ports {y_re[61]}]
set_input_delay -clock clk  0  [get_ports {y_re[60]}]
set_input_delay -clock clk  0  [get_ports {y_re[59]}]
set_input_delay -clock clk  0  [get_ports {y_re[58]}]
set_input_delay -clock clk  0  [get_ports {y_re[57]}]
set_input_delay -clock clk  0  [get_ports {y_re[56]}]
set_input_delay -clock clk  0  [get_ports {y_re[55]}]
set_input_delay -clock clk  0  [get_ports {y_re[54]}]
set_input_delay -clock clk  0  [get_ports {y_re[53]}]
set_input_delay -clock clk  0  [get_ports {y_re[52]}]
set_input_delay -clock clk  0  [get_ports {y_re[51]}]
set_input_delay -clock clk  0  [get_ports {y_re[50]}]
set_input_delay -clock clk  0  [get_ports {y_re[49]}]
set_input_delay -clock clk  0  [get_ports {y_re[48]}]
set_input_delay -clock clk  0  [get_ports {y_re[47]}]
set_input_delay -clock clk  0  [get_ports {y_re[46]}]
set_input_delay -clock clk  0  [get_ports {y_re[45]}]
set_input_delay -clock clk  0  [get_ports {y_re[44]}]
set_input_delay -clock clk  0  [get_ports {y_re[43]}]
set_input_delay -clock clk  0  [get_ports {y_re[42]}]
set_input_delay -clock clk  0  [get_ports {y_re[41]}]
set_input_delay -clock clk  0  [get_ports {y_re[40]}]
set_input_delay -clock clk  0  [get_ports {y_re[39]}]
set_input_delay -clock clk  0  [get_ports {y_re[38]}]
set_input_delay -clock clk  0  [get_ports {y_re[37]}]
set_input_delay -clock clk  0  [get_ports {y_re[36]}]
set_input_delay -clock clk  0  [get_ports {y_re[35]}]
set_input_delay -clock clk  0  [get_ports {y_re[34]}]
set_input_delay -clock clk  0  [get_ports {y_re[33]}]
set_input_delay -clock clk  0  [get_ports {y_re[32]}]
set_input_delay -clock clk  0  [get_ports {y_re[31]}]
set_input_delay -clock clk  0  [get_ports {y_re[30]}]
set_input_delay -clock clk  0  [get_ports {y_re[29]}]
set_input_delay -clock clk  0  [get_ports {y_re[28]}]
set_input_delay -clock clk  0  [get_ports {y_re[27]}]
set_input_delay -clock clk  0  [get_ports {y_re[26]}]
set_input_delay -clock clk  0  [get_ports {y_re[25]}]
set_input_delay -clock clk  0  [get_ports {y_re[24]}]
set_input_delay -clock clk  0  [get_ports {y_re[23]}]
set_input_delay -clock clk  0  [get_ports {y_re[22]}]
set_input_delay -clock clk  0  [get_ports {y_re[21]}]
set_input_delay -clock clk  0  [get_ports {y_re[20]}]
set_input_delay -clock clk  0  [get_ports {y_re[19]}]
set_input_delay -clock clk  0  [get_ports {y_re[18]}]
set_input_delay -clock clk  0  [get_ports {y_re[17]}]
set_input_delay -clock clk  0  [get_ports {y_re[16]}]
set_input_delay -clock clk  0  [get_ports {y_re[15]}]
set_input_delay -clock clk  0  [get_ports {y_re[14]}]
set_input_delay -clock clk  0  [get_ports {y_re[13]}]
set_input_delay -clock clk  0  [get_ports {y_re[12]}]
set_input_delay -clock clk  0  [get_ports {y_re[11]}]
set_input_delay -clock clk  0  [get_ports {y_re[10]}]
set_input_delay -clock clk  0  [get_ports {y_re[9]}]
set_input_delay -clock clk  0  [get_ports {y_re[8]}]
set_input_delay -clock clk  0  [get_ports {y_re[7]}]
set_input_delay -clock clk  0  [get_ports {y_re[6]}]
set_input_delay -clock clk  0  [get_ports {y_re[5]}]
set_input_delay -clock clk  0  [get_ports {y_re[4]}]
set_input_delay -clock clk  0  [get_ports {y_re[3]}]
set_input_delay -clock clk  0  [get_ports {y_re[2]}]
set_input_delay -clock clk  0  [get_ports {y_re[1]}]
set_input_delay -clock clk  0  [get_ports {y_re[0]}]
set_input_delay -clock clk  0  [get_ports {y_im[63]}]
set_input_delay -clock clk  0  [get_ports {y_im[62]}]
set_input_delay -clock clk  0  [get_ports {y_im[61]}]
set_input_delay -clock clk  0  [get_ports {y_im[60]}]
set_input_delay -clock clk  0  [get_ports {y_im[59]}]
set_input_delay -clock clk  0  [get_ports {y_im[58]}]
set_input_delay -clock clk  0  [get_ports {y_im[57]}]
set_input_delay -clock clk  0  [get_ports {y_im[56]}]
set_input_delay -clock clk  0  [get_ports {y_im[55]}]
set_input_delay -clock clk  0  [get_ports {y_im[54]}]
set_input_delay -clock clk  0  [get_ports {y_im[53]}]
set_input_delay -clock clk  0  [get_ports {y_im[52]}]
set_input_delay -clock clk  0  [get_ports {y_im[51]}]
set_input_delay -clock clk  0  [get_ports {y_im[50]}]
set_input_delay -clock clk  0  [get_ports {y_im[49]}]
set_input_delay -clock clk  0  [get_ports {y_im[48]}]
set_input_delay -clock clk  0  [get_ports {y_im[47]}]
set_input_delay -clock clk  0  [get_ports {y_im[46]}]
set_input_delay -clock clk  0  [get_ports {y_im[45]}]
set_input_delay -clock clk  0  [get_ports {y_im[44]}]
set_input_delay -clock clk  0  [get_ports {y_im[43]}]
set_input_delay -clock clk  0  [get_ports {y_im[42]}]
set_input_delay -clock clk  0  [get_ports {y_im[41]}]
set_input_delay -clock clk  0  [get_ports {y_im[40]}]
set_input_delay -clock clk  0  [get_ports {y_im[39]}]
set_input_delay -clock clk  0  [get_ports {y_im[38]}]
set_input_delay -clock clk  0  [get_ports {y_im[37]}]
set_input_delay -clock clk  0  [get_ports {y_im[36]}]
set_input_delay -clock clk  0  [get_ports {y_im[35]}]
set_input_delay -clock clk  0  [get_ports {y_im[34]}]
set_input_delay -clock clk  0  [get_ports {y_im[33]}]
set_input_delay -clock clk  0  [get_ports {y_im[32]}]
set_input_delay -clock clk  0  [get_ports {y_im[31]}]
set_input_delay -clock clk  0  [get_ports {y_im[30]}]
set_input_delay -clock clk  0  [get_ports {y_im[29]}]
set_input_delay -clock clk  0  [get_ports {y_im[28]}]
set_input_delay -clock clk  0  [get_ports {y_im[27]}]
set_input_delay -clock clk  0  [get_ports {y_im[26]}]
set_input_delay -clock clk  0  [get_ports {y_im[25]}]
set_input_delay -clock clk  0  [get_ports {y_im[24]}]
set_input_delay -clock clk  0  [get_ports {y_im[23]}]
set_input_delay -clock clk  0  [get_ports {y_im[22]}]
set_input_delay -clock clk  0  [get_ports {y_im[21]}]
set_input_delay -clock clk  0  [get_ports {y_im[20]}]
set_input_delay -clock clk  0  [get_ports {y_im[19]}]
set_input_delay -clock clk  0  [get_ports {y_im[18]}]
set_input_delay -clock clk  0  [get_ports {y_im[17]}]
set_input_delay -clock clk  0  [get_ports {y_im[16]}]
set_input_delay -clock clk  0  [get_ports {y_im[15]}]
set_input_delay -clock clk  0  [get_ports {y_im[14]}]
set_input_delay -clock clk  0  [get_ports {y_im[13]}]
set_input_delay -clock clk  0  [get_ports {y_im[12]}]
set_input_delay -clock clk  0  [get_ports {y_im[11]}]
set_input_delay -clock clk  0  [get_ports {y_im[10]}]
set_input_delay -clock clk  0  [get_ports {y_im[9]}]
set_input_delay -clock clk  0  [get_ports {y_im[8]}]
set_input_delay -clock clk  0  [get_ports {y_im[7]}]
set_input_delay -clock clk  0  [get_ports {y_im[6]}]
set_input_delay -clock clk  0  [get_ports {y_im[5]}]
set_input_delay -clock clk  0  [get_ports {y_im[4]}]
set_input_delay -clock clk  0  [get_ports {y_im[3]}]
set_input_delay -clock clk  0  [get_ports {y_im[2]}]
set_input_delay -clock clk  0  [get_ports {y_im[1]}]
set_input_delay -clock clk  0  [get_ports {y_im[0]}]
set_input_delay -clock clk  0  [get_ports {w_re[63]}]
set_input_delay -clock clk  0  [get_ports {w_re[62]}]
set_input_delay -clock clk  0  [get_ports {w_re[61]}]
set_input_delay -clock clk  0  [get_ports {w_re[60]}]
set_input_delay -clock clk  0  [get_ports {w_re[59]}]
set_input_delay -clock clk  0  [get_ports {w_re[58]}]
set_input_delay -clock clk  0  [get_ports {w_re[57]}]
set_input_delay -clock clk  0  [get_ports {w_re[56]}]
set_input_delay -clock clk  0  [get_ports {w_re[55]}]
set_input_delay -clock clk  0  [get_ports {w_re[54]}]
set_input_delay -clock clk  0  [get_ports {w_re[53]}]
set_input_delay -clock clk  0  [get_ports {w_re[52]}]
set_input_delay -clock clk  0  [get_ports {w_re[51]}]
set_input_delay -clock clk  0  [get_ports {w_re[50]}]
set_input_delay -clock clk  0  [get_ports {w_re[49]}]
set_input_delay -clock clk  0  [get_ports {w_re[48]}]
set_input_delay -clock clk  0  [get_ports {w_re[47]}]
set_input_delay -clock clk  0  [get_ports {w_re[46]}]
set_input_delay -clock clk  0  [get_ports {w_re[45]}]
set_input_delay -clock clk  0  [get_ports {w_re[44]}]
set_input_delay -clock clk  0  [get_ports {w_re[43]}]
set_input_delay -clock clk  0  [get_ports {w_re[42]}]
set_input_delay -clock clk  0  [get_ports {w_re[41]}]
set_input_delay -clock clk  0  [get_ports {w_re[40]}]
set_input_delay -clock clk  0  [get_ports {w_re[39]}]
set_input_delay -clock clk  0  [get_ports {w_re[38]}]
set_input_delay -clock clk  0  [get_ports {w_re[37]}]
set_input_delay -clock clk  0  [get_ports {w_re[36]}]
set_input_delay -clock clk  0  [get_ports {w_re[35]}]
set_input_delay -clock clk  0  [get_ports {w_re[34]}]
set_input_delay -clock clk  0  [get_ports {w_re[33]}]
set_input_delay -clock clk  0  [get_ports {w_re[32]}]
set_input_delay -clock clk  0  [get_ports {w_re[31]}]
set_input_delay -clock clk  0  [get_ports {w_re[30]}]
set_input_delay -clock clk  0  [get_ports {w_re[29]}]
set_input_delay -clock clk  0  [get_ports {w_re[28]}]
set_input_delay -clock clk  0  [get_ports {w_re[27]}]
set_input_delay -clock clk  0  [get_ports {w_re[26]}]
set_input_delay -clock clk  0  [get_ports {w_re[25]}]
set_input_delay -clock clk  0  [get_ports {w_re[24]}]
set_input_delay -clock clk  0  [get_ports {w_re[23]}]
set_input_delay -clock clk  0  [get_ports {w_re[22]}]
set_input_delay -clock clk  0  [get_ports {w_re[21]}]
set_input_delay -clock clk  0  [get_ports {w_re[20]}]
set_input_delay -clock clk  0  [get_ports {w_re[19]}]
set_input_delay -clock clk  0  [get_ports {w_re[18]}]
set_input_delay -clock clk  0  [get_ports {w_re[17]}]
set_input_delay -clock clk  0  [get_ports {w_re[16]}]
set_input_delay -clock clk  0  [get_ports {w_re[15]}]
set_input_delay -clock clk  0  [get_ports {w_re[14]}]
set_input_delay -clock clk  0  [get_ports {w_re[13]}]
set_input_delay -clock clk  0  [get_ports {w_re[12]}]
set_input_delay -clock clk  0  [get_ports {w_re[11]}]
set_input_delay -clock clk  0  [get_ports {w_re[10]}]
set_input_delay -clock clk  0  [get_ports {w_re[9]}]
set_input_delay -clock clk  0  [get_ports {w_re[8]}]
set_input_delay -clock clk  0  [get_ports {w_re[7]}]
set_input_delay -clock clk  0  [get_ports {w_re[6]}]
set_input_delay -clock clk  0  [get_ports {w_re[5]}]
set_input_delay -clock clk  0  [get_ports {w_re[4]}]
set_input_delay -clock clk  0  [get_ports {w_re[3]}]
set_input_delay -clock clk  0  [get_ports {w_re[2]}]
set_input_delay -clock clk  0  [get_ports {w_re[1]}]
set_input_delay -clock clk  0  [get_ports {w_re[0]}]
set_input_delay -clock clk  0  [get_ports {w_im[63]}]
set_input_delay -clock clk  0  [get_ports {w_im[62]}]
set_input_delay -clock clk  0  [get_ports {w_im[61]}]
set_input_delay -clock clk  0  [get_ports {w_im[60]}]
set_input_delay -clock clk  0  [get_ports {w_im[59]}]
set_input_delay -clock clk  0  [get_ports {w_im[58]}]
set_input_delay -clock clk  0  [get_ports {w_im[57]}]
set_input_delay -clock clk  0  [get_ports {w_im[56]}]
set_input_delay -clock clk  0  [get_ports {w_im[55]}]
set_input_delay -clock clk  0  [get_ports {w_im[54]}]
set_input_delay -clock clk  0  [get_ports {w_im[53]}]
set_input_delay -clock clk  0  [get_ports {w_im[52]}]
set_input_delay -clock clk  0  [get_ports {w_im[51]}]
set_input_delay -clock clk  0  [get_ports {w_im[50]}]
set_input_delay -clock clk  0  [get_ports {w_im[49]}]
set_input_delay -clock clk  0  [get_ports {w_im[48]}]
set_input_delay -clock clk  0  [get_ports {w_im[47]}]
set_input_delay -clock clk  0  [get_ports {w_im[46]}]
set_input_delay -clock clk  0  [get_ports {w_im[45]}]
set_input_delay -clock clk  0  [get_ports {w_im[44]}]
set_input_delay -clock clk  0  [get_ports {w_im[43]}]
set_input_delay -clock clk  0  [get_ports {w_im[42]}]
set_input_delay -clock clk  0  [get_ports {w_im[41]}]
set_input_delay -clock clk  0  [get_ports {w_im[40]}]
set_input_delay -clock clk  0  [get_ports {w_im[39]}]
set_input_delay -clock clk  0  [get_ports {w_im[38]}]
set_input_delay -clock clk  0  [get_ports {w_im[37]}]
set_input_delay -clock clk  0  [get_ports {w_im[36]}]
set_input_delay -clock clk  0  [get_ports {w_im[35]}]
set_input_delay -clock clk  0  [get_ports {w_im[34]}]
set_input_delay -clock clk  0  [get_ports {w_im[33]}]
set_input_delay -clock clk  0  [get_ports {w_im[32]}]
set_input_delay -clock clk  0  [get_ports {w_im[31]}]
set_input_delay -clock clk  0  [get_ports {w_im[30]}]
set_input_delay -clock clk  0  [get_ports {w_im[29]}]
set_input_delay -clock clk  0  [get_ports {w_im[28]}]
set_input_delay -clock clk  0  [get_ports {w_im[27]}]
set_input_delay -clock clk  0  [get_ports {w_im[26]}]
set_input_delay -clock clk  0  [get_ports {w_im[25]}]
set_input_delay -clock clk  0  [get_ports {w_im[24]}]
set_input_delay -clock clk  0  [get_ports {w_im[23]}]
set_input_delay -clock clk  0  [get_ports {w_im[22]}]
set_input_delay -clock clk  0  [get_ports {w_im[21]}]
set_input_delay -clock clk  0  [get_ports {w_im[20]}]
set_input_delay -clock clk  0  [get_ports {w_im[19]}]
set_input_delay -clock clk  0  [get_ports {w_im[18]}]
set_input_delay -clock clk  0  [get_ports {w_im[17]}]
set_input_delay -clock clk  0  [get_ports {w_im[16]}]
set_input_delay -clock clk  0  [get_ports {w_im[15]}]
set_input_delay -clock clk  0  [get_ports {w_im[14]}]
set_input_delay -clock clk  0  [get_ports {w_im[13]}]
set_input_delay -clock clk  0  [get_ports {w_im[12]}]
set_input_delay -clock clk  0  [get_ports {w_im[11]}]
set_input_delay -clock clk  0  [get_ports {w_im[10]}]
set_input_delay -clock clk  0  [get_ports {w_im[9]}]
set_input_delay -clock clk  0  [get_ports {w_im[8]}]
set_input_delay -clock clk  0  [get_ports {w_im[7]}]
set_input_delay -clock clk  0  [get_ports {w_im[6]}]
set_input_delay -clock clk  0  [get_ports {w_im[5]}]
set_input_delay -clock clk  0  [get_ports {w_im[4]}]
set_input_delay -clock clk  0  [get_ports {w_im[3]}]
set_input_delay -clock clk  0  [get_ports {w_im[2]}]
set_input_delay -clock clk  0  [get_ports {w_im[1]}]
set_input_delay -clock clk  0  [get_ports {w_im[0]}]
set_output_delay -clock clk  0  [get_ports out_valid]
set_output_delay -clock clk  0  [get_ports {X_re0[63]}]
set_output_delay -clock clk  0  [get_ports {X_re0[62]}]
set_output_delay -clock clk  0  [get_ports {X_re0[61]}]
set_output_delay -clock clk  0  [get_ports {X_re0[60]}]
set_output_delay -clock clk  0  [get_ports {X_re0[59]}]
set_output_delay -clock clk  0  [get_ports {X_re0[58]}]
set_output_delay -clock clk  0  [get_ports {X_re0[57]}]
set_output_delay -clock clk  0  [get_ports {X_re0[56]}]
set_output_delay -clock clk  0  [get_ports {X_re0[55]}]
set_output_delay -clock clk  0  [get_ports {X_re0[54]}]
set_output_delay -clock clk  0  [get_ports {X_re0[53]}]
set_output_delay -clock clk  0  [get_ports {X_re0[52]}]
set_output_delay -clock clk  0  [get_ports {X_re0[51]}]
set_output_delay -clock clk  0  [get_ports {X_re0[50]}]
set_output_delay -clock clk  0  [get_ports {X_re0[49]}]
set_output_delay -clock clk  0  [get_ports {X_re0[48]}]
set_output_delay -clock clk  0  [get_ports {X_re0[47]}]
set_output_delay -clock clk  0  [get_ports {X_re0[46]}]
set_output_delay -clock clk  0  [get_ports {X_re0[45]}]
set_output_delay -clock clk  0  [get_ports {X_re0[44]}]
set_output_delay -clock clk  0  [get_ports {X_re0[43]}]
set_output_delay -clock clk  0  [get_ports {X_re0[42]}]
set_output_delay -clock clk  0  [get_ports {X_re0[41]}]
set_output_delay -clock clk  0  [get_ports {X_re0[40]}]
set_output_delay -clock clk  0  [get_ports {X_re0[39]}]
set_output_delay -clock clk  0  [get_ports {X_re0[38]}]
set_output_delay -clock clk  0  [get_ports {X_re0[37]}]
set_output_delay -clock clk  0  [get_ports {X_re0[36]}]
set_output_delay -clock clk  0  [get_ports {X_re0[35]}]
set_output_delay -clock clk  0  [get_ports {X_re0[34]}]
set_output_delay -clock clk  0  [get_ports {X_re0[33]}]
set_output_delay -clock clk  0  [get_ports {X_re0[32]}]
set_output_delay -clock clk  0  [get_ports {X_re0[31]}]
set_output_delay -clock clk  0  [get_ports {X_re0[30]}]
set_output_delay -clock clk  0  [get_ports {X_re0[29]}]
set_output_delay -clock clk  0  [get_ports {X_re0[28]}]
set_output_delay -clock clk  0  [get_ports {X_re0[27]}]
set_output_delay -clock clk  0  [get_ports {X_re0[26]}]
set_output_delay -clock clk  0  [get_ports {X_re0[25]}]
set_output_delay -clock clk  0  [get_ports {X_re0[24]}]
set_output_delay -clock clk  0  [get_ports {X_re0[23]}]
set_output_delay -clock clk  0  [get_ports {X_re0[22]}]
set_output_delay -clock clk  0  [get_ports {X_re0[21]}]
set_output_delay -clock clk  0  [get_ports {X_re0[20]}]
set_output_delay -clock clk  0  [get_ports {X_re0[19]}]
set_output_delay -clock clk  0  [get_ports {X_re0[18]}]
set_output_delay -clock clk  0  [get_ports {X_re0[17]}]
set_output_delay -clock clk  0  [get_ports {X_re0[16]}]
set_output_delay -clock clk  0  [get_ports {X_re0[15]}]
set_output_delay -clock clk  0  [get_ports {X_re0[14]}]
set_output_delay -clock clk  0  [get_ports {X_re0[13]}]
set_output_delay -clock clk  0  [get_ports {X_re0[12]}]
set_output_delay -clock clk  0  [get_ports {X_re0[11]}]
set_output_delay -clock clk  0  [get_ports {X_re0[10]}]
set_output_delay -clock clk  0  [get_ports {X_re0[9]}]
set_output_delay -clock clk  0  [get_ports {X_re0[8]}]
set_output_delay -clock clk  0  [get_ports {X_re0[7]}]
set_output_delay -clock clk  0  [get_ports {X_re0[6]}]
set_output_delay -clock clk  0  [get_ports {X_re0[5]}]
set_output_delay -clock clk  0  [get_ports {X_re0[4]}]
set_output_delay -clock clk  0  [get_ports {X_re0[3]}]
set_output_delay -clock clk  0  [get_ports {X_re0[2]}]
set_output_delay -clock clk  0  [get_ports {X_re0[1]}]
set_output_delay -clock clk  0  [get_ports {X_re0[0]}]
set_output_delay -clock clk  0  [get_ports {X_im0[63]}]
set_output_delay -clock clk  0  [get_ports {X_im0[62]}]
set_output_delay -clock clk  0  [get_ports {X_im0[61]}]
set_output_delay -clock clk  0  [get_ports {X_im0[60]}]
set_output_delay -clock clk  0  [get_ports {X_im0[59]}]
set_output_delay -clock clk  0  [get_ports {X_im0[58]}]
set_output_delay -clock clk  0  [get_ports {X_im0[57]}]
set_output_delay -clock clk  0  [get_ports {X_im0[56]}]
set_output_delay -clock clk  0  [get_ports {X_im0[55]}]
set_output_delay -clock clk  0  [get_ports {X_im0[54]}]
set_output_delay -clock clk  0  [get_ports {X_im0[53]}]
set_output_delay -clock clk  0  [get_ports {X_im0[52]}]
set_output_delay -clock clk  0  [get_ports {X_im0[51]}]
set_output_delay -clock clk  0  [get_ports {X_im0[50]}]
set_output_delay -clock clk  0  [get_ports {X_im0[49]}]
set_output_delay -clock clk  0  [get_ports {X_im0[48]}]
set_output_delay -clock clk  0  [get_ports {X_im0[47]}]
set_output_delay -clock clk  0  [get_ports {X_im0[46]}]
set_output_delay -clock clk  0  [get_ports {X_im0[45]}]
set_output_delay -clock clk  0  [get_ports {X_im0[44]}]
set_output_delay -clock clk  0  [get_ports {X_im0[43]}]
set_output_delay -clock clk  0  [get_ports {X_im0[42]}]
set_output_delay -clock clk  0  [get_ports {X_im0[41]}]
set_output_delay -clock clk  0  [get_ports {X_im0[40]}]
set_output_delay -clock clk  0  [get_ports {X_im0[39]}]
set_output_delay -clock clk  0  [get_ports {X_im0[38]}]
set_output_delay -clock clk  0  [get_ports {X_im0[37]}]
set_output_delay -clock clk  0  [get_ports {X_im0[36]}]
set_output_delay -clock clk  0  [get_ports {X_im0[35]}]
set_output_delay -clock clk  0  [get_ports {X_im0[34]}]
set_output_delay -clock clk  0  [get_ports {X_im0[33]}]
set_output_delay -clock clk  0  [get_ports {X_im0[32]}]
set_output_delay -clock clk  0  [get_ports {X_im0[31]}]
set_output_delay -clock clk  0  [get_ports {X_im0[30]}]
set_output_delay -clock clk  0  [get_ports {X_im0[29]}]
set_output_delay -clock clk  0  [get_ports {X_im0[28]}]
set_output_delay -clock clk  0  [get_ports {X_im0[27]}]
set_output_delay -clock clk  0  [get_ports {X_im0[26]}]
set_output_delay -clock clk  0  [get_ports {X_im0[25]}]
set_output_delay -clock clk  0  [get_ports {X_im0[24]}]
set_output_delay -clock clk  0  [get_ports {X_im0[23]}]
set_output_delay -clock clk  0  [get_ports {X_im0[22]}]
set_output_delay -clock clk  0  [get_ports {X_im0[21]}]
set_output_delay -clock clk  0  [get_ports {X_im0[20]}]
set_output_delay -clock clk  0  [get_ports {X_im0[19]}]
set_output_delay -clock clk  0  [get_ports {X_im0[18]}]
set_output_delay -clock clk  0  [get_ports {X_im0[17]}]
set_output_delay -clock clk  0  [get_ports {X_im0[16]}]
set_output_delay -clock clk  0  [get_ports {X_im0[15]}]
set_output_delay -clock clk  0  [get_ports {X_im0[14]}]
set_output_delay -clock clk  0  [get_ports {X_im0[13]}]
set_output_delay -clock clk  0  [get_ports {X_im0[12]}]
set_output_delay -clock clk  0  [get_ports {X_im0[11]}]
set_output_delay -clock clk  0  [get_ports {X_im0[10]}]
set_output_delay -clock clk  0  [get_ports {X_im0[9]}]
set_output_delay -clock clk  0  [get_ports {X_im0[8]}]
set_output_delay -clock clk  0  [get_ports {X_im0[7]}]
set_output_delay -clock clk  0  [get_ports {X_im0[6]}]
set_output_delay -clock clk  0  [get_ports {X_im0[5]}]
set_output_delay -clock clk  0  [get_ports {X_im0[4]}]
set_output_delay -clock clk  0  [get_ports {X_im0[3]}]
set_output_delay -clock clk  0  [get_ports {X_im0[2]}]
set_output_delay -clock clk  0  [get_ports {X_im0[1]}]
set_output_delay -clock clk  0  [get_ports {X_im0[0]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[63]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[62]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[61]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[60]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[59]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[58]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[57]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[56]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[55]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[54]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[53]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[52]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[51]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[50]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[49]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[48]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[47]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[46]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[45]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[44]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[43]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[42]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[41]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[40]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[39]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[38]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[37]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[36]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[35]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[34]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[33]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[32]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[31]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[30]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[29]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[28]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[27]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[26]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[25]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[24]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[23]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[22]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[21]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[20]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[19]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[18]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[17]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[16]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[15]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[14]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[13]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[12]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[11]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[10]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[9]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[8]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[7]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[6]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[5]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[4]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[3]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[2]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[1]}]
set_output_delay -clock clk  0  [get_ports {Y_re0[0]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[63]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[62]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[61]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[60]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[59]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[58]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[57]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[56]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[55]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[54]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[53]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[52]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[51]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[50]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[49]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[48]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[47]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[46]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[45]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[44]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[43]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[42]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[41]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[40]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[39]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[38]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[37]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[36]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[35]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[34]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[33]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[32]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[31]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[30]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[29]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[28]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[27]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[26]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[25]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[24]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[23]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[22]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[21]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[20]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[19]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[18]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[17]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[16]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[15]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[14]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[13]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[12]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[11]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[10]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[9]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[8]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[7]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[6]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[5]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[4]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[3]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[2]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[1]}]
set_output_delay -clock clk  0  [get_ports {Y_im0[0]}]
