 
****************************************
Report : resources
Design : fpr_inv
Version: T-2022.03
Date   : Thu Jun  4 11:51:13 2026
****************************************


Resource Report for this hierarchy
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| u_FPR_RECIP    | DW_lp_piped_fp_recip | sig_width=52 | u_FPR_RECIP (fpr_inv.sv:69) |
        |                | exp_width=11 |                          |
|                |                | ieee_compliance=0 |                     |
|                |                | faithful_round=0 |                      |
|                |                | op_iso_mode=1 |                         |
|                |                | id_width=1 |                            |
|                |                | in_reg=0   |                            |
|                |                | stages=6   |                            |
|                |                | out_reg=0  |                            |
|                |                | no_pm=1    |                            |
|                |                | rst_mode=0 |                            |
=============================================================================


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| u_FPR_RECIP        | DW_lp_piped_fp_recip | rtl            |                |
===============================================================================

1
