###################################################################

# Created by write_sdc on Tue Sep  9 16:28:37 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name Small -library                                       \
sc9_cln40g_base_rvt_ss_typical_max_0p81v_125c
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {z_o[13]}]
set_load -pin_load 0.05 [get_ports {z_o[12]}]
set_load -pin_load 0.05 [get_ports {z_o[11]}]
set_load -pin_load 0.05 [get_ports {z_o[10]}]
set_load -pin_load 0.05 [get_ports {z_o[9]}]
set_load -pin_load 0.05 [get_ports {z_o[8]}]
set_load -pin_load 0.05 [get_ports {z_o[7]}]
set_load -pin_load 0.05 [get_ports {z_o[6]}]
set_load -pin_load 0.05 [get_ports {z_o[5]}]
set_load -pin_load 0.05 [get_ports {z_o[4]}]
set_load -pin_load 0.05 [get_ports {z_o[3]}]
set_load -pin_load 0.05 [get_ports {z_o[2]}]
set_load -pin_load 0.05 [get_ports {z_o[1]}]
set_load -pin_load 0.05 [get_ports {z_o[0]}]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports in_valid]
set_max_capacitance 0.15 [get_ports {x_i[13]}]
set_max_capacitance 0.15 [get_ports {x_i[12]}]
set_max_capacitance 0.15 [get_ports {x_i[11]}]
set_max_capacitance 0.15 [get_ports {x_i[10]}]
set_max_capacitance 0.15 [get_ports {x_i[9]}]
set_max_capacitance 0.15 [get_ports {x_i[8]}]
set_max_capacitance 0.15 [get_ports {x_i[7]}]
set_max_capacitance 0.15 [get_ports {x_i[6]}]
set_max_capacitance 0.15 [get_ports {x_i[5]}]
set_max_capacitance 0.15 [get_ports {x_i[4]}]
set_max_capacitance 0.15 [get_ports {x_i[3]}]
set_max_capacitance 0.15 [get_ports {x_i[2]}]
set_max_capacitance 0.15 [get_ports {x_i[1]}]
set_max_capacitance 0.15 [get_ports {x_i[0]}]
set_max_capacitance 0.15 [get_ports {y_i[13]}]
set_max_capacitance 0.15 [get_ports {y_i[12]}]
set_max_capacitance 0.15 [get_ports {y_i[11]}]
set_max_capacitance 0.15 [get_ports {y_i[10]}]
set_max_capacitance 0.15 [get_ports {y_i[9]}]
set_max_capacitance 0.15 [get_ports {y_i[8]}]
set_max_capacitance 0.15 [get_ports {y_i[7]}]
set_max_capacitance 0.15 [get_ports {y_i[6]}]
set_max_capacitance 0.15 [get_ports {y_i[5]}]
set_max_capacitance 0.15 [get_ports {y_i[4]}]
set_max_capacitance 0.15 [get_ports {y_i[3]}]
set_max_capacitance 0.15 [get_ports {y_i[2]}]
set_max_capacitance 0.15 [get_ports {y_i[1]}]
set_max_capacitance 0.15 [get_ports {y_i[0]}]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports in_valid]
set_max_fanout 10 [get_ports {x_i[13]}]
set_max_fanout 10 [get_ports {x_i[12]}]
set_max_fanout 10 [get_ports {x_i[11]}]
set_max_fanout 10 [get_ports {x_i[10]}]
set_max_fanout 10 [get_ports {x_i[9]}]
set_max_fanout 10 [get_ports {x_i[8]}]
set_max_fanout 10 [get_ports {x_i[7]}]
set_max_fanout 10 [get_ports {x_i[6]}]
set_max_fanout 10 [get_ports {x_i[5]}]
set_max_fanout 10 [get_ports {x_i[4]}]
set_max_fanout 10 [get_ports {x_i[3]}]
set_max_fanout 10 [get_ports {x_i[2]}]
set_max_fanout 10 [get_ports {x_i[1]}]
set_max_fanout 10 [get_ports {x_i[0]}]
set_max_fanout 10 [get_ports {y_i[13]}]
set_max_fanout 10 [get_ports {y_i[12]}]
set_max_fanout 10 [get_ports {y_i[11]}]
set_max_fanout 10 [get_ports {y_i[10]}]
set_max_fanout 10 [get_ports {y_i[9]}]
set_max_fanout 10 [get_ports {y_i[8]}]
set_max_fanout 10 [get_ports {y_i[7]}]
set_max_fanout 10 [get_ports {y_i[6]}]
set_max_fanout 10 [get_ports {y_i[5]}]
set_max_fanout 10 [get_ports {y_i[4]}]
set_max_fanout 10 [get_ports {y_i[3]}]
set_max_fanout 10 [get_ports {y_i[2]}]
set_max_fanout 10 [get_ports {y_i[1]}]
set_max_fanout 10 [get_ports {y_i[0]}]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports in_valid]
set_max_transition 3 [get_ports {x_i[13]}]
set_max_transition 3 [get_ports {x_i[12]}]
set_max_transition 3 [get_ports {x_i[11]}]
set_max_transition 3 [get_ports {x_i[10]}]
set_max_transition 3 [get_ports {x_i[9]}]
set_max_transition 3 [get_ports {x_i[8]}]
set_max_transition 3 [get_ports {x_i[7]}]
set_max_transition 3 [get_ports {x_i[6]}]
set_max_transition 3 [get_ports {x_i[5]}]
set_max_transition 3 [get_ports {x_i[4]}]
set_max_transition 3 [get_ports {x_i[3]}]
set_max_transition 3 [get_ports {x_i[2]}]
set_max_transition 3 [get_ports {x_i[1]}]
set_max_transition 3 [get_ports {x_i[0]}]
set_max_transition 3 [get_ports {y_i[13]}]
set_max_transition 3 [get_ports {y_i[12]}]
set_max_transition 3 [get_ports {y_i[11]}]
set_max_transition 3 [get_ports {y_i[10]}]
set_max_transition 3 [get_ports {y_i[9]}]
set_max_transition 3 [get_ports {y_i[8]}]
set_max_transition 3 [get_ports {y_i[7]}]
set_max_transition 3 [get_ports {y_i[6]}]
set_max_transition 3 [get_ports {y_i[5]}]
set_max_transition 3 [get_ports {y_i[4]}]
set_max_transition 3 [get_ports {y_i[3]}]
set_max_transition 3 [get_ports {y_i[2]}]
set_max_transition 3 [get_ports {y_i[1]}]
set_max_transition 3 [get_ports {y_i[0]}]
create_clock [get_ports clk]  -period 2  -waveform {0 1}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  -max 1  [get_ports in_valid]
set_input_delay -clock clk  -min 0  [get_ports in_valid]
set_input_delay -clock clk  -max 1  [get_ports {x_i[13]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[13]}]
set_input_delay -clock clk  -max 1  [get_ports {x_i[12]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[12]}]
set_input_delay -clock clk  -max 1  [get_ports {x_i[11]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[11]}]
set_input_delay -clock clk  -max 1  [get_ports {x_i[10]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[10]}]
set_input_delay -clock clk  -max 1  [get_ports {x_i[9]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[9]}]
set_input_delay -clock clk  -max 1  [get_ports {x_i[8]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[8]}]
set_input_delay -clock clk  -max 1  [get_ports {x_i[7]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[7]}]
set_input_delay -clock clk  -max 1  [get_ports {x_i[6]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[6]}]
set_input_delay -clock clk  -max 1  [get_ports {x_i[5]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[5]}]
set_input_delay -clock clk  -max 1  [get_ports {x_i[4]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[4]}]
set_input_delay -clock clk  -max 1  [get_ports {x_i[3]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[3]}]
set_input_delay -clock clk  -max 1  [get_ports {x_i[2]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[2]}]
set_input_delay -clock clk  -max 1  [get_ports {x_i[1]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[1]}]
set_input_delay -clock clk  -max 1  [get_ports {x_i[0]}]
set_input_delay -clock clk  -min 0  [get_ports {x_i[0]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[13]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[13]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[12]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[12]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[11]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[11]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[10]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[10]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[9]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[9]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[8]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[8]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[7]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[7]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[6]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[6]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[5]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[5]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[4]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[4]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[3]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[3]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[2]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[2]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[1]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[1]}]
set_input_delay -clock clk  -max 1  [get_ports {y_i[0]}]
set_input_delay -clock clk  -min 0  [get_ports {y_i[0]}]
set_output_delay -clock clk  -max 1  [get_ports out_valid]
set_output_delay -clock clk  -min 0  [get_ports out_valid]
set_output_delay -clock clk  -max 1  [get_ports {z_o[13]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[13]}]
set_output_delay -clock clk  -max 1  [get_ports {z_o[12]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[12]}]
set_output_delay -clock clk  -max 1  [get_ports {z_o[11]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[11]}]
set_output_delay -clock clk  -max 1  [get_ports {z_o[10]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[10]}]
set_output_delay -clock clk  -max 1  [get_ports {z_o[9]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[9]}]
set_output_delay -clock clk  -max 1  [get_ports {z_o[8]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[8]}]
set_output_delay -clock clk  -max 1  [get_ports {z_o[7]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[7]}]
set_output_delay -clock clk  -max 1  [get_ports {z_o[6]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[6]}]
set_output_delay -clock clk  -max 1  [get_ports {z_o[5]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[5]}]
set_output_delay -clock clk  -max 1  [get_ports {z_o[4]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[4]}]
set_output_delay -clock clk  -max 1  [get_ports {z_o[3]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[3]}]
set_output_delay -clock clk  -max 1  [get_ports {z_o[2]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[2]}]
set_output_delay -clock clk  -max 1  [get_ports {z_o[1]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[1]}]
set_output_delay -clock clk  -max 1  [get_ports {z_o[0]}]
set_output_delay -clock clk  -min 0  [get_ports {z_o[0]}]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports in_valid]
set_input_transition -min 0.5  [get_ports in_valid]
set_input_transition -max 0.5  [get_ports {x_i[13]}]
set_input_transition -min 0.5  [get_ports {x_i[13]}]
set_input_transition -max 0.5  [get_ports {x_i[12]}]
set_input_transition -min 0.5  [get_ports {x_i[12]}]
set_input_transition -max 0.5  [get_ports {x_i[11]}]
set_input_transition -min 0.5  [get_ports {x_i[11]}]
set_input_transition -max 0.5  [get_ports {x_i[10]}]
set_input_transition -min 0.5  [get_ports {x_i[10]}]
set_input_transition -max 0.5  [get_ports {x_i[9]}]
set_input_transition -min 0.5  [get_ports {x_i[9]}]
set_input_transition -max 0.5  [get_ports {x_i[8]}]
set_input_transition -min 0.5  [get_ports {x_i[8]}]
set_input_transition -max 0.5  [get_ports {x_i[7]}]
set_input_transition -min 0.5  [get_ports {x_i[7]}]
set_input_transition -max 0.5  [get_ports {x_i[6]}]
set_input_transition -min 0.5  [get_ports {x_i[6]}]
set_input_transition -max 0.5  [get_ports {x_i[5]}]
set_input_transition -min 0.5  [get_ports {x_i[5]}]
set_input_transition -max 0.5  [get_ports {x_i[4]}]
set_input_transition -min 0.5  [get_ports {x_i[4]}]
set_input_transition -max 0.5  [get_ports {x_i[3]}]
set_input_transition -min 0.5  [get_ports {x_i[3]}]
set_input_transition -max 0.5  [get_ports {x_i[2]}]
set_input_transition -min 0.5  [get_ports {x_i[2]}]
set_input_transition -max 0.5  [get_ports {x_i[1]}]
set_input_transition -min 0.5  [get_ports {x_i[1]}]
set_input_transition -max 0.5  [get_ports {x_i[0]}]
set_input_transition -min 0.5  [get_ports {x_i[0]}]
set_input_transition -max 0.5  [get_ports {y_i[13]}]
set_input_transition -min 0.5  [get_ports {y_i[13]}]
set_input_transition -max 0.5  [get_ports {y_i[12]}]
set_input_transition -min 0.5  [get_ports {y_i[12]}]
set_input_transition -max 0.5  [get_ports {y_i[11]}]
set_input_transition -min 0.5  [get_ports {y_i[11]}]
set_input_transition -max 0.5  [get_ports {y_i[10]}]
set_input_transition -min 0.5  [get_ports {y_i[10]}]
set_input_transition -max 0.5  [get_ports {y_i[9]}]
set_input_transition -min 0.5  [get_ports {y_i[9]}]
set_input_transition -max 0.5  [get_ports {y_i[8]}]
set_input_transition -min 0.5  [get_ports {y_i[8]}]
set_input_transition -max 0.5  [get_ports {y_i[7]}]
set_input_transition -min 0.5  [get_ports {y_i[7]}]
set_input_transition -max 0.5  [get_ports {y_i[6]}]
set_input_transition -min 0.5  [get_ports {y_i[6]}]
set_input_transition -max 0.5  [get_ports {y_i[5]}]
set_input_transition -min 0.5  [get_ports {y_i[5]}]
set_input_transition -max 0.5  [get_ports {y_i[4]}]
set_input_transition -min 0.5  [get_ports {y_i[4]}]
set_input_transition -max 0.5  [get_ports {y_i[3]}]
set_input_transition -min 0.5  [get_ports {y_i[3]}]
set_input_transition -max 0.5  [get_ports {y_i[2]}]
set_input_transition -min 0.5  [get_ports {y_i[2]}]
set_input_transition -max 0.5  [get_ports {y_i[1]}]
set_input_transition -min 0.5  [get_ports {y_i[1]}]
set_input_transition -max 0.5  [get_ports {y_i[0]}]
set_input_transition -min 0.5  [get_ports {y_i[0]}]
