 
****************************************
Report : resources
Design : MQ_INTT
Version: T-2022.03
Date   : Tue Sep 16 17:06:54 2025
****************************************


Resource Report for this hierarchy
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_128      | DW_cmp         | width=10   | genblk1[0].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_131       | DW_cmp         | width=10   | genblk1[0].u_RADIX2/lt_152 (RADIX2.v:152) |
| sub_x_132      | DW01_dec       | width=8    | genblk1[0].u_RADIX2/sub_158 (RADIX2.v:158) |
| gte_x_144      | DW_cmp         | width=10   | genblk1[1].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_147       | DW_cmp         | width=10   | genblk1[1].u_RADIX2/lt_152 (RADIX2.v:152) |
| sub_x_148      | DW01_dec       | width=7    | genblk1[1].u_RADIX2/sub_158 (RADIX2.v:158) |
| gte_x_161      | DW_cmp         | width=10   | genblk1[2].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_164       | DW_cmp         | width=10   | genblk1[2].u_RADIX2/lt_152 (RADIX2.v:152) |
| sub_x_165      | DW01_dec       | width=6    | genblk1[2].u_RADIX2/sub_158 (RADIX2.v:158) |
| lt_x_172       | DW_cmp         | width=10   | genblk1[2].u_RADIX2/lt_182 (RADIX2.v:182) |
| gte_x_179      | DW_cmp         | width=10   | genblk1[3].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_182       | DW_cmp         | width=10   | genblk1[3].u_RADIX2/lt_152 (RADIX2.v:152) |
| sub_x_183      | DW01_dec       | width=5    | genblk1[3].u_RADIX2/sub_158 (RADIX2.v:158) |
| lt_x_190       | DW_cmp         | width=10   | genblk1[3].u_RADIX2/lt_182 (RADIX2.v:182) |
| gte_x_197      | DW_cmp         | width=10   | genblk1[4].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_200       | DW_cmp         | width=10   | genblk1[4].u_RADIX2/lt_152 (RADIX2.v:152) |
| sub_x_201      | DW01_dec       | width=4    | genblk1[4].u_RADIX2/sub_158 (RADIX2.v:158) |
| lt_x_208       | DW_cmp         | width=10   | genblk1[4].u_RADIX2/lt_182 (RADIX2.v:182) |
| gte_x_215      | DW_cmp         | width=10   | genblk1[5].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_218       | DW_cmp         | width=10   | genblk1[5].u_RADIX2/lt_152 (RADIX2.v:152) |
| sub_x_219      | DW01_dec       | width=3    | genblk1[5].u_RADIX2/sub_158 (RADIX2.v:158) |
| lt_x_226       | DW_cmp         | width=10   | genblk1[5].u_RADIX2/lt_182 (RADIX2.v:182) |
| gte_x_233      | DW_cmp         | width=10   | genblk1[6].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_236       | DW_cmp         | width=10   | genblk1[6].u_RADIX2/lt_152 (RADIX2.v:152) |
| sub_x_237      | DW01_dec       | width=2    | genblk1[6].u_RADIX2/sub_158 (RADIX2.v:158) |
| add_x_238      | DW01_add       | width=4    | genblk1[6].u_RADIX2/add_159 (RADIX2.v:159) |
| lt_x_244       | DW_cmp         | width=10   | genblk1[6].u_RADIX2/lt_182 (RADIX2.v:182) |
| gte_x_251      | DW_cmp         | width=10   | genblk1[7].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_254       | DW_cmp         | width=10   | genblk1[7].u_RADIX2/lt_152 (RADIX2.v:152) |
| add_x_255      | DW01_add       | width=3    | genblk1[7].u_RADIX2/add_159 (RADIX2.v:159) |
| lt_x_261       | DW_cmp         | width=10   | genblk1[7].u_RADIX2/lt_182 (RADIX2.v:182) |
| gte_x_268      | DW_cmp         | width=10   | genblk1[8].u_RADIX2/gte_139 (RADIX2.v:139) |
| lt_x_271       | DW_cmp         | width=10   | genblk1[8].u_RADIX2/lt_152 (RADIX2.v:152) |
| sub_x_272      | DW01_dec       | width=2    | genblk1[8].u_RADIX2/sub_158 (RADIX2.v:158) |
| add_x_273      | DW01_inc       | width=3    | genblk1[8].u_RADIX2/add_159 (RADIX2.v:159) |
| lt_x_279       | DW_cmp         | width=10   | genblk1[8].u_RADIX2/lt_182 (RADIX2.v:182) |
| mult_x_283     | DW_mult_uns    | a_width=16 | genblk1[0].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_285     | DW_mult_uns    | a_width=16 | genblk1[8].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_287     | DW_mult_uns    | a_width=16 | genblk1[7].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_289     | DW_mult_uns    | a_width=16 | genblk1[6].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_291     | DW_mult_uns    | a_width=16 | genblk1[5].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_293     | DW_mult_uns    | a_width=16 | genblk1[4].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_295     | DW_mult_uns    | a_width=16 | genblk1[3].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_297     | DW_mult_uns    | a_width=16 | genblk1[2].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| mult_x_299     | DW_mult_uns    | a_width=16 | genblk1[1].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154) |
       | b_width=14 |                            |
| add_x_129      | DW01_inc       | width=10   | genblk1[0].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[0].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_145      | DW01_inc       | width=10   | genblk1[1].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[1].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_162      | DW01_inc       | width=10   | genblk1[2].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[2].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_180      | DW01_inc       | width=10   | genblk1[3].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[3].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_198      | DW01_inc       | width=10   | genblk1[4].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[4].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_216      | DW01_inc       | width=10   | genblk1[5].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[5].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_234      | DW01_inc       | width=10   | genblk1[6].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[6].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_252      | DW01_inc       | width=10   | genblk1[7].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[7].u_RADIX2/add_142 (RADIX2.v:142) |
| add_x_269      | DW01_inc       | width=10   | genblk1[8].u_RADIX2/add_140 (RADIX2.v:140) |
 |                |            | genblk1[8].u_RADIX2/add_142 (RADIX2.v:142) |
| DP_OP_532J1_122_2608            |            |                            |
|                | DP_OP_532J1_122_2608 |      |                            |
| DP_OP_533J1_123_6698            |            |                            |
|                | DP_OP_533J1_123_6698 |      |                            |
| DP_OP_534J1_124_2608            |            |                            |
|                | DP_OP_534J1_124_2608 |      |                            |
| DP_OP_535J1_125_6698            |            |                            |
|                | DP_OP_535J1_125_6698 |      |                            |
| DP_OP_536J1_126_2608            |            |                            |
|                | DP_OP_536J1_126_2608 |      |                            |
| DP_OP_537J1_127_6698            |            |                            |
|                | DP_OP_537J1_127_6698 |      |                            |
| DP_OP_538J1_128_2608            |            |                            |
|                | DP_OP_538J1_128_2608 |      |                            |
| DP_OP_539J1_129_6698            |            |                            |
|                | DP_OP_539J1_129_6698 |      |                            |
| DP_OP_540J1_130_2608            |            |                            |
|                | DP_OP_540J1_130_2608 |      |                            |
| DP_OP_541J1_131_6698            |            |                            |
|                | DP_OP_541J1_131_6698 |      |                            |
| DP_OP_542J1_132_2608            |            |                            |
|                | DP_OP_542J1_132_2608 |      |                            |
| DP_OP_543J1_133_6698            |            |                            |
|                | DP_OP_543J1_133_6698 |      |                            |
| DP_OP_544J1_134_2608            |            |                            |
|                | DP_OP_544J1_134_2608 |      |                            |
| DP_OP_545J1_135_6698            |            |                            |
|                | DP_OP_545J1_135_6698 |      |                            |
| DP_OP_546J1_136_2608            |            |                            |
|                | DP_OP_546J1_136_2608 |      |                            |
| DP_OP_547J1_137_6698            |            |                            |
|                | DP_OP_547J1_137_6698 |      |                            |
| DP_OP_548J1_138_2608            |            |                            |
|                | DP_OP_548J1_138_2608 |      |                            |
| DP_OP_549J1_139_6698            |            |                            |
|                | DP_OP_549J1_139_6698 |      |                            |
| DP_OP_550J1_140_8553            |            |                            |
|                | DP_OP_550J1_140_8553 |      |                            |
| DP_OP_551J1_141_553             |            |                            |
|                | DP_OP_551J1_141_553 |       |                            |
| DP_OP_552J1_142_8553            |            |                            |
|                | DP_OP_552J1_142_8553 |      |                            |
| DP_OP_553J1_143_553             |            |                            |
|                | DP_OP_553J1_143_553 |       |                            |
| DP_OP_554J1_144_8553            |            |                            |
|                | DP_OP_554J1_144_8553 |      |                            |
| DP_OP_555J1_145_553             |            |                            |
|                | DP_OP_555J1_145_553 |       |                            |
| DP_OP_556J1_146_8553            |            |                            |
|                | DP_OP_556J1_146_8553 |      |                            |
| DP_OP_557J1_147_553             |            |                            |
|                | DP_OP_557J1_147_553 |       |                            |
| DP_OP_558J1_148_8553            |            |                            |
|                | DP_OP_558J1_148_8553 |      |                            |
| DP_OP_559J1_149_553             |            |                            |
|                | DP_OP_559J1_149_553 |       |                            |
| DP_OP_560J1_150_8553            |            |                            |
|                | DP_OP_560J1_150_8553 |      |                            |
| DP_OP_561J1_151_553             |            |                            |
|                | DP_OP_561J1_151_553 |       |                            |
| DP_OP_562J1_152_8553            |            |                            |
|                | DP_OP_562J1_152_8553 |      |                            |
| DP_OP_563J1_153_553             |            |                            |
|                | DP_OP_563J1_153_553 |       |                            |
| DP_OP_564J1_154_8553            |            |                            |
|                | DP_OP_564J1_154_8553 |      |                            |
| DP_OP_565J1_155_553             |            |                            |
|                | DP_OP_565J1_155_553 |       |                            |
| DP_OP_566J1_156_8553            |            |                            |
|                | DP_OP_566J1_156_8553 |      |                            |
| DP_OP_567J1_157_553             |            |                            |
|                | DP_OP_567J1_157_553 |       |                            |
=============================================================================

Datapath Report for DP_OP_532J1_122_2608
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_532J1_122_2608 | genblk1[0].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[0].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T488  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T488 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_533J1_123_6698
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_533J1_123_6698 | genblk1[0].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[0].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[0].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T354  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T486  | IFO  | Signed   | 14    | T354[13:0]                               |
| O1    | PO   | Signed   | 14    | T486 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T354 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_534J1_124_2608
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_534J1_124_2608 | genblk1[1].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[1].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T520  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T520 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_535J1_125_6698
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_535J1_125_6698 | genblk1[1].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[1].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[1].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T380  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T504  | IFO  | Signed   | 14    | T380[13:0]                               |
| O1    | PO   | Signed   | 14    | T504 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T380 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_536J1_126_2608
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_536J1_126_2608 | genblk1[2].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[2].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T518  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T518 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_537J1_127_6698
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_537J1_127_6698 | genblk1[2].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[2].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[2].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T377  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T502  | IFO  | Signed   | 14    | T377[13:0]                               |
| O1    | PO   | Signed   | 14    | T502 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T377 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_538J1_128_2608
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_538J1_128_2608 | genblk1[3].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[3].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T516  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T516 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_539J1_129_6698
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_539J1_129_6698 | genblk1[3].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[3].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[3].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T374  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T500  | IFO  | Signed   | 14    | T374[13:0]                               |
| O1    | PO   | Signed   | 14    | T500 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T374 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_540J1_130_2608
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_540J1_130_2608 | genblk1[4].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[4].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T514  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T514 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_541J1_131_6698
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_541J1_131_6698 | genblk1[4].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[4].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[4].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T371  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T498  | IFO  | Signed   | 14    | T371[13:0]                               |
| O1    | PO   | Signed   | 14    | T498 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T371 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_542J1_132_2608
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_542J1_132_2608 | genblk1[5].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[5].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T512  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T512 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_543J1_133_6698
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_543J1_133_6698 | genblk1[5].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[5].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[5].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T368  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T496  | IFO  | Signed   | 14    | T368[13:0]                               |
| O1    | PO   | Signed   | 14    | T496 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T368 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_544J1_134_2608
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_544J1_134_2608 | genblk1[6].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[6].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T510  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T510 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_545J1_135_6698
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_545J1_135_6698 | genblk1[6].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[6].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[6].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T365  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T494  | IFO  | Signed   | 14    | T365[13:0]                               |
| O1    | PO   | Signed   | 14    | T494 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T365 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_546J1_136_2608
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_546J1_136_2608 | genblk1[7].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[7].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T508  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T508 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_547J1_137_6698
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_547J1_137_6698 | genblk1[7].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[7].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[7].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T362  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T492  | IFO  | Signed   | 14    | T362[13:0]                               |
| O1    | PO   | Signed   | 14    | T492 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T362 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_548J1_138_2608
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_548J1_138_2608 | genblk1[8].u_RADIX2/u_BUTTERFLY/u_mq_sub/sub_86 (MQ.v:86) |
                 | genblk1[8].u_RADIX2/u_BUTTERFLY/u_mq_sub/add_87_aco (MQ.v:87) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T506  | IFO  | Signed   | 14    | O1[13:0]                                 |
| O1    | PO   | Signed   | 15    | I1 - I2 (MQ.v:86)                        |
| O2    | PO   | Signed   | 14    | T506 + I3 (MQ.v:87)                      |
==============================================================================

Datapath Report for DP_OP_549J1_139_6698
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_549J1_139_6698 | genblk1[8].u_RADIX2/u_BUTTERFLY/u_mq_add/add_42 (MQ.v:42) |
                 | genblk1[8].u_RADIX2/u_BUTTERFLY/u_mq_add/sub_43_aco (MQ.v:43) |
             | genblk1[8].u_RADIX2/u_BUTTERFLY/u_mq_add/gte_44 (MQ.v:44) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T359  | IFO  | Unsigned | 15    | I1 + I2 (MQ.v:42)                        |
| T490  | IFO  | Signed   | 14    | T359[13:0]                               |
| O1    | PO   | Signed   | 14    | T490 - I3 (MQ.v:43)                      |
| O2    | PO   | Unsigned | 1     | T359 >= $unsigned(14'b11000000000001) (MQ.v:44) |
==============================================================================

Datapath Report for DP_OP_550J1_140_8553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_550J1_140_8553 | genblk1[0].u_RADIX2/u_MQ_MONTYMUL/mult_152 (MQ.v:152) |
                     | genblk1[0].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T442  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T442 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_551J1_141_553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_551J1_141_553  | genblk1[0].u_RADIX2/u_MQ_MONTYMUL/add_162 (MQ.v:162) |
                      | genblk1[0].u_RADIX2/u_MQ_MONTYMUL/gte_172 (MQ.v:172) |
                      | genblk1[0].u_RADIX2/u_MQ_MONTYMUL/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T294  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T443  | IFO  | Unsigned | 15    | T294[30:16]                              |
| T444  | IFO  | Signed   | 14    | T294[29:16]                              |
| O1    | PO   | Unsigned | 1     | T443 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T444 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_552J1_142_8553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_552J1_142_8553 | genblk1[8].u_RADIX2/u_MQ_MONTYMUL/mult_152 (MQ.v:152) |
                     | genblk1[8].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T447  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T447 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_553J1_143_553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_553J1_143_553  | genblk1[8].u_RADIX2/u_MQ_MONTYMUL/add_162 (MQ.v:162) |
                      | genblk1[8].u_RADIX2/u_MQ_MONTYMUL/gte_172 (MQ.v:172) |
                      | genblk1[8].u_RADIX2/u_MQ_MONTYMUL/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T301  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T448  | IFO  | Unsigned | 15    | T301[30:16]                              |
| T449  | IFO  | Signed   | 14    | T301[29:16]                              |
| O1    | PO   | Unsigned | 1     | T448 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T449 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_554J1_144_8553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_554J1_144_8553 | genblk1[7].u_RADIX2/u_MQ_MONTYMUL/mult_152 (MQ.v:152) |
                     | genblk1[7].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T452  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T452 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_555J1_145_553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_555J1_145_553  | genblk1[7].u_RADIX2/u_MQ_MONTYMUL/add_162 (MQ.v:162) |
                      | genblk1[7].u_RADIX2/u_MQ_MONTYMUL/gte_172 (MQ.v:172) |
                      | genblk1[7].u_RADIX2/u_MQ_MONTYMUL/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T308  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T453  | IFO  | Unsigned | 15    | T308[30:16]                              |
| T454  | IFO  | Signed   | 14    | T308[29:16]                              |
| O1    | PO   | Unsigned | 1     | T453 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T454 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_556J1_146_8553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_556J1_146_8553 | genblk1[6].u_RADIX2/u_MQ_MONTYMUL/mult_152 (MQ.v:152) |
                     | genblk1[6].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T457  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T457 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_557J1_147_553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_557J1_147_553  | genblk1[6].u_RADIX2/u_MQ_MONTYMUL/add_162 (MQ.v:162) |
                      | genblk1[6].u_RADIX2/u_MQ_MONTYMUL/gte_172 (MQ.v:172) |
                      | genblk1[6].u_RADIX2/u_MQ_MONTYMUL/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T315  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T458  | IFO  | Unsigned | 15    | T315[30:16]                              |
| T459  | IFO  | Signed   | 14    | T315[29:16]                              |
| O1    | PO   | Unsigned | 1     | T458 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T459 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_558J1_148_8553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_558J1_148_8553 | genblk1[5].u_RADIX2/u_MQ_MONTYMUL/mult_152 (MQ.v:152) |
                     | genblk1[5].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T462  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T462 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_559J1_149_553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_559J1_149_553  | genblk1[5].u_RADIX2/u_MQ_MONTYMUL/add_162 (MQ.v:162) |
                      | genblk1[5].u_RADIX2/u_MQ_MONTYMUL/gte_172 (MQ.v:172) |
                      | genblk1[5].u_RADIX2/u_MQ_MONTYMUL/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T322  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T463  | IFO  | Unsigned | 15    | T322[30:16]                              |
| T464  | IFO  | Signed   | 14    | T322[29:16]                              |
| O1    | PO   | Unsigned | 1     | T463 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T464 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_560J1_150_8553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_560J1_150_8553 | genblk1[4].u_RADIX2/u_MQ_MONTYMUL/mult_152 (MQ.v:152) |
                     | genblk1[4].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T467  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T467 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_561J1_151_553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_561J1_151_553  | genblk1[4].u_RADIX2/u_MQ_MONTYMUL/add_162 (MQ.v:162) |
                      | genblk1[4].u_RADIX2/u_MQ_MONTYMUL/gte_172 (MQ.v:172) |
                      | genblk1[4].u_RADIX2/u_MQ_MONTYMUL/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T329  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T468  | IFO  | Unsigned | 15    | T329[30:16]                              |
| T469  | IFO  | Signed   | 14    | T329[29:16]                              |
| O1    | PO   | Unsigned | 1     | T468 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T469 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_562J1_152_8553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_562J1_152_8553 | genblk1[3].u_RADIX2/u_MQ_MONTYMUL/mult_152 (MQ.v:152) |
                     | genblk1[3].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T472  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T472 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_563J1_153_553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_563J1_153_553  | genblk1[3].u_RADIX2/u_MQ_MONTYMUL/add_162 (MQ.v:162) |
                      | genblk1[3].u_RADIX2/u_MQ_MONTYMUL/gte_172 (MQ.v:172) |
                      | genblk1[3].u_RADIX2/u_MQ_MONTYMUL/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T336  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T473  | IFO  | Unsigned | 15    | T336[30:16]                              |
| T474  | IFO  | Signed   | 14    | T336[29:16]                              |
| O1    | PO   | Unsigned | 1     | T473 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T474 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_564J1_154_8553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_564J1_154_8553 | genblk1[2].u_RADIX2/u_MQ_MONTYMUL/mult_152 (MQ.v:152) |
                     | genblk1[2].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T477  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T477 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_565J1_155_553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_565J1_155_553  | genblk1[2].u_RADIX2/u_MQ_MONTYMUL/add_162 (MQ.v:162) |
                      | genblk1[2].u_RADIX2/u_MQ_MONTYMUL/gte_172 (MQ.v:172) |
                      | genblk1[2].u_RADIX2/u_MQ_MONTYMUL/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T343  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T478  | IFO  | Unsigned | 15    | T343[30:16]                              |
| T479  | IFO  | Signed   | 14    | T343[29:16]                              |
| O1    | PO   | Unsigned | 1     | T478 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T479 - I3 (MQ.v:173)                     |
==============================================================================

Datapath Report for DP_OP_566J1_156_8553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_566J1_156_8553 | genblk1[1].u_RADIX2/u_MQ_MONTYMUL/mult_152 (MQ.v:152) |
                     | genblk1[1].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 14    |                                          |
| I2    | PI   | Unsigned | 14    |                                          |
| T482  | IFO  | Signed   | 16    | O1[15:0]                                 |
| O1    | PO   | Unsigned | 28    | I1 * I2 (MQ.v:152)                       |
| O2    | PO   | Unsigned | 16    | T482 * $unsigned(14'b10111111111111) (MQ.v:153) |
==============================================================================

Datapath Report for DP_OP_567J1_157_553
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_567J1_157_553  | genblk1[1].u_RADIX2/u_MQ_MONTYMUL/add_162 (MQ.v:162) |
                      | genblk1[1].u_RADIX2/u_MQ_MONTYMUL/gte_172 (MQ.v:172) |
                      | genblk1[1].u_RADIX2/u_MQ_MONTYMUL/sub_173_aco (MQ.v:173) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 28    |                                          |
| I2    | PI   | Unsigned | 30    |                                          |
| I3    | PI   | Signed   | 13    |                                          |
| T350  | IFO  | Unsigned | 31    | I1 + I2 (MQ.v:162)                       |
| T483  | IFO  | Unsigned | 15    | T350[30:16]                              |
| T484  | IFO  | Signed   | 14    | T350[29:16]                              |
| O1    | PO   | Unsigned | 1     | T483 >= $unsigned(14'b11000000000001) (MQ.v:172) |
| O2    | PO   | Signed   | 14    | T484 - I3 (MQ.v:173)                     |
==============================================================================


Datapath Extraction Report

Information: Operator associated with resources 'genblk1[0].u_RADIX2/sub_158 (RADIX2.v:158)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[0].u_RADIX2/add_159 (RADIX2.v:159)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[1].u_RADIX2/sub_158 (RADIX2.v:158)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[1].u_RADIX2/add_159 (RADIX2.v:159)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[2].u_RADIX2/sub_158 (RADIX2.v:158)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[2].u_RADIX2/add_159 (RADIX2.v:159)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[3].u_RADIX2/sub_158 (RADIX2.v:158)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[3].u_RADIX2/add_159 (RADIX2.v:159)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[4].u_RADIX2/sub_158 (RADIX2.v:158)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[4].u_RADIX2/add_159 (RADIX2.v:159)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[5].u_RADIX2/sub_158 (RADIX2.v:158)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[5].u_RADIX2/add_159 (RADIX2.v:159)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[6].u_RADIX2/sub_158 (RADIX2.v:158)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[6].u_RADIX2/add_159 (RADIX2.v:159)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[8].u_RADIX2/sub_158 (RADIX2.v:158)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch to operator of resources 'genblk1[8].u_RADIX2/add_159 (RADIX2.v:159)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[8].u_RADIX2/sub_158 (RADIX2.v:158)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[0].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[0].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[8].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[8].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[7].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[7].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[6].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[6].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[5].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[5].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[4].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[4].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[3].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[3].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[2].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[2].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[1].u_RADIX2/u_MQ_MONTYMUL/mult_153 (MQ.v:153)' in design 'MQ_INTT' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[1].u_RADIX2/u_MQ_MONTYMUL/mult_154 (MQ.v:154)'.  (HDL-120)


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| gte_x_128          | DW_cmp           | apparch (area)     |                |
| lt_x_131           | DW_cmp           | apparch (area)     |                |
| sub_x_132          | DW01_dec         | apparch (area)     |                |
| gte_x_144          | DW_cmp           | apparch (area)     |                |
| lt_x_147           | DW_cmp           | apparch (area)     |                |
| sub_x_148          | DW01_dec         | apparch (area)     |                |
| gte_x_161          | DW_cmp           | apparch (area)     |                |
| lt_x_164           | DW_cmp           | apparch (area)     |                |
| sub_x_165          | DW01_dec         | apparch (area)     |                |
| lt_x_172           | DW_cmp           | apparch (area)     |                |
| gte_x_179          | DW_cmp           | apparch (area)     |                |
| lt_x_182           | DW_cmp           | apparch (area)     |                |
| sub_x_183          | DW01_dec         | apparch (area)     |                |
| lt_x_190           | DW_cmp           | apparch (area)     |                |
| gte_x_197          | DW_cmp           | apparch (area)     |                |
| lt_x_200           | DW_cmp           | apparch (area)     |                |
| sub_x_201          | DW01_dec         | apparch (area)     |                |
| lt_x_208           | DW_cmp           | apparch (area)     |                |
| gte_x_215          | DW_cmp           | apparch (area)     |                |
| lt_x_218           | DW_cmp           | apparch (area)     |                |
| sub_x_219          | DW01_dec         | apparch (area)     |                |
| lt_x_226           | DW_cmp           | apparch (area)     |                |
| gte_x_233          | DW_cmp           | apparch (area)     |                |
| lt_x_236           | DW_cmp           | apparch (area)     |                |
| sub_x_237          | DW01_dec         | apparch (area)     |                |
| add_x_238          | DW01_add         | apparch (area)     |                |
| lt_x_244           | DW_cmp           | apparch (area)     |                |
| gte_x_251          | DW_cmp           | apparch (area)     |                |
| lt_x_254           | DW_cmp           | apparch (area)     |                |
| add_x_255          | DW01_add         | apparch (area)     |                |
| lt_x_261           | DW_cmp           | apparch (area)     |                |
| gte_x_268          | DW_cmp           | apparch (area)     |                |
| lt_x_271           | DW_cmp           | apparch (area)     |                |
| sub_x_272          | DW01_dec         | apparch (area)     |                |
| add_x_273          | DW01_inc         | apparch (area)     |                |
| lt_x_279           | DW_cmp           | apparch (area)     |                |
| mult_x_283         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_285         | DW_mult_uns      | pparch (speed)     |                |
| mult_x_287         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_289         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_291         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_293         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_295         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_297         | DW_mult_uns      | pparch (area,speed)                 |
| mult_x_299         | DW_mult_uns      | pparch (area,speed)                 |
| add_x_129          | DW01_inc         | apparch (area)     |                |
| add_x_145          | DW01_inc         | apparch (area)     |                |
| add_x_162          | DW01_inc         | apparch (area)     |                |
| add_x_180          | DW01_inc         | apparch (area)     |                |
| add_x_198          | DW01_inc         | apparch (area)     |                |
| add_x_216          | DW01_inc         | apparch (area)     |                |
| add_x_234          | DW01_inc         | apparch (area)     |                |
| add_x_252          | DW01_inc         | apparch (area)     |                |
| add_x_269          | DW01_inc         | apparch (area)     |                |
| DP_OP_532J1_122_2608                  |                    |                |
|                    | DP_OP_532J1_122_2608 | str (area,speed)                |
| DP_OP_533J1_123_6698                  |                    |                |
|                    | DP_OP_533J1_123_6698 | str (area,speed)                |
| DP_OP_534J1_124_2608                  |                    |                |
|                    | DP_OP_534J1_124_2608 | str (area,speed)                |
| DP_OP_535J1_125_6698                  |                    |                |
|                    | DP_OP_535J1_125_6698 | str (area,speed)                |
| DP_OP_536J1_126_2608                  |                    |                |
|                    | DP_OP_536J1_126_2608 | str (area,speed)                |
| DP_OP_537J1_127_6698                  |                    |                |
|                    | DP_OP_537J1_127_6698 | str (area,speed)                |
| DP_OP_538J1_128_2608                  |                    |                |
|                    | DP_OP_538J1_128_2608 | str (area,speed)                |
| DP_OP_539J1_129_6698                  |                    |                |
|                    | DP_OP_539J1_129_6698 | str (area,speed)                |
| DP_OP_540J1_130_2608                  |                    |                |
|                    | DP_OP_540J1_130_2608 | str (area,speed)                |
| DP_OP_541J1_131_6698                  |                    |                |
|                    | DP_OP_541J1_131_6698 | str (area,speed)                |
| DP_OP_542J1_132_2608                  |                    |                |
|                    | DP_OP_542J1_132_2608 | str (area,speed)                |
| DP_OP_543J1_133_6698                  |                    |                |
|                    | DP_OP_543J1_133_6698 | str (area,speed)                |
| DP_OP_544J1_134_2608                  |                    |                |
|                    | DP_OP_544J1_134_2608 | str (area,speed)                |
| DP_OP_545J1_135_6698                  |                    |                |
|                    | DP_OP_545J1_135_6698 | str (area,speed)                |
| DP_OP_546J1_136_2608                  |                    |                |
|                    | DP_OP_546J1_136_2608 | str (area,speed)                |
| DP_OP_547J1_137_6698                  |                    |                |
|                    | DP_OP_547J1_137_6698 | str (area,speed)                |
| DP_OP_548J1_138_2608                  |                    |                |
|                    | DP_OP_548J1_138_2608 | str (area,speed)                |
| DP_OP_549J1_139_6698                  |                    |                |
|                    | DP_OP_549J1_139_6698 | str (area,speed)                |
| DP_OP_550J1_140_8553                  |                    |                |
|                    | DP_OP_550J1_140_8553 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_551J1_141_553                   |                    |                |
|                    | DP_OP_551J1_141_553 | str (area,speed)                 |
| DP_OP_552J1_142_8553                  |                    |                |
|                    | DP_OP_552J1_142_8553 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_553J1_143_553                   |                    |                |
|                    | DP_OP_553J1_143_553 | str (area,speed)                 |
| DP_OP_554J1_144_8553                  |                    |                |
|                    | DP_OP_554J1_144_8553 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_555J1_145_553                   |                    |                |
|                    | DP_OP_555J1_145_553 | str (area,speed)                 |
| DP_OP_556J1_146_8553                  |                    |                |
|                    | DP_OP_556J1_146_8553 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_557J1_147_553                   |                    |                |
|                    | DP_OP_557J1_147_553 | str (area,speed)                 |
| DP_OP_558J1_148_8553                  |                    |                |
|                    | DP_OP_558J1_148_8553 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_559J1_149_553                   |                    |                |
|                    | DP_OP_559J1_149_553 | str (area,speed)                 |
| DP_OP_560J1_150_8553                  |                    |                |
|                    | DP_OP_560J1_150_8553 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_561J1_151_553                   |                    |                |
|                    | DP_OP_561J1_151_553 | str (area,speed)                 |
| DP_OP_562J1_152_8553                  |                    |                |
|                    | DP_OP_562J1_152_8553 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_563J1_153_553                   |                    |                |
|                    | DP_OP_563J1_153_553 | str (area,speed)                 |
| DP_OP_564J1_154_8553                  |                    |                |
|                    | DP_OP_564J1_154_8553 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_565J1_155_553                   |                    |                |
|                    | DP_OP_565J1_155_553 | str (area,speed)                 |
| DP_OP_566J1_156_8553                  |                    |                |
|                    | DP_OP_566J1_156_8553 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_567J1_157_553                   |                    |                |
|                    | DP_OP_567J1_157_553 | str (area,speed)                 |
===============================================================================

1
