 
****************************************
Report : resources
Design : MODP_NTT2
Version: T-2022.03
Date   : Wed Sep 24 01:28:10 2025
****************************************


Resource Report for this hierarchy in file ../01_RTL/MODP_NTT2.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| ash_55         | DW_leftsh      | A_width=10 | genblk1[0].u_RADIX2/sll_144 (RADIX2.v:144) |
 |                | SH_width=4 |                            |
| sub_x_56       | DW01_dec       | width=4    | genblk1[0].u_RADIX2/sub_145 (RADIX2.v:145) |
| ash_57         | DW_leftsh      | A_width=9  | genblk1[0].u_RADIX2/sll_146 (RADIX2.v:146) |
 |                | SH_width=4 |                            |
| sub_x_62       | DW01_dec       | width=11   | genblk1[0].u_RADIX2/sub_179 (RADIX2.v:179) |
| gte_x_63       | DW_cmp         | width=32   | genblk1[0].u_RADIX2/gte_179 (RADIX2.v:179) |
| sub_x_71       | DW01_sub       | width=11   | genblk1[0].u_RADIX2/sub_212 (RADIX2.v:212) |
| lt_x_72        | DW_cmp         | width=32   | genblk1[0].u_RADIX2/lt_212 (RADIX2.v:212) |
| add_x_73       | DW01_inc       | width=9    | genblk1[0].u_RADIX2/add_218 (RADIX2.v:218) |
| add_x_74       | DW01_add       | width=10   | genblk1[0].u_RADIX2/add_219 (RADIX2.v:219) |
| sub_x_80       | DW01_dec       | width=11   | genblk1[0].u_RADIX2/sub_255 (RADIX2.v:255) |
| gte_x_83       | DW_cmp         | width=10   | genblk1[0].u_RADIX2/gte_289 (RADIX2.v:289) |
| ash_87         | DW_leftsh      | A_width=10 | genblk1[1].u_RADIX2/sll_144 (RADIX2.v:144) |
 |                | SH_width=4 |                            |
| ash_88         | DW_leftsh      | A_width=9  | genblk1[1].u_RADIX2/sll_146 (RADIX2.v:146) |
 |                | SH_width=4 |                            |
| sub_x_93       | DW01_dec       | width=11   | genblk1[1].u_RADIX2/sub_179 (RADIX2.v:179) |
| gte_x_94       | DW_cmp         | width=32   | genblk1[1].u_RADIX2/gte_179 (RADIX2.v:179) |
| sub_x_102      | DW01_sub       | width=11   | genblk1[1].u_RADIX2/sub_212 (RADIX2.v:212) |
| lt_x_103       | DW_cmp         | width=32   | genblk1[1].u_RADIX2/lt_212 (RADIX2.v:212) |
| add_x_104      | DW01_add       | width=10   | genblk1[1].u_RADIX2/add_219 (RADIX2.v:219) |
| eq_x_107       | DW_cmp         | width=2    | genblk1[1].u_RADIX2/eq_227 (RADIX2.v:227) |
| eq_x_108       | DW_cmp         | width=2    | genblk1[1].u_RADIX2/eq_234 (RADIX2.v:234) |
| sub_x_114      | DW01_dec       | width=11   | genblk1[1].u_RADIX2/sub_255 (RADIX2.v:255) |
| gte_x_117      | DW_cmp         | width=10   | genblk1[1].u_RADIX2/gte_289 (RADIX2.v:289) |
| ash_121        | DW_leftsh      | A_width=10 | genblk1[2].u_RADIX2/sll_144 (RADIX2.v:144) |
 |                | SH_width=4 |                            |
| ash_122        | DW_leftsh      | A_width=9  | genblk1[2].u_RADIX2/sll_146 (RADIX2.v:146) |
 |                | SH_width=4 |                            |
| sub_x_126      | DW01_dec       | width=11   | genblk1[2].u_RADIX2/sub_179 (RADIX2.v:179) |
| gte_x_127      | DW_cmp         | width=32   | genblk1[2].u_RADIX2/gte_179 (RADIX2.v:179) |
| sub_x_135      | DW01_sub       | width=11   | genblk1[2].u_RADIX2/sub_212 (RADIX2.v:212) |
| lt_x_136       | DW_cmp         | width=32   | genblk1[2].u_RADIX2/lt_212 (RADIX2.v:212) |
| eq_x_139       | DW_cmp         | width=3    | genblk1[2].u_RADIX2/eq_227 (RADIX2.v:227) |
| eq_x_140       | DW_cmp         | width=3    | genblk1[2].u_RADIX2/eq_234 (RADIX2.v:234) |
| sub_x_146      | DW01_dec       | width=11   | genblk1[2].u_RADIX2/sub_255 (RADIX2.v:255) |
| gte_x_149      | DW_cmp         | width=10   | genblk1[2].u_RADIX2/gte_289 (RADIX2.v:289) |
| ash_153        | DW_leftsh      | A_width=10 | genblk1[3].u_RADIX2/sll_144 (RADIX2.v:144) |
 |                | SH_width=4 |                            |
| ash_154        | DW_leftsh      | A_width=9  | genblk1[3].u_RADIX2/sll_146 (RADIX2.v:146) |
 |                | SH_width=4 |                            |
| sub_x_158      | DW01_dec       | width=11   | genblk1[3].u_RADIX2/sub_179 (RADIX2.v:179) |
| gte_x_159      | DW_cmp         | width=32   | genblk1[3].u_RADIX2/gte_179 (RADIX2.v:179) |
| sub_x_167      | DW01_sub       | width=11   | genblk1[3].u_RADIX2/sub_212 (RADIX2.v:212) |
| lt_x_168       | DW_cmp         | width=32   | genblk1[3].u_RADIX2/lt_212 (RADIX2.v:212) |
| eq_x_171       | DW_cmp         | width=4    | genblk1[3].u_RADIX2/eq_227 (RADIX2.v:227) |
| eq_x_172       | DW_cmp         | width=4    | genblk1[3].u_RADIX2/eq_234 (RADIX2.v:234) |
| sub_x_178      | DW01_dec       | width=11   | genblk1[3].u_RADIX2/sub_255 (RADIX2.v:255) |
| gte_x_181      | DW_cmp         | width=10   | genblk1[3].u_RADIX2/gte_289 (RADIX2.v:289) |
| ash_185        | DW_leftsh      | A_width=10 | genblk1[4].u_RADIX2/sll_144 (RADIX2.v:144) |
 |                | SH_width=4 |                            |
| ash_186        | DW_leftsh      | A_width=9  | genblk1[4].u_RADIX2/sll_146 (RADIX2.v:146) |
 |                | SH_width=4 |                            |
| sub_x_190      | DW01_dec       | width=11   | genblk1[4].u_RADIX2/sub_179 (RADIX2.v:179) |
| gte_x_191      | DW_cmp         | width=32   | genblk1[4].u_RADIX2/gte_179 (RADIX2.v:179) |
| sub_x_199      | DW01_sub       | width=11   | genblk1[4].u_RADIX2/sub_212 (RADIX2.v:212) |
| lt_x_200       | DW_cmp         | width=32   | genblk1[4].u_RADIX2/lt_212 (RADIX2.v:212) |
| eq_x_203       | DW_cmp         | width=5    | genblk1[4].u_RADIX2/eq_227 (RADIX2.v:227) |
| eq_x_204       | DW_cmp         | width=5    | genblk1[4].u_RADIX2/eq_234 (RADIX2.v:234) |
| sub_x_210      | DW01_dec       | width=11   | genblk1[4].u_RADIX2/sub_255 (RADIX2.v:255) |
| gte_x_213      | DW_cmp         | width=10   | genblk1[4].u_RADIX2/gte_289 (RADIX2.v:289) |
| ash_217        | DW_leftsh      | A_width=10 | genblk1[5].u_RADIX2/sll_144 (RADIX2.v:144) |
 |                | SH_width=4 |                            |
| ash_218        | DW_leftsh      | A_width=9  | genblk1[5].u_RADIX2/sll_146 (RADIX2.v:146) |
 |                | SH_width=4 |                            |
| sub_x_222      | DW01_dec       | width=11   | genblk1[5].u_RADIX2/sub_179 (RADIX2.v:179) |
| gte_x_223      | DW_cmp         | width=32   | genblk1[5].u_RADIX2/gte_179 (RADIX2.v:179) |
| sub_x_231      | DW01_sub       | width=11   | genblk1[5].u_RADIX2/sub_212 (RADIX2.v:212) |
| lt_x_232       | DW_cmp         | width=32   | genblk1[5].u_RADIX2/lt_212 (RADIX2.v:212) |
| eq_x_235       | DW_cmp         | width=6    | genblk1[5].u_RADIX2/eq_227 (RADIX2.v:227) |
| eq_x_236       | DW_cmp         | width=6    | genblk1[5].u_RADIX2/eq_234 (RADIX2.v:234) |
| sub_x_242      | DW01_dec       | width=11   | genblk1[5].u_RADIX2/sub_255 (RADIX2.v:255) |
| gte_x_245      | DW_cmp         | width=10   | genblk1[5].u_RADIX2/gte_289 (RADIX2.v:289) |
| ash_249        | DW_leftsh      | A_width=10 | genblk1[6].u_RADIX2/sll_144 (RADIX2.v:144) |
 |                | SH_width=4 |                            |
| ash_250        | DW_leftsh      | A_width=9  | genblk1[6].u_RADIX2/sll_146 (RADIX2.v:146) |
 |                | SH_width=4 |                            |
| sub_x_254      | DW01_dec       | width=11   | genblk1[6].u_RADIX2/sub_179 (RADIX2.v:179) |
| gte_x_255      | DW_cmp         | width=32   | genblk1[6].u_RADIX2/gte_179 (RADIX2.v:179) |
| sub_x_263      | DW01_sub       | width=11   | genblk1[6].u_RADIX2/sub_212 (RADIX2.v:212) |
| lt_x_264       | DW_cmp         | width=32   | genblk1[6].u_RADIX2/lt_212 (RADIX2.v:212) |
| eq_x_267       | DW_cmp         | width=7    | genblk1[6].u_RADIX2/eq_227 (RADIX2.v:227) |
| eq_x_268       | DW_cmp         | width=7    | genblk1[6].u_RADIX2/eq_234 (RADIX2.v:234) |
| sub_x_274      | DW01_dec       | width=11   | genblk1[6].u_RADIX2/sub_255 (RADIX2.v:255) |
| gte_x_277      | DW_cmp         | width=10   | genblk1[6].u_RADIX2/gte_289 (RADIX2.v:289) |
| ash_281        | DW_leftsh      | A_width=10 | genblk1[7].u_RADIX2/sll_144 (RADIX2.v:144) |
 |                | SH_width=4 |                            |
| ash_282        | DW_leftsh      | A_width=9  | genblk1[7].u_RADIX2/sll_146 (RADIX2.v:146) |
 |                | SH_width=4 |                            |
| sub_x_286      | DW01_dec       | width=11   | genblk1[7].u_RADIX2/sub_179 (RADIX2.v:179) |
| gte_x_287      | DW_cmp         | width=32   | genblk1[7].u_RADIX2/gte_179 (RADIX2.v:179) |
| sub_x_295      | DW01_sub       | width=11   | genblk1[7].u_RADIX2/sub_212 (RADIX2.v:212) |
| lt_x_296       | DW_cmp         | width=32   | genblk1[7].u_RADIX2/lt_212 (RADIX2.v:212) |
| eq_x_299       | DW_cmp         | width=8    | genblk1[7].u_RADIX2/eq_227 (RADIX2.v:227) |
| eq_x_300       | DW_cmp         | width=8    | genblk1[7].u_RADIX2/eq_234 (RADIX2.v:234) |
| sub_x_306      | DW01_dec       | width=11   | genblk1[7].u_RADIX2/sub_255 (RADIX2.v:255) |
| gte_x_309      | DW_cmp         | width=10   | genblk1[7].u_RADIX2/gte_289 (RADIX2.v:289) |
| ash_313        | DW_leftsh      | A_width=10 | genblk1[8].u_RADIX2/sll_144 (RADIX2.v:144) |
 |                | SH_width=4 |                            |
| ash_314        | DW_leftsh      | A_width=9  | genblk1[8].u_RADIX2/sll_146 (RADIX2.v:146) |
 |                | SH_width=4 |                            |
| sub_x_318      | DW01_dec       | width=11   | genblk1[8].u_RADIX2/sub_179 (RADIX2.v:179) |
| gte_x_319      | DW_cmp         | width=32   | genblk1[8].u_RADIX2/gte_179 (RADIX2.v:179) |
| sub_x_327      | DW01_sub       | width=11   | genblk1[8].u_RADIX2/sub_212 (RADIX2.v:212) |
| lt_x_328       | DW_cmp         | width=32   | genblk1[8].u_RADIX2/lt_212 (RADIX2.v:212) |
| eq_x_331       | DW_cmp         | width=9    | genblk1[8].u_RADIX2/eq_227 (RADIX2.v:227) |
| eq_x_332       | DW_cmp         | width=9    | genblk1[8].u_RADIX2/eq_234 (RADIX2.v:234) |
| sub_x_338      | DW01_dec       | width=11   | genblk1[8].u_RADIX2/sub_255 (RADIX2.v:255) |
| gte_x_341      | DW_cmp         | width=10   | genblk1[8].u_RADIX2/gte_289 (RADIX2.v:289) |
| mult_x_346     | DW_mult_uns    | a_width=31 | genblk1[0].u_RADIX2/u_BUTTERFLY/u_modp_sub/mult_add_85_aco (MQ.v:85) |
| b_width=1 |                     |
| mult_x_355     | DW_mult_uns    | a_width=31 | genblk1[8].u_RADIX2/u_BUTTERFLY/u_modp_sub/mult_add_85_aco (MQ.v:85) |
| b_width=1 |                     |
| mult_x_356     | DW_mult_uns    | a_width=31 | genblk1[7].u_RADIX2/u_BUTTERFLY/u_modp_sub/mult_add_85_aco (MQ.v:85) |
| b_width=1 |                     |
| mult_x_357     | DW_mult_uns    | a_width=31 | genblk1[6].u_RADIX2/u_BUTTERFLY/u_modp_sub/mult_add_85_aco (MQ.v:85) |
| b_width=1 |                     |
| mult_x_358     | DW_mult_uns    | a_width=31 | genblk1[5].u_RADIX2/u_BUTTERFLY/u_modp_sub/mult_add_85_aco (MQ.v:85) |
| b_width=1 |                     |
| mult_x_359     | DW_mult_uns    | a_width=31 | genblk1[4].u_RADIX2/u_BUTTERFLY/u_modp_sub/mult_add_85_aco (MQ.v:85) |
| b_width=1 |                     |
| mult_x_360     | DW_mult_uns    | a_width=31 | genblk1[3].u_RADIX2/u_BUTTERFLY/u_modp_sub/mult_add_85_aco (MQ.v:85) |
| b_width=1 |                     |
| mult_x_361     | DW_mult_uns    | a_width=31 | genblk1[2].u_RADIX2/u_BUTTERFLY/u_modp_sub/mult_add_85_aco (MQ.v:85) |
| b_width=1 |                     |
| mult_x_362     | DW_mult_uns    | a_width=31 | genblk1[1].u_RADIX2/u_BUTTERFLY/u_modp_sub/mult_add_85_aco (MQ.v:85) |
| b_width=1 |                     |
| add_x_363      | DW01_add       | width=4    | genblk1[1].u_RADIX2/sub_145 (RADIX2.v:145) |
 |                |            | genblk1[1].u_RADIX2/sub_145_2 (RADIX2.v:145) |
| add_x_364      | DW01_add       | width=4    | genblk1[2].u_RADIX2/sub_145 (RADIX2.v:145) |
 |                |            | genblk1[2].u_RADIX2/sub_145_2 (RADIX2.v:145) |
| add_x_365      | DW01_add       | width=4    | genblk1[3].u_RADIX2/sub_145 (RADIX2.v:145) |
 |                |            | genblk1[3].u_RADIX2/sub_145_2 (RADIX2.v:145) |
| add_x_366      | DW01_add       | width=4    | genblk1[4].u_RADIX2/sub_145 (RADIX2.v:145) |
 |                |            | genblk1[4].u_RADIX2/sub_145_2 (RADIX2.v:145) |
| add_x_367      | DW01_add       | width=4    | genblk1[5].u_RADIX2/sub_145 (RADIX2.v:145) |
 |                |            | genblk1[5].u_RADIX2/sub_145_2 (RADIX2.v:145) |
| add_x_368      | DW01_add       | width=4    | genblk1[6].u_RADIX2/sub_145 (RADIX2.v:145) |
 |                |            | genblk1[6].u_RADIX2/sub_145_2 (RADIX2.v:145) |
| add_x_369      | DW01_add       | width=4    | genblk1[7].u_RADIX2/sub_145 (RADIX2.v:145) |
 |                |            | genblk1[7].u_RADIX2/sub_145_2 (RADIX2.v:145) |
| add_x_370      | DW01_add       | width=4    | genblk1[8].u_RADIX2/sub_145 (RADIX2.v:145) |
 |                |            | genblk1[8].u_RADIX2/sub_145_2 (RADIX2.v:145) |
| add_x_92       | DW01_inc       | width=10   | genblk1[1].u_RADIX2/add_174 (RADIX2.v:174) |
 |                |            | genblk1[1].u_RADIX2/add_180 (RADIX2.v:180) |
 |                |            | genblk1[1].u_RADIX2/add_182 (RADIX2.v:182) |
 |                |            | genblk1[1].u_RADIX2/add_218 (RADIX2.v:218) |
| add_x_330      | DW01_add       | width=9    | genblk1[8].u_RADIX2/add_227 (RADIX2.v:227) |
 |                |            | genblk1[8].u_RADIX2/add_232 (RADIX2.v:232) |
 |                |            | genblk1[8].u_RADIX2/add_234 (RADIX2.v:234) |
| add_x_61       | DW01_inc       | width=10   | genblk1[0].u_RADIX2/add_174 (RADIX2.v:174) |
 |                |            | genblk1[0].u_RADIX2/add_180 (RADIX2.v:180) |
 |                |            | genblk1[0].u_RADIX2/add_182 (RADIX2.v:182) |
| add_x_298      | DW01_add       | width=8    | genblk1[7].u_RADIX2/add_227 (RADIX2.v:227) |
 |                |            | genblk1[7].u_RADIX2/add_232 (RADIX2.v:232) |
 |                |            | genblk1[7].u_RADIX2/add_234 (RADIX2.v:234) |
| add_x_266      | DW01_add       | width=7    | genblk1[6].u_RADIX2/add_227 (RADIX2.v:227) |
 |                |            | genblk1[6].u_RADIX2/add_232 (RADIX2.v:232) |
 |                |            | genblk1[6].u_RADIX2/add_234 (RADIX2.v:234) |
| add_x_234      | DW01_add       | width=6    | genblk1[5].u_RADIX2/add_227 (RADIX2.v:227) |
 |                |            | genblk1[5].u_RADIX2/add_232 (RADIX2.v:232) |
 |                |            | genblk1[5].u_RADIX2/add_234 (RADIX2.v:234) |
| add_x_202      | DW01_add       | width=5    | genblk1[4].u_RADIX2/add_227 (RADIX2.v:227) |
 |                |            | genblk1[4].u_RADIX2/add_232 (RADIX2.v:232) |
 |                |            | genblk1[4].u_RADIX2/add_234 (RADIX2.v:234) |
| add_x_170      | DW01_add       | width=4    | genblk1[3].u_RADIX2/add_227 (RADIX2.v:227) |
 |                |            | genblk1[3].u_RADIX2/add_232 (RADIX2.v:232) |
 |                |            | genblk1[3].u_RADIX2/add_234 (RADIX2.v:234) |
| add_x_138      | DW01_add       | width=3    | genblk1[2].u_RADIX2/add_227 (RADIX2.v:227) |
 |                |            | genblk1[2].u_RADIX2/add_232 (RADIX2.v:232) |
 |                |            | genblk1[2].u_RADIX2/add_234 (RADIX2.v:234) |
| add_x_106      | DW01_add       | width=2    | genblk1[1].u_RADIX2/add_227 (RADIX2.v:227) |
 |                |            | genblk1[1].u_RADIX2/add_232 (RADIX2.v:232) |
 |                |            | genblk1[1].u_RADIX2/add_234 (RADIX2.v:234) |
| sub_x_335      | DW01_dec       | width=9    | genblk1[8].u_RADIX2/sub_249 (RADIX2.v:249) |
 |                |            | genblk1[8].u_RADIX2/sub_255_2 (RADIX2.v:255) |
| sub_x_303      | DW01_dec       | width=8    | genblk1[7].u_RADIX2/sub_249 (RADIX2.v:249) |
 |                |            | genblk1[7].u_RADIX2/sub_255_2 (RADIX2.v:255) |
| sub_x_271      | DW01_dec       | width=7    | genblk1[6].u_RADIX2/sub_249 (RADIX2.v:249) |
 |                |            | genblk1[6].u_RADIX2/sub_255_2 (RADIX2.v:255) |
| sub_x_239      | DW01_dec       | width=6    | genblk1[5].u_RADIX2/sub_249 (RADIX2.v:249) |
 |                |            | genblk1[5].u_RADIX2/sub_255_2 (RADIX2.v:255) |
| sub_x_207      | DW01_dec       | width=5    | genblk1[4].u_RADIX2/sub_249 (RADIX2.v:249) |
 |                |            | genblk1[4].u_RADIX2/sub_255_2 (RADIX2.v:255) |
| sub_x_175      | DW01_dec       | width=4    | genblk1[3].u_RADIX2/sub_249 (RADIX2.v:249) |
 |                |            | genblk1[3].u_RADIX2/sub_255_2 (RADIX2.v:255) |
| sub_x_143      | DW01_dec       | width=3    | genblk1[2].u_RADIX2/sub_249 (RADIX2.v:249) |
 |                |            | genblk1[2].u_RADIX2/sub_255_2 (RADIX2.v:255) |
| sub_x_111      | DW01_dec       | width=2    | genblk1[1].u_RADIX2/sub_249 (RADIX2.v:249) |
 |                |            | genblk1[1].u_RADIX2/sub_255_2 (RADIX2.v:255) |
| DP_OP_768J1_122_6350            |            |                            |
|                | DP_OP_768J1_122_6350 |      |                            |
| DP_OP_769J1_123_7894            |            |                            |
|                | DP_OP_769J1_123_7894 |      |                            |
| DP_OP_770J1_124_3897            |            |                            |
|                | DP_OP_770J1_124_3897 |      |                            |
| DP_OP_771J1_125_6350            |            |                            |
|                | DP_OP_771J1_125_6350 |      |                            |
| DP_OP_772J1_126_7894            |            |                            |
|                | DP_OP_772J1_126_7894 |      |                            |
| DP_OP_773J1_127_3897            |            |                            |
|                | DP_OP_773J1_127_3897 |      |                            |
| DP_OP_774J1_128_6350            |            |                            |
|                | DP_OP_774J1_128_6350 |      |                            |
| DP_OP_775J1_129_8013            |            |                            |
|                | DP_OP_775J1_129_8013 |      |                            |
| DP_OP_776J1_130_7894            |            |                            |
|                | DP_OP_776J1_130_7894 |      |                            |
| DP_OP_777J1_131_3897            |            |                            |
|                | DP_OP_777J1_131_3897 |      |                            |
| DP_OP_778J1_132_6350            |            |                            |
|                | DP_OP_778J1_132_6350 |      |                            |
| DP_OP_779J1_133_8013            |            |                            |
|                | DP_OP_779J1_133_8013 |      |                            |
| DP_OP_780J1_134_7894            |            |                            |
|                | DP_OP_780J1_134_7894 |      |                            |
| DP_OP_781J1_135_3897            |            |                            |
|                | DP_OP_781J1_135_3897 |      |                            |
| DP_OP_782J1_136_6350            |            |                            |
|                | DP_OP_782J1_136_6350 |      |                            |
| DP_OP_783J1_137_8013            |            |                            |
|                | DP_OP_783J1_137_8013 |      |                            |
| DP_OP_784J1_138_7894            |            |                            |
|                | DP_OP_784J1_138_7894 |      |                            |
| DP_OP_785J1_139_3897            |            |                            |
|                | DP_OP_785J1_139_3897 |      |                            |
| DP_OP_786J1_140_6350            |            |                            |
|                | DP_OP_786J1_140_6350 |      |                            |
| DP_OP_787J1_141_8013            |            |                            |
|                | DP_OP_787J1_141_8013 |      |                            |
| DP_OP_788J1_142_7894            |            |                            |
|                | DP_OP_788J1_142_7894 |      |                            |
| DP_OP_789J1_143_3897            |            |                            |
|                | DP_OP_789J1_143_3897 |      |                            |
| DP_OP_790J1_144_6350            |            |                            |
|                | DP_OP_790J1_144_6350 |      |                            |
| DP_OP_791J1_145_8013            |            |                            |
|                | DP_OP_791J1_145_8013 |      |                            |
| DP_OP_792J1_146_7894            |            |                            |
|                | DP_OP_792J1_146_7894 |      |                            |
| DP_OP_793J1_147_3897            |            |                            |
|                | DP_OP_793J1_147_3897 |      |                            |
| DP_OP_794J1_148_6350            |            |                            |
|                | DP_OP_794J1_148_6350 |      |                            |
| DP_OP_795J1_149_8013            |            |                            |
|                | DP_OP_795J1_149_8013 |      |                            |
| DP_OP_796J1_150_7894            |            |                            |
|                | DP_OP_796J1_150_7894 |      |                            |
| DP_OP_797J1_151_3897            |            |                            |
|                | DP_OP_797J1_151_3897 |      |                            |
| DP_OP_798J1_152_6350            |            |                            |
|                | DP_OP_798J1_152_6350 |      |                            |
| DP_OP_799J1_153_8013            |            |                            |
|                | DP_OP_799J1_153_8013 |      |                            |
| DP_OP_800J1_154_7894            |            |                            |
|                | DP_OP_800J1_154_7894 |      |                            |
| DP_OP_801J1_155_3897            |            |                            |
|                | DP_OP_801J1_155_3897 |      |                            |
| DP_OP_26_169_9586               |            |                            |
|                | DP_OP_26_169_9586 |         |                            |
| DP_OP_27_170_7593               |            |                            |
|                | DP_OP_27_170_7593 |         |                            |
| DP_OP_26_171_9602               |            |                            |
|                | DP_OP_26_171_9602 |         |                            |
| DP_OP_27_172_1722               |            |                            |
|                | DP_OP_27_172_1722 |         |                            |
| DP_OP_26_173_9746               |            |                            |
|                | DP_OP_26_173_9746 |         |                            |
| DP_OP_27_174_2951               |            |                            |
|                | DP_OP_27_174_2951 |         |                            |
| DP_OP_26_175_9570               |            |                            |
|                | DP_OP_26_175_9570 |         |                            |
| DP_OP_27_176_3497               |            |                            |
|                | DP_OP_27_176_3497 |         |                            |
| DP_OP_26_181_9810               |            |                            |
|                | DP_OP_26_181_9810 |         |                            |
| DP_OP_27_182_6501               |            |                            |
|                | DP_OP_27_182_6501 |         |                            |
| DP_OP_26_177_9778               |            |                            |
|                | DP_OP_26_177_9778 |         |                            |
| DP_OP_27_178_8276               |            |                            |
|                | DP_OP_27_178_8276 |         |                            |
| DP_OP_26_179_9762               |            |                            |
|                | DP_OP_26_179_9762 |         |                            |
| DP_OP_27_180_4180               |            |                            |
|                | DP_OP_27_180_4180 |         |                            |
| DP_OP_26_183_9794               |            |                            |
|                | DP_OP_26_183_9794 |         |                            |
| DP_OP_27_184_2405               |            |                            |
|                | DP_OP_27_184_2405 |         |                            |
| DP_OP_26_185_9666               |            |                            |
|                | DP_OP_26_185_9666 |         |                            |
| DP_OP_27_186_5272               |            |                            |
|                | DP_OP_27_186_5272 |         |                            |
=============================================================================

Datapath Report for DP_OP_768J1_122_6350
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_768J1_122_6350 | genblk1[0].u_RADIX2/add_148 (RADIX2.v:148)          |
|                      | genblk1[0].u_RADIX2/eq_162 (RADIX2.v:162)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 10    |                                          |
| T57   | IFO  | Unsigned | 10    | I1 + $unsigned(1'b1) (RADIX2.v:148)      |
| O1    | PO   | Unsigned | 1     | I2 == T57 (RADIX2.v:162)                 |
==============================================================================

Datapath Report for DP_OP_769J1_123_7894
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_769J1_123_7894 | genblk1[0].u_RADIX2/u_BUTTERFLY/u_modp_sub/sub_84 (MQ.v:84) |
               | genblk1[0].u_RADIX2/u_BUTTERFLY/u_modp_sub/add_85_aco (MQ.v:85) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T666  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Signed   | 32    | I1 - I2 (MQ.v:84)                        |
| O2    | PO   | Unsigned | 31    | T666 + I3 (MQ.v:85)                      |
==============================================================================

Datapath Report for DP_OP_770J1_124_3897
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_770J1_124_3897 | genblk1[0].u_RADIX2/u_BUTTERFLY/u_modp_add/add_43 (MQ.v:43) |
               | genblk1[0].u_RADIX2/u_BUTTERFLY/u_modp_add/sub_44 (MQ.v:44) |
               | genblk1[0].u_RADIX2/u_BUTTERFLY/u_modp_add/gte_45 (MQ.v:45) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T665  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 32    | I1 + I2 (MQ.v:43)                        |
| O2    | PO   | Signed   | 31    | T665 - I3 (MQ.v:44)                      |
| O3    | PO   | Unsigned | 1     | O1 >= I3 (MQ.v:45)                       |
==============================================================================

Datapath Report for DP_OP_771J1_125_6350
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_771J1_125_6350 | genblk1[1].u_RADIX2/add_148 (RADIX2.v:148)          |
|                      | genblk1[1].u_RADIX2/eq_162 (RADIX2.v:162)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 10    |                                          |
| T94   | IFO  | Unsigned | 10    | I1 + $unsigned(2'b10) (RADIX2.v:148)     |
| O1    | PO   | Unsigned | 1     | I2 == T94 (RADIX2.v:162)                 |
==============================================================================

Datapath Report for DP_OP_772J1_126_7894
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_772J1_126_7894 | genblk1[1].u_RADIX2/u_BUTTERFLY/u_modp_sub/sub_84 (MQ.v:84) |
               | genblk1[1].u_RADIX2/u_BUTTERFLY/u_modp_sub/add_85_aco (MQ.v:85) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T690  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Signed   | 32    | I1 - I2 (MQ.v:84)                        |
| O2    | PO   | Unsigned | 31    | T690 + I3 (MQ.v:85)                      |
==============================================================================

Datapath Report for DP_OP_773J1_127_3897
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_773J1_127_3897 | genblk1[1].u_RADIX2/u_BUTTERFLY/u_modp_add/add_43 (MQ.v:43) |
               | genblk1[1].u_RADIX2/u_BUTTERFLY/u_modp_add/sub_44 (MQ.v:44) |
               | genblk1[1].u_RADIX2/u_BUTTERFLY/u_modp_add/gte_45 (MQ.v:45) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T675  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 32    | I1 + I2 (MQ.v:43)                        |
| O2    | PO   | Signed   | 31    | T675 - I3 (MQ.v:44)                      |
| O3    | PO   | Unsigned | 1     | O1 >= I3 (MQ.v:45)                       |
==============================================================================

Datapath Report for DP_OP_774J1_128_6350
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_774J1_128_6350 | genblk1[2].u_RADIX2/add_148 (RADIX2.v:148)          |
|                      | genblk1[2].u_RADIX2/eq_162 (RADIX2.v:162)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 10    |                                          |
| T138  | IFO  | Unsigned | 10    | I1 + $unsigned(3'b100) (RADIX2.v:148)    |
| O1    | PO   | Unsigned | 1     | I2 == T138 (RADIX2.v:162)                |
==============================================================================

Datapath Report for DP_OP_775J1_129_8013
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_775J1_129_8013 | genblk1[2].u_RADIX2/add_174 (RADIX2.v:174)          |
|                      | genblk1[2].u_RADIX2/add_180 (RADIX2.v:180)          |
|                      | genblk1[2].u_RADIX2/add_182 (RADIX2.v:182)          |
|                      | genblk1[2].u_RADIX2/add_218 (RADIX2.v:218)          |
|                      | genblk1[2].u_RADIX2/add_219 (RADIX2.v:219)          |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 9     |                                          |
| T584  | IFO  | Unsigned | 8     | O1[10:3]                                 |
| O1    | PO   | Unsigned | 11    | I1 + $unsigned(1'b1) ( RADIX2.v:174 RADIX2.v:180 RADIX2.v:182 RADIX2.v:218 ) |
| O2    | PO   | Unsigned | 10    | I2 + T584 (RADIX2.v:219)                 |
==============================================================================

Datapath Report for DP_OP_776J1_130_7894
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_776J1_130_7894 | genblk1[2].u_RADIX2/u_BUTTERFLY/u_modp_sub/sub_84 (MQ.v:84) |
               | genblk1[2].u_RADIX2/u_BUTTERFLY/u_modp_sub/add_85_aco (MQ.v:85) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T688  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Signed   | 32    | I1 - I2 (MQ.v:84)                        |
| O2    | PO   | Unsigned | 31    | T688 + I3 (MQ.v:85)                      |
==============================================================================

Datapath Report for DP_OP_777J1_131_3897
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_777J1_131_3897 | genblk1[2].u_RADIX2/u_BUTTERFLY/u_modp_add/add_43 (MQ.v:43) |
               | genblk1[2].u_RADIX2/u_BUTTERFLY/u_modp_add/sub_44 (MQ.v:44) |
               | genblk1[2].u_RADIX2/u_BUTTERFLY/u_modp_add/gte_45 (MQ.v:45) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T674  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 32    | I1 + I2 (MQ.v:43)                        |
| O2    | PO   | Signed   | 31    | T674 - I3 (MQ.v:44)                      |
| O3    | PO   | Unsigned | 1     | O1 >= I3 (MQ.v:45)                       |
==============================================================================

Datapath Report for DP_OP_778J1_132_6350
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_778J1_132_6350 | genblk1[3].u_RADIX2/add_148 (RADIX2.v:148)          |
|                      | genblk1[3].u_RADIX2/eq_162 (RADIX2.v:162)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 10    |                                          |
| T182  | IFO  | Unsigned | 10    | I1 + $unsigned(4'b1000) (RADIX2.v:148)   |
| O1    | PO   | Unsigned | 1     | I2 == T182 (RADIX2.v:162)                |
==============================================================================

Datapath Report for DP_OP_779J1_133_8013
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_779J1_133_8013 | genblk1[3].u_RADIX2/add_174 (RADIX2.v:174)          |
|                      | genblk1[3].u_RADIX2/add_180 (RADIX2.v:180)          |
|                      | genblk1[3].u_RADIX2/add_182 (RADIX2.v:182)          |
|                      | genblk1[3].u_RADIX2/add_218 (RADIX2.v:218)          |
|                      | genblk1[3].u_RADIX2/add_219 (RADIX2.v:219)          |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 9     |                                          |
| T596  | IFO  | Unsigned | 7     | O1[10:4]                                 |
| O1    | PO   | Unsigned | 11    | I1 + $unsigned(1'b1) ( RADIX2.v:174 RADIX2.v:180 RADIX2.v:182 RADIX2.v:218 ) |
| O2    | PO   | Unsigned | 10    | I2 + T596 (RADIX2.v:219)                 |
==============================================================================

Datapath Report for DP_OP_780J1_134_7894
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_780J1_134_7894 | genblk1[3].u_RADIX2/u_BUTTERFLY/u_modp_sub/sub_84 (MQ.v:84) |
               | genblk1[3].u_RADIX2/u_BUTTERFLY/u_modp_sub/add_85_aco (MQ.v:85) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T686  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Signed   | 32    | I1 - I2 (MQ.v:84)                        |
| O2    | PO   | Unsigned | 31    | T686 + I3 (MQ.v:85)                      |
==============================================================================

Datapath Report for DP_OP_781J1_135_3897
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_781J1_135_3897 | genblk1[3].u_RADIX2/u_BUTTERFLY/u_modp_add/add_43 (MQ.v:43) |
               | genblk1[3].u_RADIX2/u_BUTTERFLY/u_modp_add/sub_44 (MQ.v:44) |
               | genblk1[3].u_RADIX2/u_BUTTERFLY/u_modp_add/gte_45 (MQ.v:45) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T673  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 32    | I1 + I2 (MQ.v:43)                        |
| O2    | PO   | Signed   | 31    | T673 - I3 (MQ.v:44)                      |
| O3    | PO   | Unsigned | 1     | O1 >= I3 (MQ.v:45)                       |
==============================================================================

Datapath Report for DP_OP_782J1_136_6350
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_782J1_136_6350 | genblk1[4].u_RADIX2/add_148 (RADIX2.v:148)          |
|                      | genblk1[4].u_RADIX2/eq_162 (RADIX2.v:162)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 10    |                                          |
| T226  | IFO  | Unsigned | 10    | I1 + $unsigned(5'b10000) (RADIX2.v:148)  |
| O1    | PO   | Unsigned | 1     | I2 == T226 (RADIX2.v:162)                |
==============================================================================

Datapath Report for DP_OP_783J1_137_8013
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_783J1_137_8013 | genblk1[4].u_RADIX2/add_174 (RADIX2.v:174)          |
|                      | genblk1[4].u_RADIX2/add_180 (RADIX2.v:180)          |
|                      | genblk1[4].u_RADIX2/add_182 (RADIX2.v:182)          |
|                      | genblk1[4].u_RADIX2/add_218 (RADIX2.v:218)          |
|                      | genblk1[4].u_RADIX2/add_219 (RADIX2.v:219)          |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 9     |                                          |
| T608  | IFO  | Unsigned | 6     | O1[10:5]                                 |
| O1    | PO   | Unsigned | 11    | I1 + $unsigned(1'b1) ( RADIX2.v:174 RADIX2.v:180 RADIX2.v:182 RADIX2.v:218 ) |
| O2    | PO   | Unsigned | 10    | I2 + T608 (RADIX2.v:219)                 |
==============================================================================

Datapath Report for DP_OP_784J1_138_7894
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_784J1_138_7894 | genblk1[4].u_RADIX2/u_BUTTERFLY/u_modp_sub/sub_84 (MQ.v:84) |
               | genblk1[4].u_RADIX2/u_BUTTERFLY/u_modp_sub/add_85_aco (MQ.v:85) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T684  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Signed   | 32    | I1 - I2 (MQ.v:84)                        |
| O2    | PO   | Unsigned | 31    | T684 + I3 (MQ.v:85)                      |
==============================================================================

Datapath Report for DP_OP_785J1_139_3897
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_785J1_139_3897 | genblk1[4].u_RADIX2/u_BUTTERFLY/u_modp_add/add_43 (MQ.v:43) |
               | genblk1[4].u_RADIX2/u_BUTTERFLY/u_modp_add/sub_44 (MQ.v:44) |
               | genblk1[4].u_RADIX2/u_BUTTERFLY/u_modp_add/gte_45 (MQ.v:45) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T672  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 32    | I1 + I2 (MQ.v:43)                        |
| O2    | PO   | Signed   | 31    | T672 - I3 (MQ.v:44)                      |
| O3    | PO   | Unsigned | 1     | O1 >= I3 (MQ.v:45)                       |
==============================================================================

Datapath Report for DP_OP_786J1_140_6350
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_786J1_140_6350 | genblk1[5].u_RADIX2/add_148 (RADIX2.v:148)          |
|                      | genblk1[5].u_RADIX2/eq_162 (RADIX2.v:162)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 10    |                                          |
| T270  | IFO  | Unsigned | 10    | I1 + $unsigned(6'b100000) (RADIX2.v:148) |
| O1    | PO   | Unsigned | 1     | I2 == T270 (RADIX2.v:162)                |
==============================================================================

Datapath Report for DP_OP_787J1_141_8013
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_787J1_141_8013 | genblk1[5].u_RADIX2/add_174 (RADIX2.v:174)          |
|                      | genblk1[5].u_RADIX2/add_180 (RADIX2.v:180)          |
|                      | genblk1[5].u_RADIX2/add_182 (RADIX2.v:182)          |
|                      | genblk1[5].u_RADIX2/add_218 (RADIX2.v:218)          |
|                      | genblk1[5].u_RADIX2/add_219 (RADIX2.v:219)          |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 9     |                                          |
| T620  | IFO  | Unsigned | 5     | O1[10:6]                                 |
| O1    | PO   | Unsigned | 11    | I1 + $unsigned(1'b1) ( RADIX2.v:174 RADIX2.v:180 RADIX2.v:182 RADIX2.v:218 ) |
| O2    | PO   | Unsigned | 10    | I2 + T620 (RADIX2.v:219)                 |
==============================================================================

Datapath Report for DP_OP_788J1_142_7894
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_788J1_142_7894 | genblk1[5].u_RADIX2/u_BUTTERFLY/u_modp_sub/sub_84 (MQ.v:84) |
               | genblk1[5].u_RADIX2/u_BUTTERFLY/u_modp_sub/add_85_aco (MQ.v:85) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T682  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Signed   | 32    | I1 - I2 (MQ.v:84)                        |
| O2    | PO   | Unsigned | 31    | T682 + I3 (MQ.v:85)                      |
==============================================================================

Datapath Report for DP_OP_789J1_143_3897
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_789J1_143_3897 | genblk1[5].u_RADIX2/u_BUTTERFLY/u_modp_add/add_43 (MQ.v:43) |
               | genblk1[5].u_RADIX2/u_BUTTERFLY/u_modp_add/sub_44 (MQ.v:44) |
               | genblk1[5].u_RADIX2/u_BUTTERFLY/u_modp_add/gte_45 (MQ.v:45) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T671  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 32    | I1 + I2 (MQ.v:43)                        |
| O2    | PO   | Signed   | 31    | T671 - I3 (MQ.v:44)                      |
| O3    | PO   | Unsigned | 1     | O1 >= I3 (MQ.v:45)                       |
==============================================================================

Datapath Report for DP_OP_790J1_144_6350
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_790J1_144_6350 | genblk1[6].u_RADIX2/add_148 (RADIX2.v:148)          |
|                      | genblk1[6].u_RADIX2/eq_162 (RADIX2.v:162)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 10    |                                          |
| T314  | IFO  | Unsigned | 10    | I1 + $unsigned(7'b1000000) (RADIX2.v:148) |
| O1    | PO   | Unsigned | 1     | I2 == T314 (RADIX2.v:162)                |
==============================================================================

Datapath Report for DP_OP_791J1_145_8013
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_791J1_145_8013 | genblk1[6].u_RADIX2/add_174 (RADIX2.v:174)          |
|                      | genblk1[6].u_RADIX2/add_180 (RADIX2.v:180)          |
|                      | genblk1[6].u_RADIX2/add_182 (RADIX2.v:182)          |
|                      | genblk1[6].u_RADIX2/add_218 (RADIX2.v:218)          |
|                      | genblk1[6].u_RADIX2/add_219 (RADIX2.v:219)          |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 9     |                                          |
| T632  | IFO  | Unsigned | 4     | O1[10:7]                                 |
| O1    | PO   | Unsigned | 11    | I1 + $unsigned(1'b1) ( RADIX2.v:174 RADIX2.v:180 RADIX2.v:182 RADIX2.v:218 ) |
| O2    | PO   | Unsigned | 10    | I2 + T632 (RADIX2.v:219)                 |
==============================================================================

Datapath Report for DP_OP_792J1_146_7894
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_792J1_146_7894 | genblk1[6].u_RADIX2/u_BUTTERFLY/u_modp_sub/sub_84 (MQ.v:84) |
               | genblk1[6].u_RADIX2/u_BUTTERFLY/u_modp_sub/add_85_aco (MQ.v:85) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T680  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Signed   | 32    | I1 - I2 (MQ.v:84)                        |
| O2    | PO   | Unsigned | 31    | T680 + I3 (MQ.v:85)                      |
==============================================================================

Datapath Report for DP_OP_793J1_147_3897
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_793J1_147_3897 | genblk1[6].u_RADIX2/u_BUTTERFLY/u_modp_add/add_43 (MQ.v:43) |
               | genblk1[6].u_RADIX2/u_BUTTERFLY/u_modp_add/sub_44 (MQ.v:44) |
               | genblk1[6].u_RADIX2/u_BUTTERFLY/u_modp_add/gte_45 (MQ.v:45) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T670  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 32    | I1 + I2 (MQ.v:43)                        |
| O2    | PO   | Signed   | 31    | T670 - I3 (MQ.v:44)                      |
| O3    | PO   | Unsigned | 1     | O1 >= I3 (MQ.v:45)                       |
==============================================================================

Datapath Report for DP_OP_794J1_148_6350
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_794J1_148_6350 | genblk1[7].u_RADIX2/add_148 (RADIX2.v:148)          |
|                      | genblk1[7].u_RADIX2/eq_162 (RADIX2.v:162)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 10    |                                          |
| T358  | IFO  | Unsigned | 10    | I1 + $unsigned(8'b10000000) (RADIX2.v:148) |
| O1    | PO   | Unsigned | 1     | I2 == T358 (RADIX2.v:162)                |
==============================================================================

Datapath Report for DP_OP_795J1_149_8013
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_795J1_149_8013 | genblk1[7].u_RADIX2/add_174 (RADIX2.v:174)          |
|                      | genblk1[7].u_RADIX2/add_180 (RADIX2.v:180)          |
|                      | genblk1[7].u_RADIX2/add_182 (RADIX2.v:182)          |
|                      | genblk1[7].u_RADIX2/add_218 (RADIX2.v:218)          |
|                      | genblk1[7].u_RADIX2/add_219 (RADIX2.v:219)          |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 9     |                                          |
| T644  | IFO  | Unsigned | 3     | O1[10:8]                                 |
| O1    | PO   | Unsigned | 11    | I1 + $unsigned(1'b1) ( RADIX2.v:174 RADIX2.v:180 RADIX2.v:182 RADIX2.v:218 ) |
| O2    | PO   | Unsigned | 10    | I2 + T644 (RADIX2.v:219)                 |
==============================================================================

Datapath Report for DP_OP_796J1_150_7894
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_796J1_150_7894 | genblk1[7].u_RADIX2/u_BUTTERFLY/u_modp_sub/sub_84 (MQ.v:84) |
               | genblk1[7].u_RADIX2/u_BUTTERFLY/u_modp_sub/add_85_aco (MQ.v:85) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T678  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Signed   | 32    | I1 - I2 (MQ.v:84)                        |
| O2    | PO   | Unsigned | 31    | T678 + I3 (MQ.v:85)                      |
==============================================================================

Datapath Report for DP_OP_797J1_151_3897
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_797J1_151_3897 | genblk1[7].u_RADIX2/u_BUTTERFLY/u_modp_add/add_43 (MQ.v:43) |
               | genblk1[7].u_RADIX2/u_BUTTERFLY/u_modp_add/sub_44 (MQ.v:44) |
               | genblk1[7].u_RADIX2/u_BUTTERFLY/u_modp_add/gte_45 (MQ.v:45) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T669  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 32    | I1 + I2 (MQ.v:43)                        |
| O2    | PO   | Signed   | 31    | T669 - I3 (MQ.v:44)                      |
| O3    | PO   | Unsigned | 1     | O1 >= I3 (MQ.v:45)                       |
==============================================================================

Datapath Report for DP_OP_798J1_152_6350
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_798J1_152_6350 | genblk1[8].u_RADIX2/add_148 (RADIX2.v:148)          |
|                      | genblk1[8].u_RADIX2/eq_162 (RADIX2.v:162)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 10    |                                          |
| T402  | IFO  | Unsigned | 10    | I1 + $unsigned(9'b100000000) (RADIX2.v:148) |
| O1    | PO   | Unsigned | 1     | I2 == T402 (RADIX2.v:162)                |
==============================================================================

Datapath Report for DP_OP_799J1_153_8013
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_799J1_153_8013 | genblk1[8].u_RADIX2/add_174 (RADIX2.v:174)          |
|                      | genblk1[8].u_RADIX2/add_180 (RADIX2.v:180)          |
|                      | genblk1[8].u_RADIX2/add_182 (RADIX2.v:182)          |
|                      | genblk1[8].u_RADIX2/add_218 (RADIX2.v:218)          |
|                      | genblk1[8].u_RADIX2/add_219 (RADIX2.v:219)          |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 9     |                                          |
| T656  | IFO  | Unsigned | 2     | O1[10:9]                                 |
| O1    | PO   | Unsigned | 11    | I1 + $unsigned(1'b1) ( RADIX2.v:174 RADIX2.v:180 RADIX2.v:182 RADIX2.v:218 ) |
| O2    | PO   | Unsigned | 10    | I2 + T656 (RADIX2.v:219)                 |
==============================================================================

Datapath Report for DP_OP_800J1_154_7894
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_800J1_154_7894 | genblk1[8].u_RADIX2/u_BUTTERFLY/u_modp_sub/sub_84 (MQ.v:84) |
               | genblk1[8].u_RADIX2/u_BUTTERFLY/u_modp_sub/add_85_aco (MQ.v:85) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T676  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Signed   | 32    | I1 - I2 (MQ.v:84)                        |
| O2    | PO   | Unsigned | 31    | T676 + I3 (MQ.v:85)                      |
==============================================================================

Datapath Report for DP_OP_801J1_155_3897
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_801J1_155_3897 | genblk1[8].u_RADIX2/u_BUTTERFLY/u_modp_add/add_43 (MQ.v:43) |
               | genblk1[8].u_RADIX2/u_BUTTERFLY/u_modp_add/sub_44 (MQ.v:44) |
               | genblk1[8].u_RADIX2/u_BUTTERFLY/u_modp_add/gte_45 (MQ.v:45) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T668  | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 32    | I1 + I2 (MQ.v:43)                        |
| O2    | PO   | Signed   | 31    | T668 - I3 (MQ.v:44)                      |
| O3    | PO   | Unsigned | 1     | O1 >= I3 (MQ.v:45)                       |
==============================================================================

Datapath Report for DP_OP_26_169_9586
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_26_169_9586    | mult_153 (MQ.v:153) add_156 (MQ.v:156)              |
|                      | sub_165 (MQ.v:165)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 48    |                                          |
| T2    | IFO  | Unsigned | 47    | I1 * I2 (MQ.v:153)                       |
| T18   | IFO  | Signed   | 31    | O1[46:16]                                |
| O1    | PO   | Unsigned | 48    | I3 + T2 (MQ.v:156)                       |
| O2    | PO   | Signed   | 31    | T18 - I2 (MQ.v:165)                      |
==============================================================================

Datapath Report for DP_OP_27_170_7593
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_27_170_7593    | mult_154 (MQ.v:154) add_157 (MQ.v:157)              |
|                      | gte_170 (MQ.v:170) sub_171 (MQ.v:171)               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 62    |                                          |
| T3    | IFO  | Unsigned | 62    | I1 * I2 (MQ.v:154)                       |
| T16   | IFO  | Unsigned | 32    | O1[62:31]                                |
| T19   | IFO  | Signed   | 31    | O1[61:31]                                |
| O1    | PO   | Unsigned | 63    | I3 + T3 (MQ.v:157)                       |
| O2    | PO   | Unsigned | 1     | T16 >= I2 (MQ.v:170)                     |
| O3    | PO   | Signed   | 31    | T19 - I2 (MQ.v:171)                      |
==============================================================================

Datapath Report for DP_OP_26_171_9602
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_26_171_9602    | mult_153 (MQ.v:153) add_156 (MQ.v:156)              |
|                      | sub_165 (MQ.v:165)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 48    |                                          |
| T2    | IFO  | Unsigned | 47    | I1 * I2 (MQ.v:153)                       |
| T18   | IFO  | Signed   | 31    | O1[46:16]                                |
| O1    | PO   | Unsigned | 48    | I3 + T2 (MQ.v:156)                       |
| O2    | PO   | Signed   | 31    | T18 - I2 (MQ.v:165)                      |
==============================================================================

Datapath Report for DP_OP_27_172_1722
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_27_172_1722    | mult_154 (MQ.v:154) add_157 (MQ.v:157)              |
|                      | gte_170 (MQ.v:170) sub_171 (MQ.v:171)               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 62    |                                          |
| T3    | IFO  | Unsigned | 62    | I1 * I2 (MQ.v:154)                       |
| T16   | IFO  | Unsigned | 32    | O1[62:31]                                |
| T19   | IFO  | Signed   | 31    | O1[61:31]                                |
| O1    | PO   | Unsigned | 63    | I3 + T3 (MQ.v:157)                       |
| O2    | PO   | Unsigned | 1     | T16 >= I2 (MQ.v:170)                     |
| O3    | PO   | Signed   | 31    | T19 - I2 (MQ.v:171)                      |
==============================================================================

Datapath Report for DP_OP_26_173_9746
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_26_173_9746    | mult_153 (MQ.v:153) add_156 (MQ.v:156)              |
|                      | sub_165 (MQ.v:165)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 48    |                                          |
| T2    | IFO  | Unsigned | 47    | I1 * I2 (MQ.v:153)                       |
| T18   | IFO  | Signed   | 31    | O1[46:16]                                |
| O1    | PO   | Unsigned | 48    | I3 + T2 (MQ.v:156)                       |
| O2    | PO   | Signed   | 31    | T18 - I2 (MQ.v:165)                      |
==============================================================================

Datapath Report for DP_OP_27_174_2951
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_27_174_2951    | mult_154 (MQ.v:154) add_157 (MQ.v:157)              |
|                      | gte_170 (MQ.v:170) sub_171 (MQ.v:171)               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 62    |                                          |
| T3    | IFO  | Unsigned | 62    | I1 * I2 (MQ.v:154)                       |
| T16   | IFO  | Unsigned | 32    | O1[62:31]                                |
| T19   | IFO  | Signed   | 31    | O1[61:31]                                |
| O1    | PO   | Unsigned | 63    | I3 + T3 (MQ.v:157)                       |
| O2    | PO   | Unsigned | 1     | T16 >= I2 (MQ.v:170)                     |
| O3    | PO   | Signed   | 31    | T19 - I2 (MQ.v:171)                      |
==============================================================================

Datapath Report for DP_OP_26_175_9570
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_26_175_9570    | mult_153 (MQ.v:153) add_156 (MQ.v:156)              |
|                      | sub_165 (MQ.v:165)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 48    |                                          |
| T2    | IFO  | Unsigned | 47    | I1 * I2 (MQ.v:153)                       |
| T18   | IFO  | Signed   | 31    | O1[46:16]                                |
| O1    | PO   | Unsigned | 48    | I3 + T2 (MQ.v:156)                       |
| O2    | PO   | Signed   | 31    | T18 - I2 (MQ.v:165)                      |
==============================================================================

Datapath Report for DP_OP_27_176_3497
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_27_176_3497    | mult_154 (MQ.v:154) add_157 (MQ.v:157)              |
|                      | gte_170 (MQ.v:170) sub_171 (MQ.v:171)               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 62    |                                          |
| T3    | IFO  | Unsigned | 62    | I1 * I2 (MQ.v:154)                       |
| T16   | IFO  | Unsigned | 32    | O1[62:31]                                |
| T19   | IFO  | Signed   | 31    | O1[61:31]                                |
| O1    | PO   | Unsigned | 63    | I3 + T3 (MQ.v:157)                       |
| O2    | PO   | Unsigned | 1     | T16 >= I2 (MQ.v:170)                     |
| O3    | PO   | Signed   | 31    | T19 - I2 (MQ.v:171)                      |
==============================================================================

Datapath Report for DP_OP_26_181_9810
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_26_181_9810    | mult_153 (MQ.v:153) add_156 (MQ.v:156)              |
|                      | sub_165 (MQ.v:165)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 48    |                                          |
| T2    | IFO  | Unsigned | 47    | I1 * I2 (MQ.v:153)                       |
| T18   | IFO  | Signed   | 31    | O1[46:16]                                |
| O1    | PO   | Unsigned | 48    | I3 + T2 (MQ.v:156)                       |
| O2    | PO   | Signed   | 31    | T18 - I2 (MQ.v:165)                      |
==============================================================================

Datapath Report for DP_OP_27_182_6501
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_27_182_6501    | mult_154 (MQ.v:154) add_157 (MQ.v:157)              |
|                      | gte_170 (MQ.v:170) sub_171 (MQ.v:171)               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 62    |                                          |
| T3    | IFO  | Unsigned | 62    | I1 * I2 (MQ.v:154)                       |
| T16   | IFO  | Unsigned | 32    | O1[62:31]                                |
| T19   | IFO  | Signed   | 31    | O1[61:31]                                |
| O1    | PO   | Unsigned | 63    | I3 + T3 (MQ.v:157)                       |
| O2    | PO   | Unsigned | 1     | T16 >= I2 (MQ.v:170)                     |
| O3    | PO   | Signed   | 31    | T19 - I2 (MQ.v:171)                      |
==============================================================================

Datapath Report for DP_OP_26_177_9778
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_26_177_9778    | mult_153 (MQ.v:153) add_156 (MQ.v:156)              |
|                      | sub_165 (MQ.v:165)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 48    |                                          |
| T2    | IFO  | Unsigned | 47    | I1 * I2 (MQ.v:153)                       |
| T18   | IFO  | Signed   | 31    | O1[46:16]                                |
| O1    | PO   | Unsigned | 48    | I3 + T2 (MQ.v:156)                       |
| O2    | PO   | Signed   | 31    | T18 - I2 (MQ.v:165)                      |
==============================================================================

Datapath Report for DP_OP_27_178_8276
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_27_178_8276    | mult_154 (MQ.v:154) add_157 (MQ.v:157)              |
|                      | gte_170 (MQ.v:170) sub_171 (MQ.v:171)               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 62    |                                          |
| T3    | IFO  | Unsigned | 62    | I1 * I2 (MQ.v:154)                       |
| T16   | IFO  | Unsigned | 32    | O1[62:31]                                |
| T19   | IFO  | Signed   | 31    | O1[61:31]                                |
| O1    | PO   | Unsigned | 63    | I3 + T3 (MQ.v:157)                       |
| O2    | PO   | Unsigned | 1     | T16 >= I2 (MQ.v:170)                     |
| O3    | PO   | Signed   | 31    | T19 - I2 (MQ.v:171)                      |
==============================================================================

Datapath Report for DP_OP_26_179_9762
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_26_179_9762    | mult_153 (MQ.v:153) add_156 (MQ.v:156)              |
|                      | sub_165 (MQ.v:165)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 48    |                                          |
| T2    | IFO  | Unsigned | 47    | I1 * I2 (MQ.v:153)                       |
| T18   | IFO  | Signed   | 31    | O1[46:16]                                |
| O1    | PO   | Unsigned | 48    | I3 + T2 (MQ.v:156)                       |
| O2    | PO   | Signed   | 31    | T18 - I2 (MQ.v:165)                      |
==============================================================================

Datapath Report for DP_OP_27_180_4180
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_27_180_4180    | mult_154 (MQ.v:154) add_157 (MQ.v:157)              |
|                      | gte_170 (MQ.v:170) sub_171 (MQ.v:171)               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 62    |                                          |
| T3    | IFO  | Unsigned | 62    | I1 * I2 (MQ.v:154)                       |
| T16   | IFO  | Unsigned | 32    | O1[62:31]                                |
| T19   | IFO  | Signed   | 31    | O1[61:31]                                |
| O1    | PO   | Unsigned | 63    | I3 + T3 (MQ.v:157)                       |
| O2    | PO   | Unsigned | 1     | T16 >= I2 (MQ.v:170)                     |
| O3    | PO   | Signed   | 31    | T19 - I2 (MQ.v:171)                      |
==============================================================================

Datapath Report for DP_OP_26_183_9794
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_26_183_9794    | mult_153 (MQ.v:153) add_156 (MQ.v:156)              |
|                      | sub_165 (MQ.v:165)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 48    |                                          |
| T2    | IFO  | Unsigned | 47    | I1 * I2 (MQ.v:153)                       |
| T18   | IFO  | Signed   | 31    | O1[46:16]                                |
| O1    | PO   | Unsigned | 48    | I3 + T2 (MQ.v:156)                       |
| O2    | PO   | Signed   | 31    | T18 - I2 (MQ.v:165)                      |
==============================================================================

Datapath Report for DP_OP_27_184_2405
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_27_184_2405    | mult_154 (MQ.v:154) add_157 (MQ.v:157)              |
|                      | gte_170 (MQ.v:170) sub_171 (MQ.v:171)               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 62    |                                          |
| T3    | IFO  | Unsigned | 62    | I1 * I2 (MQ.v:154)                       |
| T16   | IFO  | Unsigned | 32    | O1[62:31]                                |
| T19   | IFO  | Signed   | 31    | O1[61:31]                                |
| O1    | PO   | Unsigned | 63    | I3 + T3 (MQ.v:157)                       |
| O2    | PO   | Unsigned | 1     | T16 >= I2 (MQ.v:170)                     |
| O3    | PO   | Signed   | 31    | T19 - I2 (MQ.v:171)                      |
==============================================================================

Datapath Report for DP_OP_26_185_9666
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_26_185_9666    | mult_153 (MQ.v:153) add_156 (MQ.v:156)              |
|                      | sub_165 (MQ.v:165)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 48    |                                          |
| T2    | IFO  | Unsigned | 47    | I1 * I2 (MQ.v:153)                       |
| T18   | IFO  | Signed   | 31    | O1[46:16]                                |
| O1    | PO   | Unsigned | 48    | I3 + T2 (MQ.v:156)                       |
| O2    | PO   | Signed   | 31    | T18 - I2 (MQ.v:165)                      |
==============================================================================

Datapath Report for DP_OP_27_186_5272
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_27_186_5272    | mult_154 (MQ.v:154) add_157 (MQ.v:157)              |
|                      | gte_170 (MQ.v:170) sub_171 (MQ.v:171)               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 62    |                                          |
| T3    | IFO  | Unsigned | 62    | I1 * I2 (MQ.v:154)                       |
| T16   | IFO  | Unsigned | 32    | O1[62:31]                                |
| T19   | IFO  | Signed   | 31    | O1[61:31]                                |
| O1    | PO   | Unsigned | 63    | I3 + T3 (MQ.v:157)                       |
| O2    | PO   | Unsigned | 1     | T16 >= I2 (MQ.v:170)                     |
| O3    | PO   | Signed   | 31    | T19 - I2 (MQ.v:171)                      |
==============================================================================


Resource Report for Ungrouped Hierarchy genblk1[8].u_RADIX2/u_MODP_MONTYMUL in
        file ../01_RTL/MQ.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_1        | DW_cmp         | width=32   | gte_164 (MQ.v:164)         |
| DP_OP_30J2_122_917              |            |                            |
|                | DP_OP_30J2_122_917 |        |                            |
=============================================================================

Datapath Report for DP_OP_30J2_122_917
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_30J2_122_917   | mult_151 (MQ.v:151) mult_152 (MQ.v:152)             |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T13   | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 62    | I1 * I2 (MQ.v:151)                       |
| O2    | PO   | Unsigned | 31    | T13 * I3 (MQ.v:152)                      |
==============================================================================


Resource Report for Ungrouped Hierarchy genblk1[7].u_RADIX2/u_MODP_MONTYMUL in
        file ../01_RTL/MQ.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_1        | DW_cmp         | width=32   | gte_164 (MQ.v:164)         |
| DP_OP_30J2_122_917              |            |                            |
|                | DP_OP_30J2_122_917 |        |                            |
=============================================================================

Datapath Report for DP_OP_30J2_122_917
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_30J2_122_917   | mult_151 (MQ.v:151) mult_152 (MQ.v:152)             |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T13   | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 62    | I1 * I2 (MQ.v:151)                       |
| O2    | PO   | Unsigned | 31    | T13 * I3 (MQ.v:152)                      |
==============================================================================


Resource Report for Ungrouped Hierarchy genblk1[6].u_RADIX2/u_MODP_MONTYMUL in
        file ../01_RTL/MQ.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_1        | DW_cmp         | width=32   | gte_164 (MQ.v:164)         |
| DP_OP_30J2_122_917              |            |                            |
|                | DP_OP_30J2_122_917 |        |                            |
=============================================================================

Datapath Report for DP_OP_30J2_122_917
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_30J2_122_917   | mult_151 (MQ.v:151) mult_152 (MQ.v:152)             |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T13   | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 62    | I1 * I2 (MQ.v:151)                       |
| O2    | PO   | Unsigned | 31    | T13 * I3 (MQ.v:152)                      |
==============================================================================


Resource Report for Ungrouped Hierarchy genblk1[5].u_RADIX2/u_MODP_MONTYMUL in
        file ../01_RTL/MQ.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_1        | DW_cmp         | width=32   | gte_164 (MQ.v:164)         |
| DP_OP_30J2_122_917              |            |                            |
|                | DP_OP_30J2_122_917 |        |                            |
=============================================================================

Datapath Report for DP_OP_30J2_122_917
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_30J2_122_917   | mult_151 (MQ.v:151) mult_152 (MQ.v:152)             |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T13   | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 62    | I1 * I2 (MQ.v:151)                       |
| O2    | PO   | Unsigned | 31    | T13 * I3 (MQ.v:152)                      |
==============================================================================


Resource Report for Ungrouped Hierarchy genblk1[4].u_RADIX2/u_MODP_MONTYMUL in
        file ../01_RTL/MQ.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_1        | DW_cmp         | width=32   | gte_164 (MQ.v:164)         |
| DP_OP_30J2_122_917              |            |                            |
|                | DP_OP_30J2_122_917 |        |                            |
=============================================================================

Datapath Report for DP_OP_30J2_122_917
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_30J2_122_917   | mult_151 (MQ.v:151) mult_152 (MQ.v:152)             |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T13   | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 62    | I1 * I2 (MQ.v:151)                       |
| O2    | PO   | Unsigned | 31    | T13 * I3 (MQ.v:152)                      |
==============================================================================


Resource Report for Ungrouped Hierarchy genblk1[3].u_RADIX2/u_MODP_MONTYMUL in
        file ../01_RTL/MQ.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_1        | DW_cmp         | width=32   | gte_164 (MQ.v:164)         |
| DP_OP_30J2_122_917              |            |                            |
|                | DP_OP_30J2_122_917 |        |                            |
=============================================================================

Datapath Report for DP_OP_30J2_122_917
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_30J2_122_917   | mult_151 (MQ.v:151) mult_152 (MQ.v:152)             |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T13   | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 62    | I1 * I2 (MQ.v:151)                       |
| O2    | PO   | Unsigned | 31    | T13 * I3 (MQ.v:152)                      |
==============================================================================


Resource Report for Ungrouped Hierarchy genblk1[2].u_RADIX2/u_MODP_MONTYMUL in
        file ../01_RTL/MQ.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_1        | DW_cmp         | width=32   | gte_164 (MQ.v:164)         |
| DP_OP_30J2_122_917              |            |                            |
|                | DP_OP_30J2_122_917 |        |                            |
=============================================================================

Datapath Report for DP_OP_30J2_122_917
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_30J2_122_917   | mult_151 (MQ.v:151) mult_152 (MQ.v:152)             |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T13   | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 62    | I1 * I2 (MQ.v:151)                       |
| O2    | PO   | Unsigned | 31    | T13 * I3 (MQ.v:152)                      |
==============================================================================


Resource Report for Ungrouped Hierarchy genblk1[1].u_RADIX2/u_MODP_MONTYMUL in
        file ../01_RTL/MQ.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_1        | DW_cmp         | width=32   | gte_164 (MQ.v:164)         |
| DP_OP_30J2_122_917              |            |                            |
|                | DP_OP_30J2_122_917 |        |                            |
=============================================================================

Datapath Report for DP_OP_30J2_122_917
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_30J2_122_917   | mult_151 (MQ.v:151) mult_152 (MQ.v:152)             |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T13   | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 62    | I1 * I2 (MQ.v:151)                       |
| O2    | PO   | Unsigned | 31    | T13 * I3 (MQ.v:152)                      |
==============================================================================


Resource Report for Ungrouped Hierarchy genblk1[0].u_RADIX2/u_MODP_MONTYMUL in
        file ../01_RTL/MQ.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_1        | DW_cmp         | width=32   | gte_164 (MQ.v:164)         |
| DP_OP_30J2_122_917              |            |                            |
|                | DP_OP_30J2_122_917 |        |                            |
=============================================================================

Datapath Report for DP_OP_30J2_122_917
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_30J2_122_917   | mult_151 (MQ.v:151) mult_152 (MQ.v:152)             |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 31    |                                          |
| I2    | PI   | Unsigned | 31    |                                          |
| I3    | PI   | Unsigned | 31    |                                          |
| T13   | IFO  | Signed   | 31    | O1[30:0]                                 |
| O1    | PO   | Unsigned | 62    | I1 * I2 (MQ.v:151)                       |
| O2    | PO   | Unsigned | 31    | T13 * I3 (MQ.v:152)                      |
==============================================================================


Datapath Extraction Report

Information: Operator associated with resources 'genblk1[0].u_RADIX2/sub_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[0].u_RADIX2/sll_144 (RADIX2.v:144)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[0].u_RADIX2/gte_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[0].u_RADIX2/sub_179 (RADIX2.v:179)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[0].u_RADIX2/sub_179 (RADIX2.v:179)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[0].u_RADIX2/lt_212 (RADIX2.v:212)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[0].u_RADIX2/sub_212 (RADIX2.v:212)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[0].u_RADIX2/sub_212 (RADIX2.v:212)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[0].u_RADIX2/add_219 (RADIX2.v:219)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[0].u_RADIX2/sll_146 (RADIX2.v:146)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[1].u_RADIX2/sub_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[1].u_RADIX2/sll_144 (RADIX2.v:144)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[1].u_RADIX2/gte_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[1].u_RADIX2/sub_179 (RADIX2.v:179)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[1].u_RADIX2/sub_179 (RADIX2.v:179)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[1].u_RADIX2/lt_212 (RADIX2.v:212)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[1].u_RADIX2/sub_212 (RADIX2.v:212)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[1].u_RADIX2/sub_212 (RADIX2.v:212)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[1].u_RADIX2/add_219 (RADIX2.v:219)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[1].u_RADIX2/sll_146 (RADIX2.v:146)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[2].u_RADIX2/sub_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[2].u_RADIX2/sll_144 (RADIX2.v:144)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[2].u_RADIX2/gte_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[2].u_RADIX2/sub_179 (RADIX2.v:179)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[2].u_RADIX2/sub_179 (RADIX2.v:179)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[2].u_RADIX2/lt_212 (RADIX2.v:212)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[2].u_RADIX2/sub_212 (RADIX2.v:212)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[2].u_RADIX2/sub_212 (RADIX2.v:212)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[2].u_RADIX2/add_219 (RADIX2.v:219)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[2].u_RADIX2/sll_146 (RADIX2.v:146)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[3].u_RADIX2/sub_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[3].u_RADIX2/sll_144 (RADIX2.v:144)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[3].u_RADIX2/gte_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[3].u_RADIX2/sub_179 (RADIX2.v:179)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[3].u_RADIX2/sub_179 (RADIX2.v:179)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[3].u_RADIX2/lt_212 (RADIX2.v:212)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[3].u_RADIX2/sub_212 (RADIX2.v:212)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[3].u_RADIX2/sub_212 (RADIX2.v:212)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[3].u_RADIX2/add_219 (RADIX2.v:219)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[3].u_RADIX2/sll_146 (RADIX2.v:146)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[4].u_RADIX2/sub_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[4].u_RADIX2/sll_144 (RADIX2.v:144)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[4].u_RADIX2/gte_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[4].u_RADIX2/sub_179 (RADIX2.v:179)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[4].u_RADIX2/sub_179 (RADIX2.v:179)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[4].u_RADIX2/lt_212 (RADIX2.v:212)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[4].u_RADIX2/sub_212 (RADIX2.v:212)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[4].u_RADIX2/sub_212 (RADIX2.v:212)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[4].u_RADIX2/add_219 (RADIX2.v:219)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[4].u_RADIX2/sll_146 (RADIX2.v:146)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[5].u_RADIX2/sub_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[5].u_RADIX2/sll_144 (RADIX2.v:144)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[5].u_RADIX2/gte_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[5].u_RADIX2/sub_179 (RADIX2.v:179)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[5].u_RADIX2/sub_179 (RADIX2.v:179)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[5].u_RADIX2/lt_212 (RADIX2.v:212)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[5].u_RADIX2/sub_212 (RADIX2.v:212)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[5].u_RADIX2/sub_212 (RADIX2.v:212)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[5].u_RADIX2/add_219 (RADIX2.v:219)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[5].u_RADIX2/sll_146 (RADIX2.v:146)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[6].u_RADIX2/sub_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[6].u_RADIX2/sll_144 (RADIX2.v:144)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[6].u_RADIX2/gte_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[6].u_RADIX2/sub_179 (RADIX2.v:179)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[6].u_RADIX2/sub_179 (RADIX2.v:179)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[6].u_RADIX2/lt_212 (RADIX2.v:212)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[6].u_RADIX2/sub_212 (RADIX2.v:212)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[6].u_RADIX2/sub_212 (RADIX2.v:212)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[6].u_RADIX2/add_219 (RADIX2.v:219)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[6].u_RADIX2/sll_146 (RADIX2.v:146)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[7].u_RADIX2/sub_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[7].u_RADIX2/sll_144 (RADIX2.v:144)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[7].u_RADIX2/gte_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[7].u_RADIX2/sub_179 (RADIX2.v:179)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[7].u_RADIX2/sub_179 (RADIX2.v:179)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[7].u_RADIX2/lt_212 (RADIX2.v:212)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[7].u_RADIX2/sub_212 (RADIX2.v:212)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[7].u_RADIX2/sub_212 (RADIX2.v:212)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[7].u_RADIX2/add_219 (RADIX2.v:219)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[7].u_RADIX2/sll_146 (RADIX2.v:146)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[8].u_RADIX2/sub_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[8].u_RADIX2/sll_144 (RADIX2.v:144)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[8].u_RADIX2/gte_179 (RADIX2.v:179)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[8].u_RADIX2/sub_179 (RADIX2.v:179)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[8].u_RADIX2/sub_179 (RADIX2.v:179)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[8].u_RADIX2/lt_212 (RADIX2.v:212)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'genblk1[8].u_RADIX2/sub_212 (RADIX2.v:212)'.  (HDL-120)

Information: The output of subtractor associated with resources 'genblk1[8].u_RADIX2/sub_212 (RADIX2.v:212)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'genblk1[8].u_RADIX2/add_219 (RADIX2.v:219)' in design 'MODP_NTT2' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'genblk1[8].u_RADIX2/sll_146 (RADIX2.v:146)'.  (HDL-120)


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| ash_55             | DW_leftsh        | astr (area)        |                |
| sub_x_56           | DW01_dec         | apparch (area)     |                |
| ash_57             | DW_leftsh        | astr (area)        |                |
| sub_x_62           | DW01_dec         | apparch (area)     |                |
| gte_x_63           | DW_cmp           | apparch (area)     |                |
| sub_x_71           | DW01_sub         | apparch (area)     |                |
| lt_x_72            | DW_cmp           | apparch (area)     |                |
| add_x_73           | DW01_inc         | apparch (area)     |                |
| add_x_74           | DW01_add         | apparch (area)     |                |
| sub_x_80           | DW01_dec         | apparch (area)     |                |
| gte_x_83           | DW_cmp           | apparch (area)     |                |
| ash_87             | DW_leftsh        | astr (area)        |                |
| ash_88             | DW_leftsh        | astr (area)        |                |
| sub_x_93           | DW01_dec         | apparch (area)     |                |
| gte_x_94           | DW_cmp           | apparch (area)     |                |
| sub_x_102          | DW01_sub         | apparch (area)     |                |
| lt_x_103           | DW_cmp           | apparch (area)     |                |
| add_x_104          | DW01_add         | apparch (area)     |                |
| eq_x_107           | DW_cmp           | apparch (area)     |                |
| eq_x_108           | DW_cmp           | apparch (area)     |                |
| sub_x_114          | DW01_dec         | apparch (area)     |                |
| gte_x_117          | DW_cmp           | apparch (area)     |                |
| ash_121            | DW_leftsh        | astr (area)        |                |
| ash_122            | DW_leftsh        | astr (area)        |                |
| sub_x_126          | DW01_dec         | apparch (area)     |                |
| gte_x_127          | DW_cmp           | apparch (area)     |                |
| sub_x_135          | DW01_sub         | apparch (area)     |                |
| lt_x_136           | DW_cmp           | apparch (area)     |                |
| eq_x_139           | DW_cmp           | apparch (area)     |                |
| eq_x_140           | DW_cmp           | apparch (area)     |                |
| sub_x_146          | DW01_dec         | apparch (area)     |                |
| gte_x_149          | DW_cmp           | apparch (area)     |                |
| ash_153            | DW_leftsh        | astr (area)        |                |
| ash_154            | DW_leftsh        | astr (area)        |                |
| sub_x_158          | DW01_dec         | apparch (area)     |                |
| gte_x_159          | DW_cmp           | apparch (area)     |                |
| sub_x_167          | DW01_sub         | apparch (area)     |                |
| lt_x_168           | DW_cmp           | apparch (area)     |                |
| eq_x_171           | DW_cmp           | apparch (area)     |                |
| eq_x_172           | DW_cmp           | apparch (area)     |                |
| sub_x_178          | DW01_dec         | apparch (area)     |                |
| gte_x_181          | DW_cmp           | apparch (area)     |                |
| ash_185            | DW_leftsh        | astr (area)        |                |
| ash_186            | DW_leftsh        | astr (area)        |                |
| sub_x_190          | DW01_dec         | apparch (area)     |                |
| gte_x_191          | DW_cmp           | apparch (area)     |                |
| sub_x_199          | DW01_sub         | apparch (area)     |                |
| lt_x_200           | DW_cmp           | apparch (area)     |                |
| eq_x_203           | DW_cmp           | apparch (area)     |                |
| eq_x_204           | DW_cmp           | apparch (area)     |                |
| sub_x_210          | DW01_dec         | apparch (area)     |                |
| gte_x_213          | DW_cmp           | apparch (area)     |                |
| ash_217            | DW_leftsh        | astr (area)        |                |
| ash_218            | DW_leftsh        | astr (area)        |                |
| sub_x_222          | DW01_dec         | apparch (area)     |                |
| gte_x_223          | DW_cmp           | apparch (area)     |                |
| sub_x_231          | DW01_sub         | apparch (area)     |                |
| lt_x_232           | DW_cmp           | apparch (area)     |                |
| eq_x_235           | DW_cmp           | apparch (area)     |                |
| eq_x_236           | DW_cmp           | apparch (area)     |                |
| sub_x_242          | DW01_dec         | apparch (area)     |                |
| gte_x_245          | DW_cmp           | apparch (area)     |                |
| ash_249            | DW_leftsh        | astr (area)        |                |
| ash_250            | DW_leftsh        | astr (area)        |                |
| sub_x_254          | DW01_dec         | apparch (area)     |                |
| gte_x_255          | DW_cmp           | apparch (area)     |                |
| sub_x_263          | DW01_sub         | apparch (area)     |                |
| lt_x_264           | DW_cmp           | apparch (area)     |                |
| eq_x_267           | DW_cmp           | apparch (area)     |                |
| eq_x_268           | DW_cmp           | apparch (area)     |                |
| sub_x_274          | DW01_dec         | apparch (area)     |                |
| gte_x_277          | DW_cmp           | apparch (area)     |                |
| ash_281            | DW_leftsh        | astr (area)        |                |
| ash_282            | DW_leftsh        | astr (area)        |                |
| sub_x_286          | DW01_dec         | apparch (area)     |                |
| gte_x_287          | DW_cmp           | apparch (area)     |                |
| sub_x_295          | DW01_sub         | apparch (area)     |                |
| lt_x_296           | DW_cmp           | apparch (area)     |                |
| eq_x_299           | DW_cmp           | apparch (area)     |                |
| eq_x_300           | DW_cmp           | apparch (area)     |                |
| sub_x_306          | DW01_dec         | apparch (area)     |                |
| gte_x_309          | DW_cmp           | apparch (area)     |                |
| ash_313            | DW_leftsh        | astr (area)        |                |
| ash_314            | DW_leftsh        | astr (area)        |                |
| sub_x_318          | DW01_dec         | apparch (area)     |                |
| gte_x_319          | DW_cmp           | apparch (area)     |                |
| sub_x_327          | DW01_sub         | apparch (area)     |                |
| lt_x_328           | DW_cmp           | apparch (area)     |                |
| eq_x_331           | DW_cmp           | apparch (area)     |                |
| eq_x_332           | DW_cmp           | apparch (area)     |                |
| sub_x_338          | DW01_dec         | apparch (area)     |                |
| gte_x_341          | DW_cmp           | apparch (area)     |                |
| mult_x_346         | DW_mult_uns      | pparch (area,speed)                 |
|                    |                  | mult_arch: and     |                |
| mult_x_355         | DW_mult_uns      | pparch (area,speed)                 |
|                    |                  | mult_arch: and     |                |
| mult_x_356         | DW_mult_uns      | pparch (area,speed)                 |
|                    |                  | mult_arch: and     |                |
| mult_x_357         | DW_mult_uns      | pparch (area,speed)                 |
|                    |                  | mult_arch: and     |                |
| mult_x_358         | DW_mult_uns      | pparch (area,speed)                 |
|                    |                  | mult_arch: and     |                |
| mult_x_359         | DW_mult_uns      | pparch (area,speed)                 |
|                    |                  | mult_arch: and     |                |
| mult_x_360         | DW_mult_uns      | pparch (area,speed)                 |
|                    |                  | mult_arch: and     |                |
| mult_x_361         | DW_mult_uns      | pparch (area,speed)                 |
|                    |                  | mult_arch: and     |                |
| mult_x_362         | DW_mult_uns      | pparch (area,speed)                 |
|                    |                  | mult_arch: and     |                |
| add_x_363          | DW01_add         | apparch (area)     |                |
| add_x_364          | DW01_add         | apparch (area)     |                |
| add_x_365          | DW01_add         | apparch (area)     |                |
| add_x_366          | DW01_add         | apparch (area)     |                |
| add_x_367          | DW01_add         | apparch (area)     |                |
| add_x_368          | DW01_add         | apparch (area)     |                |
| add_x_369          | DW01_add         | apparch (area)     |                |
| add_x_370          | DW01_add         | apparch (area)     |                |
| add_x_92           | DW01_inc         | apparch (area)     |                |
| add_x_330          | DW01_add         | apparch (area)     |                |
| add_x_61           | DW01_inc         | apparch (area)     |                |
| add_x_298          | DW01_add         | apparch (area)     |                |
| add_x_266          | DW01_add         | apparch (area)     |                |
| add_x_234          | DW01_add         | apparch (area)     |                |
| add_x_202          | DW01_add         | apparch (area)     |                |
| add_x_170          | DW01_add         | apparch (area)     |                |
| add_x_138          | DW01_add         | apparch (area)     |                |
| add_x_106          | DW01_add         | apparch (area)     |                |
| sub_x_335          | DW01_dec         | apparch (area)     |                |
| sub_x_303          | DW01_dec         | apparch (area)     |                |
| sub_x_271          | DW01_dec         | apparch (area)     |                |
| sub_x_239          | DW01_dec         | apparch (area)     |                |
| sub_x_207          | DW01_dec         | apparch (area)     |                |
| sub_x_175          | DW01_dec         | apparch (area)     |                |
| sub_x_143          | DW01_dec         | apparch (area)     |                |
| sub_x_111          | DW01_dec         | apparch (area)     |                |
| gte_x_1            | DW_cmp           | pparch (area,speed)                 |
| gte_x_1            | DW_cmp           | pparch (area,speed)                 |
| gte_x_1            | DW_cmp           | pparch (area,speed)                 |
| gte_x_1            | DW_cmp           | pparch (area,speed)                 |
| gte_x_1            | DW_cmp           | pparch (area,speed)                 |
| gte_x_1            | DW_cmp           | pparch (area,speed)                 |
| gte_x_1            | DW_cmp           | pparch (area,speed)                 |
| gte_x_1            | DW_cmp           | pparch (area,speed)                 |
| gte_x_1            | DW_cmp           | pparch (area,speed)                 |
| DP_OP_768J1_122_6350                  |                    |                |
|                    | DP_OP_768J1_122_6350 | str (area)     |                |
| DP_OP_769J1_123_7894                  |                    |                |
|                    | DP_OP_769J1_123_7894 | str (area,speed)                |
| DP_OP_770J1_124_3897                  |                    |                |
|                    | DP_OP_770J1_124_3897 | str (area,speed)                |
| DP_OP_771J1_125_6350                  |                    |                |
|                    | DP_OP_771J1_125_6350 | str (area)     |                |
| DP_OP_772J1_126_7894                  |                    |                |
|                    | DP_OP_772J1_126_7894 | str (area,speed)                |
| DP_OP_773J1_127_3897                  |                    |                |
|                    | DP_OP_773J1_127_3897 | str (area,speed)                |
| DP_OP_774J1_128_6350                  |                    |                |
|                    | DP_OP_774J1_128_6350 | str (area)     |                |
| DP_OP_775J1_129_8013                  |                    |                |
|                    | DP_OP_775J1_129_8013 | str (area)     |                |
| DP_OP_776J1_130_7894                  |                    |                |
|                    | DP_OP_776J1_130_7894 | str (area,speed)                |
| DP_OP_777J1_131_3897                  |                    |                |
|                    | DP_OP_777J1_131_3897 | str (area,speed)                |
| DP_OP_778J1_132_6350                  |                    |                |
|                    | DP_OP_778J1_132_6350 | str (area)     |                |
| DP_OP_779J1_133_8013                  |                    |                |
|                    | DP_OP_779J1_133_8013 | str (area)     |                |
| DP_OP_780J1_134_7894                  |                    |                |
|                    | DP_OP_780J1_134_7894 | str (area,speed)                |
| DP_OP_781J1_135_3897                  |                    |                |
|                    | DP_OP_781J1_135_3897 | str (area,speed)                |
| DP_OP_782J1_136_6350                  |                    |                |
|                    | DP_OP_782J1_136_6350 | str (area)     |                |
| DP_OP_783J1_137_8013                  |                    |                |
|                    | DP_OP_783J1_137_8013 | str (area)     |                |
| DP_OP_784J1_138_7894                  |                    |                |
|                    | DP_OP_784J1_138_7894 | str (area,speed)                |
| DP_OP_785J1_139_3897                  |                    |                |
|                    | DP_OP_785J1_139_3897 | str (area,speed)                |
| DP_OP_786J1_140_6350                  |                    |                |
|                    | DP_OP_786J1_140_6350 | str (area)     |                |
| DP_OP_787J1_141_8013                  |                    |                |
|                    | DP_OP_787J1_141_8013 | str (area)     |                |
| DP_OP_788J1_142_7894                  |                    |                |
|                    | DP_OP_788J1_142_7894 | str (area,speed)                |
| DP_OP_789J1_143_3897                  |                    |                |
|                    | DP_OP_789J1_143_3897 | str (area,speed)                |
| DP_OP_790J1_144_6350                  |                    |                |
|                    | DP_OP_790J1_144_6350 | str (area)     |                |
| DP_OP_791J1_145_8013                  |                    |                |
|                    | DP_OP_791J1_145_8013 | str (area)     |                |
| DP_OP_792J1_146_7894                  |                    |                |
|                    | DP_OP_792J1_146_7894 | str (area,speed)                |
| DP_OP_793J1_147_3897                  |                    |                |
|                    | DP_OP_793J1_147_3897 | str (area,speed)                |
| DP_OP_794J1_148_6350                  |                    |                |
|                    | DP_OP_794J1_148_6350 | str (area)     |                |
| DP_OP_795J1_149_8013                  |                    |                |
|                    | DP_OP_795J1_149_8013 | str (area)     |                |
| DP_OP_796J1_150_7894                  |                    |                |
|                    | DP_OP_796J1_150_7894 | str (area,speed)                |
| DP_OP_797J1_151_3897                  |                    |                |
|                    | DP_OP_797J1_151_3897 | str (area,speed)                |
| DP_OP_798J1_152_6350                  |                    |                |
|                    | DP_OP_798J1_152_6350 | str (area)     |                |
| DP_OP_799J1_153_8013                  |                    |                |
|                    | DP_OP_799J1_153_8013 | str (area)     |                |
| DP_OP_800J1_154_7894                  |                    |                |
|                    | DP_OP_800J1_154_7894 | str (area,speed)                |
| DP_OP_801J1_155_3897                  |                    |                |
|                    | DP_OP_801J1_155_3897 | str (area,speed)                |
| DP_OP_26_169_9586  | DP_OP_26_169_9586 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_27_170_7593  | DP_OP_27_170_7593 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_26_171_9602  | DP_OP_26_171_9602 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_27_172_1722  | DP_OP_27_172_1722 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_26_173_9746  | DP_OP_26_173_9746 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_27_174_2951  | DP_OP_27_174_2951 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_26_175_9570  | DP_OP_26_175_9570 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_27_176_3497  | DP_OP_27_176_3497 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_26_181_9810  | DP_OP_26_181_9810 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_27_182_6501  | DP_OP_27_182_6501 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_26_177_9778  | DP_OP_26_177_9778 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_27_178_8276  | DP_OP_27_178_8276 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_26_179_9762  | DP_OP_26_179_9762 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_27_180_4180  | DP_OP_27_180_4180 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_26_183_9794  | DP_OP_26_183_9794 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_27_184_2405  | DP_OP_27_184_2405 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_26_185_9666  | DP_OP_26_185_9666 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_27_186_5272  | DP_OP_27_186_5272 | str (area,speed)  |                |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_30J2_122_917 | DP_OP_30J2_122_917 | str (area,speed) |                |
|                    |                  | mult_arch: benc_radix4              |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_30J2_122_917 | DP_OP_30J2_122_917 | str (area,speed) |                |
|                    |                  | mult_arch: benc_radix4              |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_30J2_122_917 | DP_OP_30J2_122_917 | str (area,speed) |                |
|                    |                  | mult_arch: benc_radix4              |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_30J2_122_917 | DP_OP_30J2_122_917 | str (area,speed) |                |
|                    |                  | mult_arch: benc_radix4              |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_30J2_122_917 | DP_OP_30J2_122_917 | str (area,speed) |                |
|                    |                  | mult_arch: benc_radix4              |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_30J2_122_917 | DP_OP_30J2_122_917 | str (area,speed) |                |
|                    |                  | mult_arch: benc_radix4              |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_30J2_122_917 | DP_OP_30J2_122_917 | str (area,speed) |                |
|                    |                  | mult_arch: benc_radix4              |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_30J2_122_917 | DP_OP_30J2_122_917 | str (area,speed) |                |
|                    |                  | mult_arch: benc_radix4              |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_30J2_122_917 | DP_OP_30J2_122_917 | str (area,speed) |                |
|                    |                  | mult_arch: benc_radix4              |
|                    |                  | mult_arch: benc_radix4              |
===============================================================================

1
