###################################################################

# Created by write_sdc on Thu Jun  4 11:51:15 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name Small -library                                       \
sc9_cln40g_base_rvt_ss_typical_max_0p81v_125c
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {z[63]}]
set_load -pin_load 0.05 [get_ports {z[62]}]
set_load -pin_load 0.05 [get_ports {z[61]}]
set_load -pin_load 0.05 [get_ports {z[60]}]
set_load -pin_load 0.05 [get_ports {z[59]}]
set_load -pin_load 0.05 [get_ports {z[58]}]
set_load -pin_load 0.05 [get_ports {z[57]}]
set_load -pin_load 0.05 [get_ports {z[56]}]
set_load -pin_load 0.05 [get_ports {z[55]}]
set_load -pin_load 0.05 [get_ports {z[54]}]
set_load -pin_load 0.05 [get_ports {z[53]}]
set_load -pin_load 0.05 [get_ports {z[52]}]
set_load -pin_load 0.05 [get_ports {z[51]}]
set_load -pin_load 0.05 [get_ports {z[50]}]
set_load -pin_load 0.05 [get_ports {z[49]}]
set_load -pin_load 0.05 [get_ports {z[48]}]
set_load -pin_load 0.05 [get_ports {z[47]}]
set_load -pin_load 0.05 [get_ports {z[46]}]
set_load -pin_load 0.05 [get_ports {z[45]}]
set_load -pin_load 0.05 [get_ports {z[44]}]
set_load -pin_load 0.05 [get_ports {z[43]}]
set_load -pin_load 0.05 [get_ports {z[42]}]
set_load -pin_load 0.05 [get_ports {z[41]}]
set_load -pin_load 0.05 [get_ports {z[40]}]
set_load -pin_load 0.05 [get_ports {z[39]}]
set_load -pin_load 0.05 [get_ports {z[38]}]
set_load -pin_load 0.05 [get_ports {z[37]}]
set_load -pin_load 0.05 [get_ports {z[36]}]
set_load -pin_load 0.05 [get_ports {z[35]}]
set_load -pin_load 0.05 [get_ports {z[34]}]
set_load -pin_load 0.05 [get_ports {z[33]}]
set_load -pin_load 0.05 [get_ports {z[32]}]
set_load -pin_load 0.05 [get_ports {z[31]}]
set_load -pin_load 0.05 [get_ports {z[30]}]
set_load -pin_load 0.05 [get_ports {z[29]}]
set_load -pin_load 0.05 [get_ports {z[28]}]
set_load -pin_load 0.05 [get_ports {z[27]}]
set_load -pin_load 0.05 [get_ports {z[26]}]
set_load -pin_load 0.05 [get_ports {z[25]}]
set_load -pin_load 0.05 [get_ports {z[24]}]
set_load -pin_load 0.05 [get_ports {z[23]}]
set_load -pin_load 0.05 [get_ports {z[22]}]
set_load -pin_load 0.05 [get_ports {z[21]}]
set_load -pin_load 0.05 [get_ports {z[20]}]
set_load -pin_load 0.05 [get_ports {z[19]}]
set_load -pin_load 0.05 [get_ports {z[18]}]
set_load -pin_load 0.05 [get_ports {z[17]}]
set_load -pin_load 0.05 [get_ports {z[16]}]
set_load -pin_load 0.05 [get_ports {z[15]}]
set_load -pin_load 0.05 [get_ports {z[14]}]
set_load -pin_load 0.05 [get_ports {z[13]}]
set_load -pin_load 0.05 [get_ports {z[12]}]
set_load -pin_load 0.05 [get_ports {z[11]}]
set_load -pin_load 0.05 [get_ports {z[10]}]
set_load -pin_load 0.05 [get_ports {z[9]}]
set_load -pin_load 0.05 [get_ports {z[8]}]
set_load -pin_load 0.05 [get_ports {z[7]}]
set_load -pin_load 0.05 [get_ports {z[6]}]
set_load -pin_load 0.05 [get_ports {z[5]}]
set_load -pin_load 0.05 [get_ports {z[4]}]
set_load -pin_load 0.05 [get_ports {z[3]}]
set_load -pin_load 0.05 [get_ports {z[2]}]
set_load -pin_load 0.05 [get_ports {z[1]}]
set_load -pin_load 0.05 [get_ports {z[0]}]
create_clock [get_ports clk]  -period 1.2  -waveform {0 0.6}
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  0  [get_ports in_valid]
set_input_delay -clock clk  0  [get_ports {b[63]}]
set_input_delay -clock clk  0  [get_ports {b[62]}]
set_input_delay -clock clk  0  [get_ports {b[61]}]
set_input_delay -clock clk  0  [get_ports {b[60]}]
set_input_delay -clock clk  0  [get_ports {b[59]}]
set_input_delay -clock clk  0  [get_ports {b[58]}]
set_input_delay -clock clk  0  [get_ports {b[57]}]
set_input_delay -clock clk  0  [get_ports {b[56]}]
set_input_delay -clock clk  0  [get_ports {b[55]}]
set_input_delay -clock clk  0  [get_ports {b[54]}]
set_input_delay -clock clk  0  [get_ports {b[53]}]
set_input_delay -clock clk  0  [get_ports {b[52]}]
set_input_delay -clock clk  0  [get_ports {b[51]}]
set_input_delay -clock clk  0  [get_ports {b[50]}]
set_input_delay -clock clk  0  [get_ports {b[49]}]
set_input_delay -clock clk  0  [get_ports {b[48]}]
set_input_delay -clock clk  0  [get_ports {b[47]}]
set_input_delay -clock clk  0  [get_ports {b[46]}]
set_input_delay -clock clk  0  [get_ports {b[45]}]
set_input_delay -clock clk  0  [get_ports {b[44]}]
set_input_delay -clock clk  0  [get_ports {b[43]}]
set_input_delay -clock clk  0  [get_ports {b[42]}]
set_input_delay -clock clk  0  [get_ports {b[41]}]
set_input_delay -clock clk  0  [get_ports {b[40]}]
set_input_delay -clock clk  0  [get_ports {b[39]}]
set_input_delay -clock clk  0  [get_ports {b[38]}]
set_input_delay -clock clk  0  [get_ports {b[37]}]
set_input_delay -clock clk  0  [get_ports {b[36]}]
set_input_delay -clock clk  0  [get_ports {b[35]}]
set_input_delay -clock clk  0  [get_ports {b[34]}]
set_input_delay -clock clk  0  [get_ports {b[33]}]
set_input_delay -clock clk  0  [get_ports {b[32]}]
set_input_delay -clock clk  0  [get_ports {b[31]}]
set_input_delay -clock clk  0  [get_ports {b[30]}]
set_input_delay -clock clk  0  [get_ports {b[29]}]
set_input_delay -clock clk  0  [get_ports {b[28]}]
set_input_delay -clock clk  0  [get_ports {b[27]}]
set_input_delay -clock clk  0  [get_ports {b[26]}]
set_input_delay -clock clk  0  [get_ports {b[25]}]
set_input_delay -clock clk  0  [get_ports {b[24]}]
set_input_delay -clock clk  0  [get_ports {b[23]}]
set_input_delay -clock clk  0  [get_ports {b[22]}]
set_input_delay -clock clk  0  [get_ports {b[21]}]
set_input_delay -clock clk  0  [get_ports {b[20]}]
set_input_delay -clock clk  0  [get_ports {b[19]}]
set_input_delay -clock clk  0  [get_ports {b[18]}]
set_input_delay -clock clk  0  [get_ports {b[17]}]
set_input_delay -clock clk  0  [get_ports {b[16]}]
set_input_delay -clock clk  0  [get_ports {b[15]}]
set_input_delay -clock clk  0  [get_ports {b[14]}]
set_input_delay -clock clk  0  [get_ports {b[13]}]
set_input_delay -clock clk  0  [get_ports {b[12]}]
set_input_delay -clock clk  0  [get_ports {b[11]}]
set_input_delay -clock clk  0  [get_ports {b[10]}]
set_input_delay -clock clk  0  [get_ports {b[9]}]
set_input_delay -clock clk  0  [get_ports {b[8]}]
set_input_delay -clock clk  0  [get_ports {b[7]}]
set_input_delay -clock clk  0  [get_ports {b[6]}]
set_input_delay -clock clk  0  [get_ports {b[5]}]
set_input_delay -clock clk  0  [get_ports {b[4]}]
set_input_delay -clock clk  0  [get_ports {b[3]}]
set_input_delay -clock clk  0  [get_ports {b[2]}]
set_input_delay -clock clk  0  [get_ports {b[1]}]
set_input_delay -clock clk  0  [get_ports {b[0]}]
set_output_delay -clock clk  0  [get_ports out_valid]
set_output_delay -clock clk  0  [get_ports {z[63]}]
set_output_delay -clock clk  0  [get_ports {z[62]}]
set_output_delay -clock clk  0  [get_ports {z[61]}]
set_output_delay -clock clk  0  [get_ports {z[60]}]
set_output_delay -clock clk  0  [get_ports {z[59]}]
set_output_delay -clock clk  0  [get_ports {z[58]}]
set_output_delay -clock clk  0  [get_ports {z[57]}]
set_output_delay -clock clk  0  [get_ports {z[56]}]
set_output_delay -clock clk  0  [get_ports {z[55]}]
set_output_delay -clock clk  0  [get_ports {z[54]}]
set_output_delay -clock clk  0  [get_ports {z[53]}]
set_output_delay -clock clk  0  [get_ports {z[52]}]
set_output_delay -clock clk  0  [get_ports {z[51]}]
set_output_delay -clock clk  0  [get_ports {z[50]}]
set_output_delay -clock clk  0  [get_ports {z[49]}]
set_output_delay -clock clk  0  [get_ports {z[48]}]
set_output_delay -clock clk  0  [get_ports {z[47]}]
set_output_delay -clock clk  0  [get_ports {z[46]}]
set_output_delay -clock clk  0  [get_ports {z[45]}]
set_output_delay -clock clk  0  [get_ports {z[44]}]
set_output_delay -clock clk  0  [get_ports {z[43]}]
set_output_delay -clock clk  0  [get_ports {z[42]}]
set_output_delay -clock clk  0  [get_ports {z[41]}]
set_output_delay -clock clk  0  [get_ports {z[40]}]
set_output_delay -clock clk  0  [get_ports {z[39]}]
set_output_delay -clock clk  0  [get_ports {z[38]}]
set_output_delay -clock clk  0  [get_ports {z[37]}]
set_output_delay -clock clk  0  [get_ports {z[36]}]
set_output_delay -clock clk  0  [get_ports {z[35]}]
set_output_delay -clock clk  0  [get_ports {z[34]}]
set_output_delay -clock clk  0  [get_ports {z[33]}]
set_output_delay -clock clk  0  [get_ports {z[32]}]
set_output_delay -clock clk  0  [get_ports {z[31]}]
set_output_delay -clock clk  0  [get_ports {z[30]}]
set_output_delay -clock clk  0  [get_ports {z[29]}]
set_output_delay -clock clk  0  [get_ports {z[28]}]
set_output_delay -clock clk  0  [get_ports {z[27]}]
set_output_delay -clock clk  0  [get_ports {z[26]}]
set_output_delay -clock clk  0  [get_ports {z[25]}]
set_output_delay -clock clk  0  [get_ports {z[24]}]
set_output_delay -clock clk  0  [get_ports {z[23]}]
set_output_delay -clock clk  0  [get_ports {z[22]}]
set_output_delay -clock clk  0  [get_ports {z[21]}]
set_output_delay -clock clk  0  [get_ports {z[20]}]
set_output_delay -clock clk  0  [get_ports {z[19]}]
set_output_delay -clock clk  0  [get_ports {z[18]}]
set_output_delay -clock clk  0  [get_ports {z[17]}]
set_output_delay -clock clk  0  [get_ports {z[16]}]
set_output_delay -clock clk  0  [get_ports {z[15]}]
set_output_delay -clock clk  0  [get_ports {z[14]}]
set_output_delay -clock clk  0  [get_ports {z[13]}]
set_output_delay -clock clk  0  [get_ports {z[12]}]
set_output_delay -clock clk  0  [get_ports {z[11]}]
set_output_delay -clock clk  0  [get_ports {z[10]}]
set_output_delay -clock clk  0  [get_ports {z[9]}]
set_output_delay -clock clk  0  [get_ports {z[8]}]
set_output_delay -clock clk  0  [get_ports {z[7]}]
set_output_delay -clock clk  0  [get_ports {z[6]}]
set_output_delay -clock clk  0  [get_ports {z[5]}]
set_output_delay -clock clk  0  [get_ports {z[4]}]
set_output_delay -clock clk  0  [get_ports {z[3]}]
set_output_delay -clock clk  0  [get_ports {z[2]}]
set_output_delay -clock clk  0  [get_ports {z[1]}]
set_output_delay -clock clk  0  [get_ports {z[0]}]
